import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  selector: 'app-static-abstract-members-compile-time-dispatch-subtopic',
  standalone: true,
  imports: [
    PageMetaComponent, TheoryBlockComponent, CodeBlockComponent,
    TryItComponent, MisconceptionsComponent, SubtopicNavComponent,
    SubtopicEyebrowComponent,
  ],
  templateUrl: './static-abstract-members-compile-time-dispatch.html',
  styleUrl: './static-abstract-members-compile-time-dispatch.scss',
})
export class HowStaticAbstractInterfaceMembersDispatchCompileTimeGenericSpecializationSubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'The main page says static abstract members "enable generic algorithms over numeric types" — but HOW does calling T.Zero or T + T actually resolve at runtime, if there is no instance to dispatch through?',
      points: [
        'The main C# 11 &amp; 12 page\'s <code>Sum&lt;T&gt;(IEnumerable&lt;T&gt;) where T : INumber&lt;T&gt;</code> calls <code>T.Zero</code> and uses <code>+=</code> — but ordinary interface dispatch works through an INSTANCE (<code>obj.Method()</code> looks up <code>obj</code>\'s actual runtime type in a vtable). Static abstract members have NO instance at all — <code>T.Zero</code> is called on the TYPE PARAMETER itself. Understanding how this resolves without any object to inspect is the key mechanic behind "zero-overhead generic math."',
      ],
    },
    {
      heading: 'For VALUE TYPES (structs like int, double, decimal), the JIT compiles a SEPARATE, fully specialized version of the generic method for EACH concrete T — there is no shared, type-erased code path at all',
      points: [
        'Unlike Java\'s generics (type erasure — one shared bytecode implementation for all reference types, with casts inserted) or even C#\'s OWN generics over reference types (which DO share one JIT-compiled implementation, using object references uniformly), .NET generics over VALUE TYPES get their OWN separate, fully specialized native code generated by the JIT for each distinct value-type instantiation — <code>Sum&lt;int&gt;</code> and <code>Sum&lt;double&gt;</code> are two COMPLETELY DIFFERENT compiled method bodies in memory, not one shared body with runtime type checks.',
        'Because each instantiation is specialized, when the JIT compiles <code>Sum&lt;int&gt;</code>, it already KNOWS <code>T</code> is <code>int</code> at compile time (of THAT specific generic instantiation) — so <code>T.Zero</code> becomes a DIRECT call to <code>int</code>\'s own implementation of <code>INumber&lt;int&gt;.Zero</code> (which is just the constant <code>0</code>), and <code>total += v</code> becomes a DIRECT native <code>add</code> instruction — there is no vtable lookup, no boxing, no runtime type check ANYWHERE in the compiled code for <code>Sum&lt;int&gt;</code> specifically.',
      ],
    },
    {
      heading: 'This is why generic math has ZERO runtime dispatch overhead — the "polymorphism" is entirely resolved at JIT-compile time, per instantiation, not at call time',
      points: [
        'Compare this to a REGULAR (non-static) interface method call through <code>IShape shape; shape.Area();</code> — THAT genuinely requires a vtable lookup at runtime, because <code>shape</code>\'s actual concrete type is not known until the call executes. Generic math\'s static abstract members sidestep this ENTIRELY: by the time <code>Sum&lt;int&gt;</code> exists as compiled native code, the compiler already fully knows which concrete <code>INumber&lt;T&gt;</code> implementation (<code>int</code>\'s) every <code>T.Xxx</code> call resolves to, baking in a direct call with no indirection at all — genuinely as fast as if you had hand-written a non-generic <code>SumInts(IEnumerable&lt;int&gt;)</code> method from scratch.',
      ],
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'The main page\'s own generic Sum<T> — what looks like it SHOULD need dispatch',
      language: 'csharp',
      code: `using System.Numerics;

public static T Sum<T>(IEnumerable<T> values) where T : INumber<T>
{
    T total = T.Zero;      // <-- static member access on a TYPE PARAMETER
    foreach (var v in values)
        total += v;        // <-- operator+ resolved via INumber<T>'s
                            //     static abstract operator +
    return total;
}

Console.WriteLine(Sum(new[] { 1, 2, 3 }));        // Sum<int>
Console.WriteLine(Sum(new[] { 1.5, 2.5, 3.0 }));  // Sum<double>

// Both calls go through the "SAME" generic method definition in source
// — but they do NOT execute the same compiled machine code at all.`,
    },
    {
      label: 'What the JIT actually produces — two entirely separate compiled methods',
      language: 'csharp',
      code: `// CONCEPTUALLY, once JIT-compiled, Sum<int> and Sum<double> are as if
// you had hand-written these two COMPLETELY SEPARATE, non-generic
// methods — there is no shared "generic Sum body with runtime type
// checks" anywhere in the compiled output:

// The JIT-specialized equivalent of Sum<int>:
public static int Sum_Specialized_Int(IEnumerable<int> values)
{
    int total = 0;          // T.Zero resolved DIRECTLY to int's own 0 —
                             // no INumber<int>.Zero vtable lookup at all
    foreach (var v in values)
        total += v;          // a genuine native "add" instruction —
                             // no operator-dispatch overhead whatsoever
    return total;
}

// The JIT-specialized equivalent of Sum<double>:
public static double Sum_Specialized_Double(IEnumerable<double> values)
{
    double total = 0.0;     // T.Zero resolved DIRECTLY to double's 0.0
    foreach (var v in values)
        total += v;          // a genuine native floating-point add
    return total;
}

// These are TWO SEPARATE regions of compiled native code, generated
// independently the FIRST time each generic instantiation is actually
// used at runtime (or ahead-of-time, under Native AOT) — NEITHER one
// contains any conditional logic checking "what is T right now."`,
    },
    {
      label: 'Contrast: a GENUINE runtime dispatch, through an ordinary (non-static) interface member',
      language: 'csharp',
      code: `public interface IShape
{
    double Area();   // ORDINARY (non-static) interface member —
                      // requires an INSTANCE to call
}

public class Circle : IShape
{
    public double Radius { get; init; }
    public double Area() => Math.PI * Radius * Radius;
}

public class Square : IShape
{
    public double Side { get; init; }
    public double Area() => Side * Side;
}

public static double TotalArea(IEnumerable<IShape> shapes)
{
    double total = 0;
    foreach (var shape in shapes)
        total += shape.Area();   // GENUINE vtable dispatch — the JIT
                                   // CANNOT know at compile time whether
                                   // "shape" will be a Circle, a Square,
                                   // or some other IShape implementation
                                   // written in a completely different
                                   // assembly loaded at runtime
    return total;
}

// THIS is what real, unavoidable runtime polymorphism looks like — a
// single compiled method body that MUST look up the actual object's
// vtable on every single call, because the set of possible concrete
// types is not fully known until the actual objects arrive at runtime.
// Generic math's static abstract members are architected SPECIFICALLY
// to avoid ever needing this kind of dispatch.`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'A generic method <code>T Max&lt;T&gt;(T a, T b) where T : IComparisonOperators&lt;T, T, bool&gt;</code> is called as <code>Max&lt;int&gt;(3, 7)</code> and, elsewhere, <code>Max&lt;MyCustomStruct&gt;(x, y)</code> where <code>MyCustomStruct</code> is a user-defined struct implementing that interface. Explain whether the JIT generates ONE shared compiled method body for both calls, or two separate ones — and why the answer would be DIFFERENT if <code>T</code> were constrained to a REFERENCE type instead.',
    hint: 'Consider the fundamental size/layout difference between value types (each has its own distinct size and memory layout, baked directly into generated code) versus reference types (every reference type variable is uniformly just a pointer of the same size, regardless of what class it actually points to).',
    solution: `public static T Max<T>(T a, T b) where T : IComparisonOperators<T, T, bool>
    => a > b ? a : b;

int intResult = Max(3, 7);                          // Max<int>
MyCustomStruct customResult = Max(x, y);             // Max<MyCustomStruct>

// ANSWER: the JIT generates TWO SEPARATE, independently-specialized
// compiled method bodies — Max<int> and Max<MyCustomStruct> are NOT
// sharing any compiled code, for the SAME reason the Sum<int> /
// Sum<double> example does not: BOTH int and MyCustomStruct are VALUE
// TYPES, each with their OWN distinct size and memory layout that must
// be baked directly into the generated machine code (how many bytes to
// copy when passing "a" and "b" as parameters, how to lay out the
// comparison, etc.) — this literally cannot be shared across two
// value types with different sizes/layouts.

// WHY THE ANSWER WOULD DIFFER FOR A REFERENCE TYPE CONSTRAINT:
// If T were constrained to a REFERENCE type instead (e.g. "where T :
// class, IComparable<T>"), EVERY possible T — regardless of which
// specific class it actually is — is represented UNIFORMLY as a single
// pointer-sized reference at runtime. Because ALL reference types share
// this SAME uniform representation, the CLR can (and does) share ONE
// single compiled method body across ALL reference-type instantiations
// of a generic method — Max<string> and Max<MyReferenceClass> WOULD
// share the exact same underlying compiled code, with the actual
// concrete type resolved via ordinary virtual/interface dispatch
// INSIDE that shared body when a specific member is actually invoked.
//
// This is the core distinction covered in this subtopic: value-type
// generic instantiations get FULL, separate JIT specialization (no
// dispatch overhead, but more generated code / larger memory footprint
// if many distinct value types are used); reference-type generic
// instantiations SHARE one compiled body (less generated code, but any
// actual polymorphic member call inside it still goes through ordinary
// runtime dispatch). Generic math specifically targets the VALUE TYPE
// case — INumber<T>, IComparisonOperators<T,...>, etc. are designed
// around numeric structs, which is exactly where the full-specialization
// behavior delivers its zero-overhead benefit.`,
  };

  misconceptions: Misconception[] = [
    {
      thought: 'calling a static abstract interface member like T.Zero requires a runtime vtable lookup, similar to calling an ordinary (non-static) interface method through an instance.',
      reality: 'for value-type generic instantiations, the JIT compiles a fully separate, specialized method body per concrete T — by the time that specialized code exists, T.Zero already resolves to a direct call with no dispatch mechanism involved at all.',
    },
    {
      thought: '.NET generics always share one compiled implementation across all type arguments, the same way Java\'s type-erased generics do.',
      reality: '.NET generics over VALUE TYPES get their own fully specialized, separately JIT-compiled code per concrete type — only generic instantiations over REFERENCE types share one compiled body, since all references have the same uniform pointer-sized representation.',
    },
    {
      thought: 'generic math (INumber<T>, static abstract operators) has some inherent runtime performance cost compared to writing type-specific arithmetic code by hand, as a tradeoff for the convenience.',
      reality: 'for value-type instantiations, the JIT-specialized code is functionally identical to hand-written type-specific code — the static abstract member calls are resolved directly at compile time for that specific instantiation, with no added indirection.',
    },
  ];
}
