import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PageMetaComponent } from '../../../shared/page-meta/page-meta';
import { QuickRefComponent, QuickRefItem } from '../../../shared/quick-ref/quick-ref';
import { TheoryBlockComponent, TheoryPoint } from '../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../shared/code-block/code-block';
import { CommonMistakesComponent, CommonMistake } from '../../../shared/common-mistakes/common-mistakes';
import { ChallengeBlockComponent, Challenge } from '../../../shared/challenge-block/challenge-block';
import { QuizBlockComponent, QuizQuestion } from '../../../shared/quiz-block/quiz-block';
import { QnaBlockComponent, QnaItem } from '../../../shared/qna-block/qna-block';
import { RevisionCardComponent, RevisionSummary } from '../../../shared/revision-card/revision-card';
import { PageCompleteComponent } from '../../../shared/page-complete/page-complete';

@Component({
  selector: 'app-mesh-metrics',
  standalone: true,
  imports: [CommonModule, PageMetaComponent, QuickRefComponent, TheoryBlockComponent, CodeBlockComponent,
            CommonMistakesComponent, ChallengeBlockComponent, QuizBlockComponent, QnaBlockComponent,
            RevisionCardComponent, PageCompleteComponent],
  templateUrl: './metrics.html',
  styleUrl: './metrics.scss',
})
export class MeshMetrics {
  quickRef: QuickRefItem[] = [
    { name: 'istio_requests_total', type: 'keyword', desc: 'Counter — total HTTP requests by source, destination, method, response code, and reporter.' },
    { name: 'istio_request_duration_milliseconds', type: 'keyword', desc: 'Histogram — request latency distribution. Use for p50/p95/p99 SLO tracking.' },
    { name: 'istio_tcp_sent_bytes_total', type: 'keyword', desc: 'Counter — total bytes sent over TCP connections. Used for bandwidth monitoring.' },
    { name: 'reporter', type: 'keyword', desc: 'Label indicating which Envoy reported the metric: "source" (client sidecar) or "destination" (server sidecar).' },
    { name: 'Telemetry API', type: 'syntax', desc: 'Istio CRD for customising metric collection: add/remove labels, filter metrics, set sampling rates.' },
    { name: 'ServiceMonitor', type: 'syntax', desc: 'Prometheus Operator CRD to configure scrape targets — used to scrape Envoy /metrics endpoints.' },
    { name: 'istio_agent_pilot_xds_pushes', type: 'keyword', desc: 'Counter tracking xDS config pushes from Istiod to Envoy proxies — useful for control-plane health.' },
    { name: 'proxy_config_outbound_clusters', type: 'keyword', desc: 'Gauge — number of upstream clusters each proxy knows about. High values indicate config bloat.' },
  ];

  theory: TheoryPoint[] = [
    {
      heading: 'Golden Signals from Envoy',
      points: [
        'Istio provides the four golden signals for every service automatically: Rate (requests/sec), Errors (5xx rate), Duration (latency percentiles), and Saturation (connection pool utilisation). No application code changes needed.',
        'Metrics are generated by the Envoy sidecar on BOTH ends of each connection: the client sidecar (`reporter=source`) and the server sidecar (`reporter=destination`). Using both provides end-to-end visibility.',
        'The `reporter=source` metric shows what the client experienced. `reporter=destination` shows what the server received. Discrepancies between them reveal network-level failures (packets lost, sidecar crashes).',
        '`istio_requests_total` is a counter with labels: `source_workload`, `destination_workload`, `destination_service`, `request_protocol`, `response_code`, `response_flags`, `reporter`. Query with PromQL `rate()` for RPS.',
        '`istio_request_duration_milliseconds` is a histogram (sum + count + buckets). Use `histogram_quantile(0.99, rate(istio_request_duration_milliseconds_bucket[5m]))` for p99 latency.',
        'Response flags (`response_flags` label): UH=no healthy upstream, NR=no route, DC=downstream connection terminated, UO=upstream overflow (circuit breaker). These are invaluable for diagnosing 503 causes.',
      ],
    },
    {
      heading: 'Prometheus Integration',
      points: [
        'Istio exposes Envoy metrics on port 15090 (`/stats/prometheus`) of each injected pod. Prometheus must be configured to scrape this port for metrics to be collected.',
        'Recommended setup: use kube-prometheus-stack (kube-prometheus + Prometheus Operator). Create a `PodMonitor` or `ServiceMonitor` targeting the `15090` port of all injected pods.',
        'Istio\'s bundled Prometheus (from `istioctl install --set profile=demo`): auto-configured, no setup needed. Not suitable for production — no persistence, no HA, no alerting.',
        'Production Prometheus: disable the bundled Prometheus and point Istio\'s Kiali/Grafana to your existing Prometheus instance. This keeps all metrics in one place with your existing retention and alert rules.',
        'Metric cardinality: Istio default metrics include high-cardinality labels. With thousands of pods, `istio_requests_total` can generate millions of time series. Use the Telemetry API to drop high-cardinality labels or reduce metric collection on low-traffic services.',
        'Scrape interval: Prometheus default 15s scrape interval is fine for most metrics. For low-latency SLOs (p99 < 50ms), consider 5s scrape interval for more accurate histogram data.',
      ],
    },
    {
      heading: 'Telemetry API — Customising Metrics',
      points: [
        'The Telemetry API (Istio 1.12+) replaces the older EnvoyFilter/MeshConfig approach for customising telemetry. It is a CRD (`Telemetry`) that can be scoped per workload, namespace, or mesh.',
        'Add custom labels to metrics: extract values from request headers or attributes and add them as metric labels. Useful for adding `customer-tier` or `api-version` to per-request metrics for SLO segmentation.',
        'Drop metrics by type: disable HTTP metrics for a high-traffic health check path that would pollute RPS and error rate calculations. Use `match.metric: REQUEST_COUNT` with a path match.',
        'Override sampling rate for access logs: set `accessLogging.providers[0].name = envoy` and configure percentage-based sampling. Log 100% in staging, 1% in production for high-traffic services.',
        'Disable metrics for specific workloads: internal health check services with thousands of calls/second can pollute metric storage. Use `metrics[0].overrides[0].disabled: true` in the Telemetry resource.',
        'The Telemetry API is additive and composable — mesh-level policies are overridden by namespace-level, which are overridden by workload-level. This mirrors AuthorizationPolicy scope hierarchy.',
      ],
    },
    {
      heading: 'Key PromQL Queries for Service Mesh',
      points: [
        'Success rate (5xx error rate): `sum(rate(istio_requests_total{reporter="destination",response_code!~"5.."}[5m])) / sum(rate(istio_requests_total{reporter="destination"}[5m]))`',
        'p99 latency by service: `histogram_quantile(0.99, sum by (destination_service_name, le) (rate(istio_request_duration_milliseconds_bucket{reporter="destination"}[5m])))`',
        'Request rate by service: `sum by (destination_service_name) (rate(istio_requests_total{reporter="destination"}[5m]))`',
        'Circuit breaker trips: `sum(rate(envoy_cluster_upstream_rq_pending_overflow[5m]))` — non-zero means connection pool circuit breaker is tripping.',
        'Outlier detection ejections: `sum(envoy_cluster_outlier_detection_ejections_active)` — how many pods are currently ejected.',
        'Control plane push errors: `rate(pilot_xds_push_errors[5m])` — non-zero indicates Istiod is failing to push config to some proxies.',
      ],
    },
    {
      heading: 'Grafana Dashboards',
      points: [
        'Istio provides official Grafana dashboards via the `istio/grafana` Helm chart or the `samples/addons/grafana.yaml` manifest. They are pre-built for the standard Istio metrics.',
        'Key dashboards: "Istio Mesh Dashboard" (global service graph), "Istio Service Dashboard" (per-service golden signals), "Istio Workload Dashboard" (per-pod metrics), "Istio Control Plane Dashboard" (Istiod health).',
        'Import by ID from grafana.com: Istio official dashboards have IDs 7636 (mesh), 7630 (service), 7645 (workload), 7639 (performance). Use these with any Prometheus data source.',
        'Custom dashboards: use `destination_service_name` and `source_workload` labels to build service topology views. Combine Prometheus metrics with Loki log data for correlated traces.',
        'SLO dashboards: track error budget burn rate using `(1 - success_rate) / (1 - slo_target)`. Alert when burn rate exceeds 2× for 1 hour or 14.4× for 5 minutes (Google SRE model).',
        'Flame graphs: Grafana supports Pyroscope integration for continuous profiling. Combine with Istio latency percentiles to correlate high p99 latency with specific code paths.',
      ],
    },
    {
      heading: 'Control Plane Metrics',
      points: [
        'Istiod exposes its own metrics on port 15014 (`/metrics`). These reveal the health of the control plane itself — not individual service traffic.',
        '`pilot_xds_pushes`: rate of xDS config pushes (CDS/EDS/LDS/RDS). High rate indicates frequent config churn — too many pod restarts or ConfigMap changes triggering cascading xDS updates.',
        '`pilot_xds_push_errors`: xDS pushes that failed. Non-zero means some proxies are not receiving config updates — stale routing or security policies.',
        '`pilot_vservice_count`, `pilot_destrule_count`: number of VirtualService and DestinationRule resources Istiod knows about. Very high values (1000+) can slow xDS processing.',
        '`citadel_server_csr_count`: Certificate Signing Requests processed by the Istiod CA. Track to ensure cert rotation is happening. A sudden drop indicates broken CSR pipeline.',
        '`galley_validation_failed`: validation webhook rejections. Non-zero means invalid Istio CRD configs are being submitted — check your GitOps pipeline for malformed VirtualService/DestinationRule YAML.',
      ],
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'PromQL Queries',
      language: 'bash',
      code: `# Success rate for payment service (last 5 minutes)
sum(rate(istio_requests_total{
  reporter="destination",
  destination_service_name="payment",
  response_code!~"5.."
}[5m]))
/
sum(rate(istio_requests_total{
  reporter="destination",
  destination_service_name="payment"
}[5m]))

# p99 latency per service
histogram_quantile(0.99,
  sum by (destination_service_name, le) (
    rate(istio_request_duration_milliseconds_bucket{
      reporter="destination"
    }[5m])
  )
)

# Circuit breaker trips (upstream overflow)
sum by (cluster_name) (
  rate(envoy_cluster_upstream_rq_pending_overflow[5m])
)`,
    },
    {
      label: 'Telemetry API',
      language: 'bash',
      code: `# Add custom label to metrics (extract from request header)
cat <<EOF | kubectl apply -f -
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: production
spec:
  selector:
    matchLabels:
      app: api
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_COUNT
      tagOverrides:
        customer_tier:
          value: "request.headers['x-customer-tier'] | 'unknown'"
    # Disable health check metrics (high volume, low value)
    - match:
        metric: ALL_METRICS
        customMetricSearch:
          request:
            url:
              prefix: /health
      disabled: true
EOF`,
    },
    {
      label: 'Prometheus Scrape Config',
      language: 'bash',
      code: `# PodMonitor for scraping Envoy metrics from injected pods
cat <<EOF | kubectl apply -f -
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies
  namespace: monitoring
spec:
  selector:
    matchExpressions:
    - key: istio-prometheus-ignore
      operator: DoesNotExist
  podMetricsEndpoints:
  - port: http-envoy-prom    # Port 15090
    path: /stats/prometheus
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      action: keep
      regex: istio-proxy   # Only scrape the sidecar container
  namespaceSelector:
    any: true
EOF`,
    },
    {
      label: 'Response Flag Debugging',
      language: 'bash',
      code: `# Check response flags in Envoy access logs
kubectl logs deploy/api -n production -c istio-proxy \\
  | grep -v "200\\|204" \\
  | grep "response_flags"

# Common response_flags values:
# UH  - No healthy upstream (all pods ejected by outlier detection)
# NR  - No route (VirtualService or DestinationRule misconfiguration)
# DC  - Downstream connection terminated (client closed before response)
# UO  - Upstream overflow (circuit breaker tripped, connection pool full)
# URX - Upstream retry limit exceeded (all retries exhausted)
# UT  - Upstream request timeout (exceeded VirtualService timeout)
# UF  - Upstream connection failure (TCP connect failed)

# Query specific response flags in Prometheus
sum by (response_flags, destination_service_name) (
  rate(istio_requests_total{
    response_flags!="",
    reporter="source"
  }[5m])
)`,
    },
  ];

  mistakes: CommonMistake[] = [
    {
      title: 'Using the bundled Prometheus in production',
      wrong: `istioctl install --set profile=demo
# Bundled Prometheus: no storage, no HA, data lost on pod restart
# Querying 7-day trends is impossible`,
      right: `# Use kube-prometheus-stack (Helm chart)
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack \\
  -n monitoring
# Point Istio to existing Prometheus via Telemetry API
# Set Kiali prometheusUrl to http://prometheus.monitoring.svc:9090`,
      explanation: 'The bundled Prometheus in Istio\'s demo profile has no persistent storage (data lost on restart), no HA (single replica), and no alerting rules. Use kube-prometheus-stack or your existing Prometheus for production. The Istio Grafana dashboards work with any Prometheus data source.',
    },
    {
      title: 'Querying istio_requests_total without reporter filter — double-counting',
      wrong: `# This counts each request TWICE (source + destination reporter)
sum(rate(istio_requests_total[5m]))`,
      right: `# Always filter to ONE reporter to avoid double-counting
sum(rate(istio_requests_total{reporter="destination"}[5m]))
# "destination" is preferred — shows what the server received
# "source" shows what the client sent (useful for cross-cluster comparison)`,
      explanation: 'Each request generates two metric data points — one from the client Envoy (`reporter=source`) and one from the server Envoy (`reporter=destination`). Querying without a reporter filter doubles all counts. Always filter to one reporter; `reporter="destination"` is the most reliable for server-side SLOs.',
    },
    {
      title: 'Ignoring response_flags — treating all 503s as the same',
      wrong: `# Alert fires: "503 error rate > 5%"
# Team assumes upstream service is down and starts restarting pods
# Actual cause: UO (upstream overflow = circuit breaker tripped)`,
      right: `# Check response_flags to identify the root cause
sum by (response_flags) (
  rate(istio_requests_total{response_code="503"}[5m])
)
# UO → circuit breaker → tune connection pool settings
# UH → outlier detection drained pool → fix unhealthy pods
# NR → routing misconfiguration → check VirtualService/DestinationRule`,
      explanation: 'Istio\'s `response_flags` label classifies the CAUSE of non-2xx responses. 503 UO means circuit breaker overflow. 503 UH means no healthy upstreams. 503 NR means no route found. Debugging from the error code alone misses the root cause; always check `response_flags` first.',
    },
    {
      title: 'High-cardinality labels causing metric explosion',
      wrong: `# Telemetry API adding user-id as a metric label
tagOverrides:
  user_id:
    value: "request.headers['x-user-id']"
# With 1M users: 1M unique label values × all metric series = billions of time series`,
      right: `# Use low-cardinality labels only: tier, region, api-version, status
tagOverrides:
  customer_tier:
    value: "request.headers['x-customer-tier'] | 'standard'"
# 3-5 distinct values max per custom label`,
      explanation: 'Prometheus stores one time series per unique combination of label values. Adding a high-cardinality label (user ID, request ID, session token) to a metric creates an explosion of time series — crashing Prometheus or causing massive storage costs. Only add labels with a small, bounded set of values.',
    },
    {
      title: 'Not alerting on control plane metrics',
      wrong: `# Only alerting on service-level error rates
# pilot_xds_push_errors spikes for 10 minutes → stale config on proxies
# Traffic routes to wrong subsets → silent errors, no alert fires`,
      right: `# Alert on Istiod health metrics too:
# - pilot_xds_push_errors > 0 for 5m
# - pilot_xds_pushes dropping to 0 for 5m (push stall)
# - citadel_server_csr_count dropping to 0 (cert renewal broken)
# - galley_validation_failed > 0 (bad config being submitted)`,
      explanation: 'Service-level metrics show EFFECTS of control plane problems; control plane metrics show CAUSES. If Istiod stops pushing xDS config, proxies use stale routing tables — wrong subsets, missing retries, outdated mTLS certs. Monitor Istiod health metrics with the same rigour as service metrics.',
    },
  ];

  challenge: Challenge = {
    title: 'Write SLO PromQL Queries',
    language: 'typescript',
    description: `Write PromQL queries for a service mesh SLO dashboard for the "checkout" service:

1. Success rate: percentage of non-5xx requests (last 5 min, destination reporter)
2. p99 latency: 99th percentile request duration in milliseconds
3. Error budget burn rate: (1 - success_rate) / (1 - 0.999) where SLO target is 99.9%

Return all three queries as an object with keys: successRate, p99Latency, burnRate.`,
    hints: [
      'Rate of non-5xx: response_code!~"5.."',
      'histogram_quantile needs _bucket metric and le label',
      'Burn rate = actual error rate / allowed error rate (1 - SLO)',
      'Filter to destination_service_name="checkout"',
    ],
    starterCode: `function getSloQueries(): { successRate: string; p99Latency: string; burnRate: string } {
  return {
    successRate: '# Success rate query here',
    p99Latency: '# p99 latency query here',
    burnRate: '# Burn rate query here',
  };
}
console.log(JSON.stringify(getSloQueries(), null, 2));`,
    solution: `function getSloQueries(): { successRate: string; p99Latency: string; burnRate: string } {
  const successRate = \`sum(rate(istio_requests_total{reporter="destination",destination_service_name="checkout",response_code!~"5.."}[5m]))
/
sum(rate(istio_requests_total{reporter="destination",destination_service_name="checkout"}[5m]))\`;

  const p99Latency = \`histogram_quantile(0.99,
  sum by (le) (
    rate(istio_request_duration_milliseconds_bucket{
      reporter="destination",
      destination_service_name="checkout"
    }[5m])
  )
)\`;

  const burnRate = \`(
  1 - sum(rate(istio_requests_total{reporter="destination",destination_service_name="checkout",response_code!~"5.."}[5m]))
    / sum(rate(istio_requests_total{reporter="destination",destination_service_name="checkout"}[5m]))
)
/ (1 - 0.999)\`;

  return { successRate, p99Latency, burnRate };
}
console.log(JSON.stringify(getSloQueries(), null, 2));`,
  };

  quiz: QuizQuestion[] = [
    {
      q: 'What does `reporter="destination"` mean in an Istio metric label?',
      options: ['The metric was collected by the destination Kubernetes Service', 'The metric was reported by the server-side Envoy sidecar (the receiving proxy)', 'The metric tracks traffic destined for external services', 'The metric originates from the Istiod control plane'],
      answer: 1,
      explanation: 'Each request generates two Prometheus metric data points: one from the client-side Envoy (`reporter=source`) and one from the server-side Envoy (`reporter=destination`). `reporter=destination` shows the server\'s perspective — what it received and how long it took to respond. Always filter to one reporter to avoid double-counting.',
    },
    {
      q: 'What does a `response_flags=UO` value indicate?',
      options: ['User operation — a user-initiated request was processed', 'Upstream overflow — the circuit breaker tripped because the connection pool was full', 'Unknown origin — the source of the request could not be determined', 'Upstream offline — all pods in the upstream service are unhealthy'],
      answer: 1,
      explanation: 'UO (Upstream Overflow) means the connection pool\'s `http1MaxPendingRequests` or `http2MaxRequests` limit was exceeded and Envoy rejected the request immediately with 503. This is the circuit breaker firing. To fix: either increase the pool limits or reduce load on the upstream service.',
    },
    {
      q: 'Why should you filter `istio_requests_total` by `reporter` in PromQL?',
      options: ['To avoid including internal Istiod health-check requests in the count', 'Because each request is counted twice (source + destination reporters) — querying without filter doubles the rate', 'To separate TCP metrics from HTTP metrics in the same query', 'To exclude metrics from pods that are not in the service mesh'],
      answer: 1,
      explanation: 'Istio\'s client-side (source) and server-side (destination) Envoys both emit the same metric for each request. Without a reporter filter, your rate() calculation doubles every request. Always filter to one reporter — use `reporter="destination"` for server SLOs and `reporter="source"` when comparing what the client experienced.',
    },
    {
      q: 'What is the risk of adding a high-cardinality label (e.g., user_id) to Istio metrics via the Telemetry API?',
      options: ['The label will be stripped by Prometheus automatically', 'Each unique label value creates a separate time series — millions of users create millions of time series, crashing Prometheus', 'High-cardinality labels cause xDS push delays in Istiod', 'The Telemetry API rejects labels with more than 100 unique values'],
      answer: 1,
      explanation: 'Prometheus stores one time series per unique combination of label values. A user_id label with 1 million unique values multiplied by all existing metric label combinations can create billions of time series — exhausting Prometheus memory and causing out-of-memory crashes. Only add labels with a small, fixed set of values (tier, region, api-version).',
    },
    {
      q: 'Which Istio metric should you use to track p99 request latency?',
      options: ['istio_requests_total with a 99th percentile function', 'istio_request_duration_milliseconds (histogram) with histogram_quantile(0.99, ...)', 'istio_request_duration_milliseconds_count divided by sum', 'pilot_xds_push_time_bucket'],
      answer: 1,
      explanation: '`istio_request_duration_milliseconds` is a Prometheus histogram — it records latency in configurable buckets and exposes `_bucket`, `_sum`, and `_count` metrics. Use `histogram_quantile(0.99, rate(istio_request_duration_milliseconds_bucket[5m]))` to compute p99 latency from the bucket distribution.',
    },
    {
      q: 'What does `pilot_xds_push_errors` indicate when it is non-zero?',
      options: ['Application pods are returning 5xx errors', 'Istiod is failing to push config updates to some Envoy proxies — they may have stale routing or security policies', 'Prometheus is failing to scrape Istio metrics', 'EnvoyFilters are causing configuration conflicts'],
      answer: 1,
      explanation: '`pilot_xds_push_errors` counts failed xDS config pushes from Istiod to Envoy proxies. When non-zero, some proxies are not receiving the latest config — they may route to wrong subsets, miss retry policies, or have stale mTLS certs. Alert on this metric in production alongside service-level error rates.',
    },
  ];

  qna: QnaItem[] = [
    {
      q: 'What are the four golden signals and how does Istio provide them automatically?',
      a: '<strong>Rate</strong> (requests/sec): <code>rate(istio_requests_total[5m])</code> — no app code needed; Envoy counts every request. <br><strong>Errors</strong> (error rate): <code>rate(istio_requests_total{response_code=~"5.."}[5m])</code> — Envoy records every response code. <br><strong>Duration</strong> (latency): <code>histogram_quantile(0.99, rate(istio_request_duration_milliseconds_bucket[5m]))</code> — Envoy measures every request\'s round-trip time. <br><strong>Saturation</strong> (resource pressure): <code>rate(envoy_cluster_upstream_rq_pending_overflow[5m])</code> — circuit breaker trips indicate saturation. <br>All four are available for every meshed service immediately after injection, with zero application instrumentation.',
    },
    {
      q: 'How do you connect Istio metrics to an existing Prometheus without using the bundled one?',
      a: 'Two approaches: <ol><li><strong>PodMonitor/ServiceMonitor</strong> (Prometheus Operator): create a <code>PodMonitor</code> targeting the <code>15090</code> port of all injected pods. The Operator auto-configures Prometheus scrape jobs.</li><li><strong>Static scrape config</strong>: add Istio pods as targets in <code>prometheus.yml</code> with <code>kubernetes_sd_configs</code> targeting pods with the <code>istio-proxy</code> container, scraping port 15090 at path <code>/stats/prometheus</code>.</li></ol>Then disable the Istio bundled Prometheus: <code>--set values.prometheus.enabled=false</code> in the IstioOperator or Helm values. Point Kiali and Grafana at your existing Prometheus URL.',
    },
    {
      q: 'How do you use the Telemetry API to reduce metric cardinality on a high-traffic service?',
      a: 'Use the Telemetry API to: <ol><li><strong>Drop unwanted labels</strong>: remove <code>source_version</code> or <code>destination_version</code> from metrics if you don\'t use them in queries — each unique value creates a new time series.</li><li><strong>Disable metrics for specific paths</strong>: health check paths (<code>/health</code>, <code>/readyz</code>) generate thousands of requests/sec — disable <code>REQUEST_COUNT</code> and <code>REQUEST_DURATION</code> for those paths.</li><li><strong>Per-workload overrides</strong>: a batch processing service may generate millions of small jobs — disable mesh metrics entirely with <code>disabled: true</code> in the Telemetry resource selector.</li></ol>Start by running <code>kubectl top pods -n monitoring</code> to identify which Prometheus pods have high memory, then investigate which metric series are largest.',
    },
    {
      q: 'What is the difference between source and destination reporters and when do you use each?',
      a: '<strong>reporter=destination</strong> (server-side Envoy): measures what the server received and responded to. Use for: <ul><li>Server SLOs (error rate, latency the server is responsible for)</li><li>Capacity planning (actual server request rate)</li><li>Per-service dashboards (how the service is performing)</li></ul><strong>reporter=source</strong> (client-side Envoy): measures what the client sent and what it received. Use for: <ul><li>Detecting network-level failures (source sees 503; destination sees nothing — packet loss or sidecar crash)</li><li>Client-perspective latency (includes network transit time not visible to destination)</li><li>Cross-cluster comparison (source in cluster A calling destination in cluster B)</li></ul>',
    },
    {
      q: 'How do you build an SLO burn rate alert using Istio metrics?',
      a: 'SLO burn rate alert (Google SRE model): <ol><li>Define SLO: 99.9% success rate (0.1% error budget).</li><li>Measure current error rate: <code>1 - success_rate</code></li><li>Burn rate = current error rate / allowed error rate = <code>(1 - success_rate) / (1 - 0.999)</code></li><li>Alert rules: <ul><li>Burn rate > 14.4 for 5 minutes → critical (2% error budget burned in 1 hour)</li><li>Burn rate > 6 for 30 minutes → warning (5% burned in 6 hours)</li><li>Burn rate > 3 for 1 hour → low severity (10% burned in 3 days)</li></ul></li></ol>These multi-window alerts catch both spikes (fast burn) and slow degradation (slow burn) — neither alone is sufficient.',
    },
  ];

  revision: RevisionSummary = {
    oneLiner: 'Istio provides golden signals (rate, errors, duration, saturation) via Envoy metrics automatically. Key metrics: istio_requests_total (counter), istio_request_duration_milliseconds (histogram). Always filter by reporter to avoid double-counting.',
    mustKnow: [
      'reporter=source (client Envoy) vs reporter=destination (server Envoy) — always filter to one',
      'istio_requests_total: counter with response_code, response_flags, source/destination labels',
      'istio_request_duration_milliseconds: histogram → histogram_quantile for p50/p95/p99',
      'response_flags: UO=overflow, UH=no healthy upstreams, NR=no route, UT=timeout',
      'Telemetry API: add/remove labels, disable high-volume metrics, per-workload overrides',
      'Control plane metrics: pilot_xds_push_errors, citadel_server_csr_count for Istiod health',
      'Production: use kube-prometheus-stack, NOT bundled Prometheus (no persistence)',
    ],
    interviewFocus: [
      'What are the four golden signals and which Istio metrics provide them?',
      'Why double-filtering reporter matters — explain source vs destination',
      'How to diagnose a 503 surge using response_flags (UO vs UH vs NR)',
      'How the Telemetry API reduces metric cardinality',
      'SLO burn rate formula and why multi-window alerting catches both spikes and slow degradation',
    ],
  };
}
