import { Component } from '@angular/core';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';

@Component({
  selector: 'app-test-explicit-ids-sequence',
  standalone: true,
  imports: [SubtopicEyebrowComponent, PageMetaComponent, TheoryBlockComponent, CodeBlockComponent,
    TryItComponent, MisconceptionsComponent, SubtopicNavComponent],
  templateUrl: './explicit-ids-sequence.html',
  styleUrl: './explicit-ids-sequence.scss'
})
export class ExplicitIdsSequenceSubtopic {
  theory: TheoryPoint[] = [
    {
      "heading": "Measured on PostgreSQL 16",
      "points": [
        "With <code>id serial primary key</code>, inserting <code>(1, \"Alice\")</code> and <code>(2, \"Bob\")</code> with explicit ids succeeded. The next <code>insert into users (name) values (\"Carol\")</code> failed: \"duplicate key value violates unique constraint users_pkey, Key (id)=(1) already exists\".",
        "The sequence behind <code>serial</code> only advances when it is asked for a value. Explicit ids bypass it, so it still hands out 1. Identity columns created with <code>GENERATED BY DEFAULT</code> behave the same way.",
        "After <code>SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT max(id) FROM users))</code>, the next insert received id 3. (Not 2: the failed insert had already consumed one value.)",
        "The page's Seeding Pattern now notes this. Deterministic ids are still a good idea for fixtures; the sequence just has to be told about them."
      ]
    }
  ];

  codeTabs: CodeTab[] = [
    {
      "label": "Measured",
      "language": "sql",
      "code": "CREATE TABLE users (id serial PRIMARY KEY, name text);\nINSERT INTO users (id, name) VALUES (1, 'Alice'), (2, 'Bob');\n\nINSERT INTO users (name) VALUES ('Carol');\n-- ERROR: duplicate key value violates unique constraint \"users_pkey\"\n-- DETAIL: Key (id)=(1) already exists.\n\nSELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT max(id) FROM users));\nINSERT INTO users (name) VALUES ('Carol');   -- id 3"
    },
    {
      "label": "Seed helper with reset",
      "language": "typescript",
      "code": "async function seedUsers(prisma: PrismaClient) {\n  await prisma.user.createMany({\n    data: [\n      { id: 1, name: 'Alice', email: 'alice@example.com', role: 'admin' },\n      { id: 2, name: 'Bob',   email: 'bob@example.com',   role: 'user'  },\n    ],\n  });\n  await prisma.$executeRawUnsafe(\n    `SELECT setval(pg_get_serial_sequence('\"User\"', 'id'), (SELECT max(id) FROM \"User\"))`,\n  );\n}"
    }
  ];

  exercise: TryItExercise = {
    "prompt": "After seeding ids 1 to 50 and calling setval correctly, a test creates a user and asserts its id is 51. A later run fails because the id is 53. What could have consumed 51 and 52?",
    "hint": "Sequence values are used even when the insert does not survive.",
    "solution": "Any insert that asked the sequence for a value and then failed or was rolled back, for example two inserts in an earlier test that ran inside a rolled-back transaction. Sequence values are never returned, so do not assert on exact generated ids; read the id from the insert result instead."
  };

  misconceptions: Misconception[] = [
    {
      "thought": "Inserting an explicit id moves the sequence past it.",
      "reality": "In PostgreSQL the sequence is untouched unless something calls nextval or setval."
    },
    {
      "thought": "skipDuplicates makes seeding safe.",
      "reality": "It only skips conflicting seed rows. The stale sequence still breaks later inserts."
    }
  ];
}
