import { Component, signal, computed } from '@angular/core';
import { RouterLink } from '@angular/router';

interface Topic { title: string; route: string; badge: string; description: string; keyPoints: string[]; available: boolean; }

const BADGE_CSS: Record<string, string> = {
  'Foundations': 'foundations', 'Istio': 'istio', 'Linkerd': 'linkerd',
  'Traffic': 'traffic', 'Security': 'security', 'Observability': 'observability',
  'Gateway API': 'gateway', 'Reference': 'reference',
};
const GROUP_ORDER = ['All', 'Foundations', 'Istio', 'Linkerd', 'Traffic', 'Security', 'Observability', 'Gateway API', 'Reference'];

const ALL_TOPICS: Topic[] = [
  { title: 'Service Mesh Fundamentals', route: '/service-mesh/fundamentals', badge: 'Foundations', description: 'What a service mesh is — sidecar proxies, control plane vs data plane, and why you need one.', keyPoints: ['Sidecar proxy pattern', 'Control plane vs data plane', 'mTLS automatic encryption', 'Observability without code changes', 'Service mesh trade-offs'], available: true },
  { title: 'Istio Architecture', route: '/service-mesh/istio-architecture', badge: 'Istio', description: 'Istiod control plane, Envoy sidecar data plane, and how Istio manages service-to-service communication.', keyPoints: ['Istiod: Pilot, Citadel, Galley', 'Envoy sidecar injection', 'xDS discovery APIs', 'Service entry for external services', 'istioctl CLI'], available: true },
  { title: 'Istio Installation & Configuration', route: '/service-mesh/istio-install', badge: 'Istio', description: 'Install Istio with istioctl or Helm, IstioOperator CRD, and namespace injection configuration.', keyPoints: ['istioctl install profile', 'IstioOperator configuration', 'Namespace label injection', 'Istio revision tagging', 'Minimal vs demo profile'], available: true },
  { title: 'Linkerd', route: '/service-mesh/linkerd', badge: 'Linkerd', description: 'Lightweight CNCF service mesh — simpler than Istio, Rust-based micro-proxy, and CLI workflows.', keyPoints: ['linkerd install / check', 'Automatic mTLS', 'Rust micro-proxy (less overhead)', 'linkerd viz dashboard', 'Linkerd vs Istio trade-offs'], available: true },
  { title: 'Traffic Management', route: '/service-mesh/traffic-management', badge: 'Traffic', description: 'VirtualService, DestinationRule, weighted routing, canary releases, and A/B testing with Istio.', keyPoints: ['VirtualService routing rules', 'DestinationRule subsets', 'Weight-based canary routing', 'Header-based routing', 'Fault injection for testing'], available: true },
  { title: 'Retries, Timeouts & Circuit Breaking', route: '/service-mesh/resilience', badge: 'Traffic', description: 'Configure retries, request timeouts, and circuit breaking in DestinationRule to improve resilience.', keyPoints: ['retries attempts and perTryTimeout', 'VirtualService timeout field', 'outlierDetection circuit breaker', 'consecutiveErrors threshold', 'Passive health checking'], available: true },
  { title: 'Load Balancing Algorithms', route: '/service-mesh/load-balancing', badge: 'Traffic', description: 'Round-robin, least request, random, and consistent hashing load balancing in a service mesh.', keyPoints: ['ROUND_ROBIN (default)', 'LEAST_CONN for latency', 'Random algorithm', 'Consistent hash with cookie/header', 'Locality load balancing'], available: true },
  { title: 'mTLS & Service Identity', route: '/service-mesh/mtls', badge: 'Security', description: 'Mutual TLS between services — SPIFFE/SVID identities, PeerAuthentication, and certificate rotation.', keyPoints: ['SPIFFE identities (SVID)', 'PeerAuthentication STRICT mode', 'Automatic cert rotation', 'Trust domain configuration', 'mTLS debugging with istioctl'], available: true },
  { title: 'Authorization Policies', route: '/service-mesh/authorization', badge: 'Security', description: 'Istio AuthorizationPolicy — allow/deny rules by source, destination, HTTP method, and JWT claims.', keyPoints: ['AuthorizationPolicy ALLOW/DENY', 'source.principals (SPIFFE)', 'HTTP methods and paths', 'JWT claims conditions', 'Namespace-wide deny-all policy'], available: true },
  { title: 'Metrics & Telemetry', route: '/service-mesh/metrics', badge: 'Observability', description: 'Istio-generated Prometheus metrics — request rate, error rate, and latency (RED metrics).', keyPoints: ['istio_requests_total metric', 'request_duration histogram', 'Prometheus scrape config', 'Grafana Istio dashboards', 'Custom Telemetry API'], available: true },
  { title: 'Distributed Tracing', route: '/service-mesh/tracing', badge: 'Observability', description: 'Trace requests across services with Zipkin/Jaeger and B3/W3C propagation headers.', keyPoints: ['B3 / W3C TraceContext headers', 'Zipkin and Jaeger backends', 'Trace sampling rate', 'Propagate headers in code', 'Kiali service graph'], available: true },
  { title: 'Kiali & Dashboards', route: '/service-mesh/kiali', badge: 'Observability', description: 'Kiali topology graph, Grafana Istio dashboards, and Jaeger trace UI for visualising mesh health.', keyPoints: ['Kiali graph topology', 'Traffic flow animation', 'Grafana service dashboards', 'Jaeger trace timeline', 'Alerting on error rate'], available: true },
  { title: 'Kubernetes Gateway API', route: '/service-mesh/gateway-api', badge: 'Gateway API', description: 'The successor to Ingress — Gateway, HTTPRoute, GRPCRoute, and TCPRoute CRDs.', keyPoints: ['GatewayClass and Gateway', 'HTTPRoute routing rules', 'Role-based route ownership', 'Supports weighted routing', 'Istio and Envoy Gateway support'], available: true },
  { title: 'Ingress Gateway', route: '/service-mesh/ingress-gateway', badge: 'Gateway API', description: 'Istio Gateway and VirtualService for north-south traffic, TLS termination, and SNI routing.', keyPoints: ['Istio Gateway resource', 'VirtualService with gateway binding', 'TLS termination configuration', 'SNI-based routing', 'Expose via LoadBalancer'], available: true },
  { title: 'Service Mesh Performance', route: '/service-mesh/performance', badge: 'Reference', description: 'Latency overhead, memory cost per sidecar, tuning Envoy, and deciding when to skip the mesh.', keyPoints: ['Sidecar latency overhead', 'Memory per Envoy process', 'Envoy concurrency tuning', 'Selective injection', 'Ambient mesh sidecar-less option'], available: true },
  { title: 'Envoy Proxy Deep Dive', route: '/service-mesh/envoy', badge: 'Istio', description: 'Envoy architecture — listeners, routes, clusters, endpoints, filters, and the xDS API.', keyPoints: ['LDS → RDS → CDS → EDS discovery chain', 'HTTP filters: router, rate-limit, JWT, WASM', 'Access log format and sampling', 'Admin API: /stats, /config_dump, /clusters', 'Hot restart for zero-downtime config reload'], available: true },
  { title: 'Ambient Mesh', route: '/service-mesh/ambient-mesh', badge: 'Foundations', description: 'Istio ambient mode — ztunnel L4 layer without sidecars, waypoint proxies for L7, and reduced overhead.', keyPoints: ['No sidecar injection needed', 'ztunnel: node-level L4 mTLS transparently', 'Waypoint proxy: optional L7 per service', '60-90% memory reduction vs sidecar', 'Label: istio.io/dataplane-mode=ambient'], available: true },
  { title: 'Multi-cluster Mesh', route: '/service-mesh/multi-cluster', badge: 'Foundations', description: 'Extend the service mesh across clusters — Istio multi-cluster models, east-west gateway, and trust.', keyPoints: ['Primary-remote vs multi-primary models', 'East-west gateway for cross-cluster traffic', 'Shared trust domain with common root CA', 'ServiceEntry for cross-cluster endpoints', 'Locality load balancing prefers local cluster'], available: true },
  { title: 'Consul Connect', route: '/service-mesh/consul', badge: 'Reference', description: 'HashiCorp Consul as a service mesh — service discovery, Connect intentions, and multi-platform support.', keyPoints: ['Consul catalog: service registry + health checks', 'Connect: sidecar proxies with mTLS', 'Intentions: allow/deny service-to-service rules', 'Works outside Kubernetes (VMs, bare metal)', 'Consul Dataplane: lightweight mode for K8s'], available: true },
  { title: 'Service Mesh Cheat Sheet', route: '/service-mesh/cheatsheet', badge: 'Reference', description: 'Istio CRDs, istioctl commands, mTLS modes, and traffic management YAML quick reference.', keyPoints: ['Key CRDs: VirtualService, DestinationRule, Gateway, AuthorizationPolicy', 'istioctl analyze; istioctl proxy-status; istioctl dashboard kiali', 'PeerAuthentication modes: DISABLE, PERMISSIVE, STRICT'], available: true },
  { title: 'Service Mesh Interview Prep', route: '/service-mesh/interview-prep', badge: 'Reference', description: '30+ service mesh interview questions — sidecar pattern, mTLS, traffic management, and observability.', keyPoints: ['What problem does a service mesh solve that a service itself cannot?', 'Explain the difference between a Gateway and a VirtualService', 'How does ambient mesh eliminate sidecar overhead?'], available: true },
];

@Component({ selector: 'app-service-mesh-home', standalone: true, imports: [RouterLink], templateUrl: './home.html', styleUrl: './home.scss' })
export class ServiceMeshHome {
  activeFilter = signal('All');
  expandedCard = signal<string | null>(null);
  topics = computed(() => { const f = this.activeFilter(); return f === 'All' ? ALL_TOPICS : ALL_TOPICS.filter(t => t.badge === f); });
  filters = GROUP_ORDER;
  counts = computed(() => { const map: Record<string, number> = { All: ALL_TOPICS.length }; for (const t of ALL_TOPICS) map[t.badge] = (map[t.badge] ?? 0) + 1; return map; });
  availableCount = ALL_TOPICS.filter(t => t.available).length;
  totalCount = ALL_TOPICS.length;
  setFilter(f: string) { this.activeFilter.set(f); }
  badgeCss(badge: string) { return 'badge badge-' + (BADGE_CSS[badge] ?? 'foundations'); }
  toggleCard(key: string, event: Event) { event.preventDefault(); this.expandedCard.update(c => c === key ? null : key); }
}
