import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PageMetaComponent } from '../../../shared/page-meta/page-meta';
import { QuickRefComponent, QuickRefItem } from '../../../shared/quick-ref/quick-ref';
import { TheoryBlockComponent, TheoryPoint } from '../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../shared/code-block/code-block';
import { ChallengeBlockComponent, Challenge } from '../../../shared/challenge-block/challenge-block';
import { QuizBlockComponent, QuizQuestion } from '../../../shared/quiz-block/quiz-block';
import { QnaBlockComponent, QnaItem } from '../../../shared/qna-block/qna-block';
import { PageCompleteComponent } from '../../../shared/page-complete/page-complete';

@Component({
  selector: 'app-sql-sequences',
  standalone: true,
  imports: [
    CommonModule, PageMetaComponent, QuickRefComponent, TheoryBlockComponent,
    CodeBlockComponent, ChallengeBlockComponent, QuizBlockComponent,
    QnaBlockComponent, PageCompleteComponent
  ],
  templateUrl: './sequences.html',
  styleUrls: ['./sequences.scss']
})
export class SqlSequences {

  quickRef: QuickRefItem[] = [
    { name: 'IDENTITY (MSSQL)',        type: 'keyword',  desc: 'Auto-increment column property: IDENTITY(seed, increment)' },
    { name: 'SERIAL / BIGSERIAL (PG)', type: 'keyword',  desc: 'PostgreSQL shorthand for auto-increment (creates a sequence)' },
    { name: 'GENERATED ALWAYS AS IDENTITY', type: 'keyword', desc: 'SQL:2003 standard identity; works in both MSSQL & PG' },
    { name: 'CREATE SEQUENCE',         type: 'keyword',  desc: 'Standalone, shareable counter object' },
    { name: 'NEXT VALUE FOR (MSSQL)',   type: 'function', desc: 'Get next value from a named sequence' },
    { name: 'nextval() (PG)',           type: 'function', desc: 'PostgreSQL: get next value from a sequence' },
    { name: 'SCOPE_IDENTITY() (MSSQL)', type: 'function', desc: 'Last identity value in the current scope' },
    { name: 'RETURNING id (PG)',        type: 'keyword',  desc: 'Retrieve generated key after INSERT in PostgreSQL' },
  ];

  theory: TheoryPoint[] = [
    {
      heading: 'IDENTITY vs SEQUENCE',
      points: [
        'IDENTITY (MSSQL) / SERIAL (PG) are column properties that auto-generate values — each table gets its own independent counter.',
        'SEQUENCE is a standalone database object. Multiple tables or columns can share one sequence, and you can call it independently of a table.',
        'GENERATED ALWAYS AS IDENTITY (SQL:2003 standard) is now available in both MSSQL (2012+) and PostgreSQL (10+) and preferred over SERIAL/IDENTITY for new schemas.',
      ]
    },
    {
      heading: 'IDENTITY in MSSQL',
      points: [
        'Column declared as INT IDENTITY(1,1) — seed is the start value, increment is the step.',
        'After INSERT: SCOPE_IDENTITY() returns the last generated value in the current scope; @@IDENTITY returns the last in the session (may differ if a trigger fired).',
        'DBCC CHECKIDENT (\'table\', RESEED, N) resets the counter; use with caution in production.',
      ]
    },
    {
      heading: 'SERIAL and sequences in PostgreSQL',
      points: [
        'SERIAL is shorthand — it creates a sequence behind the scenes and sets the column DEFAULT to nextval(seq).',
        'GENERATED ALWAYS AS IDENTITY prevents manual inserts into the identity column (use GENERATED BY DEFAULT if you need to override).',
        'Create a standalone sequence: CREATE SEQUENCE seq_order_id START 1000 INCREMENT 10 CACHE 20;',
      ]
    },
    {
      heading: 'Gaps in sequences',
      points: [
        'Sequences are not transactional — a rolled-back INSERT still consumes the value, creating gaps.',
        'CACHE N pre-allocates N values in memory; server restart can skip up to N values.',
        'Gaps are normal and expected. Never use identity/sequence values to count rows or detect missing data.',
      ]
    },
    {
      heading: 'Retrieving generated keys',
      points: [
        'MSSQL: INSERT … OUTPUT INSERTED.id or SELECT SCOPE_IDENTITY() immediately after INSERT.',
        'PostgreSQL: INSERT … RETURNING id; — cleaner and atomic.',
        'JDBC/ADO.NET: use getGeneratedKeys() / ExecuteScalarAsync() to retrieve the new key without a second round-trip.',
      ]
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'MSSQL IDENTITY',
      language: 'sql',
      code: `-- IDENTITY column
CREATE TABLE orders (
    order_id   INT  IDENTITY(1,1) PRIMARY KEY,
    customer   VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT GETDATE()
);

-- Insert without specifying order_id
INSERT INTO orders (customer) VALUES ('Alice'), ('Bob');

-- Retrieve the last generated key (current scope)
SELECT SCOPE_IDENTITY() AS new_order_id;

-- OUTPUT clause: get key in the same statement
INSERT INTO orders (customer)
OUTPUT INSERTED.order_id
VALUES ('Carol');

-- Reset the counter (dev/test only)
DBCC CHECKIDENT ('orders', RESEED, 0);`
    },
    {
      label: 'PostgreSQL IDENTITY / SERIAL',
      language: 'sql',
      code: `-- Preferred: SQL standard GENERATED ALWAYS AS IDENTITY
CREATE TABLE orders (
    order_id   INT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer   TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Insert; RETURNING retrieves the generated id
INSERT INTO orders (customer)
VALUES ('Alice'), ('Bob')
RETURNING order_id;

-- GENERATED BY DEFAULT: allows manual override
CREATE TABLE legacy_orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer TEXT NOT NULL
);
INSERT INTO legacy_orders (order_id, customer)
OVERRIDING SYSTEM VALUE VALUES (9999, 'Manual');

-- Old SERIAL shorthand (still common)
CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,
    name       TEXT NOT NULL
);`
    },
    {
      label: 'Standalone SEQUENCE',
      language: 'sql',
      code: `-- Create a shared sequence
-- PostgreSQL
CREATE SEQUENCE seq_invoice_no
    START WITH 100000
    INCREMENT BY 1
    NO CYCLE
    CACHE 50;

-- Use in a column DEFAULT
CREATE TABLE invoices (
    invoice_no INT DEFAULT nextval('seq_invoice_no') PRIMARY KEY,
    customer   TEXT
);

-- Or call directly for a batch of IDs
SELECT nextval('seq_invoice_no');  -- 100000
SELECT nextval('seq_invoice_no');  -- 100001

-- Peek without incrementing (current value)
SELECT currval('seq_invoice_no');  -- same session only

-- MSSQL equivalent
CREATE SEQUENCE dbo.seq_invoice_no
    AS INT START WITH 100000 INCREMENT BY 1 CACHE 50;

SELECT NEXT VALUE FOR dbo.seq_invoice_no;   -- 100000

-- Use in column DEFAULT (MSSQL)
CREATE TABLE invoices (
    invoice_no INT DEFAULT (NEXT VALUE FOR dbo.seq_invoice_no) PRIMARY KEY,
    customer   NVARCHAR(200)
);`
    },
    {
      label: 'Gaps & best practices',
      language: 'sql',
      code: `-- Sequences are NOT gapless:
-- 1. Rolled-back transactions still consume values.
-- 2. CACHE means server restart can skip up to CACHE values.
-- 3. Concurrent inserts may arrive out of order.

-- If you need gapless invoice numbers (legal requirement):
-- Use a separate "counter" table with SELECT … FOR UPDATE / UPDLOCK
-- *** PostgreSQL gapless pattern ***
CREATE TABLE invoice_counter (last_no INT NOT NULL DEFAULT 0);
INSERT INTO invoice_counter VALUES (0);

-- In a transaction:
BEGIN;
UPDATE invoice_counter SET last_no = last_no + 1;
SELECT last_no FROM invoice_counter;  -- your gapless number
COMMIT;

-- *** MSSQL gapless pattern ***
BEGIN TRAN;
UPDATE invoice_counter WITH (UPDLOCK) SET last_no = last_no + 1;
SELECT last_no FROM invoice_counter;
COMMIT TRAN;
-- Warning: gapless counters serialise inserts — high contention at scale.`
    },
  ];

  challenge: Challenge = {
    title: 'Shared sequence for order & invoice IDs',
    language: 'sql',
    description: 'Create a single shared sequence seq_doc_id starting at 1, then use it as the DEFAULT for both an orders table and an invoices table so that order IDs and invoice IDs never collide. After creation, write an INSERT into each table using RETURNING (PostgreSQL) or OUTPUT (MSSQL) to capture the generated IDs.',
    hints: [
      'Create the sequence first, then reference it in the DEFAULT of each table.',
      'PostgreSQL: nextval(\'seq_doc_id\') as the DEFAULT expression.',
      'PostgreSQL INSERT … RETURNING id; MSSQL INSERT … OUTPUT INSERTED.id.',
    ],
    starterCode: `-- Create the shared sequence
CREATE SEQUENCE seq_doc_id START WITH 1 INCREMENT BY 1;

-- orders table using seq_doc_id
CREATE TABLE orders (
    -- your columns here
);

-- invoices table using the same seq_doc_id
CREATE TABLE invoices (
    -- your columns here
);

-- Insert into each and retrieve the generated IDs`,
    solution: `-- PostgreSQL
CREATE SEQUENCE seq_doc_id START WITH 1 INCREMENT BY 1;

CREATE TABLE orders (
    order_id   INT DEFAULT nextval('seq_doc_id') PRIMARY KEY,
    customer   TEXT NOT NULL
);

CREATE TABLE invoices (
    invoice_id INT DEFAULT nextval('seq_doc_id') PRIMARY KEY,
    amount     NUMERIC(10,2) NOT NULL
);

INSERT INTO orders (customer) VALUES ('Alice') RETURNING order_id;
-- returns 1

INSERT INTO invoices (amount) VALUES (299.99) RETURNING invoice_id;
-- returns 2  (never collides with order_id = 1)`
  };

  quiz: QuizQuestion[] = [
    {
      q: 'Why does a rolled-back INSERT still cause a gap in an IDENTITY column?',
      options: [
        'The database reserves values before the transaction starts',
        'Sequences allocate values outside the transaction to avoid locking — rollback cannot return them',
        'IDENTITY columns increment on SELECT, not INSERT',
        'It only happens with CACHE > 1'
      ],
      answer: 1,
      explanation: 'Sequence/identity values are generated outside any transaction to prevent blocking. A rollback cannot "un-consume" the value, so gaps are a normal and expected behaviour.'
    },
    {
      q: 'What is the difference between SCOPE_IDENTITY() and @@IDENTITY in MSSQL?',
      options: [
        'SCOPE_IDENTITY() returns the last value in the session; @@IDENTITY returns the current scope only',
        'SCOPE_IDENTITY() returns the last value in the current scope; @@IDENTITY includes values from triggers fired in the same session',
        'They are identical — both return the last generated value',
        'SCOPE_IDENTITY() works only with sequences; @@IDENTITY works with IDENTITY columns'
      ],
      answer: 1,
      explanation: '@@IDENTITY returns the last identity generated in the current session including any triggered inserts. SCOPE_IDENTITY() is scoped to the current statement/procedure, making it safer to use.'
    },
    {
      q: 'Which PostgreSQL syntax retrieves a generated key in the same INSERT statement?',
      options: ['SELECT LAST_INSERT_ID()', 'SELECT @@IDENTITY', 'INSERT … RETURNING id', 'SELECT currval(seq)'],
      answer: 2,
      explanation: 'INSERT … RETURNING col is PostgreSQL\'s atomic way to get back generated or computed column values without a second query. It works for any column, not just identity.'
    },
    {
      q: 'GENERATED ALWAYS AS IDENTITY vs GENERATED BY DEFAULT AS IDENTITY — what is the difference?',
      options: [
        'ALWAYS forbids manual value insertion; BY DEFAULT allows overriding with OVERRIDING SYSTEM VALUE',
        'ALWAYS uses a sequence; BY DEFAULT uses a table counter',
        'They are synonyms — no functional difference',
        'ALWAYS works in PostgreSQL; BY DEFAULT is MSSQL-only'
      ],
      answer: 0,
      explanation: 'GENERATED ALWAYS rejects explicit values in INSERT/UPDATE. GENERATED BY DEFAULT allows you to supply a manual value using OVERRIDING SYSTEM VALUE, which is useful during data migrations.'
    },
    {
      q: 'How do you peek at the next sequence value without consuming it in PostgreSQL?',
      options: [
        'SELECT currval(\'seq\')',
        'There is no way to see the next value without consuming it',
        'SELECT last_value + increment_by FROM seq_name',
        'SELECT nextval(\'seq\') but within a SAVEPOINT that you roll back'
      ],
      answer: 2,
      explanation: 'Querying the sequence relation directly (SELECT last_value, increment_by FROM my_sequence) shows the current state without advancing it. Note: currval() returns the last value consumed in the current session; it errors if nextval has not been called this session.'
    },
    {
      q: 'What does CYCLE do on a sequence and when should you use it?',
      options: [
        'Makes the sequence restart from MINVALUE after reaching MAXVALUE — useful for cyclic IDs like day-of-week counters or short-lived identifiers',
        'CYCLE makes the sequence increment in a circular pattern (e.g., 1, 2, 3, 1, 2, 3)',
        'CYCLE enables the sequence to be used across multiple databases',
        'CYCLE is the default behaviour — NO CYCLE must be specified to prevent wrap-around'
      ],
      answer: 0,
      explanation: 'CYCLE allows the sequence to wrap around from MAXVALUE back to MINVALUE. Only use it when you are certain old values have been consumed/deleted and collisions are impossible — for example, a short-lived session token counter that is always cleared before cycling.'
    },
  ];

  qna: QnaItem[] = [
    {
      q: 'Can I reset an IDENTITY or sequence without gaps?',
      a: 'You can reseed (MSSQL: DBCC CHECKIDENT; PG: ALTER SEQUENCE … RESTART WITH N) but any future value may collide with existing rows if the table is not empty. Always truncate or ensure the table is empty first, or set the restart value above MAX(id).',
    },
    {
      q: 'What is CACHE on a sequence and when should I change it?',
      a: 'CACHE N pre-allocates N values in memory per server node, reducing disk I/O per call. The default (often 1 or 20) is safe but slow at very high INSERT rates. Increase CACHE for high-throughput bulk loads. The trade-off: if the server restarts, up to N values are lost, creating larger gaps.',
    },
    {
      q: 'When should I use a standalone SEQUENCE instead of IDENTITY/SERIAL?',
      a: 'Use a standalone SEQUENCE when: (1) multiple tables need non-colliding IDs from one counter, (2) you want to pre-generate a batch of IDs before INSERT, or (3) you need full control over increment, min/max, cycling, and caching independently of any table.',
    },
    {
      q: 'Why does a sequence not guarantee gap-free IDs even without rollbacks?',
      a: 'Sequences allocate values outside any transaction to prevent contention. If a server process pre-fetches CACHE N values and then crashes, those values are permanently lost. Similarly, multi-threaded applications reserve values in parallel and write them in a different order — so committed IDs appear out of sequence. Gap-free monotonic IDs require a serialised counter (e.g., a table-based counter with locking) at the cost of serialised throughput.',
    },
    {
      q: 'How do you coordinate sequence values across multiple application servers?',
      a: 'Sequences are server-side objects — all application servers share the same sequence by calling nextval()/NEXT VALUE FOR through their database connections. The database serialises sequence allocation internally. With CACHE, each connection pre-fetches a range, so values may be non-contiguous across connections but are globally unique.',
    },
    {
      q: 'When should I prefer a UUID over a sequence/identity for primary keys?',
      a: 'UUIDs are globally unique without coordination, making them ideal for distributed systems, offline inserts, and cross-database merges. Drawbacks: 16 bytes vs 4–8 bytes (larger indexes), random UUIDs (v4) fragment B-tree indexes causing page splits. UUID v7 (time-ordered) or NEWSEQUENTIALID() in MSSQL mitigate fragmentation. Use sequences when the database is the single source of truth; use UUIDs when multiple systems generate IDs independently.',
    },
  ];
}
