import { Component, signal, computed } from '@angular/core';
import { RouterLink } from '@angular/router';

interface Topic { title: string; route: string; badge: string; description: string; keyPoints: string[]; available: boolean; }

const BADGE_CSS: Record<string, string> = {
  'Foundations': 'foundations', 'Resources': 'resources', 'State': 'state',
  'Modules': 'modules', 'Advanced': 'advanced', 'Reference': 'reference',
};
const GROUP_ORDER = ['All', 'Foundations', 'Resources', 'State', 'Modules', 'Advanced', 'Reference'];

const ALL_TOPICS: Topic[] = [
  { title: 'Terraform Fundamentals', route: '/terraform/fundamentals', badge: 'Foundations', description: 'HCL syntax, terraform init/plan/apply/destroy, providers, and the IaC mental model.', keyPoints: ['HCL blocks, arguments, expressions', 'terraform init downloads providers', 'terraform plan — preview changes', 'terraform apply — provision infra', 'State tracks real-world resources'], available: true },
  { title: 'Providers', route: '/terraform/providers', badge: 'Foundations', description: 'Provider configuration, version constraints, required_providers, and the Terraform Registry.', keyPoints: ['required_providers block', 'source = "hashicorp/aws"', 'version = "~> 5.0" constraints', 'provider alias for multi-region', 'terraform.required_version'], available: true },
  { title: 'Variables & Locals', route: '/terraform/variables', badge: 'Foundations', description: 'Input variables, local values, type constraints, validation rules, and variable precedence.', keyPoints: ['variable "name" { type, default }', 'locals { computed expressions }', 'Type constraints: string, number, bool, list, map, object', 'Variable validation rules', 'Precedence: CLI > env > .tfvars'], available: true },
  { title: 'Outputs', route: '/terraform/outputs', badge: 'Foundations', description: 'Output values, sensitive outputs, cross-module output references, and terraform output command.', keyPoints: ['output "name" { value = ... }', 'sensitive = true masks values', 'Cross-module: module.name.output', 'terraform output -json', 'Remote state outputs'], available: true },
  { title: 'Resources & Meta-Arguments', route: '/terraform/resources', badge: 'Resources', description: 'Resource blocks, meta-arguments (count, for_each, depends_on, lifecycle, provider), and resource addressing.', keyPoints: ['resource "aws_instance" "web" {}', 'count and count.index', 'for_each with maps and sets', 'depends_on explicit dependency', 'lifecycle: create_before_destroy'], available: true },
  { title: 'Data Sources', route: '/terraform/data-sources', badge: 'Resources', description: 'data blocks for querying existing infrastructure — AMIs, VPCs, secrets, and read-only lookups.', keyPoints: ['data "aws_ami" "latest" {}', 'data.aws_ami.latest.id reference', 'Filtering with filters block', 'External data source', 'Remote state data source'], available: true },
  { title: 'Expressions & Dynamic Blocks', route: '/terraform/expressions', badge: 'Resources', description: 'Conditional expressions, for expressions, splat operators, dynamic blocks, and templatefile().', keyPoints: ['condition ? true_val : false_val', 'for s in list : s.attr', 'Splat: aws_instance.web[*].id', 'dynamic "ingress" { for_each = ... }', 'templatefile() for config templates'], available: true },
  { title: 'Built-in Functions', route: '/terraform/functions', badge: 'Resources', description: 'String, collection, numeric, encoding, filesystem, and IP network functions in Terraform HCL.', keyPoints: ['toset(), tolist(), tomap()', 'length(), merge(), flatten()', 'lookup(map, key, default)', 'format(), formatlist(), join()', 'cidrsubnet() and cidrhost()'], available: true },
  { title: 'Terraform State', route: '/terraform/state', badge: 'State', description: 'State file anatomy, terraform.tfstate, state locking, sensitive data in state, and state commands.', keyPoints: ['terraform.tfstate JSON format', 'terraform state list', 'terraform state show resource', 'State locking prevents concurrent runs', 'Sensitive values are plaintext in state'], available: true },
  { title: 'Remote Backends', route: '/terraform/remote-backends', badge: 'State', description: 'S3+DynamoDB, Azure Blob, GCS, and Terraform Cloud backends — remote state storage and locking.', keyPoints: ['backend "s3" with DynamoDB lock', 'backend "azurerm" Blob Storage', 'terraform init -migrate-state', 'Partial backend config', 'Terraform Cloud remote backend'], available: true },
  { title: 'Workspaces', route: '/terraform/workspaces', badge: 'State', description: 'Terraform workspaces for environment isolation — terraform.workspace, switching, and limitations.', keyPoints: ['terraform workspace new dev', 'terraform workspace select prod', 'terraform.workspace in expressions', 'Separate state per workspace', 'Workspaces vs directories debate'], available: true },
  { title: 'Modules', route: '/terraform/modules', badge: 'Modules', description: 'Module structure, source types (local, registry, Git), inputs, outputs, and module versioning.', keyPoints: ['module "vpc" { source = "./../modules/vpc" }', 'Registry: source = "terraform-aws-modules/vpc/aws"', 'module.name.output_name reference', 'version = "3.0.0" for registry modules', 'Child module variables and outputs'], available: true },
  { title: 'Module Patterns', route: '/terraform/module-patterns', badge: 'Modules', description: 'Root vs child modules, module composition, feature flags, optional objects, and module testing.', keyPoints: ['Root module = entry point', 'Composition: modules calling modules', 'Feature flags with nullable variables', 'object({ }) type constraints in modules', 'Module testing with terraform test'], available: true },
  { title: 'Provisioners', route: '/terraform/provisioners', badge: 'Advanced', description: 'local-exec, remote-exec, file provisioner — when to use them and better alternatives.', keyPoints: ['local-exec runs on operator machine', 'remote-exec requires SSH/WinRM connection', 'file transfers files to remote host', 'connection block configuration', 'Provisioners are a last resort'], available: true },
  { title: 'Import & Generated Config', route: '/terraform/import', badge: 'Advanced', description: 'terraform import, import blocks, terraform plan -generate-config-out, and migrating existing infra.', keyPoints: ['terraform import resource.name id', 'import {} block (Terraform 1.5+)', '-generate-config-out=generated.tf', 'Iterative import workflow', 'Bringing legacy infra under Terraform'], available: true },
  { title: 'CI/CD with Terraform', route: '/terraform/cicd', badge: 'Advanced', description: 'GitHub Actions, GitLab CI, atlantis, terraform plan/apply in pipelines, and environment promotion.', keyPoints: ['GitHub Actions: hashicorp/setup-terraform', 'Plan on PR, apply on merge', 'Atlantis pull request automation', 'OIDC auth (no long-lived secrets)', 'Environment promotion with workspaces'], available: true },
  { title: 'Testing Terraform Code', route: '/terraform/testing', badge: 'Advanced', description: 'terraform validate, terraform test (native), Terratest, checkov, and testing strategies.', keyPoints: ['terraform validate syntax check', 'terraform test native framework (1.6+)', 'Terratest Go-based integration tests', 'checkov static analysis', 'Unit vs integration vs e2e testing'], available: true },
  { title: 'Security & Compliance', route: '/terraform/security', badge: 'Advanced', description: 'Secrets management, tfsec, Sentinel policies, OPA, least-privilege IAM, and Vault integration.', keyPoints: ['Never hardcode secrets in HCL', 'AWS SSM / Vault for secrets', 'tfsec static security scanning', 'HashiCorp Sentinel policy-as-code', 'OPA with Conftest for policy checks'], available: true },
  { title: 'Drift Detection', route: '/terraform/drift', badge: 'Advanced', description: 'terraform plan to detect drift, refresh-only plans, preventing and remediating configuration drift.', keyPoints: ['terraform plan detects drift by default', 'terraform plan -refresh-only', 'terraform refresh (deprecated)', 'Automated drift detection in CI', 'Remediating vs ignoring drift'], available: true },
  { title: 'Refactoring & State Ops', route: '/terraform/refactoring', badge: 'Advanced', description: 'terraform state mv, rm, replace, moved blocks, and safely restructuring Terraform configurations.', keyPoints: ['moved {} block (Terraform 1.1+)', 'terraform state mv old new', 'terraform state rm to untrack', 'terraform taint / replace', 'Breaking out monoliths safely'], available: true },
  { title: 'OpenTofu', route: '/terraform/opentofu', badge: 'Advanced', description: 'OpenTofu — the OSS Terraform fork, feature parity, provider-defined functions, and migration path.', keyPoints: ['MPL → BSL license change drove fork', 'tofu init / plan / apply commands', 'Provider-defined functions (unique feature)', 'State encryption (OpenTofu 1.7+)', 'Migration: mostly drop-in replacement'], available: true },
  { title: 'Terraform Cheatsheet', route: '/terraform/cheatsheet', badge: 'Reference', description: 'Quick reference — CLI commands, HCL syntax, meta-arguments, and common provider resource types.', keyPoints: ['terraform init/plan/apply/destroy', 'State, workspace, and import commands', 'HCL syntax quick reference', 'Common AWS/Azure resource types', 'Provider version constraints'], available: true },
  { title: 'Terraform Interview Prep', route: '/terraform/interview-prep', badge: 'Reference', description: 'Interview questions covering state, modules, backends, workspaces, drift, and IaC best practices.', keyPoints: ['State locking and remote backends', 'Workspaces vs directory structure', 'Modules and composition patterns', 'Drift detection and remediation', 'Security and secrets management'], available: true },
];

@Component({ selector: 'app-terraform-home', standalone: true, imports: [RouterLink], templateUrl: './home.html', styleUrl: './home.scss' })
export class TerraformHome {
  activeFilter = signal('All');
  expandedCard = signal<string | null>(null);
  topics = computed(() => { const f = this.activeFilter(); return f === 'All' ? ALL_TOPICS : ALL_TOPICS.filter(t => t.badge === f); });
  filters = GROUP_ORDER;
  counts = computed(() => { const map: Record<string, number> = { All: ALL_TOPICS.length }; for (const t of ALL_TOPICS) map[t.badge] = (map[t.badge] ?? 0) + 1; return map; });
  availableCount = ALL_TOPICS.filter(t => t.available).length;
  totalCount = ALL_TOPICS.length;
  setFilter(f: string) { this.activeFilter.set(f); }
  badgeCss(badge: string) { return 'badge badge-' + (BADGE_CSS[badge] ?? 'foundations'); }
  toggleCard(key: string, event: Event) { event.preventDefault(); this.expandedCard.update(c => c === key ? null : key); }
}
