// Regenerates src/app/data/hub-<key>.ts (breadcrumb labels, search entries, sidebar data)
// from the hub config plus any page specs found in tools/phase11/pages/<key>/*.js
const fs = require('fs'), path = require('path');
module.exports = function writeDataFile(cfg, root) {
  const C = cfg.constName, dir = path.join(root, 'tools/phase11/pages', cfg.key);
  const specs = {};
  if (fs.existsSync(dir)) for (const f of fs.readdirSync(dir)) if (f.endsWith('.js')) {
    const p = path.join(dir, f); delete require.cache[require.resolve(p)];
    const s = require(p); specs[s.slug] = s;
  }
  const plain = x => x.replace(/`([^`]+)`/g, '$1');
  const labels = {}, search = [], sidebar = {};
  const topics = cfg.topics;
  topics.forEach((t, i) => {
    labels[t.slug] = t.title;
    search.push({ route: cfg.searchPrefix + t.slug, title: t.title, section: cfg.sectionLabel, difficulty: t.difficulty, keywords: t.keywords });
    const s = specs[t.slug] || {};
    const related = [];
    const prev = topics[i - 1], next = topics[i + 1];
    if (prev) related.push({ label: prev.title + ' — previous', route: `/${cfg.route}/${prev.slug}` });
    if (next) related.push({ label: next.title + ' — next', route: `/${cfg.route}/${next.slug}` });
    related.push({ label: cfg.name + ' Home', route: '/' + cfg.route });
    sidebar[`${cfg.route}/${t.slug}`] = {
      apis: s.apis || cfg.sidebarDefault.apis,
      related: s.related || related,
      tip: plain(s.tip || cfg.sidebarDefault.tip),
      docs: s.docs || cfg.sidebarDefault.docs,
      resources: s.resources || cfg.sidebarDefault.resources,
      gotchas: (s.gotchas || cfg.sidebarDefault.gotchas).map(plain),
    };
  });
  search.push({ route: 'hub-' + cfg.route, title: cfg.name, section: cfg.hubSection, difficulty: 'intermediate', keywords: cfg.hubKeywords });
  const defRelated = [{ label: cfg.name + ' Home', route: '/' + cfg.route }].concat(topics.slice(0, 4).map(t => ({ label: t.title, route: `/${cfg.route}/${t.slug}` })));
  const def = Object.assign({}, cfg.sidebarDefault, { related: defRelated });
  const J = v => JSON.stringify(v, null, 2);
  const out = `// AUTO-GENERATED by tools/phase11 — do not edit by hand; edit the config/page specs and re-run.
import type { SidebarData } from '../components/shared/page-sidebar/page-sidebar';
import type { SearchEntry } from '../services/search.service';

export const ${C}_LABELS: Record<string, string> = ${J(labels)};

export const ${C}_SEARCH: SearchEntry[] = ${J(search)};

export const ${C}_DEFAULT: SidebarData = ${J(def)};

export const ${C}_SIDEBAR: Record<string, SidebarData> = ${J(sidebar)};
`;
  fs.writeFileSync(path.join(root, `src/app/data/hub-${cfg.key}.ts`), out);
};
