import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PageMetaComponent } from '../../../shared/page-meta/page-meta';
import { QuickRefComponent, QuickRefItem } from '../../../shared/quick-ref/quick-ref';
import { TheoryBlockComponent, TheoryPoint } from '../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../shared/code-block/code-block';
import { CommonMistakesComponent, CommonMistake } from '../../../shared/common-mistakes/common-mistakes';
import { ChallengeBlockComponent, Challenge } from '../../../shared/challenge-block/challenge-block';
import { QuizBlockComponent, QuizQuestion } from '../../../shared/quiz-block/quiz-block';
import { QnaBlockComponent, QnaItem } from '../../../shared/qna-block/qna-block';
import { RevisionCardComponent, RevisionSummary } from '../../../shared/revision-card/revision-card';
import { PageCompleteComponent } from '../../../shared/page-complete/page-complete';

@Component({
  selector: 'app-azure-security-defender',
  standalone: true,
  imports: [CommonModule, PageMetaComponent, QuickRefComponent, TheoryBlockComponent, CodeBlockComponent,
    CommonMistakesComponent, ChallengeBlockComponent, QuizBlockComponent, QnaBlockComponent,
    RevisionCardComponent, PageCompleteComponent],
  templateUrl: './security-defender.html',
  styleUrl: './security-defender.scss'
})
export class AzureSecurityDefender {

  quickRef: QuickRefItem[] = [
    { name: 'Microsoft Defender for Cloud', type: 'type', desc: 'Unified cloud security posture management (CSPM) and cloud workload protection platform (CWPP). Free tier: foundational recommendations. Defender plans: advanced threat protection per resource type.' },
    { name: 'Secure Score', type: 'type', desc: 'A 0–100% metric showing how well your environment follows Microsoft security recommendations. Higher is better. Grouped by security controls — each control has a max points value. Fixing recommendations raises the score.' },
    { name: 'Security Recommendation', type: 'type', desc: 'Specific actionable findings: "Enable MFA on accounts with owner permissions", "Remediate vulnerabilities in container images". Each recommendation has severity (High/Medium/Low) and potential score increase.' },
    { name: 'Defender Plan', type: 'type', desc: 'Per-resource-type threat protection plans: Defender for Servers, SQL, Containers, Storage, Key Vault, App Service, etc. Each is enabled/disabled per subscription or resource. Adds threat alerts and advanced scanning.' },
    { name: 'Just-in-Time (JIT) VM Access', type: 'type', desc: 'Locks down RDP/SSH ports (3389/22) by default. Requests for access open the port for a limited time (default 3h) for a specific source IP only — reducing attack surface dramatically.' },
    { name: 'Security Alert', type: 'type', desc: 'A threat detection finding: brute-force attack, crypto mining, malware, suspicious process execution. Generated by Defender plans. Each alert has severity, affected resource, and remediation steps.' },
    { name: 'Regulatory Compliance', type: 'type', desc: 'Dashboard mapping Azure recommendations to compliance frameworks (PCI DSS, ISO 27001, SOC 2, NIST, CIS). Shows which controls are passing/failing and generates compliance reports.' },
  ];

  theory: TheoryPoint[] = [
    {
      heading: 'Defender for Cloud Architecture',
      points: [
        'Microsoft Defender for Cloud (formerly Azure Security Center + Azure Defender) has two layers: (1) Cloud Security Posture Management (CSPM): continuously evaluates resource configurations against security best practices and regulations — produces the Secure Score. (2) Cloud Workload Protection Platform (CWPP): runtime threat detection, vulnerability scanning, and security alerts — provided by Defender plans.',
        'Free tier (CSPM): available to all subscriptions automatically. Provides: Secure Score, security recommendations, Azure Policy compliance, network map, and basic cloud security posture. No cost, no installation — Defender for Cloud reads ARM/resource metadata.',
        'Defender plans (CWPP): paid per resource type, typically per VM/hour or per storage GB. Each plan adds specific protection: Servers (agent-based EDR, threat detection), SQL (SQL injection detection, anomalous access), Containers (Kubernetes threat detection, image vulnerability scanning), Storage (malware scanning, sensitive data discovery), App Service (threat detection on web app traffic), Key Vault (anomalous access alerts).',
        'The legacy Log Analytics Agent (MMA) was fully retired on August 31, 2024 — it is no longer supported or installable from the portal. Defender for Servers Plan 2 has moved to agentless scanning for vulnerability and secrets detection instead of relying on an installed agent; where in-VM telemetry is still needed, deploy the Azure Monitor Agent (AMA) via Data Collection Rules, not MMA.',
        'Multi-cloud and hybrid: Defender for Cloud supports AWS and GCP via connectors (Azure Arc for on-premises). AWS connector discovers EC2, S3, RDS, EKS resources and applies Defender recommendations to them. Provides a single-pane-of-glass view across cloud environments.',
      ]
    },
    {
      heading: 'Secure Score & Recommendations',
      points: [
        'Secure Score formula: (points earned across all controls) / (max points across all applicable controls) × 100. Each security control has a max score (e.g., "Enable MFA" = 10 points). Fulfilling ALL recommendations in a control grants its full points. Partial fulfilment is proportional.',
        'Security controls group related recommendations: "Enable MFA", "Apply system updates", "Restrict unauthorized network access", "Enable endpoint protection", etc. Each control shows: current score, max score, number of unhealthy resources, and the recommendations to fix.',
        'Recommendation states: Healthy (compliant), Unhealthy (non-compliant — contributes to low score), Not applicable (resource type doesn\'t apply), Exempted (manually exempted with a business justification). Exemptions pause a recommendation from affecting the score for a set period.',
        'Quick fixes: many recommendations have a "Fix" button that remediates the issue directly from the Defender portal — e.g., enable disk encryption, enable MFA, apply a missing NSG. For bulk remediation, use Logic Apps triggered by Defender recommendations.',
        'Continuous export: export security recommendations, secure score data, and alerts to Log Analytics or Event Hub for integration with SIEM tools (Sentinel, Splunk, QRadar). Configure under Defender for Cloud → Environment Settings → Continuous Export.',
      ]
    },
    {
      heading: 'Just-in-Time VM Access & Network Hardening',
      points: [
        'JIT VM Access: when enabled, NSG rules are automatically set to DENY inbound on management ports (RDP 3389, SSH 22, WinRM 5985/5986). When a user requests access, Defender creates a temporary NSG ALLOW rule for their specific source IP for a time-limited window (1–24 hours, default 3 hours). The rule is automatically removed when the time expires.',
        'JIT access workflow: (1) User requests access in Defender portal or via Azure CLI/PowerShell. (2) Defender validates RBAC: user needs "Microsoft.Security/locations/jitNetworkAccessPolicies/initiate/action" permission. (3) NSG rule opens for the specified IP and time window. (4) Rule auto-deleted on expiry. Activity logged in Activity Log and Defender alerts.',
        'Adaptive network hardening: Defender analyses actual network traffic (from NSG flow logs + ML) and recommends tightening NSG rules — e.g., "This NSG allows port 3389 from Any but only connections from 10.0.0.0/8 are seen in 30 days — restrict to that range." Review and apply recommendations to harden network rules based on real traffic patterns.',
        'Adaptive application controls: for Windows VMs, Defender analyses running processes and recommends an allowlist (application control policy). Alerts on processes that are not in the allowlist — reduces malware execution risk. Based on Windows Defender Application Control (WDAC) or AppLocker.',
        'File integrity monitoring (FIM): monitors critical OS files, registry keys, and application files for unexpected changes. Alerts when a monitored file is modified — detects malware persistence, configuration tampering, and insider threats. Configure FIM under Defender for Servers (Plan 2).',
      ]
    },
    {
      heading: 'Security Alerts & Regulatory Compliance',
      points: [
        'Security alerts: generated by Defender plans when threat indicators are detected. Alert types: "Potential reverse shell", "Crypto mining activity detected", "SQL injection attempt", "Suspicious authentication activity", "Lateral movement — pass-the-hash". Each alert has: severity, MITRE ATT&CK tactic, affected resource, evidence, and recommended remediation.',
        'Alert integration: export alerts to: Azure Sentinel (SIEM/SOAR — recommended for correlation across all signals), Event Hub (for SIEM), Logic Apps (for automated response — isolate VM, revoke tokens, notify Slack). Configure suppression rules for known-benign alerts (e.g., pen test activity).',
        'Defender for Containers: vulnerability assessment scans container images in Azure Container Registry (ACR) on push and on a schedule. Identifies CVEs in OS packages and application dependencies. Kubernetes runtime protection: alerts on cryptomining pods, privilege escalation, suspicious API calls to the Kubernetes API server.',
        'Regulatory compliance dashboard: maps Azure security configurations to compliance framework controls. Supported frameworks: PCI DSS 4.0, ISO 27001:2022, SOC 2 Type II, NIST SP 800-53, CIS Azure Foundations Benchmark, HIPAA, Azure Security Benchmark (ASB). Export compliance reports as PDF for auditors. Custom initiatives: create custom Policy initiatives and add them to the compliance dashboard.',
        'Microsoft Sentinel integration: Defender for Cloud acts as a data source for Microsoft Sentinel. Connect the Defender connector in Sentinel to pull all security alerts and recommendations into Sentinel\'s SIEM. Sentinel then correlates Defender alerts with identity signals (Entra ID), network signals (NSG logs), and endpoint signals (Defender for Endpoint) for comprehensive threat detection.',
      ]
    },
    {
      heading: 'Secure Score as an Actionable Security Posture Metric',
      points: [
        'Microsoft Defender for Cloud\'s Secure Score aggregates many individual security recommendations into a single percentage, giving a quick, trackable indicator of overall security posture that can be monitored over time and compared across subscriptions.',
        'Each recommendation contributing to Secure Score comes with specific remediation guidance and impact weighting — recommendations are not all equally important, and the scoring reflects relative risk reduction, helping teams prioritize which gaps to close first.',
        'Secure Score is a POINT-IN-TIME snapshot that changes as new resources are deployed or configurations drift — treating it as a one-time compliance check rather than a continuously monitored metric misses newly introduced misconfigurations.',
        'A high Secure Score reduces but does not eliminate risk — it measures adherence to known best-practice configurations, not protection against zero-day vulnerabilities or application-layer logic flaws that fall outside its recommendation set.',
      ],
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'Enable Defender Plans',
      language: 'bash',
      code: `# Check current Defender pricing tier (free vs standard/paid)
az security pricing list --output table

# Enable Defender for Servers (Plan 2) on a subscription
az security pricing create \\
  --name VirtualMachines \\
  --tier Standard

# Enable Defender for SQL (Azure SQL Databases)
az security pricing create \\
  --name SqlServerVirtualMachines \\
  --tier Standard

# Enable Defender for Containers (AKS + ACR)
az security pricing create \\
  --name Containers \\
  --tier Standard

# Enable Defender for Storage (malware scanning + sensitive data)
az security pricing create \\
  --name StorageAccounts \\
  --tier Standard

# Enable Defender for Key Vault
az security pricing create \\
  --name KeyVaults \\
  --tier Standard

# List all Defender plans and their status
az security pricing list \\
  --query "[].{Name:name, Tier:pricingTier}" \\
  --output table`
    },
    {
      label: 'JIT VM Access',
      language: 'bash',
      code: `# Enable JIT policy on a VM (via Defender for Cloud)
az security jit-policy create \\
  --resource-group my-rg \\
  --location eastus \\
  --name default \\
  --virtual-machines "[{
    'id': '/subscriptions/{sub-id}/resourceGroups/my-rg/providers/Microsoft.Compute/virtualMachines/my-vm',
    'ports': [
      {
        'number': 22,
        'protocol': 'TCP',
        'allowedSourceAddressPrefix': '*',
        'maxRequestAccessDuration': 'PT3H'
      },
      {
        'number': 3389,
        'protocol': 'TCP',
        'allowedSourceAddressPrefix': '*',
        'maxRequestAccessDuration': 'PT3H'
      }
    ]
  }]"

# Request JIT access for 2 hours from your current IP
MY_IP=$(curl -s https://api.ipify.org)
az security jit-policy initiate \\
  --resource-group my-rg \\
  --location eastus \\
  --name default \\
  --virtual-machines "[{
    'id': '/subscriptions/{sub-id}/resourceGroups/my-rg/providers/Microsoft.Compute/virtualMachines/my-vm',
    'ports': [{
      'number': 22,
      'duration': 'PT2H',
      'allowedSourceAddressPrefix': '$MY_IP'
    }]
  }]"

# Check active JIT requests
az security jit-policy show \\
  --resource-group my-rg \\
  --location eastus \\
  --name default`
    },
    {
      label: 'Security Alerts & Recommendations',
      language: 'bash',
      code: `# List all security recommendations for a subscription
az security task list --output table

# List high-severity recommendations only
az security task list \\
  --query "[?properties.severity=='High']" \\
  --output table

# List active security alerts
az security alert list \\
  --location eastus \\
  --output table

# Get Secure Score for current subscription
az security secure-score-controls list \\
  --name "ascScore" \\
  --query "{score:properties.score, max:properties.max, percentage:properties.percentage}"

# List individual control scores
az security secure-score-controls list \\
  --query "[].{Control:properties.displayName, Score:properties.score.current, Max:properties.score.max}" \\
  --output table

# Export recommendations to Log Analytics (via Bicep/ARM — simplified)
# Configure Continuous Export:
az security automations create \\
  --name export-to-sentinel \\
  --resource-group security-rg \\
  --location eastus \\
  --scopes "[{\"description\":\"Current subscription\",\"scopePath\":\"/subscriptions/{sub-id}\"}]" \\
  --sources "[{\"eventSource\":\"Alerts\"}]" \\
  --actions "[{\"actionType\":\"Workspace\",\"workspaceResourceId\":\"/subscriptions/{sub-id}/resourceGroups/sentinel-rg/providers/Microsoft.OperationalInsights/workspaces/sentinel-ws\"}]"`
    },
  ];

  mistakes: CommonMistake[] = [
    {
      title: 'Leaving management ports (RDP/SSH) open to the internet without JIT',
      wrong: `# NSG rule: Allow port 3389 from source 0.0.0.0/0 (Any)
# VMs exposed 24/7 to brute-force attacks from the entire internet`,
      right: `# Enable JIT VM Access — locks ports by default, opens temporarily per-IP per-request
az security jit-policy create --name default --resource-group my-rg ...
# Defender Secure Score flags "Management ports of VMs should be protected with JIT" as High severity`,
      explanation: 'Leaving RDP (3389) or SSH (22) open to the entire internet is one of the most common causes of VM compromise — brute-force attacks start within minutes of a new VM being exposed. JIT VM Access locks these ports by default with an NSG DENY rule and only opens them temporarily for specific source IPs when access is explicitly requested and approved. Defender for Cloud flags open management ports as High severity recommendations.'
    },
    {
      title: 'Enabling Defender plans only on the primary subscription, not all subscriptions',
      wrong: `# Defender enabled on production subscription only
# Dev/test subscriptions unprotected — used as pivot points for lateral movement`,
      right: `# Enable Defender at Management Group level to cover ALL subscriptions
az policy assignment create \\
  --name enable-defender-servers \\
  --policy "8e86a5b6-b9bd-49a1-8181-ebb30604b7d0" \\  # Built-in: Enable Defender for Servers
  --scope "/providers/Microsoft.Management/managementGroups/{mg-id}"`,
      explanation: 'Attackers frequently compromise dev/test environments first — they have weaker controls but often share network connectivity with production (via VNet peering or managed identity trust). Enabling Defender only on production leaves these paths unmonitored. Use Azure Policy at Management Group scope to enforce Defender plan enablement across all subscriptions. Defender for Cloud shows "management group coverage" to identify unprotected subscriptions.'
    },
    {
      title: 'Dismissing security recommendations without exemptions — they reappear next scan',
      wrong: `# Clicking "Dismiss" in the portal without creating a formal exemption
# The recommendation disappears temporarily but reappears after the next evaluation cycle`,
      right: `# Create a formal exemption with business justification and expiry date
az security assessment exemption create \\
  --name "waived-disk-encryption-dev" \\
  --assessment-name "1195afff-c881-495e-9bc5-1486211ae03f" \\
  --resource-group dev-rg \\
  --exemption-category Waiver \\
  --expires-on "2026-12-31"`,
      explanation: 'Dismissing recommendations in the Defender portal is temporary — they re-evaluate on the next scan cycle and reappear. Use formal Exemptions to acknowledge recommendations that are intentionally not implemented, with: a business justification, expiry date (mandatory), and category (Waiver: risk accepted; Mitigated: addressed by other means). Exemptions are tracked, auditable, and time-limited — they expire automatically and appear in compliance reports.'
    },
    {
      title: 'Not connecting Defender for Cloud alerts to Microsoft Sentinel',
      wrong: `# Reviewing Defender alerts only in the Defender portal
# Alerts viewed in isolation — no correlation with identity, network, or endpoint signals`,
      right: `# Connect Defender for Cloud to Microsoft Sentinel as a data connector
# Sentinel correlates Defender alerts + Entra ID sign-in logs + NSG flow logs
# Enables: incident correlation, automated response playbooks, UEBA`,
      explanation: 'Defender for Cloud alerts viewed in isolation miss the full attack story. An alert like "Suspicious process execution" on a VM means more when correlated with an Entra ID sign-in from an unusual location at the same timestamp, plus an NSG flow log showing lateral movement. Microsoft Sentinel as a SIEM stitches these signals together, enabling analyst investigation workflows, automated response (playbooks), and UEBA (user entity behaviour analytics).'
    },
  ];

  challenge: Challenge = {
    title: 'Secure Score calculator',
    language: 'typescript',
    description: 'Calculate a Defender for Cloud Secure Score from security control data.\n\nGiven:\n```typescript\ninterface SecurityControl {\n  name: string;\n  maxPoints: number;\n  healthyResources: number;\n  unhealthyResources: number;\n}\n```\n\nWrite `calculateSecureScore(controls: SecurityControl[])`:\n- Each control earns points proportional to its healthy resource ratio: `maxPoints × (healthy / (healthy + unhealthy))`\n- If a control has 0 resources total, exclude it from the calculation (not applicable)\n- `secureScore`: number 0–100 (percentage of total earned vs total max)\n- `controlBreakdown`: array of `{ name, earned, max, percentHealthy }` sorted by earned points ascending (lowest first — what to fix first)\n- `topPriority`: name of the control with the most potential improvement (lowest earned/max ratio)',
    hints: [
      'Exclude controls where healthyResources + unhealthyResources === 0',
      'earned = maxPoints × (healthy / total) — round to 2 decimal places',
      'secureScore = (sum of earned) / (sum of max) × 100',
      'topPriority = control with lowest (earned / max) ratio among controls with max > 0',
    ],
    starterCode: `interface SecurityControl {
  name: string;
  maxPoints: number;
  healthyResources: number;
  unhealthyResources: number;
}

export function calculateSecureScore(controls: SecurityControl[]) {
  return {
    secureScore: 0,
    controlBreakdown: [] as { name: string; earned: number; max: number; percentHealthy: number }[],
    topPriority: '',
  };
}`,
    solution: `interface SecurityControl {
  name: string;
  maxPoints: number;
  healthyResources: number;
  unhealthyResources: number;
}

export function calculateSecureScore(controls: SecurityControl[]) {
  const applicable = controls.filter(c => c.healthyResources + c.unhealthyResources > 0);

  const breakdown = applicable.map(c => {
    const total = c.healthyResources + c.unhealthyResources;
    const ratio = c.healthyResources / total;
    const earned = Math.round(c.maxPoints * ratio * 100) / 100;
    const percentHealthy = Math.round(ratio * 100);
    return { name: c.name, earned, max: c.maxPoints, percentHealthy };
  });

  breakdown.sort((a, b) => a.earned - b.earned);

  const totalEarned = breakdown.reduce((s, c) => s + c.earned, 0);
  const totalMax = breakdown.reduce((s, c) => s + c.max, 0);
  const secureScore = totalMax > 0 ? Math.round((totalEarned / totalMax) * 100 * 10) / 10 : 0;

  const topPriority = [...breakdown]
    .filter(c => c.max > 0)
    .sort((a, b) => (a.earned / a.max) - (b.earned / b.max))[0]?.name ?? '';

  return { secureScore, controlBreakdown: breakdown, topPriority };
}`
  };

  quiz: QuizQuestion[] = [
    {
      q: 'What is the difference between the free tier of Defender for Cloud and Defender plans?',
      options: [
        'Free tier is for development only; Defender plans are required for production subscriptions',
        'Free tier provides CSPM (secure score, recommendations, compliance); Defender plans add CWPP (threat detection, vulnerability scanning, runtime alerts)',
        'Free tier provides threat alerts; Defender plans add compliance frameworks',
        'There is no free tier — Defender for Cloud always requires a paid plan'
      ],
      answer: 1,
      explanation: 'Defender for Cloud\'s free tier provides Cloud Security Posture Management (CSPM): Secure Score, security recommendations, Azure Policy compliance dashboard, and network map — automatically available to all subscriptions at no cost. Defender plans (Servers, SQL, Containers, Storage, etc.) add Cloud Workload Protection Platform (CWPP): runtime threat detection, vulnerability assessments, malware scanning, and detailed security alerts. Plans are paid per resource type.'
    },
    {
      q: 'How does Just-in-Time (JIT) VM Access reduce attack surface?',
      options: [
        'It encrypts all traffic to RDP/SSH ports using JIT-specific TLS certificates',
        'It permanently closes RDP/SSH ports and routes access through Azure Bastion instead',
        'It sets NSG rules to DENY management ports by default, and opens them temporarily for a specific source IP only when access is explicitly requested',
        'It requires MFA for every RDP/SSH connection using Azure AD authentication'
      ],
      answer: 2,
      explanation: 'JIT VM Access modifies NSG rules to DENY inbound traffic on management ports (RDP 3389, SSH 22, WinRM 5985/5986) by default — unlike a typical open NSG. When a user requests access, Defender creates a time-limited ALLOW rule for their specific source IP only. After the time window (default 3 hours) expires, the ALLOW rule is automatically removed, restoring the DENY state. This eliminates the 24/7 exposure to brute-force attacks without requiring Azure Bastion.'
    },
    {
      q: 'What does the Secure Score measure?',
      options: [
        'The percentage of security alerts that have been resolved in the past 30 days',
        'How well your Azure environment follows Microsoft security recommendations — measured as points earned across security controls vs maximum possible points',
        'The number of active Defender plans enabled as a percentage of available plans',
        'A penetration test score generated by automated red-team simulations'
      ],
      answer: 1,
      explanation: 'Secure Score is a 0–100% metric: (points earned across all security controls) / (maximum possible points) × 100. Each security control groups related recommendations (e.g., "Enable MFA" = 10 max points). Fulfilling all recommendations in a control grants its full points; unhealthy resources reduce the earned points proportionally. A higher score means better security posture. The score is NOT based on alert resolution or Defender plan enablement directly.'
    },
    {
      q: 'Which Defender feature analyses actual NSG traffic to recommend tighter rules?',
      options: [
        'File Integrity Monitoring',
        'Adaptive Network Hardening',
        'Just-in-Time VM Access',
        'Defender for DNS'
      ],
      answer: 1,
      explanation: 'Adaptive Network Hardening uses NSG flow logs and ML to analyse 30 days of real traffic patterns. It then recommends tighter NSG rules: "This rule allows port 3389 from Any Internet, but in 30 days only 10.1.0.0/24 actually connected — restrict to that range." These recommendations appear in Defender for Cloud under "Adaptive network hardening recommendations should be applied on internet facing virtual machines." Review and apply them to reduce the attack surface based on real traffic evidence.'
    },
    {
      q: 'Why should Defender for Cloud alerts be connected to Microsoft Sentinel?',
      options: [
        'Sentinel is required to store alerts — Defender for Cloud does not store alerts natively',
        'Sentinel provides alert correlation across Defender, Entra ID, NSG flow logs, and endpoint telemetry — enabling full attack-chain investigation and automated response',
        'Connecting to Sentinel reduces the cost of Defender plans by 50%',
        'Sentinel must approve all Defender alerts before they appear in the Azure portal'
      ],
      answer: 1,
      explanation: 'Defender for Cloud generates alerts per resource, but each alert is seen in isolation. Microsoft Sentinel is a SIEM/SOAR that correlates signals from multiple sources: Defender alerts, Entra ID sign-in logs, NSG flow logs, Azure Activity logs, and endpoint telemetry (Defender for Endpoint). This correlation exposes the full attack chain: e.g., a suspicious process on VM X → correlates with an Entra ID sign-in from an anomalous IP → plus NSG logs showing lateral movement — a full incident Sentinel can automatically raise and trigger a response playbook for.'
    },
    {
      q: 'Why can two subscriptions with the exact same number of unresolved recommendations end up with different Secure Scores?',
      options: [
        'Secure Score is randomized to prevent gaming the metric',
        'Each security control (and each recommendation within it) is weighted differently based on its security impact, so resolving a handful of high-weight recommendations raises the score more than resolving many low-weight ones — raw recommendation count alone does not determine the score',
        'Secure Score only counts recommendations from paid Defender plans, so free-tier subscriptions always score lower',
        'The score is purely a function of subscription age, not actual security posture',
      ],
      answer: 1,
      explanation: 'Secure Score is not "unresolved recommendations count / total recommendations" — each control (e.g. "Enable MFA," "Remediate vulnerabilities") carries its own weighting based on its actual security impact, and points within a control are further split across the individual resources affected. Two environments with the same NUMBER of open recommendations can have meaningfully different scores if one environment\'s open items are concentrated in high-weight controls (like exposed management ports) versus low-weight ones (like resource tagging hygiene) — this is intentional, so the score reflects genuine risk reduction priority, not just a raw completion percentage.',
    },
  ];

  qna: QnaItem[] = [
    {
      q: 'What is the difference between Defender for Cloud and Microsoft Sentinel?',
      a: '<strong>Defender for Cloud</strong>: security posture management + cloud workload protection for Azure (and multi-cloud) resources. Focus: "Is my Azure configuration secure? Are my VMs/SQL/containers/storage being actively attacked?" Provides: Secure Score, recommendations, Defender plans with per-resource threat detection. Native to Azure — reads ARM resource state. <strong>Microsoft Sentinel</strong>: cloud-native SIEM (Security Information and Event Management) and SOAR (Security Orchestration, Automation and Response). Focus: "Correlate signals across my entire digital estate — cloud, on-premises, SaaS — to detect complex multi-stage attacks and automate response." Ingests logs from hundreds of connectors (Microsoft 365, AWS, on-premises SIEM, Defender for Cloud). The two are complementary: Defender for Cloud generates signals; Sentinel correlates them.'
    },
    {
      q: 'How does Defender for Containers protect AKS workloads?',
      a: '<strong>Two protection layers</strong>: (1) <strong>Image vulnerability assessment</strong>: scans container images in Azure Container Registry (ACR) on push and on a regular schedule. Finds CVEs in OS packages and application dependencies. Shows findings in Defender for Cloud with CVSS scores and fix recommendations. (2) <strong>Runtime threat protection</strong>: monitors Kubernetes audit logs and node-level signals for: cryptomining pods (high CPU, unusual network destinations), privilege escalation attempts (container requesting privileged access), suspicious API server calls (creating ClusterRoleBindings to gain cluster-admin), and data exfiltration patterns. Alerts appear in Defender for Cloud and can be forwarded to Sentinel. Also checks Kubernetes configuration against CIS Kubernetes Benchmark via Defender\'s policy initiative.'
    },
    {
      q: 'What is Defender for DevOps and how does it integrate with pipelines?',
      a: '<strong>Defender for DevOps</strong> extends security left into CI/CD pipelines. Connect your GitHub or Azure DevOps organisation to Defender for Cloud. Once connected: (1) <strong>Code scanning</strong>: integrates GitHub Advanced Security / Azure DevOps\'s built-in scanning — SAST, secret scanning, dependency vulnerability alerts appear in Defender. (2) <strong>IaC scanning</strong>: scans Bicep/ARM/Terraform templates for misconfigured resources before deployment (e.g., storage account allowing public blob access, NSG open to 0.0.0.0/0). (3) <strong>Pull request annotations</strong>: Defender findings appear as PR comments, blocking merges with high-severity findings. (4) <strong>Pipeline task</strong>: `MicrosoftSecurityDevOps@1` task runs tools (Bandit, Checkov, ESLint security rules, Trivy) in your YAML pipeline. Results feed into Defender for Cloud\'s DevOps security view.'
    },
    {
      q: 'How do you use the Regulatory Compliance dashboard for an audit?',
      a: '<strong>Steps</strong>: (1) Navigate to Defender for Cloud → Regulatory Compliance. (2) Select the relevant framework (PCI DSS 4.0, ISO 27001, SOC 2, NIST SP 800-53, or Azure Security Benchmark). (3) Each framework control is mapped to Azure Policy assessments — green (passing), red (failing), grey (not applicable). (4) Click any failing control to see the specific Azure recommendations causing failure and the affected resources. (5) Remediate failing controls or create Exemptions with business justification for controls that are mitigated by other means. (6) Export the compliance report as PDF for auditors — shows compliance percentage and evidence of control mappings. (7) Use Continuous Export to send compliance data to Log Analytics for historical trending and custom Power BI dashboards.'
    },
    {
      q: 'How does Defender for Cloud handle multi-cloud environments (AWS, GCP)?',
      a: '<strong>Multi-cloud connectors</strong> bring non-Azure clouds into Defender for Cloud\'s single pane. (1) <strong>AWS connector</strong>: uses a cross-account IAM role (no credentials stored in Azure — role trust relationship only) to read AWS resource inventory via AWS Security Hub, GuardDuty, and Config. Discovers: EC2, S3, RDS, EKS, Lambda. Applies Defender CSPM recommendations (e.g., "S3 bucket should not allow public access") and can run Defender for Servers on EC2 via Arc. (2) <strong>GCP connector</strong>: reads GCP projects via Workload Identity Federation. Discovers: Compute Engine, GKE, Cloud SQL, Cloud Storage. (3) <strong>Azure Arc</strong>: onboard on-premises servers as Azure resources. Once Arc-enabled, Defender for Servers protects them exactly like Azure VMs — same Secure Score, JIT access, FIM, and threat detection. Multi-cloud data appears in a unified inventory and Secure Score per cloud.'
    },
    {
      q: 'If an organization only enables Defender for Cloud and never connects Sentinel, what visibility gap remains?',
      a: 'Defender for Cloud alone only sees signals from Azure (and connected multi-cloud) resources — it cannot correlate those signals with events from on-premises systems, Microsoft 365, third-party SIEM feeds, or SaaS applications outside its connectors. A multi-stage attack that starts with a phishing email in Microsoft 365 and pivots into Azure would show fragments in Defender for Cloud, but only Sentinel\'s cross-estate correlation can connect those fragments into one recognizable attack chain and trigger an automated SOAR response.',
    },
  ];

  revision: RevisionSummary = {
    oneLiner: 'Microsoft Defender for Cloud provides CSPM (Secure Score, recommendations) via the free tier, and CWPP (threat alerts, JIT VM access, vulnerability scanning) via paid Defender plans — alerts feed into Microsoft Sentinel for full attack-chain correlation.',
    mustKnow: [
      'Free tier: CSPM only (Secure Score, recommendations). Defender plans add CWPP (runtime threat detection)',
      'Secure Score: earned points / max points across applicable security controls — higher is better',
      'JIT VM Access: locks RDP/SSH with NSG DENY; opens temporarily per-IP per-request for defined window',
      'Adaptive Network Hardening: recommends tighter NSG rules based on actual traffic analysis',
      'Regulatory Compliance dashboard: maps Azure configurations to PCI DSS, ISO 27001, SOC 2, NIST frameworks',
      'Defender alerts + Sentinel = full attack-chain correlation across Azure, identity, endpoint, and network signals',
    ],
    interviewFocus: [
      'What is the difference between Defender for Cloud\'s free tier and paid Defender plans?',
      'Explain how Just-in-Time VM Access works and why it reduces attack surface',
      'How does Secure Score work and what does it measure?',
      'Why would you connect Defender for Cloud to Microsoft Sentinel?',
    ],
  };
}
