import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  standalone: true,
  imports: [PageMetaComponent, TheoryBlockComponent, CodeBlockComponent, TryItComponent, MisconceptionsComponent, SubtopicNavComponent, SubtopicEyebrowComponent],
  templateUrl: './remote-state-grants-access-to-the-entire-state-not-just-outputs.html',
  styleUrl: './remote-state-grants-access-to-the-entire-state-not-just-outputs.scss'
})
export class RemoteStateGrantsAccessToTheEntireStateNotJustOutputsSubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'The main page shows the syntax with zero security caveat',
      points: [
        'The main page\'s Remote State Outputs example shows <code>data "terraform_remote_state" "network" { backend = "s3" ... }</code> reading <code>data.terraform_remote_state.network.outputs.private_subnets[0]</code> — clean, working syntax, with no mention at all of what access this actually grants the consuming configuration.',
      ]
    },
    {
      heading: 'terraform_remote_state does not scope access to the specific outputs referenced',
      points: [
        'Even though a configuration might reference only ONE specific output (like <code>private_subnets</code>), the <code>terraform_remote_state</code> data source works by reading the ENTIRE state file from the configured backend — every resource attribute, every output (referenced or not), and anything else stored in that state snapshot becomes available to whatever code has access to the consuming configuration, not just the one output actually used in an expression.',
        'This matters because state files commonly contain values well beyond what any output intentionally exposes — full resource attribute values, and in some cases genuinely sensitive data (database passwords set via a provider resource argument, private keys generated by a resource) that were never meant to be part of any module\'s "public API," yet are fully readable by anyone with access to the raw state snapshot.',
      ]
    },
    {
      heading: 'HashiCorp\'s own current recommendation: avoid terraform_remote_state, prefer scoped alternatives',
      points: [
        'The officially recommended alternative for reading actual cloud-resource information is to query the cloud provider directly via resource-specific data sources (e.g. <code>data "aws_vpc" "existing"</code>) instead of reaching into another configuration\'s state file at all.',
        'For teams using HCP Terraform / Terraform Enterprise, HashiCorp specifically recommends the <code>tfe_outputs</code> data source (from the Terraform Enterprise provider) as a more secure alternative — it exposes only that workspace\'s intentionally-declared outputs, without requiring full read access to the underlying state snapshot the way <code>terraform_remote_state</code> does.',
        'The practical takeaway: <code>terraform_remote_state</code> remains a working, documented feature (and the main page\'s own example is syntactically correct) — but choosing it means accepting that anyone with read access to the consuming configuration effectively also has read access to the ENTIRE producing state file, a much broader exposure than "just the outputs I reference."',
      ]
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'The main page\'s own example — syntactically fine, access implications unstated',
      language: 'bash',
      code: `# --- In the "compute" workspace ---
data "terraform_remote_state" "network" {
  backend = "s3"
  config = {
    bucket = "my-tf-state"
    key    = "network/terraform.tfstate"
    region = "us-east-1"
  }
}

resource "aws_instance" "app" {
  subnet_id = data.terraform_remote_state.network.outputs.private_subnets[0]
}
# Only private_subnets is REFERENCED in this expression -- but
# this data source pulls the ENTIRE "network" state file, which
# may contain resource attributes, other outputs, or even
# provider-set secrets that were never meant to be exposed to
# whatever configuration/person can read this "compute" workspace.`,
    },
    {
      label: 'The more scoped alternatives',
      language: 'bash',
      code: `# Option 1: query the cloud provider directly instead of
# reaching into another workspace's state file at all --
# HashiCorp's own general recommendation:
data "aws_subnets" "private" {
  filter {
    name   = "tag:Tier"
    values = ["private"]
  }
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.existing.id]
  }
}

resource "aws_instance" "app" {
  subnet_id = data.aws_subnets.private.ids[0]
}

# Option 2 (HCP Terraform / Terraform Enterprise specifically):
# tfe_outputs exposes ONLY that workspace's declared outputs,
# without requiring full state-snapshot read access:
data "tfe_outputs" "network" {
  organization = "my-org"
  workspace    = "network"
}

resource "aws_instance" "app" {
  subnet_id = data.tfe_outputs.network.values.private_subnets[0]
}`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'Following the main page\'s own Remote State Outputs example exactly, a "compute" workspace uses terraform_remote_state to read only `private_subnets` from the "network" workspace\'s state. A security review flags this as a risk, even though the compute configuration only ever references that one output. What is the actual scope of access being granted here, and what are two alternatives that avoid it?',
    hint: 'Ask what terraform_remote_state actually reads from the backend — the whole state file, or just the specific output referenced in an expression?',
    solution: 'terraform_remote_state reads the ENTIRE state file from the configured backend, regardless of which specific output is referenced in an expression — so anyone with access to the "compute" configuration effectively gains read access to everything in the "network" state snapshot, including resource attributes and other outputs never intentionally exposed, some of which may be genuinely sensitive. Two alternatives that avoid this: (1) query the cloud provider directly with a resource-specific data source (e.g. `data "aws_subnets"`) instead of reading another workspace\'s state at all — HashiCorp\'s general recommendation; (2) for HCP Terraform/Terraform Enterprise users specifically, use the `tfe_outputs` data source, which exposes only that workspace\'s declared outputs without requiring full state-snapshot read access.'
  };

  misconceptions: Misconception[] = [
    {
      thought: 'terraform_remote_state only grants access to the specific output values an expression actually references, the same way a variable only exposes what it is assigned.',
      reality: 'Per this subtopic\'s theory, terraform_remote_state reads the ENTIRE state file from the backend regardless of which output is referenced — access is effectively all-or-nothing at the state-file level, not scoped to individual outputs.'
    },
    {
      thought: 'State files only ever contain the values explicitly declared in output blocks, so reading a remote state can never expose more than a module\'s intended public interface.',
      reality: 'Per this subtopic\'s theory, state files commonly contain full resource attribute values — including provider-set secrets in some cases — well beyond what any output block intentionally exposes, all of which becomes readable via terraform_remote_state.'
    },
    {
      thought: 'The main page\'s Remote State Outputs example represents Terraform\'s current best-practice recommendation for cross-configuration data sharing.',
      reality: 'Per this subtopic\'s theory, the syntax shown works correctly, but HashiCorp\'s own current guidance recommends avoiding terraform_remote_state in favor of resource-specific data sources or (for HCP Terraform/Enterprise) the tfe_outputs data source, specifically because of this exposure.'
    }
  ];
}
