import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../components/shared/page-meta/page-meta';
import { QuickRefComponent, QuickRefItem } from '../../../../components/shared/quick-ref/quick-ref';
import { TheoryBlockComponent, TheoryPoint } from '../../../../components/shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../components/shared/code-block/code-block';
import { CommonMistakesComponent, CommonMistake } from '../../../../components/shared/common-mistakes/common-mistakes';
import { ChallengeBlockComponent, Challenge } from '../../../../components/shared/challenge-block/challenge-block';
import { QuizBlockComponent, QuizQuestion } from '../../../../components/shared/quiz-block/quiz-block';
import { QnaBlockComponent, QnaItem } from '../../../../components/shared/qna-block/qna-block';
import { RevisionCardComponent, RevisionSummary } from '../../../../components/shared/revision-card/revision-card';
import { PageCompleteComponent } from '../../../../components/shared/page-complete/page-complete';

@Component({
  selector: 'app-rust-modules-cargo',
  standalone: true,
  imports: [PageMetaComponent, QuickRefComponent, TheoryBlockComponent, CodeBlockComponent,
    CommonMistakesComponent, ChallengeBlockComponent, QuizBlockComponent, QnaBlockComponent,
    RevisionCardComponent, PageCompleteComponent],
  templateUrl: './modules-cargo.html',
  styleUrl: './modules-cargo.scss'
})
export class RustModulesCargo {
  readingTime = 24;
  difficulty: 'beginner' | 'intermediate' | 'advanced' = 'beginner';
  since = 'Rust 2021+';
  route = 'rust-modules-cargo';

  quickRef: QuickRefItem[] = [
    { name: 'mod name { ... }', type: 'keyword', desc: 'Declares a module inline; write mod name; to load it from name.rs or name/mod.rs instead' },
    { name: 'pub', type: 'keyword', desc: 'Makes an item visible outside its module — everything is private by default' },
    { name: 'pub(crate)', type: 'keyword', desc: 'Visible anywhere inside the current crate but not to other crates' },
    { name: 'use path::Item;', type: 'keyword', desc: 'Brings an item into scope so you can refer to it by its short name' },
    { name: 'use path::Item as Alias;', type: 'keyword', desc: 'Imports an item under a different name, to avoid clashes' },
    { name: 'crate:: / self:: / super::', type: 'syntax', desc: 'Path prefixes: from the crate root, from the current module, or from the parent module' },
    { name: 'pub use', type: 'keyword', desc: 'Re-exports an item so users of your module can reach it through a shorter or friendlier path' },
    { name: 'Cargo.toml', type: 'syntax', desc: 'The package manifest — name, version, edition, dependencies and profile settings' },
    { name: 'Cargo.lock', type: 'syntax', desc: 'The exact resolved versions of every dependency, generated by Cargo — commit it for applications' },
    { name: '[workspace]', type: 'syntax', desc: 'Groups several crates so they share one target directory and one Cargo.lock' },
  ];

  theory: TheoryPoint[] = [
    {
      heading: 'Modules and paths',
      points: [
        'A module groups related items and controls their visibility. Modules form a tree rooted at the crate root, which is <code>src/main.rs</code> for a binary or <code>src/lib.rs</code> for a library.',
        'Declare a module inline with <code>mod name { ... }</code>, or write <code>mod name;</code> to tell the compiler to load it from <code>name.rs</code> or <code>name/mod.rs</code>. The <code>mod</code> declaration is what adds a file to the crate — creating the file alone does nothing.',
        'Refer to an item by path: <code>crate::a::b</code> starts at the crate root, <code>self::b</code> starts at the current module, and <code>super::b</code> starts at the parent module.',
        'A <code>use</code> declaration brings a path into scope: <code>use std::collections::HashMap;</code>. You can group (<code>use a::{b, c}</code>), rename with <code>as</code>, or import everything with a glob, though globs are best kept to tests and preludes.',
        'By convention, import a function\'s parent module and call <code>module::function()</code>, but import structs and enums directly. It keeps the origin of functions obvious.',
      ]
    },
    {
      heading: 'Visibility and privacy',
      points: [
        'Everything is PRIVATE by default. A private item is visible inside its own module and in every module nested below it, but not from the outside.',
        'Add <code>pub</code> to expose an item. Finer control comes from <code>pub(crate)</code> (visible in this crate only) and <code>pub(super)</code> (visible to the parent module).',
        'Making a module public does not make its contents public — each item needs its own <code>pub</code>. A sibling or a child can see a private item in a parent module, but never the reverse.',
        'Struct fields have their own visibility. A public struct with a private field cannot be built with a struct literal outside its module, so you provide a constructor. That is how you protect an invariant such as "balance is never set directly".',
        'If you make an enum public, ALL of its variants are public automatically. Use <code>pub use</code> to re-export an item from a deeper module so users see a short, stable path while you stay free to reorganise the files.',
      ]
    },
    {
      heading: 'Packages, crates and workspaces',
      points: [
        'A crate is the unit of compilation: either a binary (has a main function) or a library. A PACKAGE is what Cargo builds and is described by one Cargo.toml; it holds at most one library crate and any number of binary crates.',
        'By convention <code>src/main.rs</code> is the root of a binary crate, <code>src/lib.rs</code> is the root of a library crate, and extra binaries live in <code>src/bin/</code>. Integration tests live in a top-level <code>tests/</code> directory.',
        'A workspace groups several packages under a single top-level Cargo.toml with a <code>[workspace]</code> section. Its members share one <code>target/</code> directory and one Cargo.lock, so dependencies are compiled once and versions stay consistent.',
        'The <code>edition</code> key in Cargo.toml selects a language edition (2015, 2018, 2021, and the newer 2024). Editions let the language make otherwise breaking changes while every crate in your dependency tree keeps compiling, even if it uses a different edition.',
        'Split code into separate crates when you want independent versioning, faster incremental builds, or a clear public API boundary. Splitting into modules is enough when you only need organisation.',
      ]
    },
    {
      heading: 'Dependencies in Cargo.toml',
      points: [
        'Dependencies are listed under <code>[dependencies]</code>. A plain version such as <code>rand = "0.8"</code> means "any compatible 0.8.x release" (a caret requirement, following semantic versioning).',
        'Add one from the command line with <code>cargo add serde</code>. Enable optional functionality with features: <code>serde = { version = "1", features = ["derive"] }</code>. Features turn parts of a crate on, keeping compile times down when you do not need them.',
        '<code>[dev-dependencies]</code> are used only for tests, examples and benchmarks, and <code>[build-dependencies]</code> only for build scripts. Neither ends up in your final binary.',
        'Cargo.lock records the exact version of every crate that was resolved. Commit it for applications so builds are reproducible; run <code>cargo update</code> to refresh it within your allowed version ranges.',
        'Dependencies can also come from a path (<code>{ path = "../core" }</code>) or a git repository. Public crates live on crates.io, and <code>cargo publish</code> uploads yours — a wildcard version such as "*" is rejected there.',
      ]
    },
    {
      heading: 'Everyday Cargo commands',
      points: [
        '<code>cargo new</code> creates a package, <code>cargo check</code> type-checks without generating code and is the fastest feedback loop, <code>cargo build</code> compiles, and <code>cargo run</code> builds and runs.',
        'The default build is a DEBUG build with no optimisation, written to <code>target/debug</code>. Add <code>--release</code> for an optimised build in <code>target/release</code>; it can be many times faster, so always benchmark with it.',
        'Tune release builds in <code>[profile.release]</code>, for example <code>opt-level</code> and <code>lto</code> (link-time optimisation), which trade longer compile times for smaller, faster binaries.',
        '<code>cargo test</code> runs unit tests (in a <code>#[cfg(test)]</code> module beside the code), integration tests in <code>tests/</code>, and the code examples in your doc comments.',
        '<code>cargo fmt</code> formats code, <code>cargo clippy</code> lints it with hundreds of suggestions, <code>cargo doc --open</code> builds and opens documentation, and <code>cargo tree</code> shows the dependency graph.',
      ]
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'Modules & Visibility',
      language: 'rust',
      code: `mod restaurant {
    pub mod front_of_house {
        pub fn add_to_waitlist() {
            println!("added to the waitlist");
        }

        fn seat_at_table() {
            println!("seated");
        }

        pub fn seat() {
            seat_at_table();                    // private, but same module
            super::back_of_house::cook();       // parent's private module, still visible
        }
    }

    // A private module: visible inside restaurant, hidden from outside
    mod back_of_house {
        pub fn cook() {
            println!("cooking");
        }

        pub struct Breakfast {
            pub toast: String,
            seasonal_fruit: String, // private field
        }

        impl Breakfast {
            pub fn summer(toast: &str) -> Breakfast {
                Breakfast {
                    toast: toast.to_string(),
                    seasonal_fruit: "peaches".to_string(),
                }
            }

            pub fn fruit(&self) -> &str {
                &self.seasonal_fruit
            }
        }
    }

    // Re-export: users can write restaurant::Breakfast
    pub use self::back_of_house::Breakfast;
}

use restaurant::front_of_house;
use restaurant::Breakfast;

fn main() {
    front_of_house::add_to_waitlist();
    front_of_house::seat();

    let mut meal = Breakfast::summer("rye");
    meal.toast = String::from("wheat"); // public field
    println!("{} with {}", meal.toast, meal.fruit()); // wheat with peaches

    // meal.seasonal_fruit = String::from("figs");
    // error[E0616]: field seasonal_fruit of struct Breakfast is private

    // restaurant::back_of_house::cook();
    // error[E0603]: module back_of_house is private
}`
    },
    {
      label: 'Files & Paths',
      language: 'rust',
      code: `// Project layout (illustrative — each section below is a separate file):
//
// my_app/
//   Cargo.toml
//   src/
//     main.rs
//     config.rs
//     network/
//       mod.rs
//       client.rs

// ---- src/main.rs ----
mod config;   // loads src/config.rs
mod network;  // loads src/network/mod.rs (src/network.rs also works)

use crate::config::Config;
use network::client::connect;

fn main() {
    let cfg = Config::default();
    connect(&cfg);
}

// ---- src/config.rs ----
#[derive(Default)]
pub struct Config {
    pub port: u16,
}

// ---- src/network/mod.rs ----
pub mod client; // loads src/network/client.rs

// ---- src/network/client.rs ----
use crate::config::Config;

pub fn connect(cfg: &Config) {
    println!("connecting on port {}", cfg.port);
}`
    },
    {
      label: 'Cargo.toml',
      language: 'bash',
      code: `# ---- Cargo.toml of a single package ----
[package]
name = "my_app"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"                                           # any compatible 0.8.x
serde = { version = "1", features = ["derive"] }       # enable an optional feature
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
core_lib = { path = "../core_lib" }                    # a local crate

[dev-dependencies]
pretty_assertions = "1"                                # tests only

[profile.release]
opt-level = 3
lto = true                                             # slower build, faster binary

# ---- Cargo.toml at the top of a workspace ----
[workspace]
members = ["app", "core_lib", "utils"]
resolver = "2"`
    },
    {
      label: 'Cargo Commands',
      language: 'bash',
      code: `cargo new my_app              # new binary package (add --lib for a library)
cargo add serde --features derive   # add a dependency to Cargo.toml
cargo check                   # type-check only: fastest feedback while editing
cargo build                   # debug build  -> target/debug
cargo build --release         # optimised    -> target/release
cargo run -- --port 8080      # arguments after -- go to your program
cargo test                    # unit, integration and doc tests
cargo fmt && cargo clippy     # format, then lint
cargo doc --open              # build and open the documentation
cargo tree                    # show the dependency graph
cargo update                  # refresh Cargo.lock within allowed version ranges
cargo publish                 # upload the crate to crates.io`
    },
  ];

  mistakes: CommonMistake[] = [
    {
      title: 'Using a private item from outside its module',
      wrong: `mod bank {
    fn audit() {}
}

fn main() {
    bank::audit();
}
// error[E0603]: function audit is private`,
      right: `mod bank {
    pub fn audit() {}
}

fn main() {
    bank::audit();
}`,
      explanation: 'Privacy is the default, so an item must be marked pub to be reachable from another module. Expose only what forms your public API and keep everything else private so you can change it freely.'
    },
    {
      title: 'Creating a file but never declaring the module',
      wrong: `// src/util.rs exists, containing: pub fn helper() {}
// src/main.rs:
use crate::util::helper;

fn main() {
    helper();
}
// error[E0432]: unresolved import crate::util`,
      right: `// src/main.rs:
mod util; // this line adds src/util.rs to the crate
use crate::util::helper;

fn main() {
    helper();
}`,
      explanation: 'Rust does not discover files automatically. A source file only becomes part of the crate when a mod declaration names it, which makes the module tree explicit and searchable in code.'
    },
    {
      title: 'A public struct with private fields that nobody can construct',
      wrong: `pub mod shapes {
    pub struct Circle {
        radius: f64,
    }
}

let c = shapes::Circle { radius: 1.0 };
// error[E0451]: field radius of struct Circle is private`,
      right: `pub mod shapes {
    pub struct Circle {
        radius: f64,
    }

    impl Circle {
        pub fn new(radius: f64) -> Circle {
            Circle { radius }
        }
    }
}

let c = shapes::Circle::new(1.0);`,
      explanation: 'A struct literal needs every field to be visible. Keeping a field private is a feature — it protects invariants — so supply a constructor function that is allowed to fill it in.'
    },
    {
      title: 'Benchmarking or shipping a debug build',
      wrong: `cargo run
# unoptimised: often many times slower than a release build,
# so any timing you take is misleading`,
      right: `cargo run --release
# or build once and run the binary from target/release`,
      explanation: 'A plain cargo build favours fast compilation and debuggability over speed. Always measure performance and produce production binaries with --release.'
    },
    {
      title: 'Not committing Cargo.lock for an application',
      wrong: `# .gitignore
Cargo.lock
# teammates and CI each resolve dependency versions on their own,
# so two builds of the same commit can differ`,
      right: `# Commit Cargo.lock for binaries and applications
git add Cargo.lock`,
      explanation: 'The lock file pins the exact version of every dependency, which is what makes a build reproducible. Leaving it out lets each machine pick newer versions, and a surprise bug can appear with no change to your own code.'
    },
    {
      title: 'Putting a wildcard version on a dependency',
      wrong: `[dependencies]
serde = "*"
# crates.io rejects packages with wildcard dependencies`,
      right: `[dependencies]
serde = "1"
# any compatible 1.x release`,
      explanation: 'A wildcard accepts every future version, including breaking ones. Use a normal semantic-version requirement, which Cargo treats as a compatible range, and let Cargo.lock pin the exact version you tested against.'
    },
  ];

  challenge: Challenge = {
    title: 'Encapsulated Bank Account',
    language: 'rust',
    description: `Use a module and privacy to protect an invariant.

Inside \`mod bank\`, define \`pub struct Account\` with a public field \`owner: String\` and a PRIVATE field \`balance: u64\`. Provide these public functions:
- \`Account::new(owner: &str) -> Account\` — starts with a balance of 0.
- \`deposit(&mut self, amount: u64)\` — adds to the balance.
- \`withdraw(&mut self, amount: u64) -> Result<(), String>\` — subtracts from the balance, or returns \`Err\` with the message \`"insufficient funds: balance B, requested R"\` (with the real numbers) and leaves the balance unchanged.
- \`balance(&self) -> u64\` — reads the balance.

Outside the module, code must NOT be able to assign to \`balance\` directly.

Example:
\`\`\`
let mut acct = Account::new("ana");
acct.deposit(100);
acct.withdraw(30)   // Ok(())
acct.withdraw(500)  // Err("insufficient funds: balance 70, requested 500")
acct.balance()      // 70
\`\`\``,
    hints: [
      'Only the fields and functions marked pub are reachable from outside the module, so leave balance without pub.',
      'Because balance is private, code outside the module cannot use a struct literal, which is why new is required.',
      'Check amount > self.balance first, return early with Err(format!(...)), and only then subtract.',
      'Bring the type into scope in main with use bank::Account;.',
    ],
    starterCode: `mod bank {
    pub struct Account {
        pub owner: String,
        // TODO: a private balance field
    }

    impl Account {
        // TODO: new, deposit, withdraw, balance
    }
}

use bank::Account;

fn main() {
    // let mut acct = Account::new("ana");
    // acct.deposit(100);
    // println!("{:?}", acct.withdraw(30));   // Ok(())
    // println!("{:?}", acct.withdraw(500));  // Err("insufficient funds: balance 70, requested 500")
    // println!("{} {}", acct.owner, acct.balance()); // ana 70
}`,
    solution: `mod bank {
    pub struct Account {
        pub owner: String,
        balance: u64,
    }

    impl Account {
        pub fn new(owner: &str) -> Account {
            Account { owner: owner.to_string(), balance: 0 }
        }

        pub fn deposit(&mut self, amount: u64) {
            self.balance += amount;
        }

        pub fn withdraw(&mut self, amount: u64) -> Result<(), String> {
            if amount > self.balance {
                return Err(format!(
                    "insufficient funds: balance {}, requested {}",
                    self.balance, amount
                ));
            }
            self.balance -= amount;
            Ok(())
        }

        pub fn balance(&self) -> u64 {
            self.balance
        }
    }
}

use bank::Account;

fn main() {
    let mut acct = Account::new("ana");
    acct.deposit(100);
    println!("{:?}", acct.withdraw(30));   // Ok(())
    println!("{:?}", acct.withdraw(500));  // Err("insufficient funds: balance 70, requested 500")
    println!("{} {}", acct.owner, acct.balance()); // ana 70

    // acct.balance = 1_000_000;
    // error[E0616]: field balance of struct Account is private
}`,
  };

  quiz: QuizQuestion[] = [
    {
      q: 'What is the default visibility of an item in Rust?',
      options: [
        'Public',
        'Private to its module (and modules nested inside it)',
        'Visible to the whole crate',
        'Visible to every crate',
      ],
      answer: 1,
      explanation: 'Everything is private unless marked pub. A private item can be used within its own module and descendants but not from the outside.'
    },
    {
      q: 'You add src/util.rs but the compiler cannot find crate::util. What is missing?',
      options: [
        'A dependency in Cargo.toml',
        'The pub keyword on the file',
        'A restart of rust-analyzer',
        'A mod util; declaration, which is what adds the file to the crate',
      ],
      answer: 3,
      explanation: 'Files are not discovered automatically. A mod declaration in the parent module names the file and makes it part of the module tree.'
    },
    {
      q: 'What is the purpose of Cargo.lock?',
      options: [
        'To record the exact resolved version of every dependency so builds are reproducible',
        'To list the files in the package',
        'To store compiled artifacts',
        'To prevent other people editing Cargo.toml',
      ],
      answer: 0,
      explanation: 'Cargo.toml states allowed version ranges and Cargo.lock records the precise versions that were chosen. Commit it for applications so every build uses the same dependencies.'
    },
    {
      q: 'What does a Cargo workspace let several crates share?',
      options: [
        'The same version number automatically',
        'A single main function',
        'One target directory and one Cargo.lock',
        'A single source file',
      ],
      answer: 2,
      explanation: 'Members of a workspace are compiled into a shared target directory and resolved against one lock file, so common dependencies are built once and versions stay consistent.'
    },
    {
      q: 'What does pub use do?',
      options: [
        'Imports an item privately',
        'Declares a public constant',
        'Makes a module unsafe',
        'Re-exports an item so that users can reach it through a different, often shorter, public path',
      ],
      answer: 3,
      explanation: 'pub use both imports the item and makes that import part of your public API. It lets you keep an internal file layout while offering users a tidy path.'
    },
    {
      q: 'Which command type-checks your code quickest, without producing an executable?',
      options: ['cargo run', 'cargo build --release', 'cargo check', 'cargo publish'],
      answer: 2,
      explanation: 'cargo check runs the compiler front end and reports errors but skips code generation, so it gives much faster feedback than a full build while you are editing.'
    },
  ];

  qna: QnaItem[] = [
    {
      q: 'What is the difference between a package, a crate and a module?',
      a: 'A module is a namespace inside a crate. A crate is a single unit of compilation, either a binary or a library. A package is what Cargo manages, described by one Cargo.toml, and it contains at most one library crate plus any number of binary crates. A workspace groups several packages together.'
    },
    {
      q: 'Why is everything private by default?',
      a: 'It makes the public API a deliberate decision. Because internal items are invisible to other modules and crates, you can rename, restructure or delete them without breaking anyone, and the compiler will tell you exactly which items you accidentally exposed.'
    },
    {
      q: 'When should I split code into a new crate rather than a module?',
      a: 'Use a module when you only want to organise code. Use a separate crate when you want to version or publish a part independently, reuse it in several applications, enforce a strict API boundary, or speed up incremental builds by isolating rarely-changing code. Workspaces make multi-crate projects easy to manage.'
    },
    {
      q: 'What does a caret version requirement like "1.2" mean?',
      a: 'It allows any version that is semver-compatible with 1.2.0, which means at least 1.2.0 and below 2.0.0. Cargo picks the newest matching release, and Cargo.lock then pins the exact one. For versions below 1.0, compatibility is narrower: a requirement of 0.8 allows 0.8.x but not 0.9.'
    },
    {
      q: 'What are Cargo features?',
      a: 'Features are optional parts of a crate that you switch on in Cargo.toml, such as serde with the derive feature. They let a crate offer extra functionality without forcing every user to compile it. Features should be additive: turning one on must never break code that relied on it being off.'
    },
    {
      q: 'What is the difference between cargo build and cargo check?',
      a: 'cargo build runs the whole compiler and produces artifacts. cargo check stops after type and borrow checking, so it reports the same errors in a fraction of the time. Use check while writing code, and build or run when you need to execute the program.'
    },
  ];

  revision: RevisionSummary = {
    oneLiner: 'Modules form a tree with everything private by default, use and pub control what you can reach, and Cargo manages packages, dependencies, workspaces and builds.',
    mustKnow: [
      'Everything is private by default; <code>pub</code>, <code>pub(crate)</code> and <code>pub(super)</code> widen visibility',
      'A file joins the crate only through a <code>mod name;</code> declaration',
      'Paths start with <code>crate::</code>, <code>self::</code> or <code>super::</code>; <code>pub use</code> re-exports',
      'A public struct with private fields needs a constructor function',
      'Cargo.toml holds ranges; Cargo.lock pins exact versions and is committed for applications',
      'A workspace shares one <code>target/</code> directory and one Cargo.lock',
      'Debug builds are slow — use <code>cargo build --release</code> for speed, and <code>cargo check</code> for fast feedback',
    ],
    interviewFocus: [
      'Explain the difference between a package, a crate and a module',
      'How does privacy in Rust differ from private in class-based languages?',
      'Why should applications commit Cargo.lock?',
      'What is a workspace and why would you use one?',
      'When is a debug build an unreliable basis for performance conclusions?',
    ],
  };
}
