import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  standalone: true,
  imports: [PageMetaComponent, TheoryBlockComponent, CodeBlockComponent, TryItComponent, MisconceptionsComponent, SubtopicNavComponent, SubtopicEyebrowComponent],
  templateUrl: './kms-rotation-never-touches-already-generated-data-keys.html',
  styleUrl: './kms-rotation-never-touches-already-generated-data-keys.scss'
})
export class KmsRotationNeverTouchesAlreadyGeneratedDataKeysSubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'The main page teaches rotation and envelope encryption separately — never what rotation does to data keys already generated',
      points: [
        'The main page\'s own theory bullet states: "Automatic key rotation: annual rotation of key material; existing ciphertexts remain decryptable because KMS tracks all key versions." Its own mistake entry reinforces the same framing: "KMS automatic key rotation generates new key material under the same CMK ID, so all existing ciphertexts remain decryptable transparently."',
        'Separately, the main page\'s own "Envelope Encryption Pattern" code tab teaches generating a data key via generate-data-key and storing its encrypted CiphertextBlob "alongside your ciphertext" — but the two sections are never connected. A reader is left to assume rotation "just handles" data keys the same reassuring way it handles the CMK\'s own ciphertexts.',
      ]
    },
    {
      heading: 'Rotation changes what NEW operations use — it never touches data keys already generated, and "annual" is only the default',
      points: [
        'Per AWS\'s own documentation, stated directly: "Key rotation has no effect on the data that the KMS key protects. It does not rotate the data keys that the KMS key generated or re-encrypt any data protected by the KMS key. Key rotation will not mitigate the effect of a compromised data key." Every encrypted data key (CiphertextBlob) generated by generate-data-key BEFORE a rotation stays wrapped under the OLD key material permanently — rotation never revisits it.',
        'The direct envelope-encryption consequence: if a specific data key (or its plaintext form) is ever suspected compromised, rotating the CMK that generated it does nothing to protect whatever that data key already encrypted. The only real mitigation is re-encrypting that specific data under a freshly-generated data key — rotation alone is not a response to a compromised data key.',
        'The "annual" framing is also incomplete for a CUSTOMER managed key: "By default, when you enable automatic key rotation... AWS KMS generates new cryptographic material... every year. You can also specify a custom rotation-period to define the number of days after you enable automatic key rotation that AWS KMS will rotate your key material." 365 days is the DEFAULT, not a fixed rule — RotationPeriodInDays is configurable. Separately, on-demand rotation lets you trigger an immediate, out-of-schedule rotation at any time without disturbing the underlying automatic schedule.',
        'AWS managed keys — the main page\'s own quickRef examples, aws/s3 and aws/rds — are the one genuinely fixed case: "You cannot enable or disable key rotation for AWS managed keys... every year (approximately 365 days)." For a CMK you create yourself, though, the rotation period is a choice, not an AWS-enforced annual cadence.',
      ]
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'Demonstrating what rotation does and doesn\'t touch',
      language: 'bash',
      code: `# Following the main page's own envelope encryption pattern exactly:
aws kms generate-data-key \\
  --key-id alias/prod-app-key \\
  --key-spec AES_256 \\
  --query '{Plaintext:Plaintext,CiphertextBlob:CiphertextBlob}' \\
  > data-key.json
# Plaintext -> used to encrypt data in memory, then discarded
# CiphertextBlob -> stored alongside the encrypted data, as the
# main page's own pattern instructs

# Trigger an on-demand rotation of the CMK RIGHT NOW -- no waiting
# for the annual schedule, to make the effect immediately visible:
aws kms rotate-key-on-demand --key-id alias/prod-app-key

# The PREVIOUSLY-stored encrypted data key still decrypts fine --
# per AWS's own docs, KMS "automatically chooses the correct
# [key material] version" for decrypt:
aws kms decrypt \\
  --key-id alias/prod-app-key \\
  --ciphertext-blob fileb://<(jq -r '.CiphertextBlob' data-key.json | base64 -d) \\
  --query 'Plaintext' --output text
# -- succeeds, exactly as the main page's own mistake entry
# describes ("existing ciphertexts remain decryptable").

# But this success is exactly why rotation is NOT a fix for a
# compromised data key -- the OLD key material that wrapped this
# specific CiphertextBlob still exists and still works, untouched
# by the rotation that just ran. Per AWS's own docs: "Key rotation
# will not mitigate the effect of a compromised data key." If THIS
# specific data-key.json had leaked, rotating the CMK changed
# nothing about its continued validity.`,
    },
    {
      label: 'Correcting "annual" — a configurable rotation period, and on-demand control',
      language: 'bash',
      code: `# The main page's own example enables rotation with no period
# specified -- silently taking the 365-day default:
aws kms enable-key-rotation --key-id alias/prod-app-key
# equivalent to:
aws kms enable-key-rotation --key-id alias/prod-app-key \\
  --rotation-period-in-days 365

# A CUSTOMER managed key's period is a real, adjustable choice --
# e.g. a compliance requirement for 90-day rotation:
aws kms enable-key-rotation --key-id alias/prod-app-key \\
  --rotation-period-in-days 90

# Confirm the configured period and next rotation date:
aws kms get-key-rotation-status --key-id alias/prod-app-key
# {
#   "KeyRotationEnabled": true,
#   "RotationPeriodInDays": 90,
#   "NextRotationDate": "2026-10-01T00:00:00Z"
# }

# Contrast with an AWS MANAGED key (aws/s3, aws/rds -- the main
# page's own quickRef examples) -- rotation here is NOT configurable
# at all:
aws kms get-key-rotation-status --key-id alias/aws/s3
# {
#   "KeyRotationEnabled": true
#   # -- no RotationPeriodInDays shown; AWS fixes this at ~365 days
#   # and it cannot be changed, per AWS's own docs: "You cannot
#   # enable or disable key rotation for AWS managed keys."
# }`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'A monitoring alert flags that an application\'s plaintext KMS data key was accidentally written to a debug log that a third party may have accessed. Following the main page\'s own framing that "existing ciphertexts remain decryptable" and rotation is "transparent," the on-call engineer immediately runs an on-demand rotation of the CMK that generated the leaked data key, reasoning this "rotates out" the compromised key and closes the exposure. Using this subtopic\'s theory, evaluate whether this response actually protects the data the leaked key could decrypt, and describe what would.',
    hint: 'Per AWS\'s own documentation, does rotating a CMK touch the data KEYS that CMK has already generated — or only the CMK\'s own key material for future operations?',
    solution: 'Per this subtopic\'s theory, the on-call engineer\'s response does not mitigate the exposure. AWS\'s own documentation states this precisely: "Key rotation will not mitigate the effect of a compromised data key." Rotating the CMK generates new key material for FUTURE encrypt/generate-data-key operations — it has no effect whatsoever on the specific data key that already leaked, or on any data that data key encrypted. That leaked plaintext data key remains just as valid for decrypting whatever it was used to encrypt, completely independent of how many times the parent CMK is rotated afterward, since — per AWS\'s own docs — rotation "does not rotate the data keys that the KMS key generated." The actual mitigation has to operate at the data-key level, not the CMK level: identify every piece of data that specific leaked data key encrypted, generate a FRESH data key for each of those, re-encrypt the data under the new data key, and only then can the exposure be considered closed. Rotating the CMK is good hygiene generally, but it is a red herring as a response to this specific incident.'
  };

  misconceptions: Misconception[] = [
    {
      thought: 'Rotating a CMK re-encrypts (or otherwise invalidates) every data key that CMK has ever generated via generate-data-key, protecting all the data those data keys encrypted.',
      reality: 'Per this subtopic\'s theory, AWS\'s own documentation states the opposite directly — "Key rotation... does not rotate the data keys that the KMS key generated or re-encrypt any data protected by the KMS key" — every previously-generated data key remains exactly as valid as before.'
    },
    {
      thought: 'KMS automatic key rotation is always exactly annual (365 days) and cannot be changed for a customer managed key.',
      reality: 'Per this subtopic\'s theory, 365 days is only the DEFAULT — a customer managed key\'s RotationPeriodInDays is independently configurable, and on-demand rotation can additionally trigger an immediate rotation outside the schedule at any time. Only AWS managed keys have a genuinely fixed, non-configurable annual rotation.'
    },
    {
      thought: 'Rotating a CMK is an effective, sufficient response to a suspected compromised data key or leaked plaintext key material.',
      reality: 'Per this subtopic\'s exercise, AWS\'s own documentation explicitly states rotation "will not mitigate the effect of a compromised data key" — the actual fix requires re-encrypting the affected data under a newly-generated data key, independent of any CMK-level rotation.'
    }
  ];
}
