import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  selector: 'app-addproject-type-parameter-subtopic',
  standalone: true,
  imports: [
    PageMetaComponent, TheoryBlockComponent, CodeBlockComponent,
    TryItComponent, MisconceptionsComponent, SubtopicNavComponent,
    SubtopicEyebrowComponent,
  ],
  templateUrl: './addproject-type-parameter-requires-build-not-just-project-reference.html',
  styleUrl: './addproject-type-parameter-requires-build-not-just-project-reference.scss',
})
export class AddprojectTypeParameterRequiresBuildNotJustProjectReferenceSubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'The main page shows AddProject<Projects.MyApp_Api>("api") throughout its examples without ever explaining where the Projects.MyApp_Api TYPE comes from — it is not a type you write; it is generated by an MSBuild source generator that runs as part of BUILDING the AppHost project, scanning its <ProjectReference> entries',
      points: [
        'When the AppHost <code>.csproj</code> has a <code>&lt;ProjectReference Include="../MyApp.Api/MyApp.Api.csproj" /&gt;</code>, the Aspire SDK\'s build-time source generator creates a static class named after the referenced project (dots and hyphens become underscores — <code>MyApp.Api</code> becomes <code>Projects.MyApp_Api</code>) that exposes metadata the AppHost uses to launch that project as a child process: its assembly path, its configured launch profile, and how to inject environment variables into it.',
        'This means the TYPE parameter and the STRING name in <code>AddProject&lt;Projects.MyApp_Api&gt;("api")</code> are two COMPLETELY INDEPENDENT things serving different purposes: the <strong>type</strong> (resolved entirely at COMPILE TIME, via the project reference) tells Aspire WHICH project to launch; the <strong>string</strong> (used entirely at RUNTIME) is the logical resource name used for service discovery and configuration keys — you could name the string anything, and the generated Projects.MyApp_Api type would still correctly point at the same project.',
      ],
    },
    {
      heading: 'Because this is a BUILD-TIME source generator, not something that reacts to editing files, a very common onboarding friction point is adding a new project reference to the AppHost and then finding that Projects.NewProject simply doesn\'t exist yet as far as the IDE or the compiler is concerned — until an actual build runs',
      points: [
        'Adding <code>&lt;ProjectReference Include="../NewService/NewService.csproj" /&gt;</code> to the AppHost\'s <code>.csproj</code> file (whether by hand or via <code>dotnet add reference</code>) does not immediately make <code>Projects.NewService</code> resolve in the AppHost\'s <code>Program.cs</code> — the source generator that CREATES that type runs as part of the AppHost project\'s OWN build process, so IntelliSense and the compiler only see the new type after the AppHost has actually been built at least once with the new reference in place.',
        'The practical fix when this happens is simply triggering a build — <code>dotnet build</code> on the AppHost project, or a build via the IDE — before expecting <code>Projects.NewService</code> to resolve. This is not a bug or a flaky IDE; it is the deterministic, expected consequence of the type being source-generated from project references at build time rather than being a hand-written or reflection-discovered type.',
      ],
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'What the AppHost .csproj actually needs, and what gets generated',
      language: 'csharp',
      code: `<!-- MyApp.AppHost/MyApp.AppHost.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="8.0.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>
  <ItemGroup>
    <!-- THIS reference is what makes Projects.MyApp_Api exist at all -->
    <ProjectReference Include="../MyApp.Api/MyApp.Api.csproj" />
    <ProjectReference Include="../MyApp.Worker/MyApp.Worker.csproj" />
  </ItemGroup>
</Project>

// After building the AppHost, the Aspire.AppHost.Sdk's source
// generator produces (roughly, conceptually) something equivalent to:
namespace Projects
{
    // Generated — you never write this class yourself:
    internal sealed class MyApp_Api : IProjectMetadata
    {
        public string ProjectPath =>
            "/absolute/path/to/MyApp.Api/MyApp.Api.csproj";
        // Plus assembly path, launch profile info, etc. — everything
        // AddProject<T> needs to actually START this project as a
        // child process with the right working directory and config.
    }

    internal sealed class MyApp_Worker : IProjectMetadata { /* ... */ }
}

// AppHost/Program.cs — the TYPE identifies WHICH project (compile-time,
// via the reference above); the STRING is the runtime resource name
// used for discovery — these are independent:
builder.AddProject<Projects.MyApp_Api>("api");           // string = "api"
builder.AddProject<Projects.MyApp_Api>("api-secondary");  // SAME project
                                                            // type, launched
                                                            // AGAIN under a
                                                            // DIFFERENT
                                                            // resource name —
                                                            // two separate
                                                            // running instances
                                                            // of the same code`,
    },
    {
      label: 'Reproducing and fixing the onboarding friction point',
      language: 'csharp',
      code: `// Scenario: a developer adds a brand-new project to the solution and
// wants to orchestrate it via Aspire.

// Step 1 — add the project reference (by hand or via CLI):
// dotnet add MyApp.AppHost/MyApp.AppHost.csproj reference \\
//   MyApp.Notifications/MyApp.Notifications.csproj

// Step 2 — immediately try to use it in Program.cs:
builder.AddProject<Projects.MyApp_Notifications>("notifications");
// COMPILE ERROR at this point:
//   error CS0246: The type or namespace name 'MyApp_Notifications'
//   does not exist in the namespace 'Projects'
//
// This is NOT because the reference is wrong, and NOT an IDE glitch —
// the source generator that WOULD create Projects.MyApp_Notifications
// has simply never run yet, because the AppHost project itself has
// not been built since the new reference was added.

// THE FIX — build the AppHost project explicitly:
// dotnet build MyApp.AppHost/MyApp.AppHost.csproj
//
// This triggers the Aspire.AppHost.Sdk's source generator, which scans
// the (now-updated) ProjectReference list and emits
// Projects.MyApp_Notifications. After this ONE build, the type
// resolves normally in the IDE and on subsequent builds — the error
// above is a one-time, deterministic consequence of the reference
// being added AFTER the last build, not a persistent problem.

// A quick diagnostic when this happens: check the AppHost's obj/
// folder for a generated file confirming the type actually exists:
// obj/Debug/net8.0/Aspire.AppHost.Sdk/.../Projects.g.cs
// (exact path varies by SDK version — presence of a file here,
// containing "MyApp_Notifications", confirms the generator ran)`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'A team renames a project from "MyApp.Worker" to "MyApp.BackgroundJobs" (renaming the folder, the .csproj file, and the assembly name) but does NOT update the AppHost\'s ProjectReference path, which still points at the old "../MyApp.Worker/MyApp.Worker.csproj" path (now nonexistent). Predict the exact category of error this produces, and explain why it looks different from the "forgot to build" scenario in this subtopic.',
    hint: 'The "forgot to build" scenario is a TYPE that doesn\'t exist yet in the Projects namespace, because the reference IS correctly present but the generator hasn\'t run. Here, the reference path itself points at a file that no longer exists on disk at all — does that fail at the SAME point in the build pipeline, or an earlier one?',
    solution: `This produces a fundamentally different, EARLIER failure: an MSBuild
error about the ProjectReference itself, not a C# compiler error about
a missing type in the Projects namespace. Since the referenced .csproj
file at "../MyApp.Worker/MyApp.Worker.csproj" no longer exists (the
folder and file were renamed), MSBuild fails during the RESTORE/BUILD
EVALUATION phase — before the Aspire source generator ever gets a
chance to run at all — with an error along the lines of "the project
file... could not be found." This is a project-system-level failure,
not a source-generation gap.

The "forgot to build" scenario in this subtopic is different in kind:
there, the ProjectReference is valid and points at a real, existing
.csproj file — the problem is purely that the GENERATOR hasn't run
YET since that reference was added, producing a C# compiler error
(CS0246, missing type) once the AppHost project itself is compiled.
Building the AppHost resolves it immediately, because the referenced
project is real and the generator can successfully scan it.

The rename scenario requires a different, earlier fix: updating the
ProjectReference path in the AppHost's .csproj to point at the NEW
location and filename ("../MyApp.BackgroundJobs/MyApp.BackgroundJobs.csproj").
Only once that reference itself is valid again can the build proceed
far enough for the Aspire source generator to run and produce a
(newly-named) Projects.MyApp_BackgroundJobs type — at which point the
AppHost's Program.cs also needs updating, since the OLD
Projects.MyApp_Worker type reference no longer resolves either.

The general lesson: "the AddProject<T> type doesn't resolve" can stem
from two distinct root causes at two different points in the build
pipeline — a stale/broken project reference path (an MSBuild-level
problem, fixed by correcting the reference) versus a valid reference
that simply hasn't been built yet (a source-generation timing issue,
fixed by triggering a build) — and the exact error message is the
fastest way to tell which one you're actually looking at.`,
  };

  misconceptions: Misconception[] = [
    {
      thought: 'the Projects.MyApp_Api type used in AddProject<Projects.MyApp_Api>("api") is a hand-maintained or reflection-discovered reference to another project, similar to how a normal C# namespace works.',
      reality: 'it is generated by a build-time MSBuild source generator (part of the Aspire.AppHost.Sdk) that scans the AppHost project\'s ProjectReference entries — the type only exists after the AppHost has actually been built with that reference present, and its name is derived mechanically from the referenced project\'s file name.',
    },
    {
      thought: 'the type parameter (Projects.MyApp_Api) and the string argument ("api") in AddProject<Projects.MyApp_Api>("api") are two names for the same underlying concept and must always match in some way.',
      reality: 'they serve completely independent purposes — the type (resolved at compile time via the project reference) identifies WHICH project\'s code to launch, while the string (used at runtime) is purely the logical resource name for service discovery and configuration keys; the same project type can even be registered multiple times under different resource-name strings.',
    },
    {
      thought: 'adding a <ProjectReference> to the AppHost\'s .csproj file for a new project should make its Projects.X type immediately available in the code editor, the same way adding a NuGet package reference makes its namespaces available right away.',
      reality: 'the Projects.X type is produced by a source generator that runs as part of BUILDING the AppHost project — it does not exist until the AppHost has actually been built at least once after the new reference was added, which is a deterministic, expected build-ordering requirement, not an IDE glitch.',
    },
  ];
}
