module.exports = {
  slug: 'async-await',
  subtitle: 'Futures are lazy state machines driven by a runtime. Learn async fn and .await, the Tokio runtime, spawning tasks, running futures concurrently with join! and select!, timeouts, cancellation and keeping blocking work off the async threads.',
  readingTime: 28,
  prerequisites: [{ label: 'Concurrency & Threads', route: '/rust/concurrency' }, { label: 'Traits & Generics', route: '/rust/traits-generics' }],
  apis: ['async fn / .await', '#[tokio::main]', 'tokio::spawn / JoinSet', 'tokio::join! / select!', 'tokio::time::timeout', 'spawn_blocking', 'tokio::sync::Mutex / mpsc'],
  tip: 'Never block inside async code. std::thread::sleep, synchronous file or network I/O and heavy CPU loops freeze a runtime worker and every task scheduled on it. Use tokio::time::sleep, async I/O, or move the work to spawn_blocking.',
  gotchas: [
    'Calling an async fn does nothing until the returned future is awaited or spawned — a forgotten .await is a silent no-op (the compiler warns that futures must be used).',
    'tokio::spawn requires the future to be Send + \'static: holding a std MutexGuard or an Rc across an .await makes it fail to compile.',
    'select! cancels the branches that lose by dropping their futures; work that was half done in them is lost unless the operation is cancellation-safe.',
  ],
  quickRef: [
    { name: 'async fn fetch() -> T', type: 'syntax', desc: 'Returns impl Future<Output = T>; the body runs only when polled' },
    { name: 'fut.await', type: 'operator', desc: 'Suspend the current task until the future completes' },
    { name: '#[tokio::main]', type: 'decorator', desc: 'Start a multi-threaded Tokio runtime and block on async main' },
    { name: 'tokio::spawn(fut)', type: 'function', desc: 'Run a task concurrently; returns a JoinHandle (awaitable, abortable)' },
    { name: 'tokio::join!(a, b)', type: 'function', desc: 'Run futures concurrently within the current task and wait for all' },
    { name: 'tokio::select! { .. }', type: 'function', desc: 'Wait for the first of several futures; the others are dropped' },
    { name: 'tokio::time::timeout(dur, fut)', type: 'function', desc: 'Err(Elapsed) if the future does not finish in time' },
    { name: 'tokio::task::spawn_blocking(f)', type: 'function', desc: 'Run blocking or CPU-heavy code on a dedicated thread pool' },
    { name: 'JoinSet', type: 'class', desc: 'Own a dynamic set of tasks and collect results as they finish' },
    { name: 'tokio::sync::{mpsc, Mutex, Semaphore}', type: 'class', desc: 'Async-aware channels, locks and concurrency limits' },
  ],
  theory: [
    { heading: 'Futures and the runtime', points: [
      'An `async fn` returns a future: a state machine generated by the compiler that records where execution paused. Nothing runs until something polls it.',
      'Rust ships no built-in runtime. A runtime such as Tokio provides the executor (polls futures), the reactor (wakes them when sockets or timers are ready) and async versions of I/O, timers and synchronisation.',
      '`.await` polls the future; if it is not ready, the task yields so the worker thread can run other tasks, and is resumed when it is woken.',
      'Async is about concurrency for I/O-bound work — thousands of mostly-waiting connections on a few threads. CPU-bound work does not get faster by being async.',
      'Self-referential state machines are pinned in memory (`Pin`), which is why some APIs require `Box::pin(fut)` or `tokio::pin!`.',
    ] },
    { heading: 'Tasks, join! and select!', points: [
      '`tokio::spawn` creates an independent task that can run in parallel on another worker thread. It needs `Send + \'static` futures, so move owned data (or `Arc`) into it.',
      'A `JoinHandle` can be awaited for the result (`Err` if the task panicked or was aborted) or cancelled with `.abort()`. Dropping the handle does not cancel the task.',
      '`tokio::join!(a, b)` runs several futures concurrently inside the current task and waits for all of them; `try_join!` stops at the first error.',
      '`tokio::select!` waits for whichever branch completes first and drops the rest. Dropping a future is how cancellation works in Rust async — every `.await` is a possible cancellation point.',
      '`JoinSet` manages a dynamic number of spawned tasks and returns results in completion order with `join_next().await`.',
    ] },
    { heading: 'Time, cancellation and limits', points: [
      'Wrap any future in `tokio::time::timeout(duration, fut)` to bound how long it may take; on timeout the inner future is dropped.',
      'Bound concurrency with `tokio::sync::Semaphore` (e.g. at most 10 outgoing requests) or bounded `mpsc` channels, otherwise a burst of work can spawn unbounded tasks.',
      'A cancellation-safe operation loses no data when its future is dropped mid-way. `mpsc::Receiver::recv` is cancellation-safe; reading into a buffer partially and then dropping may not be — check the docs before using an operation in `select!` loops.',
      'For graceful shutdown, combine a shutdown signal (`tokio::signal::ctrl_c`, a `watch` channel or a `CancellationToken` from tokio-util) with `select!` in long-running loops.',
    ] },
    { heading: 'Blocking, locks and Send', points: [
      'Blocking calls (`std::thread::sleep`, `std::fs`, synchronous database drivers, long CPU loops) stall the worker thread. Use the async equivalents, or `tokio::task::spawn_blocking`.',
      'A `std::sync::MutexGuard` is not `Send`; holding one across `.await` makes the future non-`Send`, so `tokio::spawn` rejects it. Lock, copy what you need, drop the guard, then await.',
      'Use `tokio::sync::Mutex` only when a lock must be held across an `.await`; otherwise the std mutex is faster for short critical sections.',
      'Traits support `async fn` methods since Rust 1.75, and async closures (`async || ...`) are stable since Rust 1.85.',
    ] },
  ],
  codeTabs: [
    { label: 'Futures are lazy', language: 'rust', code: `use std::time::{Duration, Instant};
use tokio::time::sleep;

async fn fetch(name: &str, ms: u64) -> String {
    sleep(Duration::from_millis(ms)).await;     // async sleep: yields, does not block
    format!("{name} done")
}

#[tokio::main]
async fn main() {
    let fut = fetch("lazy", 10);                // nothing has run yet
    println!("created future");
    println!("{}", fut.await);                  // now it runs

    // Sequential: ~200ms
    let t = Instant::now();
    let a = fetch("a", 100).await;
    let b = fetch("b", 100).await;
    println!("{a}, {b} sequential in ~{}ms", t.elapsed().as_millis() / 100 * 100);

    // Concurrent within one task: ~100ms
    let t = Instant::now();
    let (a, b) = tokio::join!(fetch("a", 100), fetch("b", 100));
    println!("{a}, {b} concurrent in ~{}ms", t.elapsed().as_millis() / 100 * 100);
}` },
    { label: 'Spawning tasks', language: 'rust', code: `use std::sync::Arc;
use tokio::sync::Semaphore;
use tokio::task::JoinSet;
use tokio::time::{sleep, Duration};

async fn download(id: u32) -> Result<usize, String> {
    sleep(Duration::from_millis(10 * id as u64)).await;
    if id == 3 { Err(format!("item {id} failed")) } else { Ok(id as usize * 100) }
}

#[tokio::main]
async fn main() {
    let limit = Arc::new(Semaphore::new(2));     // at most 2 downloads at once
    let mut set = JoinSet::new();
    for id in 1..=5 {
        let limit = Arc::clone(&limit);          // 'static: move owned Arc in
        set.spawn(async move {
            let _permit = limit.acquire_owned().await.unwrap();
            (id, download(id).await)
        });
    }

    let mut ok = 0;
    while let Some(res) = set.join_next().await {   // completion order
        match res.expect("task panicked") {
            (id, Ok(bytes)) => { ok += bytes; println!("#{id}: {bytes} bytes"); }
            (id, Err(e)) => println!("#{id}: {e}"),
        }
    }
    println!("total {ok} bytes");

    // Aborting a long task
    let long = tokio::spawn(async { sleep(Duration::from_secs(60)).await; 42 });
    long.abort();
    println!("aborted: {}", long.await.unwrap_err().is_cancelled());
}` },
    { label: 'select!, timeout, blocking', language: 'rust', code: `use tokio::sync::mpsc;
use tokio::time::{sleep, timeout, Duration};

fn expensive_hash(n: u64) -> u64 {
    (0..n).fold(0u64, |acc, x| acc.wrapping_mul(31).wrapping_add(x))
}

#[tokio::main]
async fn main() {
    // timeout: bound how long an operation may take
    match timeout(Duration::from_millis(50), sleep(Duration::from_secs(5))).await {
        Ok(_) => println!("finished"),
        Err(_) => println!("timed out after 50ms"),
    }

    // select!: first branch wins, the other future is dropped (cancelled)
    let (tx, mut rx) = mpsc::channel::<&str>(8);
    tokio::spawn(async move {
        sleep(Duration::from_millis(20)).await;
        tx.send("job-1").await.unwrap();
    });
    let shutdown = sleep(Duration::from_millis(200));
    tokio::pin!(shutdown);
    loop {
        tokio::select! {
            Some(job) = rx.recv() => println!("got {job}"),  // recv is cancellation-safe
            _ = &mut shutdown => { println!("shutdown"); break; }
        }
    }

    // CPU-heavy work off the async worker threads
    let h = tokio::task::spawn_blocking(|| expensive_hash(5_000_000));
    println!("hash computed: {}", h.await.unwrap() != 0);
}` },
  ],
  mistakes: [
    { title: 'Forgetting to await a future', wrong: `async fn save(user: &User) -> Result<(), Error> { /* ... */ }

save(&user);        // warning: unused future; nothing is saved`, right: `save(&user).await?;`, explanation: 'Futures are lazy. Without .await (or spawning) the body never runs. The compiler warns that futures do nothing unless polled — treat that warning as an error.' },
    { title: 'Blocking the runtime', wrong: `async fn handler() {
    std::thread::sleep(Duration::from_secs(1)); // blocks the worker thread
    let data = std::fs::read_to_string("big.json").unwrap();
}`, right: `async fn handler() {
    tokio::time::sleep(Duration::from_secs(1)).await;
    let data = tokio::fs::read_to_string("big.json").await.unwrap();
}`, explanation: 'A blocked worker cannot poll any other task, so a few blocking calls can stall the whole server. Use async APIs or spawn_blocking.' },
    { title: 'Holding a std MutexGuard across .await', checkWrong: true, wrong: `use std::sync::{Arc, Mutex};
async fn work(m: Arc<Mutex<Vec<u32>>>) {
    let mut g = m.lock().unwrap();
    tokio::time::sleep(std::time::Duration::from_millis(1)).await;
    g.push(1);
}
fn start(m: Arc<Mutex<Vec<u32>>>) { tokio::spawn(work(m)); }`, right: `use std::sync::{Arc, Mutex};
async fn work(m: Arc<Mutex<Vec<u32>>>) {
    tokio::time::sleep(std::time::Duration::from_millis(1)).await;
    m.lock().unwrap().push(1);        // lock only after the await
}
fn start(m: Arc<Mutex<Vec<u32>>>) { tokio::spawn(work(m)); }`, explanation: 'std::sync::MutexGuard is not Send, so a future that keeps it alive across an await is not Send and tokio::spawn rejects it ("future cannot be sent between threads safely"). Scope the guard so it is dropped before awaiting, or use tokio::sync::Mutex if the lock must span the await.' },
    { title: 'Spawning with borrowed data', checkWrong: true, wrong: `async fn run(names: Vec<String>) {
    tokio::spawn(async {
        println!("{}", names.len());
    });
}`, right: `async fn run(names: Vec<String>) {
    tokio::spawn(async move {
        println!("{}", names.len());
    });
}`, explanation: 'tokio::spawn needs a \'static future because the task may outlive the caller. Without move the async block borrows names (E0373). Move owned data (or an Arc clone) in.' },
    { title: 'Unbounded task spawning', wrong: `for url in urls {             // 100,000 URLs
    tokio::spawn(fetch(url));  // 100,000 concurrent requests
}`, right: `let sem = Arc::new(Semaphore::new(50));
for url in urls {
    let permit = sem.clone().acquire_owned().await.unwrap();
    tokio::spawn(async move { let _p = permit; fetch(url).await });
}`, explanation: 'Tasks are cheap but the resources they use (sockets, memory, the remote server) are not. Bound concurrency with a Semaphore, a bounded channel, or a stream with buffer_unordered.' },
  ],
  challenge: {
    title: 'Fetch with retry and deadline',
    language: 'rust',
    test: false,
    description: 'Write async fn fetch_with_retry(attempts_to_fail: u32, max_retries: u32, deadline: Duration) -> Result<String, String>. Simulate a flaky call (fails attempts_to_fail times, each try sleeps 20ms) and retry with exponential backoff (10ms, 20ms, 40ms...). The whole operation must be wrapped in tokio::time::timeout(deadline, ...). Return Err("timeout") when the deadline passes and Err("gave up") when retries run out.',
    hints: ['Keep the retry loop in an inner async block and pass it to timeout.', 'backoff = Duration::from_millis(10 * 2u64.pow(attempt)).', 'Map timeout\'s Err(Elapsed) to "timeout" with map_err, then flatten the inner Result with ?.'],
    starterCode: `use tokio::time::{sleep, timeout, Duration};

async fn fetch_with_retry(attempts_to_fail: u32, max_retries: u32, deadline: Duration) -> Result<String, String> {
    todo!()
}

#[tokio::main]
async fn main() {
    println!("{:?}", fetch_with_retry(2, 5, Duration::from_secs(1)).await);
}`,
    solution: `use tokio::time::{sleep, timeout, Duration};

async fn flaky_call(attempt: u32, attempts_to_fail: u32) -> Result<String, String> {
    sleep(Duration::from_millis(20)).await;
    if attempt < attempts_to_fail { Err(format!("attempt {attempt} failed")) } else { Ok(format!("ok on attempt {attempt}")) }
}

async fn fetch_with_retry(attempts_to_fail: u32, max_retries: u32, deadline: Duration) -> Result<String, String> {
    let work = async {
        for attempt in 0..=max_retries {
            match flaky_call(attempt, attempts_to_fail).await {
                Ok(v) => return Ok(v),
                Err(_) if attempt < max_retries => {
                    sleep(Duration::from_millis(10 * 2u64.pow(attempt))).await;
                }
                Err(_) => break,
            }
        }
        Err("gave up".to_string())
    };
    timeout(deadline, work).await.map_err(|_| "timeout".to_string())?
}

#[tokio::main]
async fn main() {
    println!("{:?}", fetch_with_retry(2, 5, Duration::from_secs(1)).await);      // Ok("ok on attempt 2")
    println!("{:?}", fetch_with_retry(10, 2, Duration::from_secs(1)).await);     // Err("gave up")
    println!("{:?}", fetch_with_retry(10, 10, Duration::from_millis(100)).await); // Err("timeout")
}`,
  },
  quiz: [
    { q: 'What happens when you call an async fn without awaiting or spawning the result?', options: ['It runs in the background', 'It runs synchronously', 'Nothing runs — the future is created and dropped', 'It panics'], answer: 2, explanation: 'Futures are lazy; the body only executes when the future is polled. The compiler warns about unused futures.' },
    { q: 'What is the difference between tokio::join! and tokio::spawn?', options: ['There is none', 'join! runs futures concurrently inside the current task; spawn creates independent tasks that can run on other threads', 'join! runs in parallel threads; spawn is sequential', 'spawn waits for completion automatically'], answer: 1, explanation: 'join! interleaves futures within one task. spawn hands the future to the scheduler as its own task, which requires Send + \'static.' },
    { q: 'In tokio::select!, what happens to the branches that do not complete first?', options: ['They keep running in the background', 'They are dropped, which cancels them', 'They are retried', 'They complete before select! returns'], answer: 1, explanation: 'select! drops the remaining futures. Any progress they made is lost unless the operation is cancellation-safe.' },
    { q: 'Why might tokio::spawn reject a future that uses a std::sync::MutexGuard?', options: ['MutexGuard is too large', 'Holding the guard across .await makes the future non-Send', 'Mutex cannot be used in async code at all', 'spawn only accepts closures'], answer: 1, explanation: 'MutexGuard is not Send. If it is alive at an await point it becomes part of the future\'s state, so the future is not Send.' },
    { q: 'How should CPU-heavy work be run from async code?', options: ['Directly in the async function', 'With tokio::task::spawn_blocking or a dedicated thread pool such as rayon', 'Inside select!', 'By adding more .await calls'], answer: 1, explanation: 'Long CPU work blocks the worker thread. spawn_blocking moves it to a pool meant for blocking tasks; rayon suits parallel CPU work.' },
  ],
  qna: [
    { q: 'How do Rust futures differ from JavaScript promises?', a: 'A JavaScript promise starts running as soon as it is created. A Rust future is inert until polled, so creating one costs nothing and has no side effects. Rust also has no built-in runtime — you choose one (usually Tokio) — and futures compile to state machines without heap allocation per await. Cancellation is simply dropping the future, which has no direct equivalent for promises.' },
    { q: 'What is the difference between concurrency and parallelism in Tokio?', a: 'Concurrency means many tasks make progress by interleaving at `.await` points; parallelism means they run at the same instant on different cores. `join!` gives concurrency within one task. `tokio::spawn` on the multi-threaded runtime gives both: tasks are interleaved on each worker and spread across several worker threads. Async helps most when tasks spend their time waiting on I/O.' },
    { q: 'Why must spawned futures be Send + \'static?', a: 'The multi-threaded scheduler can move a task between worker threads whenever it yields, so everything held across an `.await` must be `Send`. And the task can outlive the function that spawned it, so it cannot borrow from that function\'s stack — hence `\'static`. Fix errors by moving owned data or `Arc` clones in, and by not holding non-`Send` values (std guards, `Rc`) across awaits.' },
    { q: 'What is cancellation safety?', a: 'In Rust, cancelling a future means dropping it, which can happen at any `.await` — most commonly when another `select!` branch wins or a timeout fires. An operation is cancellation-safe if dropping it part-way loses no data. `mpsc::Receiver::recv` is safe: a message is either returned or stays in the channel. Reading a framed message into a local buffer may not be, because partially read bytes are lost. Tokio documents the cancellation safety of its methods.' },
    { q: 'When should you use tokio::sync::Mutex instead of std::sync::Mutex?', a: 'Use the std mutex by default, even in async code, as long as the guard is never held across an `.await` — it is faster and the critical section is short. Use `tokio::sync::Mutex` when you genuinely need to hold the lock while awaiting (for example serialising access to a connection during an async call). Often a better design is an actor task that owns the resource and receives commands over a channel.' },
  ],
  revision: {
    oneLiner: 'Async functions return lazy futures that a runtime like Tokio polls; spawn tasks for parallelism, join!/select! for concurrency within a task, and never block the async workers.',
    mustKnow: [
      'Futures do nothing until awaited or spawned.',
      '`tokio::spawn` needs `Send + \'static`; move owned data or `Arc` in.',
      '`join!` waits for all; `select!` takes the first and drops (cancels) the rest.',
      'Bound work with `timeout`, `Semaphore` and bounded channels.',
      'No blocking calls in async code — use async I/O or `spawn_blocking`.',
      'Do not hold a std `MutexGuard` across `.await`.',
    ],
    interviewFocus: [
      'Explain how futures, executors and wakers fit together.',
      'Compare join!, select!, spawn and JoinSet.',
      'Explain cancellation by dropping and cancellation safety.',
      'Diagnose a "future cannot be sent between threads safely" error.',
    ],
  },
};
