import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./components/hub-home/hub-home').then(m => m.HubHome) },

  // ── Angular ───────────────────────────────────────────────────────────────
  {
    path: 'angular',
    children: [
      { path: '', loadComponent: () => import('./components/home/home').then(m => m.Home) },
      { path: 'counter',            loadComponent: () => import('./components/counter/counter').then(m => m.Counter) },
      { path: 'todo',               canActivate: [authGuard], loadComponent: () => import('./components/todo/todo').then(m => m.TodoComponent) },
      { path: 'forms',              loadComponent: () => import('./components/forms-demo/forms-demo').then(m => m.FormsDemo) },
      { path: 'http',               loadComponent: () => import('./components/http-demo/http-demo').then(m => m.HttpDemo) },
      { path: 'parent-child',       loadComponent: () => import('./components/parent-child/parent-child').then(m => m.ParentChildComponent) },
      { path: 'form-array',         loadComponent: () => import('./components/form-array/form-array').then(m => m.FormArrayDemo) },
      { path: 'defer',              loadComponent: () => import('./components/defer-demo/defer-demo').then(m => m.DeferDemo) },
      { path: 'material',           loadComponent: () => import('./components/material-demo/material-demo').then(m => m.MaterialDemo) },
      { path: 'store',              loadComponent: () => import('./components/signal-store/signal-store').then(m => m.SignalStoreDemo) },
      { path: 'templates',          loadComponent: () => import('./components/template-syntax/template-syntax').then(m => m.TemplateSyntax) },
      { path: 'directives',         loadComponent: () => import('./components/directives-demo/directives-demo').then(m => m.DirectivesDemo) },
      { path: 'lifecycle',          loadComponent: () => import('./components/lifecycle/lifecycle').then(m => m.LifecycleDemo) },
      { path: 'pipes',              loadComponent: () => import('./components/pipes-demo/pipes-demo').then(m => m.PipesDemo) },
      { path: 'di',                 loadComponent: () => import('./components/di-demo/di-demo').then(m => m.DiDemo) },
      { path: 'routing',            loadComponent: () => import('./components/routing-demo/routing-demo').then(m => m.RoutingDemo) },
      { path: 'charts',             loadComponent: () => import('./components/charts/charts').then(m => m.ChartsDemo) },
      { path: 'zod-forms',          loadComponent: () => import('./components/zod-forms/zod-forms').then(m => m.ZodFormsDemo) },
      { path: 'content-projection', loadComponent: () => import('./components/content-projection/content-projection').then(m => m.ContentProjectionDemo) },
      { path: 'change-detection',   loadComponent: () => import('./components/change-detection/change-detection').then(m => m.ChangeDetectionDemo) },
      { path: 'custom-validators',  loadComponent: () => import('./components/custom-validators/custom-validators').then(m => m.CustomValidatorsDemo) },
      { path: 'rxjs',               loadComponent: () => import('./components/rxjs-demo/rxjs-demo').then(m => m.RxjsDemo) },
      { path: 'cdk',                loadComponent: () => import('./components/cdk-demo/cdk-demo').then(m => m.CdkDemo) },
      { path: 'ag-grid',            loadComponent: () => import('./components/ag-grid-demo/ag-grid-demo').then(m => m.AgGridDemo) },
      { path: 'tanstack-query',     loadComponent: () => import('./components/tanstack-query/tanstack-query').then(m => m.TanstackQueryDemo) },
      { path: 'date-fns',           loadComponent: () => import('./components/datefns-demo/datefns-demo').then(m => m.DateFnsDemo) },
      { path: 'animations',         loadComponent: () => import('./components/animations-demo/animations-demo').then(m => m.AnimationsDemo) },
      { path: 'cva',                loadComponent: () => import('./components/cva-demo/cva-demo').then(m => m.CvaDemo) },
      { path: 'testing',            loadComponent: () => import('./components/testing-demo/testing-demo').then(m => m.TestingDemo) },
      { path: 'tailwind',           loadComponent: () => import('./components/tailwind-demo/tailwind-demo').then(m => m.TailwindDemo) },
      { path: 'resource-api',       loadComponent: () => import('./components/resource-api/resource-api').then(m => m.ResourceApiDemo) },
      { path: 'ngrx-signals',       loadComponent: () => import('./components/ngrx-signals/ngrx-signals').then(m => m.NgrxSignalsDemo) },
      { path: 'dynamic-forms',      loadComponent: () => import('./components/dynamic-forms/dynamic-forms').then(m => m.DynamicFormsDemo) },
      { path: 'route-resolvers',    loadComponent: () => import('./components/route-resolvers/route-resolvers').then(m => m.RouteResolversDemo) },
      { path: 'preloading',         loadComponent: () => import('./components/preloading/preloading').then(m => m.PreloadingDemo) },
      { path: 'ng-image',           loadComponent: () => import('./components/ng-image/ng-image').then(m => m.NgImageDemo) },
      { path: 'destroy-ref',        loadComponent: () => import('./components/destroy-ref/destroy-ref').then(m => m.DestroyRefDemo) },
      { path: 'linked-signal',      loadComponent: () => import('./components/linked-signal/linked-signal').then(m => m.LinkedSignalDemo) },
      { path: 'zoneless',           loadComponent: () => import('./components/zoneless/zoneless').then(m => m.ZonelessDemo) },
      { path: 'wizard-form',        loadComponent: () => import('./components/wizard-form/wizard-form').then(m => m.WizardFormDemo) },
      { path: 'web-workers',        loadComponent: () => import('./components/web-workers/web-workers').then(m => m.WebWorkersDemo) },
      { path: 'pwa',                loadComponent: () => import('./components/pwa/pwa').then(m => m.PwaDemo) },
      { path: 'i18n',               loadComponent: () => import('./components/i18n/i18n').then(m => m.I18nDemo) },
      { path: 'e2e',                loadComponent: () => import('./components/e2e/e2e').then(m => m.E2eDemo) },
      { path: 'harnesses',          loadComponent: () => import('./components/harnesses/harnesses').then(m => m.HarnessesDemo) },
      { path: 'ssr',                loadComponent: () => import('./components/ssr/ssr').then(m => m.SsrDemo) },
      { path: 'cheatsheet',         loadComponent: () => import('./components/cheatsheet/cheatsheet').then(m => m.CheatsheetComponent) },
      { path: 'errors',             loadComponent: () => import('./components/errors-page/errors-page').then(m => m.ErrorsPageComponent) },
      { path: 'whats-new',          loadComponent: () => import('./components/whats-new/whats-new').then(m => m.WhatsNewComponent) },
      { path: 'mini-projects',      loadComponent: () => import('./components/mini-projects/mini-projects').then(m => m.MiniProjectsComponent) },
      { path: 'learning-paths',     loadComponent: () => import('./components/learning-paths/learning-paths').then(m => m.LearningPathsComponent) },
    ],
  },

  { path: '**', redirectTo: '' },
];
