import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./components/hub-home/hub-home').then(m => m.HubHome) },

  // ── Angular ───────────────────────────────────────────────────────────────
  {
    path: 'angular',
    children: [
      { path: '', loadComponent: () => import('./components/angular/home/home').then(m => m.Home) },
      { path: 'counter',            loadComponent: () => import('./components/angular/counter/counter').then(m => m.Counter) },
      { path: 'todo',               canActivate: [authGuard], loadComponent: () => import('./components/angular/todo/todo').then(m => m.TodoComponent) },
      { path: 'forms',              loadComponent: () => import('./components/angular/forms-demo/forms-demo').then(m => m.FormsDemo) },
      { path: 'http',               loadComponent: () => import('./components/angular/http-demo/http-demo').then(m => m.HttpDemo) },
      { path: 'parent-child',       loadComponent: () => import('./components/angular/parent-child/parent-child').then(m => m.ParentChildComponent) },
      { path: 'form-array',         loadComponent: () => import('./components/angular/form-array/form-array').then(m => m.FormArrayDemo) },
      { path: 'defer',              loadComponent: () => import('./components/angular/defer-demo/defer-demo').then(m => m.DeferDemo) },
      { path: 'material',           loadComponent: () => import('./components/angular/material-demo/material-demo').then(m => m.MaterialDemo) },
      { path: 'store',              loadComponent: () => import('./components/angular/signal-store/signal-store').then(m => m.SignalStoreDemo) },
      { path: 'templates',          loadComponent: () => import('./components/angular/template-syntax/template-syntax').then(m => m.TemplateSyntax) },
      { path: 'directives',         loadComponent: () => import('./components/angular/directives-demo/directives-demo').then(m => m.DirectivesDemo) },
      { path: 'lifecycle',          loadComponent: () => import('./components/angular/lifecycle/lifecycle').then(m => m.LifecycleDemo) },
      { path: 'pipes',              loadComponent: () => import('./components/angular/pipes-demo/pipes-demo').then(m => m.PipesDemo) },
      { path: 'di',                 loadComponent: () => import('./components/angular/di-demo/di-demo').then(m => m.DiDemo) },
      { path: 'routing',            loadComponent: () => import('./components/angular/routing-demo/routing-demo').then(m => m.RoutingDemo) },
      { path: 'charts',             loadComponent: () => import('./components/angular/charts/charts').then(m => m.ChartsDemo) },
      { path: 'zod-forms',          loadComponent: () => import('./components/angular/zod-forms/zod-forms').then(m => m.ZodFormsDemo) },
      { path: 'content-projection', loadComponent: () => import('./components/angular/content-projection/content-projection').then(m => m.ContentProjectionDemo) },
      { path: 'change-detection',   loadComponent: () => import('./components/angular/change-detection/change-detection').then(m => m.ChangeDetectionDemo) },
      { path: 'custom-validators',  loadComponent: () => import('./components/angular/custom-validators/custom-validators').then(m => m.CustomValidatorsDemo) },
      { path: 'rxjs',               loadComponent: () => import('./components/angular/rxjs-demo/rxjs-demo').then(m => m.RxjsDemo) },
      { path: 'cdk',                loadComponent: () => import('./components/angular/cdk-demo/cdk-demo').then(m => m.CdkDemo) },
      { path: 'ag-grid',            loadComponent: () => import('./components/angular/ag-grid-demo/ag-grid-demo').then(m => m.AgGridDemo) },
      { path: 'tanstack-query',     loadComponent: () => import('./components/angular/tanstack-query/tanstack-query').then(m => m.TanstackQueryDemo) },
      { path: 'date-fns',           loadComponent: () => import('./components/angular/datefns-demo/datefns-demo').then(m => m.DateFnsDemo) },
      { path: 'animations',         loadComponent: () => import('./components/angular/animations-demo/animations-demo').then(m => m.AnimationsDemo) },
      { path: 'cva',                loadComponent: () => import('./components/angular/cva-demo/cva-demo').then(m => m.CvaDemo) },
      { path: 'testing',            loadComponent: () => import('./components/angular/testing-demo/testing-demo').then(m => m.TestingDemo) },
      { path: 'tailwind',           loadComponent: () => import('./components/angular/tailwind-demo/tailwind-demo').then(m => m.TailwindDemo) },
      { path: 'resource-api',       loadComponent: () => import('./components/angular/resource-api/resource-api').then(m => m.ResourceApiDemo) },
      { path: 'ngrx-signals',       loadComponent: () => import('./components/angular/ngrx-signals/ngrx-signals').then(m => m.NgrxSignalsDemo) },
      { path: 'dynamic-forms',      loadComponent: () => import('./components/angular/dynamic-forms/dynamic-forms').then(m => m.DynamicFormsDemo) },
      { path: 'route-resolvers',    loadComponent: () => import('./components/angular/route-resolvers/route-resolvers').then(m => m.RouteResolversDemo) },
      { path: 'preloading',         loadComponent: () => import('./components/angular/preloading/preloading').then(m => m.PreloadingDemo) },
      { path: 'ng-image',           loadComponent: () => import('./components/angular/ng-image/ng-image').then(m => m.NgImageDemo) },
      { path: 'destroy-ref',        loadComponent: () => import('./components/angular/destroy-ref/destroy-ref').then(m => m.DestroyRefDemo) },
      { path: 'linked-signal',      loadComponent: () => import('./components/angular/linked-signal/linked-signal').then(m => m.LinkedSignalDemo) },
      { path: 'zoneless',           loadComponent: () => import('./components/angular/zoneless/zoneless').then(m => m.ZonelessDemo) },
      { path: 'wizard-form',        loadComponent: () => import('./components/angular/wizard-form/wizard-form').then(m => m.WizardFormDemo) },
      { path: 'web-workers',        loadComponent: () => import('./components/angular/web-workers/web-workers').then(m => m.WebWorkersDemo) },
      { path: 'pwa',                loadComponent: () => import('./components/angular/pwa/pwa').then(m => m.PwaDemo) },
      { path: 'i18n',               loadComponent: () => import('./components/angular/i18n/i18n').then(m => m.I18nDemo) },
      { path: 'e2e',                loadComponent: () => import('./components/angular/e2e/e2e').then(m => m.E2eDemo) },
      { path: 'harnesses',          loadComponent: () => import('./components/angular/harnesses/harnesses').then(m => m.HarnessesDemo) },
      { path: 'ssr',                loadComponent: () => import('./components/angular/ssr/ssr').then(m => m.SsrDemo) },
      { path: 'cheatsheet',         loadComponent: () => import('./components/angular/cheatsheet/cheatsheet').then(m => m.CheatsheetComponent) },
      { path: 'errors',             loadComponent: () => import('./components/angular/errors-page/errors-page').then(m => m.ErrorsPageComponent) },
      { path: 'whats-new',          loadComponent: () => import('./components/angular/whats-new/whats-new').then(m => m.WhatsNewComponent) },
      { path: 'mini-projects',      loadComponent: () => import('./components/angular/mini-projects/mini-projects').then(m => m.MiniProjectsComponent) },
      { path: 'learning-paths',     loadComponent: () => import('./components/angular/learning-paths/learning-paths').then(m => m.LearningPathsComponent) },
    ],
  },

  // ── C# ────────────────────────────────────────────────────────────────────
  {
    path: 'csharp',
    children: [
      { path: '',                loadComponent: () => import('./components/backend/csharp/home/home').then(m => m.CsharpHome) },
      { path: 'basics',          loadComponent: () => import('./components/backend/csharp/basics/basics').then(m => m.CsharpBasics) },
      { path: 'oop',             loadComponent: () => import('./components/backend/csharp/oop/oop').then(m => m.CsharpOop) },
      { path: 'records',         loadComponent: () => import('./components/backend/csharp/records/records').then(m => m.CsharpRecords) },
      { path: 'generics',        loadComponent: () => import('./components/backend/csharp/generics/generics').then(m => m.CsharpGenerics) },
      { path: 'collections',     loadComponent: () => import('./components/backend/csharp/collections/collections').then(m => m.CsharpCollections) },
      { path: 'linq',            loadComponent: () => import('./components/backend/csharp/linq/linq').then(m => m.CsharpLinq) },
      { path: 'async',           loadComponent: () => import('./components/backend/csharp/async/async').then(m => m.CsharpAsync) },
      { path: 'null-safety',     loadComponent: () => import('./components/backend/csharp/null-safety/null-safety').then(m => m.CsharpNullSafety) },
      { path: 'pattern-matching',loadComponent: () => import('./components/backend/csharp/pattern-matching/pattern-matching').then(m => m.CsharpPatternMatching) },
      { path: 'exceptions',      loadComponent: () => import('./components/backend/csharp/exceptions/exceptions').then(m => m.CsharpExceptions) },
      { path: 'delegates',         loadComponent: () => import('./components/backend/csharp/delegates/delegates').then(m => m.CsharpDelegates) },
      // ── Fundamentals ──
      { path: 'fields',            loadComponent: () => import('./components/backend/csharp/fields/fields').then(m => m.CsharpFields) },
      { path: 'methods',           loadComponent: () => import('./components/backend/csharp/methods/methods').then(m => m.CsharpMethods) },
      { path: 'type-conversion',   loadComponent: () => import('./components/backend/csharp/type-conversion/type-conversion').then(m => m.CsharpTypeConversion) },
      { path: 'constructors',      loadComponent: () => import('./components/backend/csharp/constructors/constructors').then(m => m.CsharpConstructors) },
      { path: 'properties-indexers', loadComponent: () => import('./components/backend/csharp/properties-indexers/properties-indexers').then(m => m.CsharpPropertiesIndexers) },
      { path: 'namespaces',        loadComponent: () => import('./components/backend/csharp/namespaces/namespaces').then(m => m.CsharpNamespaces) },
      // ── OOP ──
      { path: 'inheritance',       loadComponent: () => import('./components/backend/csharp/inheritance/inheritance').then(m => m.CsharpInheritance) },
      { path: 'abstract-interfaces', loadComponent: () => import('./components/backend/csharp/abstract-interfaces/abstract-interfaces').then(m => m.CsharpAbstractInterfaces) },
      { path: 'static-enums',      loadComponent: () => import('./components/backend/csharp/static-enums/static-enums').then(m => m.CsharpStaticEnums) },
      { path: 'structures',        loadComponent: () => import('./components/backend/csharp/structures/structures').then(m => m.CsharpStructures) },
      { path: 'system-object',     loadComponent: () => import('./components/backend/csharp/system-object/system-object').then(m => m.CsharpSystemObject) },
      // ── Types ──
      { path: 'extension-methods', loadComponent: () => import('./components/backend/csharp/extension-methods/extension-methods').then(m => m.CsharpExtensionMethods) },
      { path: 'tuples',            loadComponent: () => import('./components/backend/csharp/tuples/tuples').then(m => m.CsharpTuples) },
      { path: 'arrays',            loadComponent: () => import('./components/backend/csharp/arrays/arrays').then(m => m.CsharpArrays) },
      { path: 'strings-datetime',  loadComponent: () => import('./components/backend/csharp/strings-datetime/strings-datetime').then(m => m.CsharpStringsDatetime) },
      // ── Data / Memory ──
      { path: 'io-serialization',  loadComponent: () => import('./components/backend/csharp/io-serialization/io-serialization').then(m => m.CsharpIoSerialization) },
      { path: 'gc-disposable',     loadComponent: () => import('./components/backend/csharp/gc-disposable/gc-disposable').then(m => m.CsharpGcDisposable) },
      // ── Concurrency ──
      { path: 'threading',         loadComponent: () => import('./components/backend/csharp/threading/threading').then(m => m.CsharpThreading) },
      { path: 'tasks',             loadComponent: () => import('./components/backend/csharp/tasks/tasks').then(m => m.CsharpTasks) },
      // ── What's New ──
      { path: 'whats-new-9-10',    loadComponent: () => import('./components/backend/csharp/whats-new-9-10/whats-new-9-10').then(m => m.CsharpWhatsNew910) },
      { path: 'whats-new-11-12',   loadComponent: () => import('./components/backend/csharp/whats-new-11-12/whats-new-11-12').then(m => m.CsharpWhatsNew1112) },
      { path: 'whats-new-latest',  loadComponent: () => import('./components/backend/csharp/whats-new-latest/whats-new-latest').then(m => m.CsharpWhatsNewLatest) },
      { path: 'cheatsheet',        loadComponent: () => import('./components/backend/csharp/cheatsheet/cheatsheet').then(m => m.CsharpCheatsheetComponent) },
      { path: 'errors',            loadComponent: () => import('./components/backend/csharp/errors/errors').then(m => m.CsharpErrorsComponent) },
    ],
  },

  { path: '**', redirectTo: '' },
];
