import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./components/hub-home/hub-home').then(m => m.HubHome) },

  // ── Angular ───────────────────────────────────────────────────────────────
  {
    path: 'angular',
    children: [
      { path: '', loadComponent: () => import('./components/angular/home/home').then(m => m.Home) },
      { path: 'counter',            loadComponent: () => import('./components/angular/counter/counter').then(m => m.Counter) },
      { path: 'todo',               canActivate: [authGuard], loadComponent: () => import('./components/angular/todo/todo').then(m => m.TodoComponent) },
      { path: 'forms',              loadComponent: () => import('./components/angular/forms-demo/forms-demo').then(m => m.FormsDemo) },
      { path: 'http',               loadComponent: () => import('./components/angular/http-demo/http-demo').then(m => m.HttpDemo) },
      { path: 'http-interceptors',  loadComponent: () => import('./components/angular/http-interceptors/http-interceptors').then(m => m.HttpInterceptorsDemo) },
      { path: 'parent-child',       loadComponent: () => import('./components/angular/parent-child/parent-child').then(m => m.ParentChildComponent) },
      { path: 'form-array',         loadComponent: () => import('./components/angular/form-array/form-array').then(m => m.FormArrayDemo) },
      { path: 'defer',              loadComponent: () => import('./components/angular/defer-demo/defer-demo').then(m => m.DeferDemo) },
      { path: 'material',           loadComponent: () => import('./components/angular/material-demo/material-demo').then(m => m.MaterialDemo) },
      { path: 'store',              loadComponent: () => import('./components/angular/signal-store/signal-store').then(m => m.SignalStoreDemo) },
      { path: 'templates',          loadComponent: () => import('./components/angular/template-syntax/template-syntax').then(m => m.TemplateSyntax) },
      { path: 'directives',         loadComponent: () => import('./components/angular/directives-demo/directives-demo').then(m => m.DirectivesDemo) },
      { path: 'lifecycle',          loadComponent: () => import('./components/angular/lifecycle/lifecycle').then(m => m.LifecycleDemo) },
      { path: 'pipes',              loadComponent: () => import('./components/angular/pipes-demo/pipes-demo').then(m => m.PipesDemo) },
      { path: 'di',                 loadComponent: () => import('./components/angular/di-demo/di-demo').then(m => m.DiDemo) },
      { path: 'routing',            loadComponent: () => import('./components/angular/routing-demo/routing-demo').then(m => m.RoutingDemo) },
      { path: 'charts',             loadComponent: () => import('./components/angular/charts/charts').then(m => m.ChartsDemo) },
      { path: 'zod-forms',          loadComponent: () => import('./components/angular/zod-forms/zod-forms').then(m => m.ZodFormsDemo) },
      { path: 'content-projection', loadComponent: () => import('./components/angular/content-projection/content-projection').then(m => m.ContentProjectionDemo) },
      { path: 'change-detection',   loadComponent: () => import('./components/angular/change-detection/change-detection').then(m => m.ChangeDetectionDemo) },
      { path: 'custom-validators',  loadComponent: () => import('./components/angular/custom-validators/custom-validators').then(m => m.CustomValidatorsDemo) },
      { path: 'rxjs',               loadComponent: () => import('./components/angular/rxjs-demo/rxjs-demo').then(m => m.RxjsDemo) },
      { path: 'cdk',                loadComponent: () => import('./components/angular/cdk-demo/cdk-demo').then(m => m.CdkDemo) },
      { path: 'ag-grid',            loadComponent: () => import('./components/angular/ag-grid-demo/ag-grid-demo').then(m => m.AgGridDemo) },
      { path: 'tanstack-query',     loadComponent: () => import('./components/angular/tanstack-query/tanstack-query').then(m => m.TanstackQueryDemo) },
      { path: 'date-fns',           loadComponent: () => import('./components/angular/datefns-demo/datefns-demo').then(m => m.DateFnsDemo) },
      { path: 'animations',         loadComponent: () => import('./components/angular/animations-demo/animations-demo').then(m => m.AnimationsDemo) },
      { path: 'cva',                loadComponent: () => import('./components/angular/cva-demo/cva-demo').then(m => m.CvaDemo) },
      { path: 'testing',            loadComponent: () => import('./components/angular/testing-demo/testing-demo').then(m => m.TestingDemo) },
      { path: 'tailwind',           loadComponent: () => import('./components/angular/tailwind-demo/tailwind-demo').then(m => m.TailwindDemo) },
      { path: 'resource-api',       loadComponent: () => import('./components/angular/resource-api/resource-api').then(m => m.ResourceApiDemo) },
      { path: 'ngrx-signals',       loadComponent: () => import('./components/angular/ngrx-signals/ngrx-signals').then(m => m.NgrxSignalsDemo) },
      { path: 'dynamic-forms',      loadComponent: () => import('./components/angular/dynamic-forms/dynamic-forms').then(m => m.DynamicFormsDemo) },
      { path: 'route-resolvers',    loadComponent: () => import('./components/angular/route-resolvers/route-resolvers').then(m => m.RouteResolversDemo) },
      { path: 'preloading',         loadComponent: () => import('./components/angular/preloading/preloading').then(m => m.PreloadingDemo) },
      { path: 'route-guards',       loadComponent: () => import('./components/angular/route-guards/route-guards').then(m => m.RouteGuardsDemo) },
      { path: 'ng-image',           loadComponent: () => import('./components/angular/ng-image/ng-image').then(m => m.NgImageDemo) },
      { path: 'destroy-ref',        loadComponent: () => import('./components/angular/destroy-ref/destroy-ref').then(m => m.DestroyRefDemo) },
      { path: 'linked-signal',      loadComponent: () => import('./components/angular/linked-signal/linked-signal').then(m => m.LinkedSignalDemo) },
      { path: 'zoneless',           loadComponent: () => import('./components/angular/zoneless/zoneless').then(m => m.ZonelessDemo) },
      { path: 'signal-effects',     loadComponent: () => import('./components/angular/signal-effects/signal-effects').then(m => m.SignalEffectsDemo) },
      { path: 'typed-forms',        loadComponent: () => import('./components/angular/typed-forms/typed-forms').then(m => m.TypedFormsDemo) },
      { path: 'host-directives',    loadComponent: () => import('./components/angular/host-directives/host-directives').then(m => m.HostDirectivesDemo) },
      { path: 'let-template-vars',       loadComponent: () => import('./components/angular/let-template-vars/let-template-vars').then(m => m.LetTemplateVarsDemo) },
      { path: 'standalone-migration',    loadComponent: () => import('./components/angular/standalone-migration/standalone-migration').then(m => m.StandaloneMigrationDemo) },
      { path: 'error-handling-patterns', loadComponent: () => import('./components/angular/error-handling-patterns/error-handling-patterns').then(m => m.ErrorHandlingPatternsDemo) },
      { path: 'msw',                     loadComponent: () => import('./components/angular/msw/msw').then(m => m.MswDemo) },
      { path: 'accessibility',           loadComponent: () => import('./components/angular/accessibility/accessibility').then(m => m.AccessibilityDemo) },
      { path: 'micro-frontends',         loadComponent: () => import('./components/angular/micro-frontends/micro-frontends').then(m => m.MicroFrontendsDemo) },
      { path: 'angular-devtools',        loadComponent: () => import('./components/angular/angular-devtools/angular-devtools').then(m => m.AngularDevtoolsDemo) },
      { path: 'bundle-optimization',     loadComponent: () => import('./components/angular/bundle-optimization/bundle-optimization').then(m => m.BundleOptimizationDemo) },
      { path: 'wizard-form',        loadComponent: () => import('./components/angular/wizard-form/wizard-form').then(m => m.WizardFormDemo) },
      { path: 'web-workers',        loadComponent: () => import('./components/angular/web-workers/web-workers').then(m => m.WebWorkersDemo) },
      { path: 'pwa',                loadComponent: () => import('./components/angular/pwa/pwa').then(m => m.PwaDemo) },
      { path: 'i18n',               loadComponent: () => import('./components/angular/i18n/i18n').then(m => m.I18nDemo) },
      { path: 'e2e',                loadComponent: () => import('./components/angular/e2e/e2e').then(m => m.E2eDemo) },
      { path: 'harnesses',          loadComponent: () => import('./components/angular/harnesses/harnesses').then(m => m.HarnessesDemo) },
      { path: 'ssr',                loadComponent: () => import('./components/angular/ssr/ssr').then(m => m.SsrDemo) },
      { path: 'cheatsheet',         loadComponent: () => import('./components/angular/cheatsheet/cheatsheet').then(m => m.CheatsheetComponent) },
      { path: 'errors',             loadComponent: () => import('./components/angular/errors-page/errors-page').then(m => m.ErrorsPageComponent) },
      { path: 'whats-new',          loadComponent: () => import('./components/angular/whats-new/whats-new').then(m => m.WhatsNewComponent) },
      { path: 'mini-projects',      loadComponent: () => import('./components/angular/mini-projects/mini-projects').then(m => m.MiniProjectsComponent) },
      { path: 'learning-paths',     loadComponent: () => import('./components/angular/learning-paths/learning-paths').then(m => m.LearningPathsComponent) },
      { path: 'interview-prep',     loadComponent: () => import('./components/angular/interview-prep/interview-prep').then(m => m.InterviewPrepComponent) },
      { path: 'quiz-practice',      loadComponent: () => import('./components/angular/quiz-practice/quiz-practice').then(m => m.QuizPracticeComponent) },
      { path: 'design-patterns',    loadComponent: () => import('./components/angular/design-patterns/design-patterns').then(m => m.DesignPatternsComponent) },
      { path: 'decision-guides',    loadComponent: () => import('./components/angular/decision-guides/decision-guides').then(m => m.DecisionGuidesComponent) },
      { path: 'glossary',           loadComponent: () => import('./components/angular/glossary/glossary').then(m => m.GlossaryComponent) },
    ],
  },

  // ── C# ────────────────────────────────────────────────────────────────────
  {
    path: 'csharp',
    children: [
      { path: '',                loadComponent: () => import('./components/backend/csharp/home/home').then(m => m.CsharpHome) },
      { path: 'basics',          loadComponent: () => import('./components/backend/csharp/basics/basics').then(m => m.CsharpBasics) },
      { path: 'oop',             loadComponent: () => import('./components/backend/csharp/oop/oop').then(m => m.CsharpOop) },
      { path: 'records',         loadComponent: () => import('./components/backend/csharp/records/records').then(m => m.CsharpRecords) },
      { path: 'generics',        loadComponent: () => import('./components/backend/csharp/generics/generics').then(m => m.CsharpGenerics) },
      { path: 'collections',     loadComponent: () => import('./components/backend/csharp/collections/collections').then(m => m.CsharpCollections) },
      { path: 'linq',            loadComponent: () => import('./components/backend/csharp/linq/linq').then(m => m.CsharpLinq) },
      { path: 'async',           loadComponent: () => import('./components/backend/csharp/async/async').then(m => m.CsharpAsync) },
      { path: 'null-safety',     loadComponent: () => import('./components/backend/csharp/null-safety/null-safety').then(m => m.CsharpNullSafety) },
      { path: 'pattern-matching',loadComponent: () => import('./components/backend/csharp/pattern-matching/pattern-matching').then(m => m.CsharpPatternMatching) },
      { path: 'exceptions',      loadComponent: () => import('./components/backend/csharp/exceptions/exceptions').then(m => m.CsharpExceptions) },
      { path: 'delegates',         loadComponent: () => import('./components/backend/csharp/delegates/delegates').then(m => m.CsharpDelegates) },
      // ── Fundamentals ──
      { path: 'fields',            loadComponent: () => import('./components/backend/csharp/fields/fields').then(m => m.CsharpFields) },
      { path: 'methods',           loadComponent: () => import('./components/backend/csharp/methods/methods').then(m => m.CsharpMethods) },
      { path: 'type-conversion',   loadComponent: () => import('./components/backend/csharp/type-conversion/type-conversion').then(m => m.CsharpTypeConversion) },
      { path: 'constructors',      loadComponent: () => import('./components/backend/csharp/constructors/constructors').then(m => m.CsharpConstructors) },
      { path: 'properties-indexers', loadComponent: () => import('./components/backend/csharp/properties-indexers/properties-indexers').then(m => m.CsharpPropertiesIndexers) },
      { path: 'namespaces',        loadComponent: () => import('./components/backend/csharp/namespaces/namespaces').then(m => m.CsharpNamespaces) },
      // ── OOP ──
      { path: 'inheritance',       loadComponent: () => import('./components/backend/csharp/inheritance/inheritance').then(m => m.CsharpInheritance) },
      { path: 'abstract-interfaces', loadComponent: () => import('./components/backend/csharp/abstract-interfaces/abstract-interfaces').then(m => m.CsharpAbstractInterfaces) },
      { path: 'static-enums',      loadComponent: () => import('./components/backend/csharp/static-enums/static-enums').then(m => m.CsharpStaticEnums) },
      { path: 'structures',        loadComponent: () => import('./components/backend/csharp/structures/structures').then(m => m.CsharpStructures) },
      { path: 'system-object',     loadComponent: () => import('./components/backend/csharp/system-object/system-object').then(m => m.CsharpSystemObject) },
      // ── Types ──
      { path: 'extension-methods', loadComponent: () => import('./components/backend/csharp/extension-methods/extension-methods').then(m => m.CsharpExtensionMethods) },
      { path: 'tuples',            loadComponent: () => import('./components/backend/csharp/tuples/tuples').then(m => m.CsharpTuples) },
      { path: 'arrays',            loadComponent: () => import('./components/backend/csharp/arrays/arrays').then(m => m.CsharpArrays) },
      { path: 'strings-datetime',  loadComponent: () => import('./components/backend/csharp/strings-datetime/strings-datetime').then(m => m.CsharpStringsDatetime) },
      // ── Data / Memory ──
      { path: 'io-serialization',  loadComponent: () => import('./components/backend/csharp/io-serialization/io-serialization').then(m => m.CsharpIoSerialization) },
      { path: 'gc-disposable',     loadComponent: () => import('./components/backend/csharp/gc-disposable/gc-disposable').then(m => m.CsharpGcDisposable) },
      // ── Concurrency ──
      { path: 'threading',         loadComponent: () => import('./components/backend/csharp/threading/threading').then(m => m.CsharpThreading) },
      { path: 'tasks',             loadComponent: () => import('./components/backend/csharp/tasks/tasks').then(m => m.CsharpTasks) },
      // ── Advanced & Quality ──
      { path: 'reflection',        loadComponent: () => import('./components/backend/csharp/reflection/reflection').then(m => m.CsharpReflection) },
      { path: 'iterators',         loadComponent: () => import('./components/backend/csharp/iterators/iterators').then(m => m.CsharpIterators) },
      { path: 'functional-csharp', loadComponent: () => import('./components/backend/csharp/functional-csharp/functional-csharp').then(m => m.CsharpFunctionalCsharp) },
      { path: 'regex',             loadComponent: () => import('./components/backend/csharp/regex/regex').then(m => m.CsharpRegex) },
      { path: 'channels',          loadComponent: () => import('./components/backend/csharp/channels/channels').then(m => m.CsharpChannels) },
      { path: 'unit-testing',      loadComponent: () => import('./components/backend/csharp/unit-testing/unit-testing').then(m => m.CsharpUnitTesting) },
      { path: 'expression-trees',  loadComponent: () => import('./components/backend/csharp/expression-trees/expression-trees').then(m => m.CsharpExpressionTrees) },
      { path: 'dynamic',           loadComponent: () => import('./components/backend/csharp/dynamic/dynamic').then(m => m.CsharpDynamic) },
      { path: 'source-generators', loadComponent: () => import('./components/backend/csharp/source-generators/source-generators').then(m => m.CsharpSourceGenerators) },
      { path: 'span-memory',      loadComponent: () => import('./components/backend/csharp/span-memory/span-memory').then(m => m.CsharpSpanMemory) },
      { path: 'di-dotnet',        loadComponent: () => import('./components/backend/csharp/di-dotnet/di-dotnet').then(m => m.CsharpDiDotnet) },
      { path: 'json-advanced',    loadComponent: () => import('./components/backend/csharp/json-advanced/json-advanced').then(m => m.CsharpJsonAdvanced) },
      { path: 'unsafe-pointers',  loadComponent: () => import('./components/backend/csharp/unsafe-pointers/unsafe-pointers').then(m => m.CsharpUnsafePointers) },
      { path: 'native-aot',       loadComponent: () => import('./components/backend/csharp/native-aot/native-aot').then(m => m.CsharpNativeAot) },
      { path: 'benchmarkdotnet',  loadComponent: () => import('./components/backend/csharp/benchmarkdotnet/benchmarkdotnet').then(m => m.CsharpBenchmarkdotnet) },
      { path: 'pinvoke',          loadComponent: () => import('./components/backend/csharp/pinvoke/pinvoke').then(m => m.CsharpPinvoke) },
      { path: 'dotnet-cli',       loadComponent: () => import('./components/backend/csharp/dotnet-cli/dotnet-cli').then(m => m.CsharpDotnetCli) },
      // ── What's New ──
      { path: 'whats-new-9-10',    loadComponent: () => import('./components/backend/csharp/whats-new-9-10/whats-new-9-10').then(m => m.CsharpWhatsNew910) },
      { path: 'whats-new-11-12',   loadComponent: () => import('./components/backend/csharp/whats-new-11-12/whats-new-11-12').then(m => m.CsharpWhatsNew1112) },
      { path: 'whats-new-latest',  loadComponent: () => import('./components/backend/csharp/whats-new-latest/whats-new-latest').then(m => m.CsharpWhatsNewLatest) },
      { path: 'cheatsheet',        loadComponent: () => import('./components/backend/csharp/cheatsheet/cheatsheet').then(m => m.CsharpCheatsheetComponent) },
      { path: 'errors',            loadComponent: () => import('./components/backend/csharp/errors/errors').then(m => m.CsharpErrorsComponent) },
      { path: 'mini-projects',     loadComponent: () => import('./components/backend/csharp/mini-projects/mini-projects').then(m => m.CsharpMiniProjects) },
      { path: 'learning-paths',    loadComponent: () => import('./components/backend/csharp/learning-paths/learning-paths').then(m => m.CsharpLearningPaths) },
      { path: 'interview-prep',    loadComponent: () => import('./components/backend/csharp/interview-prep/interview-prep').then(m => m.CsharpInterviewPrep) },
      { path: 'quiz-practice',     loadComponent: () => import('./components/backend/csharp/quiz-practice/quiz-practice').then(m => m.CsharpQuizPractice) },
      { path: 'design-patterns',   loadComponent: () => import('./components/backend/csharp/design-patterns/design-patterns').then(m => m.CsharpDesignPatterns) },
      { path: 'decision-guides',   loadComponent: () => import('./components/backend/csharp/decision-guides/decision-guides').then(m => m.CsharpDecisionGuides) },
      { path: 'glossary',          loadComponent: () => import('./components/backend/csharp/glossary/glossary').then(m => m.CsharpGlossary) },
    ],
  },

  // ── ASP.NET Core ──────────────────────────────────────────────────────────
  {
    path: 'aspnet',
    children: [
      { path: '', loadComponent: () => import('./components/backend/aspnet/home/home').then(m => m.AspnetHome) },
      // ── Fundamentals ──
      { path: 'hosting-startup',      loadComponent: () => import('./components/backend/aspnet/hosting-startup/hosting-startup').then(m => m.AspnetHostingStartup) },
      { path: 'middleware',           loadComponent: () => import('./components/backend/aspnet/middleware/middleware').then(m => m.AspnetMiddleware) },
      { path: 'routing',              loadComponent: () => import('./components/backend/aspnet/routing/routing').then(m => m.AspnetRouting) },
      { path: 'configuration',        loadComponent: () => import('./components/backend/aspnet/configuration/configuration').then(m => m.AspnetConfiguration) },
      { path: 'dependency-injection', loadComponent: () => import('./components/backend/aspnet/dependency-injection/dependency-injection').then(m => m.AspnetDependencyInjection) },
      { path: 'logging',              loadComponent: () => import('./components/backend/aspnet/logging/logging').then(m => m.AspnetLogging) },
      { path: 'static-files',         loadComponent: () => import('./components/backend/aspnet/static-files/static-files').then(m => m.AspnetStaticFiles) },
      // ── Web API ──
      { path: 'controllers',          loadComponent: () => import('./components/backend/aspnet/controllers/controllers').then(m => m.AspnetControllers) },
      { path: 'minimal-apis',         loadComponent: () => import('./components/backend/aspnet/minimal-apis/minimal-apis').then(m => m.AspnetMinimalApis) },
      { path: 'model-binding',        loadComponent: () => import('./components/backend/aspnet/model-binding/model-binding').then(m => m.AspnetModelBinding) },
      { path: 'filters',              loadComponent: () => import('./components/backend/aspnet/filters/filters').then(m => m.AspnetFilters) },
      { path: 'error-handling',       loadComponent: () => import('./components/backend/aspnet/error-handling/error-handling').then(m => m.AspnetErrorHandling) },
      { path: 'openapi-swagger',      loadComponent: () => import('./components/backend/aspnet/openapi-swagger/openapi-swagger').then(m => m.AspnetOpenApiSwagger) },
      { path: 'api-versioning',       loadComponent: () => import('./components/backend/aspnet/api-versioning/api-versioning').then(m => m.AspnetApiVersioning) },
      { path: 'http-clients',         loadComponent: () => import('./components/backend/aspnet/http-clients/http-clients').then(m => m.AspnetHttpClients) },
      { path: 'grpc',                 loadComponent: () => import('./components/backend/aspnet/grpc/grpc').then(m => m.AspnetGrpc) },
      { path: 'ef-core-basics',       loadComponent: () => import('./components/backend/aspnet/ef-core-basics/ef-core-basics').then(m => m.AspnetEfCoreBasics) },
      { path: 'ef-relationships',     loadComponent: () => import('./components/backend/aspnet/ef-relationships/ef-relationships').then(m => m.AspnetEfRelationships) },
      { path: 'ef-performance',       loadComponent: () => import('./components/backend/aspnet/ef-performance/ef-performance').then(m => m.AspnetEfPerformance) },
      { path: 'caching',              loadComponent: () => import('./components/backend/aspnet/caching/caching').then(m => m.AspnetCaching) },
      // ── Security ──
      { path: 'authentication',       loadComponent: () => import('./components/backend/aspnet/authentication/authentication').then(m => m.AspnetAuthentication) },
      { path: 'authorization',        loadComponent: () => import('./components/backend/aspnet/authorization/authorization').then(m => m.AspnetAuthorization) },
      { path: 'cors',                 loadComponent: () => import('./components/backend/aspnet/cors/cors').then(m => m.AspnetCors) },
      { path: 'rate-limiting',        loadComponent: () => import('./components/backend/aspnet/rate-limiting/rate-limiting').then(m => m.AspnetRateLimiting) },
      { path: 'web-security',         loadComponent: () => import('./components/backend/aspnet/web-security/web-security').then(m => m.AspnetWebSecurity) },
      { path: 'secrets',              loadComponent: () => import('./components/backend/aspnet/secrets/secrets').then(m => m.AspnetSecrets) },
      // ── Quality ──
      { path: 'testing',              loadComponent: () => import('./components/backend/aspnet/testing/testing').then(m => m.AspnetTesting) },
      { path: 'background-services',  loadComponent: () => import('./components/backend/aspnet/background-services/background-services').then(m => m.AspnetBackgroundServices) },
      { path: 'signalr',              loadComponent: () => import('./components/backend/aspnet/signalr/signalr').then(m => m.AspnetSignalR) },
      { path: 'health-checks',        loadComponent: () => import('./components/backend/aspnet/health-checks/health-checks').then(m => m.AspnetHealthChecks) },
      { path: 'deployment',           loadComponent: () => import('./components/backend/aspnet/deployment/deployment').then(m => m.AspnetDeployment) },
      { path: 'performance',          loadComponent: () => import('./components/backend/aspnet/performance/performance').then(m => m.AspnetPerformance) },
      { path: 'aspire',                    loadComponent: () => import('./components/backend/aspnet/aspire/aspire').then(m => m.AspnetAspire) },
      { path: 'fluent-validation',         loadComponent: () => import('./components/backend/aspnet/fluent-validation/fluent-validation').then(m => m.AspnetFluentValidation) },
      { path: 'minimal-api-advanced',      loadComponent: () => import('./components/backend/aspnet/minimal-api-advanced/minimal-api-advanced').then(m => m.AspnetMinimalApiAdvanced) },
      { path: 'output-caching-advanced',   loadComponent: () => import('./components/backend/aspnet/output-caching-advanced/output-caching-advanced').then(m => m.AspnetOutputCachingAdvanced) },
      { path: 'dapper',                    loadComponent: () => import('./components/backend/aspnet/dapper/dapper').then(m => m.AspnetDapper) },
      { path: 'csrf',                      loadComponent: () => import('./components/backend/aspnet/csrf/csrf').then(m => m.AspnetCsrf) },
      { path: 'feature-flags',             loadComponent: () => import('./components/backend/aspnet/feature-flags/feature-flags').then(m => m.AspnetFeatureFlags) },
      { path: 'localization',              loadComponent: () => import('./components/backend/aspnet/localization/localization').then(m => m.AspnetLocalization) },
      { path: 'masstransit',               loadComponent: () => import('./components/backend/aspnet/masstransit/masstransit').then(m => m.AspnetMasstransit) },
      { path: 'response-compression',      loadComponent: () => import('./components/backend/aspnet/response-compression/response-compression').then(m => m.AspnetResponseCompression) },
      { path: 'websockets',                loadComponent: () => import('./components/backend/aspnet/websockets/websockets').then(m => m.AspnetWebsockets) },
      { path: 'yarp',                      loadComponent: () => import('./components/backend/aspnet/yarp/yarp').then(m => m.AspnetYarp) },
      { path: 'opentelemetry',             loadComponent: () => import('./components/backend/aspnet/opentelemetry/opentelemetry').then(m => m.AspnetOpentelemetry) },
      { path: 'cheatsheet',           loadComponent: () => import('./components/backend/aspnet/cheatsheet/cheatsheet').then(m => m.AspnetCheatsheet) },
      { path: 'errors',               loadComponent: () => import('./components/backend/aspnet/errors/errors').then(m => m.AspnetErrors) },
      { path: 'quiz-practice',        loadComponent: () => import('./components/backend/aspnet/quiz-practice/quiz-practice').then(m => m.AspnetQuizPractice) },
      { path: 'interview-prep',       loadComponent: () => import('./components/backend/aspnet/interview-prep/interview-prep').then(m => m.AspnetInterviewPrep) },
      { path: 'design-patterns',      loadComponent: () => import('./components/backend/aspnet/design-patterns/design-patterns').then(m => m.AspnetDesignPatterns) },
      { path: 'decision-guides',      loadComponent: () => import('./components/backend/aspnet/decision-guides/decision-guides').then(m => m.AspnetDecisionGuides) },
      { path: 'glossary',             loadComponent: () => import('./components/backend/aspnet/glossary/glossary').then(m => m.AspnetGlossary) },
      { path: 'mini-projects',        loadComponent: () => import('./components/backend/aspnet/mini-projects/mini-projects').then(m => m.AspnetMiniProjects) },
      { path: 'learning-paths',       loadComponent: () => import('./components/backend/aspnet/learning-paths/learning-paths').then(m => m.AspnetLearningPaths) },
    ],
  },

  // ── SQL ───────────────────────────────────────────────────────────────────
  {
    path: 'sql',
    children: [
      { path: '',                  loadComponent: () => import('./components/data/sql/home/home').then(m => m.SqlHome) },
      { path: 'rdbms-concepts',    loadComponent: () => import('./components/data/sql/rdbms-concepts/rdbms-concepts').then(m => m.SqlRdbmsConcepts) },
      { path: 'data-modeling',     loadComponent: () => import('./components/data/sql/data-modeling/data-modeling').then(m => m.SqlDataModeling) },
      { path: 'normalization',     loadComponent: () => import('./components/data/sql/normalization/normalization').then(m => m.SqlNormalization) },
      { path: 'db-architecture',   loadComponent: () => import('./components/data/sql/db-architecture/db-architecture').then(m => m.SqlDbArchitecture) },
      { path: 'data-types',        loadComponent: () => import('./components/data/sql/data-types/data-types').then(m => m.SqlDataTypes) },
      { path: 'basics',            loadComponent: () => import('./components/data/sql/basics/basics').then(m => m.SqlBasics) },
      { path: 'joins',             loadComponent: () => import('./components/data/sql/joins/joins').then(m => m.SqlJoins) },
      { path: 'aggregations',      loadComponent: () => import('./components/data/sql/aggregations/aggregations').then(m => m.SqlAggregations) },
      { path: 'subqueries',        loadComponent: () => import('./components/data/sql/subqueries/subqueries').then(m => m.SqlSubqueries) },
      { path: 'ctes',              loadComponent: () => import('./components/data/sql/ctes/ctes').then(m => m.SqlCtes) },
      { path: 'window-functions',  loadComponent: () => import('./components/data/sql/window-functions/window-functions').then(m => m.SqlWindowFunctions) },
      { path: 'indexes',           loadComponent: () => import('./components/data/sql/indexes/indexes').then(m => m.SqlIndexes) },
      { path: 'transactions',      loadComponent: () => import('./components/data/sql/transactions/transactions').then(m => m.SqlTransactions) },
      { path: 'schema-design',     loadComponent: () => import('./components/data/sql/schema-design/schema-design').then(m => m.SqlSchemaDesign) },
      { path: 'stored-procedures', loadComponent: () => import('./components/data/sql/stored-procedures/stored-procedures').then(m => m.SqlStoredProcedures) },
      { path: 'performance',       loadComponent: () => import('./components/data/sql/performance/performance').then(m => m.SqlPerformance) },
      { path: 'json-features',            loadComponent: () => import('./components/data/sql/json-features/json-features').then(m => m.SqlJsonFeatures) },
      { path: 'set-operations',           loadComponent: () => import('./components/data/sql/set-operations/set-operations').then(m => m.SqlSetOperations) },
      { path: 'null-handling',            loadComponent: () => import('./components/data/sql/null-handling/null-handling').then(m => m.SqlNullHandling) },
      { path: 'merge',                    loadComponent: () => import('./components/data/sql/merge/merge').then(m => m.SqlMerge) },
      { path: 'string-functions',         loadComponent: () => import('./components/data/sql/string-functions/string-functions').then(m => m.SqlStringFunctions) },
      { path: 'date-functions',           loadComponent: () => import('./components/data/sql/date-functions/date-functions').then(m => m.SqlDateFunctions) },
      { path: 'conditional-expressions',  loadComponent: () => import('./components/data/sql/conditional-expressions/conditional-expressions').then(m => m.SqlConditionalExpressions) },
      { path: 'math-functions',           loadComponent: () => import('./components/data/sql/math-functions/math-functions').then(m => m.SqlMathFunctions) },
      { path: 'pivoting',                 loadComponent: () => import('./components/data/sql/pivoting/pivoting').then(m => m.SqlPivoting) },
      { path: 'constraints',             loadComponent: () => import('./components/data/sql/constraints/constraints').then(m => m.SqlConstraints) },
      { path: 'views',                   loadComponent: () => import('./components/data/sql/views/views').then(m => m.SqlViews) },
      { path: 'sequences',               loadComponent: () => import('./components/data/sql/sequences/sequences').then(m => m.SqlSequences) },
      { path: 'temp-tables',             loadComponent: () => import('./components/data/sql/temp-tables/temp-tables').then(m => m.SqlTempTables) },
      { path: 'computed-columns',        loadComponent: () => import('./components/data/sql/computed-columns/computed-columns').then(m => m.SqlComputedColumns) },
      { path: 'stored-functions',        loadComponent: () => import('./components/data/sql/stored-functions/stored-functions').then(m => m.SqlStoredFunctions) },
      { path: 'cursors',                 loadComponent: () => import('./components/data/sql/cursors/cursors').then(m => m.SqlCursors) },
      { path: 'triggers',                loadComponent: () => import('./components/data/sql/triggers/triggers').then(m => m.SqlTriggers) },
      { path: 'dynamic-sql',             loadComponent: () => import('./components/data/sql/dynamic-sql/dynamic-sql').then(m => m.SqlDynamicSql) },
      { path: 'isolation-levels',        loadComponent: () => import('./components/data/sql/isolation-levels/isolation-levels').then(m => m.SqlIsolationLevels) },
      { path: 'locking',                 loadComponent: () => import('./components/data/sql/locking/locking').then(m => m.SqlLocking) },
      { path: 'execution-plans',         loadComponent: () => import('./components/data/sql/execution-plans/execution-plans').then(m => m.SqlExecutionPlans) },
      { path: 'partitioning',            loadComponent: () => import('./components/data/sql/partitioning/partitioning').then(m => m.SqlPartitioning) },
      { path: 'bulk-operations',         loadComponent: () => import('./components/data/sql/bulk-operations/bulk-operations').then(m => m.SqlBulkOperations) },
      { path: 'query-store',             loadComponent: () => import('./components/data/sql/query-store/query-store').then(m => m.SqlQueryStore) },
      { path: 'statistics',              loadComponent: () => import('./components/data/sql/statistics/statistics').then(m => m.SqlStatistics) },
      { path: 'full-text-search',        loadComponent: () => import('./components/data/sql/full-text-search/full-text-search').then(m => m.SqlFullTextSearch) },
      { path: 'security',                loadComponent: () => import('./components/data/sql/security/security').then(m => m.SqlSecurity) },
      { path: 'connection-pooling',      loadComponent: () => import('./components/data/sql/connection-pooling/connection-pooling').then(m => m.SqlConnectionPooling) },
      { path: 'cheatsheet',        loadComponent: () => import('./components/data/sql/cheatsheet/cheatsheet').then(m => m.SqlCheatsheet) },
      { path: 'errors',            loadComponent: () => import('./components/data/sql/errors/errors').then(m => m.SqlErrors) },
      { path: 'quiz-practice',     loadComponent: () => import('./components/data/sql/quiz-practice/quiz-practice').then(m => m.SqlQuizPractice) },
      { path: 'interview-prep',    loadComponent: () => import('./components/data/sql/interview-prep/interview-prep').then(m => m.SqlInterviewPrep) },
      { path: 'design-patterns',   loadComponent: () => import('./components/data/sql/design-patterns/design-patterns').then(m => m.SqlDesignPatterns) },
      { path: 'decision-guides',   loadComponent: () => import('./components/data/sql/decision-guides/decision-guides').then(m => m.SqlDecisionGuides) },
      { path: 'glossary',          loadComponent: () => import('./components/data/sql/glossary/glossary').then(m => m.SqlGlossary) },
      { path: 'mini-projects',     loadComponent: () => import('./components/data/sql/mini-projects/mini-projects').then(m => m.SqlMiniProjects) },
      { path: 'learning-paths',    loadComponent: () => import('./components/data/sql/learning-paths/learning-paths').then(m => m.SqlLearningPaths) },
    ],
  },

  // ── Frontend Hubs ─────────────────────────────────────────────────────────
  { path: 'html', children: [
    { path: '', loadComponent: () => import('./components/frontend/html/home/home').then(m => m.HtmlHome) },
    { path: 'document-structure',  loadComponent: () => import('./components/frontend/html/document-structure/document-structure').then(m => m.HtmlDocumentStructure) },
    { path: 'semantic-elements',   loadComponent: () => import('./components/frontend/html/semantic-elements/semantic-elements').then(m => m.HtmlSemanticElements) },
    { path: 'forms',               loadComponent: () => import('./components/frontend/html/forms/forms').then(m => m.HtmlForms) },
    { path: 'media',               loadComponent: () => import('./components/frontend/html/media/media').then(m => m.HtmlMedia) },
    { path: 'tables',              loadComponent: () => import('./components/frontend/html/tables/tables').then(m => m.HtmlTables) },
    { path: 'links-navigation',    loadComponent: () => import('./components/frontend/html/links-navigation/links-navigation').then(m => m.HtmlLinksNavigation) },
    { path: 'accessibility',       loadComponent: () => import('./components/frontend/html/accessibility/accessibility').then(m => m.HtmlAccessibility) },
    { path: 'head-metadata',       loadComponent: () => import('./components/frontend/html/head-metadata/head-metadata').then(m => m.HtmlHeadMetadata) },
    { path: 'custom-elements',     loadComponent: () => import('./components/frontend/html/custom-elements/custom-elements').then(m => m.HtmlCustomElements) },
    { path: 'iframes-embeds',      loadComponent: () => import('./components/frontend/html/iframes-embeds/iframes-embeds').then(m => m.HtmlIframesEmbeds) },
    { path: 'canvas-svg',          loadComponent: () => import('./components/frontend/html/canvas-svg/canvas-svg').then(m => m.HtmlCanvasSvg) },
    { path: 'performance',         loadComponent: () => import('./components/frontend/html/performance/performance').then(m => m.HtmlPerformance) },
    { path: 'pwa-service-workers', loadComponent: () => import('./components/frontend/html/pwa-service-workers/pwa-service-workers').then(m => m.HtmlPwaServiceWorkers) },
    { path: 'seo',                 loadComponent: () => import('./components/frontend/html/seo/seo').then(m => m.HtmlSeo) },
    { path: 'apis',                loadComponent: () => import('./components/frontend/html/apis/apis').then(m => m.HtmlApis) },
    { path: 'cheatsheet',          loadComponent: () => import('./components/frontend/html/cheatsheet/cheatsheet').then(m => m.HtmlCheatsheet) },
    { path: 'interview-prep',      loadComponent: () => import('./components/frontend/html/interview-prep/interview-prep').then(m => m.HtmlInterviewPrep) },
  ] },
  { path: 'css', children: [
    { path: '',          loadComponent: () => import('./components/frontend/css/home/home').then(m => m.CssHome) },
    { path: 'box-model', loadComponent: () => import('./components/frontend/css/box-model/box-model').then(m => m.CssBoxModel) },
    { path: 'flexbox',   loadComponent: () => import('./components/frontend/css/flexbox/flexbox').then(m => m.CssFlexbox) },
  ] },
  { path: 'javascript', children: [
    { path: '', loadComponent: () => import('./components/frontend/javascript/home/home').then(m => m.JavaScriptHome) },
    { path: 'fundamentals',   loadComponent: () => import('./components/frontend/javascript/fundamentals/fundamentals').then(m => m.JsFundamentals) },
    { path: 'closures',       loadComponent: () => import('./components/frontend/javascript/closures/closures').then(m => m.JsClosures) },
    { path: 'hoisting',       loadComponent: () => import('./components/frontend/javascript/hoisting/hoisting').then(m => m.JsHoisting) },
    { path: 'symbols',        loadComponent: () => import('./components/frontend/javascript/symbols/symbols').then(m => m.JsSymbols) },
    { path: 'functions',      loadComponent: () => import('./components/frontend/javascript/functions/functions').then(m => m.JsFunctions) },
    { path: 'prototypes',     loadComponent: () => import('./components/frontend/javascript/prototypes/prototypes').then(m => m.JsPrototypes) },
    { path: 'objects',        loadComponent: () => import('./components/frontend/javascript/objects/objects').then(m => m.JsObjects) },
    { path: 'destructuring',  loadComponent: () => import('./components/frontend/javascript/destructuring/destructuring').then(m => m.JsDestructuring) },
    { path: 'arrays',         loadComponent: () => import('./components/frontend/javascript/arrays/arrays').then(m => m.JsArrays) },
    { path: 'promises',       loadComponent: () => import('./components/frontend/javascript/promises/promises').then(m => m.JsPromises) },
    { path: 'event-loop',     loadComponent: () => import('./components/frontend/javascript/event-loop/event-loop').then(m => m.JsEventLoop) },
    { path: 'error-handling', loadComponent: () => import('./components/frontend/javascript/error-handling/error-handling').then(m => m.JsErrorHandling) },
    { path: 'generators',     loadComponent: () => import('./components/frontend/javascript/generators/generators').then(m => m.JsGenerators) },
    { path: 'dom',            loadComponent: () => import('./components/frontend/javascript/dom/dom').then(m => m.JsDom) },
    { path: 'events',         loadComponent: () => import('./components/frontend/javascript/events/events').then(m => m.JsEvents) },
    { path: 'browser-apis',   loadComponent: () => import('./components/frontend/javascript/browser-apis/browser-apis').then(m => m.JsBrowserApis) },
    { path: 'modules',        loadComponent: () => import('./components/frontend/javascript/modules/modules').then(m => m.JsModules) },
    { path: 'bundlers',       loadComponent: () => import('./components/frontend/javascript/bundlers/bundlers').then(m => m.JsBundlers) },
    { path: 'patterns',       loadComponent: () => import('./components/frontend/javascript/patterns/patterns').then(m => m.JsPatterns) },
    { path: 'functional',     loadComponent: () => import('./components/frontend/javascript/functional/functional').then(m => m.JsFunctional) },
    { path: 'proxy',          loadComponent: () => import('./components/frontend/javascript/proxy/proxy').then(m => m.JsProxy) },
    { path: 'weakrefs',       loadComponent: () => import('./components/frontend/javascript/weakrefs/weakrefs').then(m => m.JsWeakrefs) },
    { path: 'cheatsheet',     loadComponent: () => import('./components/frontend/javascript/cheatsheet/cheatsheet').then(m => m.JsCheatsheet) },
    { path: 'interview-prep', loadComponent: () => import('./components/frontend/javascript/interview-prep/interview-prep').then(m => m.JsInterviewPrep) },
  ] },
  { path: 'typescript',    children: [
    { path: '', loadComponent: () => import('./components/frontend/typescript/home/home').then(m => m.TypeScriptHome) },
    { path: 'basics',                  loadComponent: () => import('./components/frontend/typescript/basics/basics').then(m => m.TsBasics) },
    { path: 'primitive-types',         loadComponent: () => import('./components/frontend/typescript/primitive-types/primitive-types').then(m => m.TsPrimitiveTypes) },
    { path: 'interfaces-types',        loadComponent: () => import('./components/frontend/typescript/interfaces-types/interfaces-types').then(m => m.TsInterfacesTypes) },
    { path: 'unions',                  loadComponent: () => import('./components/frontend/typescript/unions/unions').then(m => m.TsUnions) },
    { path: 'narrowing',               loadComponent: () => import('./components/frontend/typescript/narrowing/narrowing').then(m => m.TsNarrowing) },
    { path: 'enums-tuples',            loadComponent: () => import('./components/frontend/typescript/enums-tuples/enums-tuples').then(m => m.TsEnumsTuples) },
    { path: 'generics',                loadComponent: () => import('./components/frontend/typescript/generics/generics').then(m => m.TsGenerics) },
    { path: 'generic-patterns',        loadComponent: () => import('./components/frontend/typescript/generic-patterns/generic-patterns').then(m => m.TsGenericPatterns) },
    { path: 'utility-types',           loadComponent: () => import('./components/frontend/typescript/utility-types/utility-types').then(m => m.TsUtilityTypes) },
    { path: 'mapped-types',            loadComponent: () => import('./components/frontend/typescript/mapped-types/mapped-types').then(m => m.TsMappedTypes) },
    { path: 'conditional-types',       loadComponent: () => import('./components/frontend/typescript/conditional-types/conditional-types').then(m => m.TsConditionalTypes) },
    { path: 'template-literal-types',  loadComponent: () => import('./components/frontend/typescript/template-literal-types/template-literal-types').then(m => m.TsTemplateLiteralTypes) },
    { path: 'classes',                 loadComponent: () => import('./components/frontend/typescript/classes/classes').then(m => m.TsClasses) },
    { path: 'decorators',              loadComponent: () => import('./components/frontend/typescript/decorators/decorators').then(m => m.TsDecorators) },
    { path: 'tsconfig',                loadComponent: () => import('./components/frontend/typescript/tsconfig/tsconfig').then(m => m.TsTsconfig) },
    { path: 'modules',                 loadComponent: () => import('./components/frontend/typescript/modules/modules').then(m => m.TsModules) },
    { path: 'declarations',            loadComponent: () => import('./components/frontend/typescript/declarations/declarations').then(m => m.TsDeclarations) },
    { path: 'frameworks',              loadComponent: () => import('./components/frontend/typescript/frameworks/frameworks').then(m => m.TsFrameworks) },
    { path: 'strict-migration',        loadComponent: () => import('./components/frontend/typescript/strict-migration/strict-migration').then(m => m.TsStrictMigration) },
    { path: 'ts-performance',          loadComponent: () => import('./components/frontend/typescript/ts-performance/ts-performance').then(m => m.TsPerformance) },
    { path: 'cheatsheet',              loadComponent: () => import('./components/frontend/typescript/cheatsheet/cheatsheet').then(m => m.TsCheatsheet) },
    { path: 'interview-prep',          loadComponent: () => import('./components/frontend/typescript/interview-prep/interview-prep').then(m => m.TsInterviewPrep) },
  ] },
  { path: 'react', children: [
    { path: '', loadComponent: () => import('./components/frontend/react/home/home').then(m => m.ReactHome) },
    { path: 'basics',       loadComponent: () => import('./components/frontend/react/basics/basics').then(m => m.ReactBasics) },
    { path: 'hooks-core',     loadComponent: () => import('./components/frontend/react/hooks-core/hooks-core').then(m => m.ReactHooksCore) },
    { path: 'hooks-advanced', loadComponent: () => import('./components/frontend/react/hooks-advanced/hooks-advanced').then(m => m.ReactHooksAdvanced) },
    { path: 'forms',          loadComponent: () => import('./components/frontend/react/forms/forms').then(m => m.ReactForms) },
    { path: 'context',          loadComponent: () => import('./components/frontend/react/context/context').then(m => m.ReactContext) },
    { path: 'state-management', loadComponent: () => import('./components/frontend/react/state-management/state-management').then(m => m.ReactStateManagement) },
    { path: 'router',           loadComponent: () => import('./components/frontend/react/router/router').then(m => m.ReactRouter) },
    { path: 'tanstack-query',   loadComponent: () => import('./components/frontend/react/tanstack-query/tanstack-query').then(m => m.ReactTanstackQuery) },
    { path: 'performance',      loadComponent: () => import('./components/frontend/react/performance/performance').then(m => m.ReactPerformance) },
    { path: 'patterns',         loadComponent: () => import('./components/frontend/react/patterns/patterns').then(m => m.ReactPatterns) },
    { path: 'typescript',       loadComponent: () => import('./components/frontend/react/typescript/typescript').then(m => m.ReactTypescript) },
    { path: 'testing',          loadComponent: () => import('./components/frontend/react/testing/testing').then(m => m.ReactTesting) },
    { path: 'nextjs',           loadComponent: () => import('./components/frontend/react/nextjs/nextjs').then(m => m.ReactNextjs) },
    { path: 'native',           loadComponent: () => import('./components/frontend/react/native/native').then(m => m.ReactNative) },
    { path: 'hook-form',        loadComponent: () => import('./components/frontend/react/hook-form/hook-form').then(m => m.ReactHookForm) },
    { path: 'animations',       loadComponent: () => import('./components/frontend/react/animations/animations').then(m => m.ReactAnimations) },
    { path: 'security',         loadComponent: () => import('./components/frontend/react/security/security').then(m => m.ReactSecurity) },
    { path: 'cheatsheet',       loadComponent: () => import('./components/frontend/react/cheatsheet/cheatsheet').then(m => m.ReactCheatsheet) },
    { path: 'interview-prep',   loadComponent: () => import('./components/frontend/react/interview-prep/interview-prep').then(m => m.ReactInterviewPrep) },
  ] },
  { path: 'blazor',        children: [{ path: '', loadComponent: () => import('./components/frontend/blazor/home/home').then(m => m.BlazorHome) }] },
  { path: 'performance',   children: [{ path: '', loadComponent: () => import('./components/frontend/web-performance/home/home').then(m => m.WebPerformanceHome) }] },
  // ── Backend Hubs ──────────────────────────────────────────────────────────
  { path: 'node',          children: [{ path: '', loadComponent: () => import('./components/backend/nodejs/home/home').then(m => m.NodejsHome) }] },
  { path: 'python',        children: [{ path: '', loadComponent: () => import('./components/backend/python/home/home').then(m => m.PythonHome) }] },
  { path: 'go',            children: [{ path: '', loadComponent: () => import('./components/backend/go/home/home').then(m => m.GoHome) }] },
  // ── Data Hubs ─────────────────────────────────────────────────────────────
  { path: 'mongodb',       children: [{ path: '', loadComponent: () => import('./components/data/mongodb/home/home').then(m => m.MongodbHome) }] },
  { path: 'redis',         children: [{ path: '', loadComponent: () => import('./components/data/redis/home/home').then(m => m.RedisHome) }] },
  { path: 'graphql',       children: [{ path: '', loadComponent: () => import('./components/data/graphql/home/home').then(m => m.GraphqlHome) }] },
  { path: 'messaging',     children: [{ path: '', loadComponent: () => import('./components/data/messaging/home/home').then(m => m.MessagingHome) }] },
  // ── Architecture Hubs ─────────────────────────────────────────────────────
  { path: 'design-patterns', children: [{ path: '', loadComponent: () => import('./components/architecture/design-patterns/home/home').then(m => m.DesignPatternsHome) }] },
  { path: 'arch-patterns',   children: [{ path: '', loadComponent: () => import('./components/architecture/arch-patterns/home/home').then(m => m.ArchPatternsHome) }] },
  { path: 'api-design',      children: [{ path: '', loadComponent: () => import('./components/architecture/api-design/home/home').then(m => m.ApiDesignHome) }] },
  { path: 'system-design',   children: [{ path: '', loadComponent: () => import('./components/architecture/system-design/home/home').then(m => m.SystemDesignHome) }] },
  { path: 'security',        children: [{ path: '', loadComponent: () => import('./components/architecture/security/home/home').then(m => m.SecurityHome) }] },
  { path: 'observability',   children: [{ path: '', loadComponent: () => import('./components/architecture/observability/home/home').then(m => m.ObservabilityHome) }] },
  // ── Cloud Hubs ────────────────────────────────────────────────────────────
  { path: 'devops',        children: [{ path: '', loadComponent: () => import('./components/cloud/devops/home/home').then(m => m.DevopsHome) }] },
  { path: 'linux',         children: [{ path: '', loadComponent: () => import('./components/cloud/linux/home/home').then(m => m.LinuxHome) }] },
  { path: 'containers',    children: [{ path: '', loadComponent: () => import('./components/cloud/containers/home/home').then(m => m.ContainersHome) }] },
  { path: 'terraform',     children: [{ path: '', loadComponent: () => import('./components/cloud/terraform/home/home').then(m => m.TerraformHome) }] },
  { path: 'azure',         children: [{ path: '', loadComponent: () => import('./components/cloud/azure/home/home').then(m => m.AzureHome) }] },
  { path: 'aws',           children: [{ path: '', loadComponent: () => import('./components/cloud/aws/home/home').then(m => m.AwsHome) }] },
  { path: 'service-mesh',  children: [{ path: '', loadComponent: () => import('./components/cloud/service-mesh/home/home').then(m => m.ServiceMeshHome) }] },
  // ── Fundamentals & AI Hubs ────────────────────────────────────────────────
  { path: 'dsa',           children: [{ path: '', loadComponent: () => import('./components/fundamentals/dsa/home/home').then(m => m.DsaHome) }] },
  { path: 'testing-hub',   children: [{ path: '', loadComponent: () => import('./components/fundamentals/testing/home/home').then(m => m.TestingHome) }] },
  { path: 'ai',            children: [{ path: '', loadComponent: () => import('./components/fundamentals/ai/home/home').then(m => m.AiHome) }] },

  { path: '**', redirectTo: '' },
];
