import { Component, signal, computed } from '@angular/core';
import { RouterLink } from '@angular/router';

interface Topic { title: string; route: string; badge: string; description: string; keyPoints: string[]; available: boolean; }

const BADGE_CSS: Record<string, string> = {
  'Docker': 'docker', 'Dockerfile': 'dockerfile', 'Compose': 'compose',
  'Kubernetes': 'kubernetes', 'Workloads': 'workloads', 'Networking': 'networking',
  'Storage': 'storage', 'Reference': 'reference',
};
const GROUP_ORDER = ['All', 'Docker', 'Dockerfile', 'Compose', 'Kubernetes', 'Workloads', 'Networking', 'Storage', 'Reference'];

const ALL_TOPICS: Topic[] = [
  { title: 'Container Fundamentals', route: '/containers/fundamentals', badge: 'Docker', description: 'What containers are — namespaces, cgroups, OCI images, and how Docker differs from VMs.', keyPoints: ['Namespaces (pid, net, mnt, uts)', 'cgroups resource limits', 'OCI image spec', 'Container vs VM trade-offs', 'Docker Engine architecture'], available: true },
  { title: 'Docker CLI', route: '/containers/docker-cli', badge: 'Docker', description: 'docker run, pull, ps, logs, exec, stop, rm — the essential Docker command-line workflow.', keyPoints: ['docker run -d -p flags', 'docker ps -a all containers', 'docker logs -f follow', 'docker exec -it shell', 'docker stop/rm cleanup'], available: true },
  { title: 'Docker Images & Registry', route: '/containers/docker-images', badge: 'Docker', description: 'Pull and push images, tagging strategy, Docker Hub, GHCR, and private registries.', keyPoints: ['docker pull / push', 'Image tagging conventions', 'Docker Hub vs GHCR', 'docker image prune', 'Image signing (Cosign)'], available: true },
  { title: 'Writing Dockerfiles', route: '/containers/dockerfile', badge: 'Dockerfile', description: 'Dockerfile instructions — FROM, RUN, COPY, ADD, ENV, EXPOSE, CMD, ENTRYPOINT, and HEALTHCHECK.', keyPoints: ['FROM base image choice', 'RUN layer caching', 'COPY vs ADD', 'CMD vs ENTRYPOINT', 'HEALTHCHECK instruction'], available: true },
  { title: 'Multi-Stage Builds', route: '/containers/multi-stage', badge: 'Dockerfile', description: 'Use multiple FROM stages to separate build and runtime layers for lean, secure production images.', keyPoints: ['Build stage: compile/test', 'Runtime stage: minimal base', 'COPY --from=builder', 'Alpine vs distroless', 'Image size reduction'], available: true },
  { title: 'Docker Compose', route: '/containers/compose', badge: 'Compose', description: 'Define multi-container applications with compose.yml — services, volumes, networks, and depends_on.', keyPoints: ['compose.yml v3 syntax', 'services, volumes, networks', 'depends_on with condition', 'Environment variables', 'docker compose up -d'], available: true },
  { title: 'Compose Profiles & Overrides', route: '/containers/compose-profiles', badge: 'Compose', description: 'Use profiles for optional services and override files for dev/prod environment differences.', keyPoints: ['profiles: [dev] selective start', 'docker-compose.override.yml', 'Merging compose files', 'COMPOSE_FILE env var', 'Production vs dev DB services'], available: true },
  { title: 'Kubernetes Architecture', route: '/containers/k8s-architecture', badge: 'Kubernetes', description: 'Control plane, worker nodes, etcd, kube-apiserver, kubelet, and the reconciliation loop.', keyPoints: ['Control plane components', 'Worker node components', 'etcd as state store', 'Reconciliation controller loop', 'kubectl → API server'], available: true },
  { title: 'kubectl Fundamentals', route: '/containers/kubectl', badge: 'Kubernetes', description: 'kubectl get, describe, apply, delete, exec, logs, port-forward — the daily Kubernetes toolkit.', keyPoints: ['kubectl apply -f manifests', 'kubectl get pods -o wide', 'kubectl describe for events', 'kubectl exec -it shell', 'kubectl port-forward'], available: true },
  { title: 'Pods, Deployments & ReplicaSets', route: '/containers/pods-deployments', badge: 'Workloads', description: 'Pod lifecycle, Deployment rollout strategies, ReplicaSet management, and rolling updates.', keyPoints: ['Pod as smallest unit', 'Deployment manages ReplicaSets', 'Rolling update strategy', 'kubectl rollout undo', 'maxSurge and maxUnavailable'], available: true },
  { title: 'Services & Ingress', route: '/containers/services-ingress', badge: 'Networking', description: 'ClusterIP, NodePort, LoadBalancer services and Ingress rules for HTTP routing.', keyPoints: ['ClusterIP: internal only', 'NodePort: direct node access', 'LoadBalancer: cloud LB', 'Ingress controller (NGINX)', 'TLS termination at Ingress'], available: true },
  { title: 'ConfigMaps & Secrets', route: '/containers/configmaps-secrets', badge: 'Workloads', description: 'Decouple configuration from images — ConfigMaps for plain data, Secrets for sensitive values.', keyPoints: ['ConfigMap as env vars', 'ConfigMap as mounted files', 'Secrets base64 encoded', 'External Secrets Operator', 'Sealed Secrets for GitOps'], available: true },
  { title: 'Persistent Volumes & Storage', route: '/containers/storage', badge: 'Storage', description: 'PV, PVC, StorageClass, and StatefulSets for running stateful workloads in Kubernetes.', keyPoints: ['PersistentVolume claim binding', 'StorageClass dynamic provisioning', 'RWO vs RWX access modes', 'StatefulSet stable storage', 'volumeClaimTemplates'], available: true },
  { title: 'Kubernetes Operators & CRDs', route: '/containers/operators-crds', badge: 'Kubernetes', available: true,
    description: 'Extend Kubernetes with Custom Resources — Operator pattern, reconciliation loop, kubebuilder, and Operator SDK.',
    keyPoints: ['CRD: extend Kubernetes API with your own resource types (spec/status)', 'Operator pattern: controller watches CRD events and reconciles desired state', 'kubebuilder: scaffold controllers with controller-gen for RBAC markers', 'Reconciliation loop: Get current → diff desired → act → requeue on error', 'Finalizers: prevent deletion until cleanup logic completes'] },
  { title: 'Helm', route: '/containers/helm', badge: 'Reference', description: 'Package, version, and deploy Kubernetes applications with Helm charts — templating and values.', keyPoints: ['Chart structure (templates/values)', 'helm install / upgrade / rollback', 'values.yaml overrides', 'Chart dependencies', 'helm repo add/update'], available: true },
  { title: 'Container Security', route: '/containers/container-security', badge: 'Reference', description: 'Run as non-root, read-only root fs, security contexts, network policies, and image scanning.', keyPoints: ['runAsNonRoot: true', 'readOnlyRootFilesystem', 'securityContext capabilities', 'NetworkPolicy ingress/egress', 'Trivy image scanning'], available: true },
  { title: 'Kubernetes RBAC', route: '/containers/rbac', badge: 'Reference', description: 'Roles, ClusterRoles, RoleBindings, ServiceAccounts, and least-privilege access in Kubernetes.', keyPoints: ['Role vs ClusterRole scope', 'RoleBinding vs ClusterRoleBinding', 'ServiceAccount per workload', 'IRSA (AWS) / Workload Identity (GCP)', 'Audit logs for RBAC'], available: false },
  { title: 'StatefulSets & DaemonSets', route: '/containers/statefulsets', badge: 'Workloads', description: 'Stateful workloads with stable identities, and DaemonSets for running one pod per node.', keyPoints: ['StatefulSet: ordered, stable pod names (pod-0, pod-1)', 'Headless service for DNS-based peer discovery', 'DaemonSet: runs on every node — log agents, monitoring', 'Pod disruption budget for safe upgrades', 'Init containers for startup sequencing'], available: false },
  { title: 'Resource Requests & Limits', route: '/containers/resource-limits', badge: 'Workloads', description: 'CPU/memory requests and limits, LimitRange, ResourceQuota, and Quality of Service classes.', keyPoints: ['requests: scheduler reservation; limits: hard cap', 'QoS: Guaranteed (req=limit), Burstable, BestEffort', 'LimitRange sets defaults per namespace', 'ResourceQuota caps total namespace usage', 'OOMKilled: limit memory; CPU throttle never kills'], available: false },
  { title: 'Horizontal Pod Autoscaler', route: '/containers/hpa', badge: 'Workloads', description: 'HPA scales replicas based on CPU/memory or custom metrics; VPA adjusts requests; KEDA for events.', keyPoints: ['HPA targetCPUUtilizationPercentage', 'Custom metrics via Metrics Adapter', 'VPA: VerticalPodAutoscaler adjusts requests/limits', 'KEDA: event-driven scaling (queue length, etc.)', 'Cooldown and stabilisation windows'], available: false },
  { title: 'Network Policies', route: '/containers/network-policies', badge: 'Networking', description: 'Restrict pod-to-pod traffic with NetworkPolicy — namespace isolation, ingress/egress rules, and CNI support.', keyPoints: ['Default: all pods can talk to all pods', 'deny-all baseline + allow-list per service', 'podSelector + namespaceSelector for targeting', 'Requires CNI support (Calico, Cilium)', 'ipBlock for external IP ranges'], available: false },
  { title: 'Kubernetes Troubleshooting', route: '/containers/troubleshooting', badge: 'Reference', description: 'Diagnose common K8s issues — CrashLoopBackOff, ImagePullBackOff, Pending pods, and OOMKilled.', keyPoints: ['kubectl describe pod: events section shows root cause', 'CrashLoopBackOff: app exits non-zero — check kubectl logs', 'Pending: resource pressure or taints/tolerations', 'kubectl get events --sort-by=.lastTimestamp', 'k9s: interactive cluster dashboard'], available: false },
  { title: 'Containers Cheat Sheet', route: '/containers/cheatsheet', badge: 'Reference', description: 'Docker and kubectl command quick reference — run, build, push, apply, get, describe, and logs.', keyPoints: ['docker build -t name:tag . && docker push', 'kubectl apply -f ./manifests && kubectl rollout status', 'kubectl get pods -n ns -o wide; kubectl exec -it pod -- sh'], available: false },
];

@Component({ selector: 'app-containers-home', standalone: true, imports: [RouterLink], templateUrl: './home.html', styleUrl: './home.scss' })
export class ContainersHome {
  activeFilter = signal('All');
  expandedCard = signal<string | null>(null);
  topics = computed(() => { const f = this.activeFilter(); return f === 'All' ? ALL_TOPICS : ALL_TOPICS.filter(t => t.badge === f); });
  filters = GROUP_ORDER;
  counts = computed(() => { const map: Record<string, number> = { All: ALL_TOPICS.length }; for (const t of ALL_TOPICS) map[t.badge] = (map[t.badge] ?? 0) + 1; return map; });
  availableCount = ALL_TOPICS.filter(t => t.available).length;
  totalCount = ALL_TOPICS.length;
  setFilter(f: string) { this.activeFilter.set(f); }
  badgeCss(badge: string) { return 'badge badge-' + (BADGE_CSS[badge] ?? 'docker'); }
  toggleCard(key: string, event: Event) { event.preventDefault(); this.expandedCard.update(c => c === key ? null : key); }
}
