import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  standalone: true,
  imports: [PageMetaComponent, TheoryBlockComponent, CodeBlockComponent, TryItComponent, MisconceptionsComponent, SubtopicNavComponent, SubtopicEyebrowComponent],
  templateUrl: './external-id-is-not-actually-a-secret-per-aws-own-docs.html',
  styleUrl: './external-id-is-not-actually-a-secret-per-aws-own-docs.scss'
})
export class ExternalIdIsNotActuallyASecretPerAwsOwnDocsSubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'The main page originally described External ID as a "shared secret" — this batch corrected that',
      points: [
        'The main page\'s own quiz originally described External ID as something that "prevents confused-deputy attacks by requiring a shared secret," with an explanation calling it "a shared secret both parties agree on." As part of verifying this content batch, that framing was checked against AWS\'s own documentation and found to be imprecise — the theory bullets, quick-ref entry, and quiz have all been corrected as part of this batch.',
        'This matters because "secret" implies a specific security model — confidentiality, restricted visibility, something that would be rotated if exposed. External ID does not follow that model at all, and treating it as if it did leads to real, avoidable mistakes.',
      ]
    },
    {
      heading: 'AWS states explicitly that External ID is NOT treated as a secret — its protection model is different',
      points: [
        'Per AWS\'s own documentation: "AWS does not treat the external ID as a secret. After you create a secret like an access key pair or a password in AWS, you cannot view them again. The external ID for a role can be seen by anyone with permission to view the role." This is a direct, explicit statement — not an inference.',
        'The real protection External ID provides comes from two separate properties, neither of which is confidentiality: it must be UNGUESSABLE (AWS\'s own guidance: "do not use something that can be guessed, like the name or phone number of the third party"), and for a vendor serving multiple customers, it must be UNIQUE PER CUSTOMER and generated BY THE VENDOR, not the customer — AWS states this last point is "crucial... to ensure each external ID is unique."',
        'AWS\'s own documentation also gives vendors a concrete verification practice that only makes sense once External ID is understood as non-secret: "test whether you can assume the role both with and without the correct external ID. If you can assume the role without the correct external ID, don\'t store the customer\'s role ARN in your system" — this is a functional integration test, not a secret-rotation or leak-response procedure.',
      ]
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'Confirming External ID is visible, not hidden, in the role itself',
      language: 'bash',
      code: `# Matching the main page's own cross-account role setup:
aws iam create-role \\
  --role-name CrossAccountReadRole \\
  --assume-role-policy-document file://trust-policy.json

# Anyone with permission to VIEW the role -- not just the two
# parties who originally agreed on the ExternalId -- can read it
# directly out of the trust policy:
aws iam get-role --role-name CrossAccountReadRole \\
  --query 'Role.AssumeRolePolicyDocument'
# {
#   "Version": "2012-10-17",
#   "Statement": [{
#     "Effect": "Allow",
#     "Principal": { "AWS": "arn:aws:iam::123456789012:root" },
#     "Action": "sts:AssumeRole",
#     "Condition": {
#       "StringEquals": { "sts:ExternalId": "my-secret-external-id" }
#     }
#   }]
# }
# -- the ExternalId value ("my-secret-external-id") is right there
# in plain text -- exactly as AWS's own documentation states: "The
# external ID for a role can be seen by anyone with permission to
# view the role." Contrast this with a real secret, like an IAM
# access key's own secret component, which AWS never lets you
# retrieve again after initial creation -- ExternalId has no such
# protection at all, by design.`,
    },
    {
      label: 'A vendor\'s own correct, per-customer External ID pattern',
      language: 'bash',
      code: `# AWS's own documented example scenario: a monitoring vendor
# (Example Corp) serving MANY customers -- each customer must get
# a DIFFERENT, vendor-generated ExternalId, not a shared one:

# Customer A's trust policy (ExternalId generated by the vendor):
aws iam create-role --role-name VendorMonitoringRole \\
  --assume-role-policy-document '{
    "Version": "2012-10-17",
    "Statement": [{
      "Effect": "Allow",
      "Principal": { "AWS": "arn:aws:iam::VENDOR_ACCOUNT_ID:root" },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": { "sts:ExternalId": "vendor-customer-a1b2c3" }
      }
    }]
  }'

# The vendor's own integration test, following AWS's own documented
# best practice -- confirm the role CANNOT be assumed without the
# correct, customer-specific ExternalId before ever storing this
# customer's role ARN:
aws sts assume-role \\
  --role-arn arn:aws:iam::CUSTOMER_A_ACCOUNT:role/VendorMonitoringRole \\
  --role-session-name integration-test
# (no --external-id passed)
# An error occurred (AccessDenied) when calling the AssumeRole
# operation -- correctly rejected, confirming the trust policy's
# ExternalId condition is actually enforced, not accidentally
# missing or misconfigured.

aws sts assume-role \\
  --role-arn arn:aws:iam::CUSTOMER_A_ACCOUNT:role/VendorMonitoringRole \\
  --role-session-name integration-test \\
  --external-id vendor-customer-a1b2c3
# succeeds -- the role ARN is now safe to store, per AWS's own
# documented vendor integration guidance.`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'A junior engineer at a monitoring SaaS vendor proposes storing every customer\'s ExternalId encrypted at rest in the vendor\'s own secrets manager, "since it\'s a secret shared with each customer," following the framing this hub\'s own main page originally used. A senior engineer pushes back, saying this doesn\'t reflect how AWS actually designed the mechanism. Using this subtopic\'s theory, explain the senior engineer\'s reasoning, and what actually matters about how a vendor manages these values instead.',
    hint: 'AWS explicitly states External ID is visible to anyone with permission to view the role — does encrypting it in the vendor\'s own secrets manager address the actual thing AWS designed this mechanism to protect against?',
    solution: 'Per this subtopic\'s theory, the senior engineer is correct — AWS explicitly states External ID is not treated as a secret, and it is visible to anyone with permission to view the role in the CUSTOMER\'s own AWS account regardless of how carefully the vendor protects their own copy of it. Encrypting it in the vendor\'s secrets manager doesn\'t address the actual threat model External ID was designed for (the confused-deputy problem — preventing the vendor\'s own role-assumption logic from being tricked into acting on behalf of the wrong customer) since the value was never meant to be confidential in the first place; a customer or an attacker who can view the role\'s own trust policy already has full visibility into ExternalId with no need to compromise the vendor\'s systems at all. What actually matters, per this subtopic\'s theory, is that the vendor generates a genuinely unique, unguessable value per customer (not reused across customers, and not something the customer supplies themselves) and consistently supplies the CORRECT customer-specific value on every AssumeRole call — a functional-correctness and uniqueness concern, not a confidentiality one. The engineering effort is better spent on AWS\'s own recommended verification practice — testing that each customer\'s role genuinely rejects assumption without the correct ExternalId before ever storing that customer\'s role ARN — than on secrets-management infrastructure for a value AWS itself says isn\'t a secret.'
  };

  misconceptions: Misconception[] = [
    {
      thought: 'External ID functions like a password or API secret — it should be kept confidential, and its security value comes from not being exposed to unauthorized parties.',
      reality: 'Per this subtopic\'s theory, AWS explicitly states External ID is NOT treated as a secret — it is visible to anyone with permission to view the role in the target account, the same as any other trust policy condition value; there is no confidentiality protection around it at all.'
    },
    {
      thought: 'Since External ID isn\'t confidential, it doesn\'t provide any real security benefit and is essentially a formality.',
      reality: 'Per this subtopic\'s theory, External ID\'s real protection comes from being unguessable and vendor-generated (unique per customer) — this genuinely prevents the confused-deputy attack it was designed for, just through a different mechanism than secrecy.'
    },
    {
      thought: 'A vendor serving multiple customers can safely reuse the same ExternalId value across all of them, as long as that value itself is kept reasonably private.',
      reality: 'Per this subtopic\'s theory, AWS\'s own documentation states it is "crucial" that the external ID be generated by the vendor and be unique per customer — reusing the same value across customers defeats its confused-deputy protection regardless of how privately that shared value is otherwise handled.'
    }
  ];
}
