import { Component } from '@angular/core';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent, SubtopicLink } from '../../../../../shared/subtopic-nav/subtopic-nav';

@Component({
  selector: 'app-gql-performance-field-suggestion-blocking',
  standalone: true,
  imports: [SubtopicEyebrowComponent, PageMetaComponent, TheoryBlockComponent, CodeBlockComponent,
    TryItComponent, MisconceptionsComponent, SubtopicNavComponent],
  templateUrl: './field-suggestion-blocking-mechanism.html',
  styleUrl: './field-suggestion-blocking-mechanism.scss'
})
export class FieldSuggestionBlockingMechanismSubtopic {
  topicLabel = 'Performance & Security';
  topicRoute = '/graphql/performance';

  theory: TheoryPoint[] = [
    {
      heading: 'The suggestion is generated by validation itself, before introspection is even relevant',
      points: [
        'Verified directly by running graphql-js\'s own validation against a guessed, near-miss field name: <code>Cannot query field "secretAdinField" on type "Query". Did you mean "secretAdminField"?</code> -- the real field name leaks in a plain 400-level VALIDATION error, not a successful introspection query.',
        'This means disabling introspection entirely (the main page\'s own separate mistake block) does nothing to stop it -- suggestions come from the standard validation phase every GraphQL request goes through, introspection or not.',
        'An attacker with zero schema knowledge can iteratively guess field names close to what they expect (<code>admin</code>, <code>secret</code>, <code>internal</code>-prefixed variants) and let each rejected guess\'s own suggestion text reveal the real name, one field at a time.'
      ]
    },
    {
      heading: 'The real fix (graphql-armor) strips the suggestion text from the error message after validation runs',
      points: [
        'Verified directly against graphql-armor\'s own <code>block-field-suggestions</code> plugin source: the core logic is one line, <code>error.message.replace(/Did you mean ".+"\\?/g, mask).trim()</code>, applied in an <code>onValidate</code> hook after graphql-js has already computed the suggestion.',
        'This does NOT stop graphql-js from computing the suggestion in the first place -- there is no built-in graphql-js option to disable suggestion generation itself; the fix is a post-processing step that rewrites the error message before it reaches the client.',
        'The main page\'s own QnA calls this "a custom validation rule or server option" -- more precisely, it is neither: it is an error-FORMATTING step, applied after validation completes, not a rule that changes what validation itself accepts or rejects.'
      ]
    }
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'The leak, reproduced directly',
      language: 'typescript',
      code: `import { parse, validate, buildSchema, specifiedRules } from 'graphql';

const schema = buildSchema(\`
  type Query {
    publicPost: String
    secretAdminField: String
  }
\`);

// An attacker guesses a plausible near-miss -- no introspection query
// involved at all, just an ordinary (invalid) operation.
const guess = parse('{ secretAdinField }');
const errors = validate(schema, guess, specifiedRules);

console.log(errors.map(e => e.message));
// [ 'Cannot query field "secretAdinField" on type "Query".
//    Did you mean "secretAdminField"?' ]
//
// The real field name -- which the attacker never typed correctly --
// is now fully known, from a single rejected guess.`
    },
    {
      label: 'The fix: post-processing the error message',
      language: 'typescript',
      code: `// The actual mechanism graphql-armor's block-field-suggestions
// plugin uses -- confirmed directly from its own source.
function stripFieldSuggestions(message: string, mask = '[Suggestion hidden]'): string {
  return message.replace(/Did you mean ".+"\\?/g, mask).trim();
}

const rawMessage = 'Cannot query field "secretAdinField" on type "Query". Did you mean "secretAdminField"?';
console.log(stripFieldSuggestions(rawMessage));
// 'Cannot query field "secretAdinField" on type "Query". [Suggestion hidden]'

// Wired into Apollo Server's formatError, applied to EVERY error
// leaving the server, not just field-suggestion ones:
const server = new ApolloServer({
  typeDefs,
  resolvers,
  formatError: (formattedError) => ({
    ...formattedError,
    message: stripFieldSuggestions(formattedError.message)
  })
});
// graphql-js still COMPUTES the suggestion internally during
// validation -- this step only prevents it from ever reaching
// the client in the response body.`
    }
  ];

  exercise: TryItExercise = {
    prompt: 'A team disables introspection in production (the main page\'s own separate mistake-block fix) but does NOT add field-suggestion stripping. Can an attacker still discover the name <code>secretAdminField</code> exists on the schema, and if so, how?',
    hint: 'Does the "Did you mean" suggestion come from an introspection query, or from the ordinary validation phase every request -- including a deliberately wrong one -- goes through?',
    solution: 'Yes -- disabling introspection blocks the __schema/__type meta-queries specifically, but it has no effect on validation, and the suggestion is generated during validation, not introspection. An attacker sends an ordinary (intentionally wrong) query guessing a near-miss field name, like { secretAdinField }, and the resulting validation error\'s own "Did you mean" text reveals the real field name -- exactly as demonstrated above -- with introspection fully disabled the entire time. Closing this gap needs the SEPARATE fix of stripping suggestion text from outgoing error messages, on top of (not instead of) disabling introspection.'
  };

  misconceptions: Misconception[] = [
    {
      thought: 'Disabling introspection in production, by itself, closes the field-suggestion information leak too, since both are about hiding schema details.',
      reality: 'They are two independent leak paths guarded by two independent fixes. Introspection is a deliberate meta-query (<code>__schema</code>/<code>__type</code>) that a disabled flag blocks outright; field suggestions come from ordinary VALIDATION errors on any wrong query, a code path introspection\'s on/off switch never touches at all.'
    },
    {
      thought: 'A "custom validation rule" (as the main page\'s own QnA phrases it) can be written to stop graphql-js from generating the suggestion text in the first place.',
      reality: 'graphql-js has no built-in hook to suppress suggestion generation during validation itself -- the verified, real-world fix (graphql-armor\'s block-field-suggestions plugin) works AFTER validation, rewriting the already-generated error message via a regex before it is sent to the client, not by preventing graphql-js from computing it.'
    },
    {
      thought: 'Field-suggestion leakage only matters for query fields -- mutation and subscription root fields are unaffected.',
      reality: 'graphql-js\'s field-suggestion logic runs identically for any selection set, regardless of whether the parent type is Query, Mutation, or Subscription -- a guessed, near-miss mutation name leaks its real name through the exact same "Did you mean" mechanism.'
    }
  ];

  prev: SubtopicLink | null = { label: 'Aliased Root Fields Are Not Stopped by Disabling Batching', route: '/graphql/performance/aliased-root-fields-bypass-batching-disable' };
}
