import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { LivePlaygroundComponent, PlaygroundFile } from '../../../../../shared/live-playground/live-playground';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  standalone: true,
  imports: [PageMetaComponent, TheoryBlockComponent, LivePlaygroundComponent, TryItComponent, MisconceptionsComponent, SubtopicNavComponent, SubtopicEyebrowComponent],
  templateUrl: './div-role-button-lacks-keyboard-activation.html',
  styleUrl: './div-role-button-lacks-keyboard-activation.scss'
})
export class DivRoleButtonLacksKeyboardActivationSubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'ARIA only changes what assistive technology ANNOUNCES — it adds zero behavior of its own',
      points: [
        'Setting <code>role="button"</code> on a <code>&lt;div&gt;</code> tells a screen reader "announce this as a button" — nothing more. The div does not become focusable, does not enter the tab order, and does not respond to Enter or Space.',
        'A real <code>&lt;button&gt;</code> gets three things for free from the browser: focusability (<code>tabIndex</code> defaults to 0), inclusion in the tab order, and built-in Enter/Space-to-click activation. None of these three come from the <code>role</code> attribute — they come from the element being a genuine <code>&lt;button&gt;</code>.',
      ]
    },
    {
      heading: 'Making a div-based "button" actually work requires manually replicating all three',
      points: [
        '<code>tabindex="0"</code> is required to make the div focusable and put it in the natural tab order — without it, keyboard users cannot even reach the element.',
        'A <code>keydown</code> listener checking for <code>Enter</code> and <code>" "</code> (Space) is required to replicate native activation — the browser will never fire this on its own for a div, no matter what role is set.',
        'This is exactly why the first rule of ARIA is to prefer the native element: a real <code>&lt;button&gt;</code> gets all of this for free, permanently, with zero JavaScript.',
      ]
    },
    {
      heading: 'A script can\'t simulate its way to proving the real button\'s native Enter-activation — and that limitation is itself worth knowing',
      points: [
        'Browsers only run a "default action" (like a native <code>&lt;button&gt;</code>\'s built-in Enter/Space-to-click behavior) in response to a TRUSTED event — one generated by an actual user interaction, never one created by <code>new KeyboardEvent()</code> and <code>dispatchEvent()</code> from a script.',
        'This means dispatching a synthetic Enter keydown produces ZERO clicks on a real <code>&lt;button&gt;</code> too — not because the browser lacks the built-in behavior, but because that behavior is gated on trust, and script-dispatched events are always untrusted (<code>event.isTrusted === false</code>).',
        'What a script CAN prove: a manually-added <code>keydown</code> listener (application code, not a browser default action) responds identically to synthetic and real events — which is exactly why replicating button behavior on a div requires your OWN listener, since there\'s no default action to lean on either way once you\'ve stepped outside a real <code>&lt;button&gt;</code>.',
      ]
    }
  ];

  liveDemoFiles: PlaygroundFile[] = [
    {
      path: 'index.html',
      content: `<!doctype html>
<html>
  <head><title>div role=button lacks keyboard activation</title></head>
  <body>
    <p>Open the browser console (or the StackBlitz Console tab) to see output.</p>
    <div role="button" id="fakeBtn">Fake button (div)</div>
    <div role="button" id="fixedBtn" tabindex="0">Fixed fake button (div + manual handler)</div>
    <script type="module" src="index.ts"></script>
  </body>
</html>
`,
    },
    {
      path: 'index.ts',
      content: `const fakeBtn = document.querySelector<HTMLElement>('#fakeBtn')!;
const fixedBtn = document.querySelector<HTMLElement>('#fixedBtn')!;

console.log('fakeBtn.tabIndex (no tabindex set):', fakeBtn.tabIndex);
console.log('fixedBtn.tabIndex (tabindex="0" set):', fixedBtn.tabIndex);

let fakeClicks = 0;
let fixedClicks = 0;
fakeBtn.addEventListener('click', () => fakeClicks++);
fixedBtn.addEventListener('click', () => fixedClicks++);

// A manually-added keydown handler — this is APPLICATION code, not a
// browser default action, so it runs on synthetic events just like real ones.
fixedBtn.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' || e.key === ' ') fixedBtn.click();
});

function pressEnter(el: HTMLElement) {
  el.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
}

pressEnter(fakeBtn);
pressEnter(fixedBtn);

console.log('fakeBtn (no handler) click count after Enter:', fakeClicks);
console.log('fixedBtn (manual handler) click count after Enter:', fixedClicks);
`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'A script dispatches a synthetic <code>Enter</code> keydown event at a REAL, focused <code>&lt;button&gt;</code> element (no manual keydown listener added). Does its <code>click</code> listener fire?',
    hint: 'Native "default actions" like Enter-to-click only run for events the browser itself generated from actual user input — think about what property distinguishes a script-dispatched event from a real keypress.',
    solution: 'No — zero clicks, even on a genuine <code>&lt;button&gt;</code>. The browser\'s built-in Enter/Space-to-click behavior is a "default action" that only runs for TRUSTED events; a script-dispatched <code>KeyboardEvent</code> always has <code>isTrusted: false</code>, so no default action runs at all — the real button\'s native activation is completely real, just not something a script can trigger on itself.'
  };

  misconceptions: Misconception[] = [
    {
      thought: 'Adding <code>role="button"</code> to a <code>&lt;div&gt;</code> makes it behave like a button — focusable, clickable via keyboard, the works.',
      reality: 'It only changes the accessibility-tree announcement. Focusability, tab order, and Enter/Space activation are all separate browser behaviors tied to the real <code>&lt;button&gt;</code> element — none of them come from the <code>role</code> attribute.'
    },
    {
      thought: 'Adding <code>tabindex="0"</code> alone is enough to fully replicate native button behavior on a div.',
      reality: '<code>tabindex="0"</code> only handles focusability and tab order. You still need a manual <code>keydown</code> listener for Enter AND Space — the browser never wires up keyboard activation for a div, regardless of its role or tabindex.'
    },
    {
      thought: 'A script can dispatch a synthetic Enter keydown at a real <code>&lt;button&gt;</code> to prove its native keyboard activation works, the same way you\'d test any other DOM behavior.',
      reality: 'It can\'t — the browser\'s native Enter/Space-to-click default action only runs for TRUSTED events, and every script-dispatched event is untrusted. A real button\'s native activation genuinely exists, it just isn\'t something a script can trigger on itself to prove.'
    }
  ];
}
