import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  selector: 'app-instead-of-insert-trigger-demo-subtopic',
  standalone: true,
  imports: [
    PageMetaComponent, TheoryBlockComponent, CodeBlockComponent,
    TryItComponent, MisconceptionsComponent, SubtopicNavComponent,
    SubtopicEyebrowComponent,
  ],
  templateUrl: './demonstrating-an-instead-of-insert-trigger-for-a-multi-table-join-view.html',
  styleUrl: './demonstrating-an-instead-of-insert-trigger-for-a-multi-table-join-view.scss',
})
export class DemonstratingAnInsteadOfInsertTriggerForAMultiTableJoinViewSubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'A Pattern Named, Never Shown',
      points: [
        'The main page describes INSTEAD OF triggers twice — once in the theory ("For complex views (joins, unions), use an INSTEAD OF trigger to define custom DML logic") and once in the quiz explanation, which even gives a specific example in prose: "a view joining customers and addresses can have an INSTEAD OF INSERT that populates both tables correctly." Neither mention includes a single line of actual trigger code.',
        'This subtopic writes that exact example — a view joining customers and addresses, made insertable via an INSTEAD OF INSERT trigger that correctly splits one logical INSERT into two physical INSERTs, one per underlying table, with the generated customer ID threaded into the address row.',
      ],
    },
    {
      heading: 'The Core Mechanic: the inserted Pseudo-Table',
      points: [
        'Inside an INSTEAD OF INSERT trigger, MSSQL provides a special pseudo-table called inserted, containing the row(s) the original INSERT statement attempted to write — as if the insert had succeeded, even though (because this is INSTEAD OF, not AFTER) it never actually touched the view or any base table yet.',
        'The trigger\'s job is to read from inserted and manually perform whatever real INSERT statements are needed against the actual base tables — including handling any IDENTITY columns, which won\'t be present in inserted() since they\'re generated by the database, not supplied by the original INSERT.',
      ],
    },
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'The join view — not directly insertable',
      language: 'sql',
      code: `CREATE TABLE customers (customer_id INT IDENTITY PRIMARY KEY, name VARCHAR(100));
CREATE TABLE addresses (
    address_id  INT IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES customers(customer_id),
    street      VARCHAR(200),
    city        VARCHAR(100)
);
GO

CREATE VIEW v_customer_with_address AS
SELECT c.customer_id, c.name, a.street, a.city
FROM customers c
JOIN addresses a ON a.customer_id = c.customer_id;
GO

-- A plain INSERT into this view fails:
INSERT INTO v_customer_with_address (name, street, city)
VALUES ('Alice', '123 Main St', 'Springfield');
-- Msg 4405: View or function 'v_customer_with_address' is not
-- updatable because the modification affects multiple base tables.`,
    },
    {
      label: 'The INSTEAD OF INSERT trigger — actual code, not just prose',
      language: 'sql',
      code: `CREATE TRIGGER trg_customer_with_address_insert
ON v_customer_with_address
INSTEAD OF INSERT
AS
BEGIN
    SET NOCOUNT ON;

    -- "inserted" holds the row(s) the caller attempted to insert
    -- through the view -- name, street, city -- but NOT customer_id,
    -- since that's an IDENTITY column the caller never supplied.
    DECLARE @NewCustomerId INT;

    INSERT INTO customers (name)
    SELECT name FROM inserted;

    SET @NewCustomerId = SCOPE_IDENTITY();

    INSERT INTO addresses (customer_id, street, city)
    SELECT @NewCustomerId, street, city FROM inserted;
END;
GO

-- Now the same INSERT that failed above succeeds:
INSERT INTO v_customer_with_address (name, street, city)
VALUES ('Alice', '123 Main St', 'Springfield');

SELECT * FROM v_customer_with_address;
-- customer_id | name  | street       | city
-- ------------+-------+--------------+-------------
--      1      | Alice | 123 Main St  | Springfield
--
-- The trigger correctly split ONE logical insert into TWO physical
-- inserts (customers, then addresses), threading the generated
-- customer_id from the first into the second -- exactly the pattern
-- the main page describes but never actually writes out.`,
    },
    {
      label: 'Handling a multi-row INSERT correctly',
      language: 'sql',
      code: `-- This single-row example works, but a naive real-world version of
-- this trigger would break on a MULTI-ROW insert, since SCOPE_IDENTITY()
-- only returns the last identity value generated, not one per row.
-- A production-correct version uses OUTPUT to pair each new customer_id
-- back to its originating row:
ALTER TRIGGER trg_customer_with_address_insert
ON v_customer_with_address
INSTEAD OF INSERT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @NewCustomers TABLE (NewCustomerId INT, Name VARCHAR(100));

    INSERT INTO customers (name)
    OUTPUT inserted.customer_id, inserted.name INTO @NewCustomers
    SELECT name FROM inserted;

    INSERT INTO addresses (customer_id, street, city)
    SELECT nc.NewCustomerId, i.street, i.city
    FROM inserted i
    JOIN @NewCustomers nc ON nc.Name = i.name;
END;
GO

-- Now correctly handles multiple rows in a single INSERT statement,
-- each getting its own newly generated customer_id paired to its
-- own street/city -- SCOPE_IDENTITY() alone would have silently
-- paired every address row to just the LAST customer inserted.`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'A developer builds an INSTEAD OF INSERT trigger for v_customer_with_address using the simple SCOPE_IDENTITY() version (the second code tab above). It works perfectly in every manual test — until an ORM starts batching multiple customer inserts into a single multi-row INSERT statement, at which point every new address ends up attached to the same customer. What\'s happening, and why did manual testing miss it?',
    hint: 'SCOPE_IDENTITY() returns exactly ONE value, no matter how many rows the preceding INSERT created — trace what happens when "inserted" in the trigger contains more than one row.',
    solution: `SCOPE_IDENTITY() returns only the LAST identity value generated by
the most recent INSERT statement in the current scope — it has no
way to return multiple values for a multi-row insert. When the ORM's
batched INSERT puts several rows into "inserted" at once, the trigger's
"INSERT INTO customers ... SELECT name FROM inserted" creates several
new customer rows, but @NewCustomerId only captures the LAST one's
ID. The subsequent "INSERT INTO addresses ... SELECT @NewCustomerId,
..." then attaches every address row to that single last customer_id,
silently misassigning every other row's address.

Manual testing missed this because each manual test almost certainly
inserted ONE row at a time, where SCOPE_IDENTITY() genuinely does
return the correct (and only) new ID. The bug only appears once
"inserted" contains more than one row — exactly the third code tab's
scenario, which is why the production-correct version uses OUTPUT to
capture a customer_id for EACH inserted row individually, then joins
back to route each address to its own correct customer, instead of
relying on a single scalar SCOPE_IDENTITY() value.`,
  };

  misconceptions: Misconception[] = [
    {
      thought: 'an INSTEAD OF INSERT trigger using SCOPE_IDENTITY() to capture a newly generated customer_id will work correctly no matter how many rows the original INSERT statement contains.',
      reality: 'SCOPE_IDENTITY() returns exactly one value — the last identity generated — so a trigger relying on it breaks silently on any multi-row INSERT, misattributing every row except the last to the wrong parent ID.',
    },
    {
      thought: 'the "inserted" pseudo-table inside an INSTEAD OF INSERT trigger always contains exactly one row, matching how a single INSERT ... VALUES (...) statement is usually written.',
      reality: '"inserted" can contain any number of rows — a multi-row INSERT ... VALUES (...), (...), (...) or an INSERT ... SELECT from another table all populate "inserted" with multiple rows in a single trigger invocation.',
    },
    {
      thought: 'INSTEAD OF triggers are an obscure, rarely-needed feature only relevant for unusual edge cases.',
      reality: 'they are the standard, documented mechanism for making any view over a JOIN or aggregate insertable/updatable in SQL Server — the main page itself names this exact use case twice, even though it never shows the trigger code.',
    },
  ];
}
