import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../../shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../../shared/theory-block/theory-block';
import { CodeBlockComponent, CodeTab } from '../../../../../shared/code-block/code-block';
import { TryItComponent, TryItExercise } from '../../../../../shared/try-it/try-it';
import { MisconceptionsComponent, Misconception } from '../../../../../shared/misconceptions/misconceptions';
import { SubtopicNavComponent } from '../../../../../shared/subtopic-nav/subtopic-nav';
import { SubtopicEyebrowComponent } from '../../../../../shared/subtopic-eyebrow/subtopic-eyebrow';

@Component({
  standalone: true,
  imports: [PageMetaComponent, TheoryBlockComponent, CodeBlockComponent, TryItComponent, MisconceptionsComponent, SubtopicNavComponent, SubtopicEyebrowComponent],
  templateUrl: './basic-slicing-is-a-view-fancy-indexing-is-a-copy.html',
  styleUrl: './basic-slicing-is-a-view-fancy-indexing-is-a-copy.scss'
})
export class BasicSlicingIsAViewFancyIndexingIsACopySubtopic {

  theory: TheoryPoint[] = [
    {
      heading: 'Two ways to select elements from an array — two entirely different memory relationships',
      points: [
        'The main page\'s own theory covers "fancy indexing" and boolean indexing side by side with ordinary slicing, treating them as just different flavors of the same idea: selecting elements from an array. NumPy\'s own documentation draws a much sharper line — the TYPE of indexing used determines whether the result shares memory with the original array or is a genuinely separate copy.',
        'NumPy\'s own indexing documentation is direct about basic slicing (using a slice, an integer, or a tuple of slices/integers — arr[1:3], arr[::2], arr[0]): "All arrays generated by basic slicing are always views of the original array." A view is not a new array with copied data — it is a different way of looking at the SAME underlying memory. Modifying a view modifies the original array, because there is only one array in memory.',
        'Advanced indexing — using an array of integers (arr[[0, 2, 4]]) or a boolean array (arr[arr > 0]) — is documented with the opposite guarantee: "Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view)." The result is an independent array with its own memory. Modifying it has zero effect on the original.',
      ]
    },
    {
      heading: 'Assignment is the one case that behaves the same either way — reading a stored copy is where the difference bites',
      points: [
        'This is where the gotcha hides: arr[[1, 3]] = 0 (using fancy indexing directly as an ASSIGNMENT TARGET) still correctly modifies the original array — NumPy special-cases __setitem__ so that writing through a fancy-index expression writes into the original array\'s buffer, regardless of the fact that READING the same expression would produce a copy. This makes the write-path and the read-path look deceptively identical in casual code.',
        'The actual danger appears once the fancy-indexed result is stored in a variable and mutated LATER, as a separate step: sub = arr[[1, 3]] creates a genuine, independent copy (confirmed by NumPy\'s own base attribute — a copy\'s .base is None, while a view\'s .base points back to the original array). sub[0] = 999 afterward modifies only sub — the original arr is completely unaffected, which surprises anyone who has gotten used to basic-slice views (my_slice = arr[1:3]; my_slice[0] = 999 DOES change arr) behaving the "linked" way.',
        'The practical rule worth internalizing: if code stores the result of arr[start:stop] (or any pure slice/integer expression) and later mutates it, that mutation reaches back into the original array — a real, easy-to-miss side effect. If code stores the result of arr[some_list] or arr[some_boolean_mask] and later mutates it, that mutation is completely isolated — safe from that angle, but also means changes are silently NOT reflected back if the code actually intended to modify the original.',
      ]
    }
  ];

  codeTabs: CodeTab[] = [
    {
      label: 'A stored basic slice is a view — a stored fancy-indexed result is a copy',
      language: 'typescript',
      code: `import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# BASIC SLICING (slice object) -- stores a VIEW, shares memory
basic_slice = arr[1:3]        # [20, 30]
basic_slice[0] = 999
print(arr)                     # [10, 999, 30, 40, 50] -- the ORIGINAL
                                # array changed too, because
                                # 'basic_slice' is a view into the
                                # SAME underlying memory, not a copy.
print(basic_slice.base is arr) # True -- confirms it's a view

arr = np.array([10, 20, 30, 40, 50])   # reset

# ADVANCED (FANCY) INDEXING -- stores a COPY, independent memory
fancy_result = arr[[1, 2]]     # [20, 30] -- same VALUES as above
fancy_result[0] = 999
print(arr)                     # [10, 20, 30, 40, 50] -- UNCHANGED!
                                # fancy_result is a completely separate
                                # array; mutating it never touches arr.
print(fancy_result.base is None)   # True -- confirms it's a copy

# BOOLEAN INDEXING -- same rule, since it's a form of advanced indexing
mask_result = arr[arr > 15]    # [20, 30, 40, 50]
mask_result[0] = 999
print(arr)                     # STILL unchanged -- boolean indexing
                                # is documented as advanced indexing
                                # too, so it also always copies.`,
    },
    {
      label: 'Direct assignment through fancy indexing DOES still write through',
      language: 'typescript',
      code: `import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Using fancy indexing DIRECTLY as the assignment target (not stored
# in a variable first) DOES modify the original -- NumPy special-cases
# __setitem__ to write through, even though READING the same
# expression would have produced an independent copy.
arr[[1, 3]] = 0
print(arr)   # [10, 0, 30, 0, 50] -- the original WAS modified here,
              # which can make the read/write distinction feel
              # inconsistent if you haven't internalized the rule.

arr = np.array([10, 20, 30, 40, 50])   # reset

# The trap: the moment the fancy-indexed result is READ and STORED
# in its own variable, it becomes a copy -- a SEPARATE step from the
# assignment case above.
selected = arr[[1, 3]]    # READS via fancy indexing -> COPY
selected += 100            # modifies the COPY only
print(arr)                 # [10, 20, 30, 40, 50] -- unchanged!
print(selected)            # [120, 140] -- only the copy changed

# Contrast with the equivalent basic-slice pattern, which DOES
# propagate back, because it was never a copy in the first place:
arr2 = np.array([10, 20, 30, 40, 50])
selected2 = arr2[1:4]      # basic slice -> VIEW
selected2 += 100
print(arr2)                 # [10, 120, 130, 140, 50] -- CHANGED,
                              # because selected2 shares memory with arr2.`,
    },
  ];

  exercise: TryItExercise = {
    prompt: 'A data-cleaning function does: outliers = data[data > threshold]; outliers[:] = threshold (clamping every value above threshold down to threshold, intending to modify data in place). After calling this function, the developer is confused that data itself still contains the original out-of-range values, unchanged. Explain exactly why, using what this subtopic covers, and give the corrected version that actually modifies data.',
    hint: 'data[data > threshold] is a boolean-mask expression — per this subtopic\'s theory, does reading through a boolean mask return a view sharing memory with data, or an independent copy? Does storing that result in the outliers variable and then mutating outliers reach back into data?',
    solution: 'data[data > threshold] is boolean indexing, which per this subtopic\'s theory is documented as a form of advanced indexing — advanced indexing "always returns a copy of the data," never a view. So outliers = data[data > threshold] stores a completely independent array with its own memory; outliers[:] = threshold then clamps every value inside that copy, but data itself was never touched, since outliers has no memory relationship to data at all once it has been read out and stored in its own variable. This is exactly the trap this subtopic\'s theory describes: the boolean-mask READ produces a copy the instant it is stored in a variable, unlike a basic slice, which would have stayed linked to the original array\'s memory. The corrected version needs to either (a) assign directly through the boolean mask as the assignment target in one step, without storing an intermediate variable first — data[data > threshold] = threshold — which per this subtopic\'s second code example DOES write through correctly (NumPy special-cases __setitem__ for this), or (b) if the mask needs to be reused/inspected before assignment, store the MASK itself (a boolean array) rather than the indexed-out values, and then assign through it: mask = data > threshold; data[mask] = threshold. Both fixes avoid ever reading the actual VALUES out through fancy/boolean indexing into a separate variable and then trying to mutate that separate variable — that specific pattern is exactly what silently produces an isolated copy.'
  };

  misconceptions: Misconception[] = [
    {
      thought: 'All forms of NumPy array indexing (slicing, fancy/integer-array indexing, boolean masking) behave the same way with respect to memory — either they are all views, or the distinction does not matter in practice.',
      reality: 'This subtopic\'s theory and first code example show NumPy\'s own documentation draws a sharp, deliberate line — basic slicing (slices, integers) "always" returns a view sharing memory with the original, while advanced indexing (integer arrays, boolean masks) "always" returns an independent copy. These are documented, opposite guarantees, not an implementation detail that happens to vary.'
    },
    {
      thought: 'Since data[data > threshold] = value (direct assignment through a boolean mask) correctly modifies data in place, storing the same expression in a variable first — outliers = data[data > threshold] — and then mutating outliers should behave identically, since it looks like the same underlying selection.',
      reality: 'This subtopic\'s theory and second code example show these are genuinely different code paths — direct assignment through fancy/boolean indexing writes through to the original array (a special-cased __setitem__ behavior), but READING the same expression into a stored variable first produces an independent copy per NumPy\'s documented advanced-indexing rule, and mutating that stored copy afterward never reaches the original array at all.'
    },
    {
      thought: 'A NumPy array\'s .base attribute is just internal bookkeeping with no practical use — there\'s no reliable way to check in code whether a given array is a view or a copy of another array.',
      reality: 'This subtopic\'s first code example shows .base is a directly usable, documented signal — a view\'s .base attribute points back to the original array it shares memory with, while a genuine copy\'s .base is None, giving code (or a developer debugging unexpected mutation behavior) a concrete way to check which relationship a given array actually has, rather than having to guess from how it was constructed.'
    }
  ];
}
