import { Component, inject } from '@angular/core';
import { Router, RouterLink, NavigationEnd } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { filter, map, startWith } from 'rxjs';

const ROUTE_LABELS: Record<string, string> = {
  '':                   'Home',
  'counter':            'Signals & State',
  'what-is-a-signal':   'What Is a Signal?',
  'computed':           'computed() — Derived State',
  'effects':            'effect() — Reactive Side Effects',
  'control-flow':       '@if and @for — Control Flow',
  'readonly-and-services': 'Signals in Services',
  'rxjs-interop':       'RxJS Interop',
  'inject-di':          'inject() — Modern Dependency Injection',
  'reactive-forms-basics': 'Reactive Forms Basics',
  'signal-based-services': 'Signal-Based Services',
  'form-state':         'Form State — touched, dirty, status',
  'template-driven-vs-reactive': 'Template-Driven vs Reactive',
  'formgroup-formcontrol-formarray': 'FormGroup, FormControl & FormArray',
  'cross-field-validators': 'Cross-Field Validators',
  'httpclient-setup':   'HttpClient Setup',
  'get-requests':       'GET Requests — toSignal() and httpResource()',
  'mutation-requests':  'Mutation Requests — POST, PUT, DELETE',
  'error-handling-retry': 'Error Handling & Retry',
  'what-are-interceptors': 'What Are Interceptors?',
  'auth-interceptor-token-refresh': 'Auth Interceptor & Token Refresh',
  'global-error-interceptor': 'Global Error Interceptor',
  'loading-spinner-httpcontext': 'Loading Spinner & HttpContext',
  'input-signals':      'input() — Modern @Input',
  'output-signals':     'output() — Modern @Output',
  'model-two-way-binding': 'model() — Two-Way Binding',
  'viewchild-viewchildren': 'viewChild() and viewChildren()',
  'contentchild-migration': 'contentChild() & Migration',
  'dynamic-formarray-of-groups': 'FormArray of FormGroups',
  'typed-formarray':    'Typed FormArray',
  'formarray-crud-patterns': 'Add, Remove & Reorder',
  'formarray-level-validation': 'Validating the Array Itself',
  'defer-basics':        'What Is @defer?',
  'defer-triggers':      'Trigger Conditions',
  'placeholder-loading-error': 'Placeholder, Loading & Error',
  'defer-requirements-nesting': 'Requirements & Nesting',
  'defer-performance-prefetch': 'Performance & Prefetching',
  'material-setup-theming': 'Setup & Theming',
  'material-form-fields':  'Form Fields, Inputs & Validation',
  'material-common-components': 'Buttons, Dialogs & Snackbars',
  'mattable-sorting-pagination': 'MatTable — Sorting & Pagination',
  'material-testing-accessibility': 'Testing, Accessibility & Performance',
  'async-store-operations': 'Async Store Operations',
  'signal-store-vs-ngrx': 'Signal Store vs NgRx',
  'testing-composing-stores': 'Testing & Composing Stores',
  'interpolation-expressions': 'Interpolation & Expressions',
  'property-event-two-way-binding': 'Property, Event & Two-Way Binding',
  'template-refs-and-let': 'Template Refs & @let',
  'pipes-built-in-custom': 'Pipes — Built-in & Custom',
  'attribute-directive-anatomy': 'Attribute Directive Anatomy',
  'custom-structural-directives': 'Custom Structural Directives',
  'directive-composition-api': 'Directive Composition API',
  'lifecycle-hook-sequence': 'The Hook Sequence',
  'init-hooks-ngonchanges-ngoninit': 'ngOnChanges & ngOnInit',
  'view-content-hooks-afternextrender': 'View & Content Hooks',
  'cleanup-destroyref-takeuntildestroyed': 'Cleanup — DestroyRef & takeUntilDestroyed',
  'formatting-pipes-locale': 'Formatting Pipes & Locale',
  'collection-string-pipes': 'Collection & String Pipes',
  'async-pipe-let-performance': 'AsyncPipe, @let & Performance',
  'injection-context-deep-dive': 'Injection Context Deep Dive',
  'multi-providers-extension-points': 'Multi-Providers & Extension Points',
  'environment-injectors-standalone-bootstrap': 'Environment Injectors & Standalone Bootstrap',
  'custom-url-matchers-route-config': 'Custom UrlMatchers & Route Config',
  'router-events-navigation-lifecycle': 'Router Events & Navigation Lifecycle',
  'route-reuse-strategy': 'Route Reuse Strategy',
  'view-transitions-relative-navigation': 'View Transitions & Relative Navigation',
  'custom-plugins-click-interactions': 'Custom Plugins & Click Interactions',
  'mixed-charts-annotations': 'Mixed Charts & Annotations',
  'time-scale-large-datasets': 'Time Scale & Large Datasets',
  'discriminated-unions-and-transforms': 'Discriminated Unions & Transforms',
  'async-validation-with-zod': 'Async Validation with Zod',
  'nested-schemas-error-formatting': 'Nested Schemas & Error Formatting',
  'programmatic-projection-createcomponent': 'Programmatic Projection with createComponent',
  'compound-components-content-queries': 'Compound Components with Content Queries',
  'recursive-templates-ngtemplateoutlet': 'Recursive Templates with NgTemplateOutlet',
  'embedded-views-dynamic-cd': 'Embedded Views & Dynamic Component CD',
  'bridging-external-libraries-onpush': 'Bridging External Libraries to OnPush',
  'testing-onpush-components': 'Testing OnPush Components',
  'dynamic-validators-runtime': 'Dynamic Validators at Runtime',
  'validator-directives-template-forms': 'Validator Directives for Template Forms',
  'generic-reusable-validators': 'Generic Reusable Validators',
  'custom-operators-and-pipe': 'Custom Operators & pipe()',
  'multicasting-share-operators': 'Multicasting & share() Operators',
  'testing-rxjs-marble-diagrams': 'Testing RxJS with Marble Diagrams',
  'cdk-menu-keyboard-navigation': 'CDK Menu & Keyboard Navigation',
  'cdk-table-headless-data-table': 'CDK Table — Headless Data Table',
  'building-custom-overlay-component': 'Building a Custom Overlay Component',
  'custom-cell-renderers-angular-components': 'Custom Cell Renderers as Angular Components',
  'editable-cells-value-setters': 'Editable Cells & Value Setters',
  'master-detail-row-grouping': 'Master/Detail & Row Grouping',
  'optimistic-updates-rollback': 'Optimistic Updates & Rollback',
  'dependent-and-parallel-queries': 'Dependent & Parallel Queries',
  'infinite-queries-pagination': 'Infinite Queries & Pagination',
  'intervals-and-recurring-events': 'Intervals & Recurring Events',
  'timezone-handling-date-fns-tz': 'Timezone Handling with date-fns-tz',
  'reactive-date-range-picker': 'Reactive Date Range Picker',
  'animation-callbacks-lifecycle-events': 'Animation Callbacks & Lifecycle Events',
  'group-sequence-parallel-orchestration': 'group() vs sequence() Orchestration',
  'css-only-and-view-transitions-alternatives': 'CSS-Only & View Transitions Alternatives',
  'ngcontrol-self-injection-validation-display': 'NgControl Self-Injection for Validation Display',
  'composite-value-cva-with-formgroup': 'Composite Value CVA with FormGroup',
  'testing-cva-components': 'Testing CVA Components',
  'testing-directives-with-host-components': 'Testing Directives with Host Components',
  'testing-routed-components-and-guards': 'Testing Routed Components & Guards',
  'test-doubles-and-mocking-strategies': 'Test Doubles & Mocking Strategies',
  'theme-tokens-and-custom-variants': 'Theme Tokens & Custom Variants',
  'component-variant-patterns-with-cva': 'Component Variant Patterns with cva',
  'tailwind-transitions-and-animations': 'Tailwind Transitions & Animations',
  'rxresource-and-observable-integration': 'rxResource & Observable Integration',
  'resource-reload-and-polling-patterns': 'Resource Reload & Polling Patterns',
  'testing-resource-based-components': 'Testing resource()-Based Components',
  'withentities-filtering-pagination-sorting': 'withEntities — Filtering, Pagination & Sorting',
  'testing-ngrx-signal-stores': 'Testing NgRx Signal Stores',
  'signal-store-devtools-and-hooks-cleanup': 'Signal Store DevTools & Hooks Cleanup',
  'nested-and-array-schema-fields': 'Nested & Array Schema Fields',
  'schema-driven-cross-field-and-async-validation': 'Schema-Driven Cross-Field & Async Validation',
  'custom-field-renderer-registry-pattern': 'Custom Field Renderer Registry Pattern',
  'testing-route-resolvers': 'Testing Route Resolvers',
  'run-guards-and-resolvers-caching': 'runGuardsAndResolvers & Resolver Caching',
  'named-outlet-lifecycle-and-detail-drawer-pattern': 'Named Outlet Lifecycle & Detail Drawer Pattern',
  'priority-tiered-preloading-with-delay': 'Priority-Tiered Preloading with Delay',
  'testing-preloading-strategies': 'Testing Preloading Strategies',
  'measuring-preload-effectiveness': 'Measuring Preload Effectiveness',
  'canactivatechild-for-nested-admin-sections': 'canActivateChild for Nested Admin Sections',
  'tracing-guard-execution-order': 'Tracing Guard Execution Order',
  'async-guards-with-navigation-loading-indicator': 'Async Guards with a Navigation Loading Indicator',
  'custom-loader-with-blur-up-lqip-placeholder': 'Custom Loader with Blur-Up LQIP Placeholder',
  'testing-components-that-use-ngoptimizedimage': 'Testing Components That Use NgOptimizedImage',
  'measuring-lcp-impact-with-performanceobserver': 'Measuring LCP Impact with PerformanceObserver',
  'testing-destroyref-cleanup-and-takeuntildestroyed': 'Testing DestroyRef Cleanup and takeUntilDestroyed',
  'runininjectioncontext-for-composables-outside-construction': 'runInInjectionContext for Composables Outside Construction',
  'wrapping-a-non-observable-third-party-api': 'Wrapping a Non-Observable Third-Party API',
  'testing-linkedsignal-reset-behavior': 'Testing linkedSignal Reset Behavior',
  'linkedsignal-with-resource-for-editable-drafts': 'linkedSignal with resource() for Editable Drafts',
  'debugging-unexpected-linkedsignal-resets': 'Debugging Unexpected linkedSignal Resets',
  'auditing-a-codebase-for-zoneless-readiness': 'Auditing a Codebase for Zoneless Readiness',
  'zoneless-ssr-and-incremental-hydration': 'Zoneless SSR and Incremental Hydration',
  'when-ngzone-run-is-actually-unnecessary': 'When ngZone.run() Is Actually Unnecessary',
  'testing-signal-effects-and-cleanup': 'Testing Signal Effects and Cleanup',
  'afterrendereffect-for-dom-measurements': 'afterRenderEffect for DOM Measurements',
  'debouncing-effects-for-expensive-side-effects': 'Debouncing Effects for Expensive Side Effects',
  'testing-typed-reactive-forms': 'Testing Typed Reactive Forms',
  'writing-type-safe-custom-validators': 'Writing Type-Safe Custom Validators',
  'populating-a-typed-form-from-resource': 'Populating a Typed Form from resource()',
  'testing-components-that-use-hostdirectives': 'Testing Components That Use hostDirectives',
  'coordinating-multiple-stacked-host-directives': 'Coordinating Multiple Stacked Host Directives',
  'optional-host-directive-injection-for-shared-components': 'Optional Host Directive Injection for Shared Components',
  'testing-let-driven-templates': 'Testing @let-Driven Templates',
  'profiling-let-recompute-cost': 'Profiling @let Recompute Cost',
  'let-inside-ng-template-scope-closure': '@let Inside ng-template and Structural Directives',
  'testing-hybrid-standalone-and-ngmodule-components': 'Testing Hybrid Standalone and NgModule Components',
  'scam-pattern-incremental-migration-walkthrough': 'SCAM Pattern — Incremental Migration Walkthrough',
  'debugging-nullinjectorerror-after-migration': 'Debugging NullInjectorError After Migration',
  'testing-a-layered-error-handling-system': 'Testing a Layered Error Handling System',
  'retry-with-exponential-backoff-and-give-up': 'Retry with Exponential Backoff and a Give-Up State',
  'recovering-from-component-rendering-errors': 'Recovering from Component Rendering Errors',
  'testing-auth-interceptor-flows-with-msw': 'Testing Auth Interceptor Flows with MSW',
  'testing-loading-states-with-msw-delay': 'Testing Loading States with MSW delay()',
  'debugging-unhandled-requests-and-query-param-matching': 'Debugging Unhandled Requests and Query-Param Matching',
  'automated-accessibility-testing-with-jest-axe': 'Automated Accessibility Testing with jest-axe',
  'building-a-reusable-route-change-focus-management-service': 'Building a Reusable Route-Change Focus Management Service',
  'testing-focus-trap-and-restoration-in-modals': 'Testing Focus Trap and Restoration in Modals',
  'testing-cross-mfe-communication-with-a-mocked-event-bus': 'Testing Cross-MFE Communication with a Mocked Event Bus',
  'debugging-duplicate-angular-runtime-issues': 'Debugging Duplicate Angular Runtime Issues',
  'css-style-isolation-with-shadowdom-encapsulation': 'CSS Style Isolation with ShadowDom Encapsulation',
  'building-a-why-did-this-render-debug-helper': 'Building a "Why Did This Render?" Debug Helper',
  'safely-enabling-devtools-on-staging': 'Safely Enabling DevTools on Staging',
  'turning-a-profiler-finding-into-a-regression-test': 'Turning a Profiler Finding into a Regression Test',
  'testing-defer-blocks-with-deferblockfixture': 'Testing @defer Blocks with DeferBlockFixture',
  'detecting-duplicate-dependencies-across-lazy-chunks': 'Detecting Duplicate Dependencies Across Lazy Chunks',
  'automated-bundle-budget-enforcement-in-ci': 'Automated Bundle Budget Enforcement in CI',
  'deep-linking-wizard-steps-with-query-params': 'Deep-Linking Wizard Steps with Query Params',
  'cdk-stepper-vs-hand-rolled-wizard': 'Angular CDK Stepper vs a Hand-Rolled Wizard',
  'testing-wizard-steps-in-isolation': 'Testing Wizard Steps in Isolation',
  'testing-components-that-use-web-workers': 'Testing Components That Use Web Workers',
  'building-a-worker-pool-for-parallel-task-dispatch': 'Building a Worker Pool for Parallel Task Dispatch',
  'debugging-and-profiling-web-workers-in-devtools': 'Debugging and Profiling Web Workers in DevTools',
  'testing-update-prompts-and-install-banners': 'Testing Update Prompts and Install Banners',
  'handling-unrecoverable-state-and-manual-update-checks': 'Handling Unrecoverable State and Manual Update Checks',
  'spa-routing-pitfalls-navigationurls-and-app-shell-fallback': 'SPA Routing Pitfalls: navigationUrls and the App-Shell Fallback',
  'testing-components-that-use-transloco-and-signal-i18n': 'Testing Components That Use Transloco and Signal-Based i18n',
  'building-rtl-layout-support-with-logical-css-properties': 'Building RTL Layout Support with Logical CSS Properties',
  'ssr-locale-detection-and-avoiding-hydration-mismatches': 'SSR Locale Detection and Avoiding Hydration Mismatches',
  'reusing-authentication-state-across-tests-with-storagestate': 'Reusing Authentication State Across Tests with storageState',
  'visual-regression-testing-with-screenshot-comparisons': 'Visual Regression Testing with Screenshot Comparisons',
  'debugging-flaky-tests-isolation-retries-and-sharding': 'Debugging Flaky Tests: Isolation, Retries, and Sharding',
  'composing-nested-harnesses-with-getchildloader': 'Composing Nested Harnesses with getChildLoader',
  'publishing-harnesses-as-a-librarys-public-testing-entry-point': 'Publishing Harnesses as a Public Testing Entry Point',
  'debugging-harness-failures-common-causes-and-diagnosis': 'Debugging Harness Failures: Common Causes and Diagnosis',
  'debugging-hydration-mismatches-step-by-step': 'Debugging Hydration Mismatches Step by Step',
  'testing-ssr-safe-components-without-a-real-server': 'Testing SSR-Safe Components Without a Real Server',
  'incremental-hydration-triggers-interaction-viewport-and-timer': 'Incremental Hydration Triggers: Interaction, Viewport, and Timer',
  // Composite keys — these subtopic slugs collide with existing top-level Angular topics
  // (/angular/route-guards, /angular/custom-validators, /angular/typed-forms);
  // pageLabel() tries this key first.
  'todo/route-guards':      'Route Guards',
  'todo/custom-validators': 'Custom & Async Validators',
  'forms/typed-forms':      'Typed Forms',
  'templates':          'Template Syntax',
  'directives':         'Directives',
  'lifecycle':          'Lifecycle Hooks',
  'pipes':              'Pipes',
  'di':                 'Dependency Injection',
  'parent-child':       'Input / Output',
  'content-projection': 'Content Projection',
  'change-detection':   'Change Detection',
  'animations':         'Animations',
  'forms':              'Forms',
  'form-array':         'FormArray',
  'todo':               'Todo (guarded)',
  'zod-forms':          'Zod Validation',
  'custom-validators':  'Custom Validators',
  'cva':                'Control Value Accessor',
  'dynamic-forms':      'Dynamic Forms',
  'wizard-form':        'Wizard Form',
  'http':               'HTTP Client',
  'routing':            'Routing',
  'defer':              '@defer Blocks',
  'store':              'Signal Store',
  'rxjs':               'RxJS Operators',
  'testing':            'Testing',
  'route-resolvers':    'Route Resolvers',
  'preloading':         'Preloading',
  'route-guards':       'Route Guards',
  'http-interceptors':  'HTTP Interceptors',
  'signal-effects':     'Signal Effects',
  'typed-forms':        'Typed Reactive Forms',
  'host-directives':    'Host Directives',
  'let-template-vars':       '@let Template Variables',
  'standalone-migration':    'Standalone Migration',
  'error-handling-patterns': 'Error Handling Patterns',
  'msw':                     'Mock Service Worker',
  'accessibility':           'Accessibility (a11y)',
  'micro-frontends':         'Micro-Frontends',
  'angular-devtools':        'Angular DevTools',
  'bundle-optimization':     'Bundle Optimization',
  'material':           'Angular Material',
  'charts':             'Charts',
  'cdk':                'Angular CDK',
  'ag-grid':            'AG Grid',
  'tanstack-query':     'TanStack Query',
  'date-fns':           'date-fns',
  'tailwind':           'Tailwind CSS',
  'resource-api':       'resource() API',
  'ngrx-signals':       'NgRx Signals',
  'destroy-ref':        'DestroyRef',
  'linked-signal':      'linkedSignal()',
  'zoneless':           'Zoneless Angular',
  'e2e':                'E2E (Playwright)',
  'harnesses':          'Harnesses',
  'ng-image':           'NgOptimizedImage',
  'web-workers':        'Web Workers',
  'pwa':                'PWA / Service Worker',
  'i18n':               'i18n',
  'ssr':                'SSR + Hydration',
  'cheatsheet':         'Cheat Sheet',
  'errors':             'Common Errors',
  'whats-new':          "What's New",
  'mini-projects':      'Mini Projects',
  'learning-paths':     'Learning Paths',
  'interview-prep':     'Interview Prep',
  'quiz-practice':      'Quiz Practice',
  'design-patterns':    'Design Patterns',
  'decision-guides':    'Decision Guides',
  'glossary':           'Glossary',
};

const CSHARP_LABELS: Record<string, string> = {
  'basics':               'Variables & Types',
  'basics/nullable-value-types-hasvalue-and-null-coalescing-operators': 'Nullable Value Types: int?, HasValue, and Null-Coalescing',
  'basics/checked-and-unchecked-arithmetic-detecting-integer-overflow': 'Checked and Unchecked Arithmetic: Detecting Integer Overflow',
  'basics/spant-and-stackalloc-parsing-without-heap-allocations': 'Span<T> and stackalloc: Parsing Without Heap Allocations',
  'fields':               'Fields & Constants',
  'fields/testing-field-thread-safety-race-conditions-increment-vs-interlocked': 'Testing Field Thread-Safety: Race Conditions in ++ vs Interlocked',
  'fields/static-field-initialization-order-beforefieldinit': 'Static Field Initialization Order: Cross-Type Dependencies',
  'fields/asynclocal-correct-alternative-to-static-fields-for-per-request-state': 'AsyncLocal: The Correct Alternative to Static Fields',
  'methods':              'Methods',
  'methods/testing-logic-inside-local-functions-when-to-promote': 'Testing Logic Inside Local Functions: When to Promote',
  'methods/in-parameter-defensive-copy-trap': 'The in Parameter Defensive-Copy Trap',
  'methods/caller-info-attributes-callermembername-callerlinenumber': 'Caller Info Attributes: CallerMemberName, CallerLineNumber',
  'type-conversion':      'Type Conversion',
  'type-conversion/testing-conversion-operators-and-overflow-boundaries': 'Testing Conversion Operators and Overflow Boundaries',
  'type-conversion/user-defined-conversion-chaining-one-operator-limit': 'User-Defined Conversion Chaining: One Operator Limit',
  'type-conversion/compile-time-constant-overflow-always-checked': 'Compile-Time Constant Overflow: Always Checked',
  'constructors':         'Constructors',
  'constructors/testing-constructor-validation-and-chaining': 'Testing Constructor Validation and Chaining',
  'constructors/primary-constructor-parameter-capture-field-vs-fixed': 'Primary Constructor Parameter Capture: Field vs Fixed',
  'constructors/diagnosing-typeinitializationexception-inner-exception': 'Diagnosing TypeInitializationException',
  'properties-indexers':  'Properties & Indexers',
  'properties-indexers/testing-computed-properties-and-indexers': 'Testing Computed Properties and Indexers',
  'properties-indexers/init-accessors-and-readonly-fields-assignment-window': 'init Accessors and readonly Fields: The Special Assignment Window',
  'properties-indexers/indexer-initializer-syntax-without-add': 'Indexer Initializer Syntax: Without Implementing Add()',
  'namespaces':           'Namespaces & Usings',
  'namespaces/detecting-unused-using-directives-ide0005': 'Detecting Unused using Directives: IDE0005',
  'namespaces/extern-alias-resolving-assembly-type-name-collisions': 'extern alias: Resolving Assembly Type-Name Collisions',
  'namespaces/resolving-cs0104-ambiguous-using-directives': 'Resolving CS0104 Ambiguous Type References',
  'oop':                  'Classes & OOP',
  'oop/testing-polymorphic-code-mocking-interfaces-and-verifying-virtual-dispatch': 'Testing Polymorphic Code: Mocking Interfaces and Verifying Virtual Dispatch',
  'oop/virtual-member-calls-from-constructors-an-initialization-order-footgun': 'Virtual Member Calls from Constructors: An Initialization-Order Footgun',
  'oop/explicit-interface-implementation-resolving-name-collisions': 'Explicit Interface Implementation: Resolving Name Collisions',
  'inheritance':          'Inheritance & Overriding',
  'inheritance/testing-the-hiding-trap-new-vs-override': 'Testing the Hiding Trap: new vs override',
  'inheritance/how-sealed-enables-devirtualization': 'How sealed Enables Devirtualization',
  'inheritance/covariant-return-types-hidden-bridge-method': 'Covariant Return Types: The Hidden Bridge Method',
  'abstract-interfaces':  'Abstract & Interfaces',
  'abstract-interfaces/testing-default-interface-method-resolution': 'Testing Default Interface Method Resolution',
  'abstract-interfaces/default-interface-method-diamond-problem': 'Default Interface Method Diamond Problem',
  'abstract-interfaces/static-abstract-members-generic-constraint-requirement': 'static abstract Members and Generic Constraints',
  'static-enums':         'Static, Partial & Enums',
  'static-enums/testing-flags-enums-reflection-based-power-of-two-guard': 'Testing [Flags] Enums: Reflection-Based Power-of-Two Guard',
  'static-enums/modern-partial-methods-return-types-mandatory-implementation': 'Modern Partial Methods (C# 9+): Return Types',
  'static-enums/enum-value-stability-serialization-compatibility': 'Enum Value Stability: Serialization Compatibility',
  'structures':           'Structures',
  'structures/testing-the-struct-copy-mutation-trap': 'Testing the Struct-Copy Mutation Trap',
  'structures/ref-struct-interfaces-generic-constraint-dispatch': 'ref struct Interfaces (C# 13)',
  'structures/array-vs-list-vs-foreach-struct-mutation': 'Array vs List vs foreach Struct Mutation',
  'system-object':        'System.Object',
  'system-object/testing-the-equals-gethashcode-contract': 'Testing the Equals/GetHashCode Contract',
  'system-object/gethashcode-instability-across-process-runs': 'GetHashCode Instability Across Process Runs',
  'system-object/record-equality-and-equalitycontract': 'Record Equality and EqualityContract',
  'records':              'Records & Structs',
  'records/polymorphic-json-serialization-of-record-hierarchies-with-jsonderivedtype': 'Polymorphic JSON Serialization of Record Hierarchies',
  'records/positional-pattern-matching-with-records-deconstruction-in-switch-expressions': 'Positional Pattern Matching with Records',
  'records/testing-records-equality-hash-codes-and-constructor-validation': 'Testing Records: Equality, Hash Codes, and Constructor Validation',
  'generics':             'Generics',
  'generics/testing-generic-code-parameterized-tests-across-multiple-type-arguments': 'Testing Generic Code Across Multiple Type Arguments',
  'generics/generic-attributes-c-11-type-safe-custom-attributes': 'Generic Attributes (C# 11): Type-Safe Custom Attributes',
  'generics/writing-your-own-static-abstract-interface-members': 'Writing Your Own Static Abstract Interface Members',
  'null-safety':          'Null Safety',
  'null-safety/enforcing-nullable-warnings-as-build-errors': 'Enforcing Nullable Warnings as Build Errors',
  'null-safety/nullable-reference-types-with-generic-type-parameters': 'Nullable Reference Types with Generic Type Parameters',
  'null-safety/required-properties-and-system-text-json-deserialization': 'required Properties and System.Text.Json Deserialization',
  'pattern-matching':     'Pattern Matching',
  'pattern-matching/testing-exhaustiveness-catching-new-subtypes-with-reflection-based-coverage-tests': 'Testing Exhaustiveness: Catching New Subtypes with Reflection-Based Coverage Tests',
  'pattern-matching/pattern-matching-in-ef-core-linq-queries-what-translates-to-sql-and-what-throws': 'Pattern Matching in EF Core LINQ Queries: What Translates to SQL and What Throws',
  'pattern-matching/how-the-compiler-lowers-property-patterns-repeated-access-and-performance': 'How the Compiler Lowers Property Patterns: Repeated Access and Performance',
  'extension-methods':    'Extension Methods',
  'extension-methods/testing-for-extension-method-shadowing': 'Testing for Extension Method Shadowing',
  'extension-methods/resolving-extension-method-ambiguity-cs0121': 'Resolving Extension Method Ambiguity',
  'extension-methods/extension-methods-on-structs-this-in-t-receiver': 'Extension Methods on Structs: this in T',
  'tuples':               'Tuples & Anonymous Types',
  'tuples/testing-tuple-returning-methods-deconstruction-assertions': 'Testing Tuple-Returning Methods',
  'tuples/valuetuple-8-element-limit-trest-chaining-mechanism': '8-Element Limit and TRest Chaining',
  'tuples/renaming-tuple-field-breaks-some-callers-not-others': 'Renaming a Tuple Field',
  'arrays':               'Arrays',
  'arrays/testing-array-equality-sequenceequal-not-equals': 'Testing Array Equality',
  'arrays/real-cost-of-array-covariance-runtime-type-check-every-store': 'The Real Cost of Array Covariance',
  'arrays/params-array-hidden-allocation-every-call-span-fix': 'params Arrays Silently Allocate',
  'collections':          'Collections',
  'collections/writing-custom-iequalitycomparer-and-icomparer-implementations': 'Writing Custom IEqualityComparer and IComparer Implementations',
  'collections/frozendictionary-and-frozenset-optimizing-for-read-heavy-lookups': 'FrozenDictionary and FrozenSet: Optimizing for Read-Heavy Lookups',
  'collections/testing-concurrent-collections-catching-race-conditions-in-getoradd': 'Testing Concurrent Collections: Catching Race Conditions',
  'linq':                 'LINQ',
  'linq/writing-custom-lazy-linq-operators-with-yield-return': 'Writing Custom Lazy LINQ Operators with yield return',
  'linq/expression-trees-why-ef-core-needs-expression-func-t-bool-not-func-t-bool': 'Expression Trees: Why EF Core Needs Expression<Func<T,bool>>',
  'linq/testing-linq-based-repository-methods-with-ef-core-in-memory': 'Testing LINQ-Based Repository Methods with EF Core In-Memory',
  'strings-datetime':     'Strings, DateTime & Math',
  'strings-datetime/testing-culture-sensitive-code-turkish-locale-ci-failures': 'Testing Culture-Sensitive Code',
  'strings-datetime/interning-boundary-which-strings-interned-automatically': 'The Interning Boundary',
  'strings-datetime/string-create-span-char-allocation-free-building': 'string.Create and Span<char>',
  'io-serialization':     'I/O & Serialization',
  'io-serialization/testing-file-io-without-touching-real-filesystem-abstraction': 'Testing File I/O',
  'io-serialization/where-jsonserializeroptions-cache-lives-cold-cache-per-instance': 'Where the JsonSerializerOptions Cache Lives',
  'io-serialization/sync-over-async-file-io-deadlocks-result-hangs-forever': 'Sync-over-Async File I/O Deadlocks',
  'gc-disposable':        'GC & IDisposable',
  'gc-disposable/testing-dispose-actually-called-spy-wrapper-double-dispose': 'Testing That Dispose() Was Called',
  'gc-disposable/pattern-based-disposal-ref-structs-cannot-implement-idisposable': 'Pattern-Based Disposal',
  'gc-disposable/disposed-but-still-running-event-handler-fire-and-forget-outlives-dispose': 'Disposed but Still Running',
  'threading':            'Threading',
  'threading/testing-race-conditions-stress-testing-concurrent-code': 'Testing for Race Conditions',
  'threading/old-lock-codegen-bug-monitor-enter-ref-bool-taken': 'The Old lock Codegen Bug',
  'threading/lazy-hidden-thread-safety-modes-concurrentdictionary-fix-not-free': 'Lazy Thread-Safety Modes',
  'tasks':                'Tasks & Parallel',
  'async':                'async / await',
  'async/testing-async-code-verifying-cancellation-and-task-failure-behavior': 'Testing Async Code: Verifying Cancellation and Task Failure Behavior',
  'async/iasyncdisposable-and-await-using-async-resource-cleanup': 'IAsyncDisposable and await using: Async Resource Cleanup',
  'async/producer-consumer-pipelines-with-system-threading-channels': 'Producer/Consumer Pipelines with System.Threading.Channels',
  'delegates':            'Delegates & Events',
  'delegates/testing-events-xunit-assert-raises-multicast-behavior': "Testing Events: xUnit's Assert.Raises and Multicast Behavior",
  'delegates/how-delegate-equality-actually-works-target-method-pairs': 'How Delegate Equality Actually Works: Target+Method Pairs',
  'delegates/async-void-event-handlers-why-exceptions-vanish': 'async void Event Handlers: Why Exceptions Vanish',
  'exceptions':           'Exceptions',
  'exceptions/testing-exception-filters-verifying-when-predicate-logic': 'Testing Exception Filters: Verifying "when" Predicate Logic',
  'exceptions/appdomain-unhandledexception-and-taskscheduler-unobservedtaskexception': 'AppDomain.UnhandledException and TaskScheduler.UnobservedTaskException',
  'exceptions/why-exceptions-are-slow-stack-walking-first-chance-exceptions': 'Why Exceptions Are Slow: Stack Walking, First-Chance Exceptions',
  'reflection':           'Reflection & Attributes',
  'iterators':            'Iterators & yield',
  'functional-csharp':   'Functional C# & Result Pattern',
  'regex':                'Regular Expressions',
  'channels':             'Channels & Producer/Consumer',
  'unit-testing':         'Unit Testing (xUnit & Moq)',
  'expression-trees':     'Expression Trees',
  'dynamic':              'dynamic & the DLR',
  'source-generators':    'Source Generators',
  'span-memory':          'Span<T> & Memory<T>',
  'di-dotnet':            'Dependency Injection in .NET',
  'json-advanced':        'System.Text.Json Advanced',
  'unsafe-pointers':      'Unsafe Code & Pointers',
  'native-aot':           'Native AOT',
  'benchmarkdotnet':      'BenchmarkDotNet',
  'pinvoke':              'P/Invoke & Native Interop',
  'dotnet-cli':           '.NET CLI & Tooling',
  'whats-new-9-10':       "What's New in C# 9 & 10",
  'whats-new-11-12':      "What's New in C# 11 & 12",
  'whats-new-latest':     "What's New in C# 13+",
  'cheatsheet':           'C# Cheat Sheet',
  'errors':               'Common C# Errors',
  'mini-projects':        'Mini Projects',
  'learning-paths':       'Learning Paths',
  'interview-prep':       'Interview Prep',
  'quiz-practice':        'Quiz Practice',
  'design-patterns':      'Design Patterns',
  'decision-guides':      'Decision Guides',
  'glossary':             'Glossary',
};

const ASPNET_LABELS: Record<string, string> = {
  'hosting-startup':       'Hosting & Startup',
  'middleware':            'Middleware Pipeline',
  'routing':               'Routing',
  'configuration':         'Configuration & Options',
  'dependency-injection':  'Dependency Injection',
  'logging':               'Logging & Diagnostics',
  'controllers':           'Controllers & Actions',
  'minimal-apis':          'Minimal APIs',
  'model-binding':         'Model Binding & Validation',
  'filters':               'Filters',
  'error-handling':        'Error Handling',
  'ef-core-basics':        'EF Core Basics',
  'ef-relationships':      'EF Relationships & Migrations',
  'caching':               'Caching',
  'authentication':        'Authentication',
  'authorization':         'Authorization',
  'cors':                  'CORS & Security Headers',
  'testing':               'Testing',
  'background-services':   'Background Services',
  'signalr':               'SignalR',
  'health-checks':         'Health Checks & Observability',
  'deployment':            'Deployment',
  'static-files':          'Static Files & Uploads',
  'openapi-swagger':       'OpenAPI & Swagger',
  'api-versioning':        'API Versioning',
  'http-clients':          'HttpClient & Resilience',
  'grpc':                  'gRPC Services',
  'rate-limiting':         'Rate Limiting',
  'aspire':                '.NET Aspire',
  'fluent-validation':     'FluentValidation',
  'minimal-api-advanced':  'Minimal API Advanced',
  'output-caching-advanced': 'Output Caching Advanced',
  'dapper':                'Dapper & Raw SQL',
  'csrf':                  'Anti-forgery & CSRF',
  'feature-flags':         'Feature Flags',
  'localization':          'Localization & Globalization',
  'masstransit':           'MassTransit',
  'response-compression':  'Response Compression',
  'websockets':            'WebSockets',
  'yarp':                  'YARP Reverse Proxy',
  'opentelemetry':         'OpenTelemetry',
  'ef-performance':        'EF Core Performance & Concurrency',
  'web-security':          'Web Security Essentials',
  'secrets':               'Secrets & Data Protection',
  'performance':           'Performance & Diagnostics',
  'cheatsheet':            'Cheat Sheet',
  'errors':               'Common Errors',
  'quiz-practice':         'Quiz Practice',
  'interview-prep':        'Interview Prep',
  'design-patterns':       'Design Patterns',
  'decision-guides':       'Decision Guides',
  'glossary':              'Glossary',
  'mini-projects':         'Mini Projects',
  'learning-paths':        'Learning Paths',
};

const SQL_LABELS: Record<string, string> = {
  'rdbms-concepts':    'RDBMS Concepts',
  'data-modeling':     'Data Modeling',
  'normalization':     'Normalization',
  'db-architecture':   'DB Architecture',
  'data-types':        'Data Types',
  'basics':            'SQL Basics',
  'joins':             'Joins',
  'aggregations':      'Aggregations',
  'subqueries':        'Subqueries',
  'ctes':              'CTEs',
  'window-functions':  'Window Functions',
  'indexes':           'Indexes',
  'transactions':      'Transactions',
  'schema-design':     'Schema Design',
  'stored-procedures': 'Stored Procedures',
  'performance':       'Performance',
  'json-features':             'JSON Features',
  'set-operations':            'Set Operations',
  'null-handling':             'NULL Handling',
  'merge':                     'MERGE / Upsert',
  'string-functions':          'String Functions',
  'date-functions':            'Date & Time Functions',
  'conditional-expressions':   'Conditional Expressions',
  'math-functions':            'Math & Numeric Functions',
  'pivoting':                  'Pivoting & Cross-Tab',
  'constraints':               'Constraints',
  'views':                     'Views',
  'sequences':                 'Sequences & Identity',
  'temp-tables':               'Temp Tables & Table Variables',
  'computed-columns':          'Computed & Generated Columns',
  'stored-functions':          'Stored Functions',
  'cursors':                   'Cursors & Row-by-Row Processing',
  'triggers':                  'Triggers',
  'dynamic-sql':               'Dynamic SQL',
  'isolation-levels':          'Isolation Levels',
  'locking':                   'Locking & Deadlocks',
  'execution-plans':           'Execution Plans',
  'partitioning':              'Partitioning',
  'bulk-operations':           'Bulk Operations',
  'query-store':               'Query Store',
  'statistics':                'Statistics & Optimizer',
  'full-text-search':          'Full-Text Search',
  'security':                  'SQL Security',
  'connection-pooling':        'Connection Pooling',
  'cheatsheet':                'Cheat Sheet',
  'errors':            'Common Errors',
  'quiz-practice':     'Quiz Practice',
  'interview-prep':    'Interview Prep',
  'design-patterns':   'Design Patterns',
  'decision-guides':   'Decision Guides',
  'glossary':          'Glossary',
  'mini-projects':     'Mini Projects',
  'learning-paths':    'Learning Paths',
};

const TYPESCRIPT_LABELS: Record<string, string> = {
  'basics':                   'TS Fundamentals',
  'primitive-types':          'Primitive & Literal Types',
  'interfaces-types':         'Interfaces & Type Aliases',
  'unions':                   'Union & Intersection Types',
  'narrowing':                'Type Guards & Narrowing',
  'enums-tuples':             'Enums & Tuples',
  'generics':                 'Generics Fundamentals',
  'generic-patterns':         'Generic Patterns',
  'utility-types':            'Utility Types',
  'mapped-types':             'Mapped Types',
  'conditional-types':        'Conditional Types',
  'template-literal-types':   'Template Literal Types',
  'classes':                  'Classes & Visibility',
  'decorators':               'Decorators',
  'tsconfig':                 'tsconfig Deep Dive',
  'modules':                  'Module System & Namespaces',
  'declarations':             'Declaration Files (d.ts)',
  'frameworks':               'TypeScript with Frameworks',
  'strict-migration':         'Strict Mode & Migration',
  'ts-performance':           'TypeScript Performance',
  'cheatsheet':               'Cheat Sheet',
  'interview-prep':           'Interview Prep',
};

const REACT_LABELS: Record<string, string> = {
  'basics':            'React Fundamentals',
  'hooks-core':        'Core Hooks',
  'hooks-advanced':    'Advanced Hooks',
  'forms':             'Forms & Validation',
  'router':            'React Router',
  'context':           'Context API',
  'state-management':  'State Management',
  'tanstack-query':    'TanStack Query',
  'performance':       'Performance',
  'patterns':          'React Patterns',
  'typescript':        'TypeScript & React',
  'testing':           'Testing React',
  'nextjs':            'Next.js App Router',
  'native':            'React Native',
  'hook-form':         'React Hook Form',
  'animations':        'Animations',
  'security':          'Security',
  'cheatsheet':        'Cheat Sheet',
  'interview-prep':    'Interview Prep',
};

const JAVASCRIPT_LABELS: Record<string, string> = {
  'fundamentals':   'JavaScript Fundamentals',
  'closures':       'Scope & Closures',
  'hoisting':       'Hoisting & TDZ',
  'symbols':        'Symbols & Iterators',
  'functions':      'Functions Deep Dive',
  'prototypes':     'Prototypes & Classes',
  'objects':        'Object Fundamentals',
  'destructuring':  'Destructuring & Spread',
  'arrays':         'Arrays & Iteration',
  'promises':       'Promises & Async/Await',
  'event-loop':     'Event Loop & Concurrency',
  'error-handling': 'Error Handling',
  'generators':     'Generators',
  'dom':            'DOM Manipulation',
  'events':         'Events & Custom Events',
  'browser-apis':   'Browser APIs',
  'modules':        'ES Modules',
  'bundlers':       'Bundlers & Build Tools',
  'patterns':       'Design Patterns in JS',
  'functional':     'Functional JS',
  'proxy':          'Proxy & Reflect API',
  'weakrefs':       'WeakMap, WeakSet & WeakRef',
  'cheatsheet':     'Cheat Sheet',
  'interview-prep': 'Interview Prep',
};

const HTML_LABELS: Record<string, string> = {
  'document-structure': 'Document Structure',
  'semantic-elements':  'Semantic Elements',
  'forms':              'Forms & Input',
  'media':              'Media Elements',
  'tables':             'Tables',
  'links-navigation':   'Links & Navigation',
  'accessibility':      'Accessibility & ARIA',
  'head-metadata':      'Head & Metadata',
  'custom-elements':    'Web Components',
  'iframes-embeds':     'iFrames & Embeds',
  'canvas-svg':         'Canvas & SVG',
  'performance':        'HTML Performance',
  'pwa-service-workers': 'PWA & Service Workers',
  'seo':                 'HTML SEO',
  'apis':                'HTML5 Browser APIs',
  'fundamentals':         'HTML Fundamentals',
  'headings-paragraphs':  'Headings & Paragraphs',
  'input-types':          'Input Types & Attributes',
  'landmark-elements':    'Landmark Elements',
  'aria-roles':           'ARIA Roles & Attributes',
  'focus-management':     'Focus Management',
  'storage-apis':         'HTML5 Storage APIs',
  'drag-drop':            'Drag & Drop API',
  'cheatsheet':          'HTML Cheat Sheet',
  'interview-prep':      'HTML Interview Prep',
};

const CSS_LABELS: Record<string, string> = {
  'box-model':         'Box Model',
  'flexbox':           'Flexbox',
  'grid':              'CSS Grid',
  'positioning':       'Positioning & Stacking',
  'custom-properties': 'CSS Custom Properties',
  'selectors':         'Selectors Deep Dive',
  'typography':        'Typography',
  'responsive':        'Responsive Design',
  'animations':        'CSS Animations',
  'transitions':       'CSS Transitions',
  'colors-theming':        'Colors & Theming',
  'backgrounds-borders':   'Backgrounds & Borders',
  'container-queries':     'Container Queries',
  'css-layers':            'CSS Cascade Layers',
  'css-nesting':           'CSS Nesting',
  'logical-properties':    'Logical Properties',
  'css-architecture':      'CSS Architecture',
  'tailwind':                    'Tailwind CSS',
  'scroll-driven-animations':   'Scroll-Driven Animations',
  'css-transforms':             'CSS Transforms',
  'css-filters':               'CSS Filters & Effects',
  'fundamentals':              'CSS Fundamentals',
  'cheatsheet':               'CSS Cheat Sheet',
  'interview-prep':           'CSS Interview Prep',
};

const PERFORMANCE_LABELS: Record<string, string> = {
  'core-web-vitals':        'Core Web Vitals',
  'lcp':                    'Largest Contentful Paint',
  'inp':                    'Interaction to Next Paint',
  'cls':                    'Cumulative Layout Shift',
  'critical-rendering-path': 'Critical Rendering Path',
  'browser-rendering':      'Browser Rendering Pipeline',
  'resource-hints':         'Resource Hints',
  'http2-http3':            'HTTP/2 & HTTP/3',
  'caching':                'Caching & Service Workers',
  'image-optimisation':     'Image Optimisation',
  'font-performance':       'Font Performance',
  'js-performance':         'JavaScript Performance',
  'third-party-scripts':    'Third-Party Scripts',
  'measurement':            'Performance Measurement',
  'rum':                    'Real User Monitoring (RUM)',
  'ssr-streaming':          'SSR & Streaming HTML',
  'css-performance':        'CSS Performance',
  'web-workers':            'Web Workers & Off-Main-Thread',
  'performance-budgets':    'Performance Budgets & CI',
  'speculation-rules':      'Speculation Rules API',
  'cheatsheet':             'Web Performance Cheat Sheet',
  'interview-prep':         'Performance Interview Prep',
};

const BLAZOR_LABELS: Record<string, string> = {
  'fundamentals':            'Blazor Fundamentals',
  'render-modes':            'Render Modes',
  'razor-components':        'Razor Components',
  'component-communication': 'Component Communication',
  'forms':                   'Blazor Forms',
  'data-binding':            'Data Binding',
  'routing':                 'Blazor Routing',
  'dependency-injection':    'Dependency Injection',
  'state-management':        'State Management',
  'js-interop':              'JavaScript Interop',
  'server-signalr':          'Blazor Server & SignalR',
  'maui-hybrid':             'MAUI Blazor Hybrid',
  'authentication':          'Authentication in Blazor',
  'error-handling':          'Error Handling & ErrorBoundary',
  'streaming-rendering':     'Streaming Rendering',
  'sections-layouts':        'Sections & Layouts',
  'seo-metadata':            'SEO & Head Metadata',
  'virtualization':          'Component Virtualization',
  'progressive-enhancement': 'Progressive Enhancement',
  'performance':             'Blazor Performance',
  'bunit':                   'Testing with bUnit',
  'cheatsheet':              'Blazor Cheat Sheet',
  'interview-prep':          'Blazor Interview Prep',
};

const PYTHON_LABELS: Record<string, string> = {
  'fundamentals':              'Python Fundamentals',
  'functions-closures':        'Functions & Closures',
  'comprehensions-generators': 'Comprehensions & Generators',
  'file-io':                   'File I/O & Pathlib',
  'oop':                       'OOP in Python',
  'dataclasses-pydantic':      'Dataclasses & Pydantic',
  'decorators-context-managers': 'Decorators & Context Managers',
  'type-hints':                'Type Hints & mypy',
  'collections-itertools':     'Collections & Itertools',
  'asyncio':                   'Async Python (asyncio)',
  'threading-multiprocessing': 'Threading & Multiprocessing',
  'concurrency-patterns':      'Python Concurrency Patterns',
  'fastapi':                   'FastAPI',
  'django':                    'Django',
  'sqlalchemy':                'SQLAlchemy',
  'celery':                    'Celery & Task Queues',
  'numpy-pandas':              'NumPy & Pandas',
  'scikit-learn':              'Machine Learning (scikit-learn)',
  'pytest':                    'Testing with pytest',
  'packaging':                 'Python Packaging & venv',
  'debugging-profiling':       'Debugging & Profiling',
  'cheatsheet':                'Python Cheat Sheet',
  'interview-prep':            'Python Interview Prep',
};

const GO_LABELS: Record<string, string> = {
  'fundamentals':       'Go Fundamentals',
  'structs-interfaces': 'Structs & Interfaces',
  'error-handling':     'Error Handling',
  'slices-maps':        'Slices & Maps',
  'goroutines':         'Goroutines',
  'channels':           'Channels',
  'sync':               'sync & sync/atomic',
  'context':            'context Package',
  'net-http':           'net/http & REST APIs',
  'gin':                'Gin Web Framework',
  'json-encoding':      'JSON & Encoding',
  'grpc':               'gRPC in Go',
  'pgx':                'Database with pgx',
  'gorm':               'GORM',
  'generics':           'Go Generics',
  'patterns':           'Go Patterns',
  'modules':            'Go Modules',
  'testing':            'Testing in Go',
  'cli':                'Go CLI Tools',
  'profiling':          'Go Performance & Profiling',
  'build':              'Go Build & Deployment',
  'cheatsheet':         'Go Cheat Sheet',
  'interview-prep':     'Go Interview Prep',
};

const AWS_LABELS: Record<string, string> = {
  'fundamentals':       'AWS Fundamentals',
  'ec2':                'EC2 & Auto Scaling',
  'ecs-eks':            'ECS & EKS',
  'vpc':                'VPC & Networking',
  'route53-cloudfront': 'Route 53 & CloudFront',
  's3':                 'S3',
  'ebs-efs':            'EBS, EFS & FSx',
  'iam':                'IAM',
  'iam-roles':          'IAM Roles & Federation',
  'rds-aurora':         'RDS & Aurora',
  'dynamodb':           'DynamoDB',
  'lambda':             'Lambda',
  'api-gateway':        'API Gateway',
  'cloudwatch':         'CloudWatch & X-Ray',
  'cloudformation-cdk': 'CloudFormation & CDK',
  'security':           'AWS Security Services',
  'sqs-sns':            'SQS & SNS',
  'eventbridge':        'EventBridge',
  'step-functions':     'AWS Step Functions',
  'load-balancing':     'Elastic Load Balancing',
  'cost-optimization':  'AWS Cost Optimization',
  'cheatsheet':         'AWS Cheat Sheet',
};

const AZURE_LABELS: Record<string, string> = {
  'fundamentals':       'Azure Fundamentals',
  'arm':                'Azure Resource Manager',
  'virtual-machines':   'Virtual Machines',
  'app-service':        'App Service',
  'functions':          'Azure Functions',
  'aks':                'Azure Kubernetes Service',
  'virtual-network':    'Virtual Network',
  'load-balancer':      'Load Balancer & Front Door',
  'storage':            'Blob & Storage',
  'entra-id':           'Entra ID (AAD)',
  'rbac':               'Azure RBAC',
  'sql-cosmos':         'SQL & Cosmos DB',
  'monitor':            'Monitor & App Insights',
  'devops-pipelines':   'DevOps & Pipelines',
  'cost-management':    'Cost Management',
  'security-defender':  'Security Center & Defender',
  'key-vault':          'Key Vault',
  'service-bus':        'Service Bus',
  'container-apps':     'Container Apps',
  'redis':              'Cache for Redis',
  'api-management':     'API Management',
  'bicep':              'Azure Bicep Deep-dive',
  'cheatsheet':         'Azure Cheat Sheet',
};

const CONTAINERS_LABELS: Record<string, string> = {
  'fundamentals':       'Container Fundamentals',
  'docker-cli':         'Docker CLI',
  'docker-images':      'Docker Images & Registry',
  'dockerfile':         'Writing Dockerfiles',
  'multi-stage':        'Multi-Stage Builds',
  'compose':            'Docker Compose',
  'compose-profiles':   'Compose Profiles & Overrides',
  'k8s-architecture':   'Kubernetes Architecture',
  'kubectl':            'kubectl Fundamentals',
  'pods-deployments':   'Pods, Deployments & ReplicaSets',
  'services-ingress':   'Services & Ingress',
  'configmaps-secrets': 'ConfigMaps & Secrets',
  'storage':            'Persistent Volumes & Storage',
  'operators-crds':     'Kubernetes Operators & CRDs',
  'helm':               'Helm',
  'container-security': 'Container Security',
  'rbac':               'Kubernetes RBAC',
  'statefulsets':       'StatefulSets & DaemonSets',
  'resource-limits':    'Resource Requests & Limits',
  'hpa':                'Horizontal Pod Autoscaler',
  'network-policies':   'Network Policies',
  'troubleshooting':    'Kubernetes Troubleshooting',
  'cheatsheet':         'Containers Cheat Sheet',
};

const DEVOPS_LABELS: Record<string, string> = {
  'culture':               'DevOps Culture & Principles',
  'sdlc-agile':            'SDLC & Agile',
  'environment-strategy':  'Environment Strategy',
  'platform-engineering':  'Platform Engineering',
  'git-workflows':         'Git Workflows',
  'github-actions':        'GitHub Actions',
  'azure-pipelines':       'Azure DevOps Pipelines',
  'jenkins':               'Jenkins',
  'continuous-integration':'Continuous Integration',
  'continuous-delivery':   'Continuous Delivery & Deployment',
  'gitops':                'GitOps with ArgoCD & Flux',
  'artifact-management':   'Artifact Management',
  'docker-cicd':           'Docker in CI/CD',
  'kubernetes-deployments':'Kubernetes Deployments',
  'iac':                   'Infrastructure as Code',
  'monitoring':            'Monitoring & Alerting',
  'logging':               'Logging Pipelines',
  'incident-response':     'On-call & Incident Response',
  'devsecops':             'DevSecOps',
  'release-management':    'Release Management',
  'sre':                   'SRE Practices',
  'cheatsheet':            'DevOps Cheat Sheet',
};

const NODE_LABELS: Record<string, string> = {
  'architecture':    'Node.js Architecture',
  'modules':         'Modules & CommonJS',
  'core-modules':    'Core Modules',
  'env-config':      'Env Config & dotenv',
  'express':         'Express.js',
  'fastify':         'Fastify',
  'rest-api':        'REST API Design',
  'websockets':      'WebSockets & Socket.io',
  'graphql':         'GraphQL API',
  'nestjs':          'NestJS',
  'promises-async':  'Promises & Async/Await',
  'streams':         'Streams & Buffers',
  'error-handling':  'Error Handling',
  'prisma':          'Database with Prisma',
  'mongoose':        'MongoDB with Mongoose',
  'caching':         'Caching with Redis',
  'jwt-auth':        'Auth with JWT & Passport',
  'security':        'Security Best Practices',
  'performance':     'Node.js Performance',
  'logging':         'Logging with Pino/Winston',
  'worker-threads':  'Worker Threads',
  'testing':         'Testing Node.js Apps',
  'deployment':      'Deploying Node.js Apps',
  'cheatsheet':      'Node.js Cheat Sheet',
  'interview-prep':  'Node.js Interview Prep',
};

const TERRAFORM_LABELS: Record<string, string> = {
  'fundamentals':      'Terraform Fundamentals',
  'providers':         'Providers',
  'variables':         'Variables',
  'outputs':           'Outputs',
  'resources':         'Resources & Meta-Arguments',
  'data-sources':      'Data Sources',
  'expressions':       'Expressions & Dynamic Blocks',
  'functions':         'Built-in Functions',
  'state':             'Terraform State',
  'remote-backends':   'Remote Backends',
  'workspaces':        'Workspaces',
  'modules':           'Modules',
  'module-patterns':   'Module Patterns',
  'provisioners':      'Provisioners',
  'import':            'Import & Generated Config',
  'cicd':              'CI/CD with Terraform',
  'testing':           'Testing Terraform Code',
  'security':          'Security & Compliance',
  'drift':             'Drift Detection',
  'refactoring':       'Refactoring & State Ops',
  'opentofu':          'OpenTofu',
  'cheatsheet':        'Terraform Cheatsheet',
  'interview-prep':    'Terraform Interview Prep',
};

const LINUX_LABELS: Record<string, string> = {
  'fundamentals':          'Linux Fundamentals',
  'file-system':           'File System & Hierarchy',
  'essential-commands':    'Essential Commands',
  'file-permissions':      'File Permissions & Ownership',
  'users-groups':          'Users & Groups',
  'process-management':    'Process Management',
  'system-monitoring':     'System Monitoring',
  'networking':            'Networking Commands',
  'firewall':              'Firewall & iptables',
  'ssh':                   'SSH & Remote Access',
  'bash-scripting':        'Bash Scripting Basics',
  'bash-advanced':         'Advanced Bash Scripting',
  'package-management':    'Package Management',
  'systemd':               'systemd & Services',
  'disk-storage':          'Disk & Storage',
  'environment-variables': 'Environment Variables & Shell Config',
  'log-analysis':          'Log Analysis',
  'performance-tuning':    'Performance Tuning',
  'vim':                   'Vim & Text Editors',
  'security-hardening':    'Linux Security Hardening',
  'cron':                  'Cron & Scheduling',
};

const MESH_LABELS: Record<string, string> = {
  'fundamentals':       'Service Mesh Fundamentals',
  'istio-architecture': 'Istio Architecture',
  'istio-install':      'Istio Installation & Configuration',
  'linkerd':            'Linkerd',
  'traffic-management': 'Traffic Management',
  'resilience':         'Retries, Timeouts & Circuit Breaking',
  'load-balancing':     'Load Balancing Algorithms',
  'mtls':               'mTLS & Service Identity',
  'authorization':      'Authorization Policies',
  'metrics':            'Metrics & Telemetry',
  'tracing':            'Distributed Tracing',
  'kiali':              'Kiali & Dashboards',
  'gateway-api':        'Kubernetes Gateway API',
  'ingress-gateway':    'Ingress Gateway',
  'performance':        'Service Mesh Performance',
  'envoy':              'Envoy Proxy Deep Dive',
  'ambient-mesh':       'Ambient Mesh',
  'multi-cluster':      'Multi-cluster Mesh',
  'consul':             'Consul Connect',
  'cheatsheet':         'Service Mesh Cheat Sheet',
  'interview-prep':     'Service Mesh Interview Prep',
};

const ARCH_LABELS: Record<string, string> = {
  'monolith-vs-modular':       'Monolith vs Modular Monolith',
  'layered-architecture':      'Layered Architecture',
  'clean-architecture':        'Clean / Onion Architecture',
  'hexagonal-architecture':    'Hexagonal Architecture',
  'vertical-slice':            'Vertical Slice Architecture',
  'service-oriented':          'Service-Oriented Architecture',
  'microservices-principles':  'Microservices Principles',
  'service-communication':     'Service Communication',
  'api-gateway-pattern':       'API Gateway Pattern',
  'service-discovery':         'Service Discovery',
  'circuit-breaker':           'Circuit Breaker',
  'sidecar-service-mesh':      'Sidecar & Service Mesh',
  'event-driven':              'Event-Driven Architecture',
  'cqrs-event-sourcing':       'CQRS & Event Sourcing',
  'saga-choreography':         'Saga & Choreography',
  'inbox-outbox':              'Inbox & Outbox Pattern',
  'ddd-core':                  'Domain-Driven Design Core',
  'bounded-contexts':          'Bounded Contexts',
  'aggregates-domain-events':  'Aggregates & Domain Events',
  'anti-corruption-layer':     'Anti-Corruption Layer',
  'strangler-fig':             'Strangler Fig Pattern',
  'backend-for-frontend':      'Backend for Frontend (BFF)',
  'adr':                       'Architecture Decision Records',
  'pattern-comparison':        'Pattern Comparison Guide',
  'interview-prep':            'Architecture Interview Prep',
};

const DP_LABELS: Record<string, string> = {
  'singleton':               'Singleton',
  'factory-method':          'Factory Method',
  'abstract-factory':        'Abstract Factory',
  'builder':                 'Builder',
  'prototype':               'Prototype',
  'object-pool':             'Object Pool',
  'adapter':                 'Adapter',
  'bridge':                  'Bridge',
  'composite':               'Composite',
  'decorator':               'Decorator',
  'facade':                  'Facade',
  'flyweight':               'Flyweight',
  'proxy':                   'Proxy',
  'chain-of-responsibility': 'Chain of Responsibility',
  'command':                 'Command',
  'iterator':                'Iterator',
  'mediator':                'Mediator',
  'memento':                 'Memento',
  'observer':                'Observer',
  'state':                   'State',
  'strategy':                'Strategy',
  'template-method':         'Template Method',
  'visitor':                 'Visitor',
  'null-object':             'Null Object',
  'repository':              'Repository',
  'unit-of-work':            'Unit of Work',
  'cqrs':                    'CQRS Pattern',
  'event-sourcing':          'Event Sourcing',
  'saga':                    'Saga Pattern',
  'outbox':                  'Outbox Pattern',
  'specification':           'Specification Pattern',
  'clean-architecture':      'Clean Architecture Pattern',
  'solid':                   'SOLID Principles',
  'grasp':                   'GRASP Principles',
  'dry-kiss-yagni':          'DRY, KISS & YAGNI',
  'dependency-inversion':    'Dependency Inversion',
  'cheatsheet':              'Design Patterns Cheat Sheet',
  'interview-prep':          'Design Patterns Interview Prep',
  'pattern-decision':        'Pattern Decision Guide',
};

const API_DESIGN_LABELS: Record<string, string> = {
  'rest-fundamentals':       'REST Fundamentals',
  'resource-url-design':     'Resource & URL Design',
  'http-methods-status-codes': 'HTTP Methods & Status Codes',
  'pagination-patterns':     'Pagination Patterns',
  'api-versioning':          'API Versioning',
  'error-response-design':   'Error Response Design',
  'hateoas-hypermedia':      'HATEOAS & Hypermedia',
  'protocol-buffers':        'Protocol Buffers',
  'grpc-service-patterns':   'gRPC Service Patterns',
  'grpc-web-transcoding':    'gRPC-Web & Transcoding',
  'graphql-fundamentals':    'GraphQL Fundamentals',
  'graphql-vs-rest':         'GraphQL vs REST',
  'websockets-sse-polling':  'WebSockets vs SSE vs Polling',
  'webhook-design':          'Webhook Design',
  'api-design-principles':   'API Design Principles',
  'openapi-contracts':       'OpenAPI & Contracts',
  'api-security':            'API Security',
  'breaking-changes':        'Breaking Changes',
  'rate-limiting':           'Rate Limiting',
  'cheatsheet':              'API Design Cheat Sheet',
  'interview-prep':          'API Design Interview Prep',
};

const SECURITY_LABELS: Record<string, string> = {
  'fundamentals':            'Security Fundamentals',
  'owasp-top-10':            'OWASP Top 10',
  'threat-modelling':        'Threat Modelling',
  'secure-coding':           'Secure Coding',
  'password-security':       'Password Security',
  'oauth-oidc':              'OAuth 2.0 & OIDC',
  'jwt':                     'JSON Web Tokens',
  'mfa':                     'Multi-Factor Authentication',
  'sso':                     'Single Sign-On',
  'rbac-abac':               'RBAC & ABAC',
  'claims-identity':         'Claims & Identity',
  'api-security':            'API Security',
  'xss':                     'Cross-Site Scripting (XSS)',
  'csrf-clickjacking':       'CSRF & Clickjacking',
  'injection':               'Injection Attacks',
  'security-headers':        'Security Headers',
  'tls-https':               'TLS & HTTPS',
  'secrets-management':      'Secrets Management',
  'container-security':      'Container Security',
  'symmetric-encryption':    'Symmetric Encryption',
  'asymmetric-cryptography': 'Asymmetric Cryptography',
  'hashing':                 'Hashing & MACs',
  'supply-chain':            'Supply Chain Security',
  'cheatsheet':              'Security Cheat Sheet',
  'interview-prep':          'Security Interview Prep',
};

const OBS_LABELS: Record<string, string> = {
  'observability-fundamentals': 'Observability Fundamentals',
  'opentelemetry':              'OpenTelemetry',
  'sli-slo-sla':                'SLIs, SLOs & SLAs',
  'prometheus-metrics':         'Prometheus & Metrics',
  'grafana-dashboards':         'Grafana Dashboards',
  'custom-app-metrics':         'Custom App Metrics',
  'infrastructure-metrics':     'Infrastructure Metrics',
  'cloud-native-monitoring':    'Cloud-Native Monitoring',
  'structured-logging':         'Structured Logging',
  'log-aggregation':            'Log Aggregation',
  'log-best-practices':         'Log Best Practices',
  'distributed-tracing':        'Distributed Tracing',
  'opentelemetry-tracing':      'OTel Tracing Deep Dive',
  'performance-profiling':      'Performance Profiling',
  'alerting-design':            'Alerting Design',
  'on-call-incidents':          'On-Call & Incidents',
  'error-budgets-toil':         'Error Budgets & Toil',
  'chaos-engineering':          'Chaos Engineering',
  'ebpf-observability':         'eBPF Observability',
  'observability-maturity':     'Observability Maturity',
  'cheatsheet':                 'Observability Cheatsheet',
  'interview-prep':             'Observability Interview Prep',
};

const MONGO_LABELS: Record<string, string> = {
  'fundamentals':            'MongoDB Fundamentals',
  'installation-setup':      'Installation & Setup',
  'crud-operations':         'CRUD Operations',
  'update-operators':        'Update Operators',
  'query-operators':         'Query Operators',
  'array-queries':           'Array Queries',
  'projections-sorting':     'Projections & Sorting',
  'aggregation-pipeline':    'Aggregation Pipeline',
  'lookup-joins':            '$lookup & Joins',
  'aggregation-expressions': 'Aggregation Expressions',
  'schema-design-patterns':  'Schema Design Patterns',
  'data-modelling':          'Data Modelling',
  'time-series':             'Time Series Collections',
  'indexes':                 'Indexes',
  'query-performance':       'Query Performance',
  'transactions':            'Transactions',
  'change-streams':          'Change Streams',
  'replication-sharding':    'Replication & Sharding',
  'security':                'Security & Authentication',
  'mongodb-nodejs':          'MongoDB with Node.js',
  'atlas-search':            'Atlas Search & Vector Search',
  'cheatsheet':              'MongoDB Cheat Sheet',
  'interview-prep':          'MongoDB Interview Prep',
};

const REDIS_LABELS: Record<string, string> = {
  'fundamentals':          'Redis Fundamentals',
  'installation-setup':    'Installation & CLI',
  'strings':               'Strings',
  'hashes':                'Hashes',
  'lists':                 'Lists',
  'sets':                  'Sets',
  'sorted-sets':           'Sorted Sets',
  'key-commands':          'Key Commands & Patterns',
  'transactions':          'Transactions (MULTI/EXEC)',
  'lua-scripting':         'Lua Scripting',
  'persistence':           'Persistence: RDB & AOF',
  'pub-sub':               'Pub/Sub Messaging',
  'streams':               'Redis Streams',
  'caching-patterns':      'Caching Patterns',
  'eviction-policies':     'Eviction Policies',
  'rate-limiting':         'Rate Limiting',
  'replication-sentinel':  'Replication & Sentinel',
  'redis-cluster':         'Redis Cluster',
  'redis-stack':           'Redis Stack & Modules',
  'redis-nodejs':          'Redis with Node.js',
  'security':              'Redis Security',
  'cheatsheet':            'Redis Cheat Sheet',
  'interview-prep':        'Redis Interview Prep',
};

const GQL_LABELS: Record<string, string> = {
  'fundamentals':               'GraphQL Fundamentals',
  'schema-definition-language': 'Schema Definition Language',
  'type-system':                'Type System Deep Dive',
  'queries':                    'Queries',
  'variables-arguments':        'Variables & Arguments',
  'directives':                 'Directives',
  'mutations':                  'Mutations',
  'error-handling':             'Mutation Error Handling',
  'subscriptions':              'Subscriptions',
  'resolvers':                  'Resolvers',
  'dataloader':                 'DataLoader & N+1 Problem',
  'auth':                       'Authentication & Authorization',
  'apollo-server':              'Apollo Server',
  'pagination':                 'Pagination Patterns',
  'apollo-client':              'Apollo Client',
  'client-caching':             'Client Caching',
  'code-generation':            'Code Generation',
  'performance':                'Performance & Best Practices',
  'federation':                 'Schema Stitching & Federation',
  'testing':                    'Testing GraphQL APIs',
  'cheatsheet':                 'GraphQL Cheat Sheet',
  'interview-prep':             'GraphQL Interview Prep',
};

const MESSAGING_LABELS: Record<string, string> = {
  'messaging-fundamentals':    'Messaging Fundamentals',
  'message-queues-vs-streams': 'Queues vs Event Streams',
  'rabbitmq-core':             'RabbitMQ Core Concepts',
  'rabbitmq-exchanges':        'RabbitMQ Exchanges',
  'rabbitmq-patterns':         'RabbitMQ Patterns',
  'kafka-architecture':        'Kafka Architecture',
  'kafka-producers-consumers': 'Producers & Consumers',
  'kafka-streams':             'Kafka Streams & KSQL',
  'kafka-connect':             'Kafka Connect',
  'schema-registry':           'Schema Registry',
  'messaging-patterns':        'Enterprise Messaging Patterns',
  'saga-pattern':              'Saga Pattern',
  'outbox-pattern':            'Outbox Pattern',
  'azure-service-bus':         'Azure Service Bus',
  'azure-event-grid':          'Event Grid & Event Hubs',
  'aws-sqs':                   'AWS SQS',
  'aws-sns-eventbridge':       'AWS SNS & EventBridge',
  'idempotency':               'Idempotency & Exactly-Once',
  'message-ordering':          'Message Ordering',
  'backpressure':              'Backpressure & Flow Control',
  'monitoring':                'Monitoring Messaging Systems',
  'messaging-security':        'Messaging Security',
};

const DSA_LABELS: Record<string, string> = {
  'big-o':                  'Big-O Notation',
  'arrays':                 'Arrays',
  'strings':                'Strings',
  'hash-tables':            'Hash Tables',
  'stacks-queues':          'Stacks & Queues',
  'linked-lists':           'Singly Linked Lists',
  'doubly-linked-lists':    'Doubly Linked Lists',
  'binary-trees':           'Binary Trees',
  'bst':                    'Binary Search Trees',
  'heaps':                  'Heaps & Priority Queues',
  'graphs-bfs-dfs':         'Graphs — BFS & DFS',
  'graph-algorithms':       'Graph Algorithms',
  'basic-sorts':            'Basic Sorts',
  'advanced-sorts':         'Merge Sort & Quick Sort',
  'binary-search':          'Binary Search',
  'recursion-backtracking': 'Recursion & Backtracking',
  'dynamic-programming':    'Dynamic Programming',
  'dp-patterns':            'DP Patterns',
  'trie':                   'Trie',
  'bit-manipulation':       'Bit Manipulation',
  'greedy':                 'Greedy Algorithms',
};

const AI_LABELS: Record<string, string> = {
  'ml-fundamentals':             'AI & ML Fundamentals',
  'math-for-ml':                 'Mathematics for ML',
  'linear-logistic-regression':  'Linear & Logistic Regression',
  'decision-trees':              'Decision Trees & Random Forests',
  'gradient-boosting':           'Gradient Boosting (XGBoost)',
  'clustering':                  'Clustering & Dimensionality Reduction',
  'neural-networks':             'Neural Networks',
  'computer-vision':             'CNNs & Computer Vision',
  'transformers':                'Transformers & Attention',
  'llm-fundamentals':            'LLM Fundamentals',
  'fine-tuning':                 'Fine-tuning & RLHF',
  'rag':                         'RAG',
  'prompt-engineering':          'Prompt Engineering',
  'ai-agents':                   'AI Agents & Tool Use',
  'vector-databases':            'Vector Databases',
  'mlops':                       'MLOps & Model Deployment',
  'hugging-face':                'Hugging Face & Model Hub',
  'evaluating-llms':             'Evaluating LLM Outputs',
  'ai-engineering':              'AI Engineering Patterns',
  'interview-prep':              'AI Interview Prep',
  'responsible-ai':              'Responsible AI & Ethics',
  'ai-dotnet':                   'AI with .NET & C#',
};

const TESTING_LABELS: Record<string, string> = {
  'testing-fundamentals':    'Testing Fundamentals',
  'jest-fundamentals':       'Jest Fundamentals',
  'mocking-spies':           'Mocking & Spies',
  'xunit':                   'xUnit (.NET Testing)',
  'tdd':                     'Test-Driven Development',
  'test-doubles':            'Test Doubles',
  'integration-testing':     'Integration Testing',
  'testing-databases':       'Testing with Databases',
  'angular-testing':         'Angular Testing',
  'react-testing-library':   'React Testing Library',
  'playwright':              'Playwright',
  'cypress':                 'Cypress',
  'api-testing':             'API Testing',
  'contract-testing':        'Contract Testing (Pact)',
  'snapshot-testing':        'Snapshot Testing',
  'vitest':                  'Vitest',
  'msw':                     'MSW — Mock Service Worker',
  'visual-regression':       'Visual Regression Testing',
  'property-based-testing':  'Property-Based Testing',
  'cheatsheet':              'Testing Cheat Sheet',
  'performance-testing':     'Performance & Load Testing',
  'mutation-testing':        'Mutation Testing',
};

const SYSDESIGN_LABELS: Record<string, string> = {
  'framework':                'System Design Framework',
  'capacity-estimation':      'Capacity Estimation',
  'cap-theorem':              'CAP & PACELC Theorems',
  'networking':               'Networking Fundamentals',
  'scaling':                  'Horizontal vs Vertical Scaling',
  'load-balancing':           'Load Balancing',
  'caching':                  'Caching Strategies',
  'cdn':                      'Content Delivery Networks',
  'sharding':                 'Database Sharding',
  'sql-vs-nosql':             'SQL vs NoSQL',
  'replication':              'Replication Strategies',
  'indexes':                  'Indexes & Query Optimisation',
  'distributed-transactions': 'Distributed Transactions',
  'high-availability':        'High Availability Design',
  'fault-tolerance':          'Fault Tolerance Patterns',
  'distributed-tracing':      'Distributed Tracing',
  'disaster-recovery':        'Disaster Recovery',
  'url-shortener':            'Design a URL Shortener',
  'social-feed':              'Design a Social Feed',
  'chat-application':         'Design a Chat Application',
  'search-engine':            'Design a Search Engine',
  'payment-system':           'Design a Payment System',
  'video-streaming':          'Design Netflix / YouTube',
  'ai-ml-system-design':      'AI/ML System Design',
  'cheatsheet':               'System Design Cheat Sheet',
  'interview-prep':           'System Design Interview Guide',
};

const TECH_SECTIONS: Record<string, { label: string; path: string }> = {
  'angular':         { label: 'Angular',               path: '/angular'         },
  'csharp':          { label: 'C#',                    path: '/csharp'          },
  'aspnet':          { label: 'ASP.NET Core',           path: '/aspnet'          },
  'sql':             { label: 'SQL',                   path: '/sql'             },
  'html':            { label: 'HTML',                  path: '/html'            },
  'css':             { label: 'CSS',                   path: '/css'             },
  'javascript':      { label: 'JavaScript',            path: '/javascript'      },
  'typescript':      { label: 'TypeScript',            path: '/typescript'      },
  'react':           { label: 'React',                 path: '/react'           },
  'blazor':          { label: 'Blazor',                path: '/blazor'          },
  'performance':     { label: 'Web Performance',       path: '/performance'     },
  'node':            { label: 'Node.js',               path: '/node'            },
  'python':          { label: 'Python',                path: '/python'          },
  'go':              { label: 'Go',                    path: '/go'              },
  'mongodb':         { label: 'MongoDB / NoSQL',       path: '/mongodb'         },
  'redis':           { label: 'Redis',                 path: '/redis'           },
  'graphql':         { label: 'GraphQL',               path: '/graphql'         },
  'messaging':       { label: 'Messaging & Events',    path: '/messaging'       },
  'design-patterns': { label: 'Design Patterns',       path: '/design-patterns' },
  'arch-patterns':   { label: 'Architecture Patterns', path: '/arch-patterns'   },
  'api-design':      { label: 'API Design',            path: '/api-design'      },
  'system-design':   { label: 'System Design',         path: '/system-design'   },
  'security':        { label: 'Security & Auth',       path: '/security'        },
  'observability':   { label: 'Observability & SRE',   path: '/observability'   },
  'devops':          { label: 'Git & DevOps',          path: '/devops'          },
  'linux':           { label: 'Linux & Bash',          path: '/linux'           },
  'containers':      { label: 'Docker & Kubernetes',   path: '/containers'      },
  'terraform':       { label: 'Terraform / IaC',       path: '/terraform'       },
  'azure':           { label: 'Azure',                 path: '/azure'           },
  'aws':             { label: 'AWS',                   path: '/aws'             },
  'service-mesh':    { label: 'Service Mesh & Istio',  path: '/service-mesh'    },
  'dsa':             { label: 'DSA',                   path: '/dsa'             },
  'testing-hub':     { label: 'Testing',               path: '/testing-hub'     },
  'ai':              { label: 'AI & LLMs',             path: '/ai'              },
};

@Component({
  selector: 'app-breadcrumb',
  standalone: true,
  imports: [RouterLink],
  template: `
    @if (segments().length > 0) {
      <nav class="breadcrumb" aria-label="breadcrumb">
        <a routerLink="/" class="bc-home" title="Home">
          <svg width="14" height="14" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h4a1 1 0 001-1v-3h2v3a1 1 0 001 1h4a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"/>
          </svg>
        </a>
        @if (techSection()) {
          <span class="bc-sep">›</span>
          @if (segments().length > 1) {
            <a [routerLink]="techSection()!.path" class="bc-section-link">{{ techSection()!.label }}</a>
          } @else {
            <span class="bc-current">{{ techSection()!.label }}</span>
          }
        }
        @if (segments().length > 2) {
          <span class="bc-sep">›</span>
          <a [routerLink]="parentTopicRoute()" class="bc-section-link">{{ parentTopicLabel() }}</a>
        }
        @if (segments().length > 1) {
          <span class="bc-sep">›</span>
          <span class="bc-current">{{ pageLabel() }}</span>
        }
      </nav>
    }`,
  styles: [`
    .breadcrumb {
      display: flex;
      align-items: center;
      gap: .3rem;
      padding: .7rem 1.25rem .3rem;
      font-size: .82rem;
      color: #9ca3af;
    }
    .bc-home {
      display: flex;
      align-items: center;
      color: #6366f1;
      text-decoration: none;
      padding: 2px 4px;
      border-radius: 4px;
      transition: background .12s;
      &:hover { background: #f0f0ff; color: #4338ca; }
    }
    .bc-sep { color: #d1d5db; font-size: .9rem; }
    .bc-section-link {
      color: #6366f1;
      font-size: .82rem;
      font-weight: 600;
      text-decoration: none;
      padding: 2px 4px;
      border-radius: 4px;
      transition: background .12s;
      &:hover { background: #f0f0ff; color: #4338ca; }
    }
    .bc-current {
      color: #374151;
      font-weight: 600;
      font-size: .82rem;
    }
  `],
})
export class BreadcrumbComponent {
  private router = inject(Router);

  segments = toSignal(
    this.router.events.pipe(
      filter(e => e instanceof NavigationEnd),
      startWith(null),
      map(() => this.router.url.replace(/\?.*/, '').split('/').filter(Boolean)),
    ),
    { initialValue: [] as string[] },
  );

  techSection = () => {
    const segs = this.segments();
    return segs.length > 0 ? (TECH_SECTIONS[segs[0]] ?? null) : null;
  };

  /** Middle crumb for subtopic-depth routes: /hub/topic/subtopic → links to /hub/topic. */
  parentTopicRoute = () => {
    const segs = this.segments();
    return '/' + segs[0] + '/' + segs[1];
  };

  parentTopicLabel = () => {
    const segs = this.segments();
    if (segs.length < 3) return '';
    return this.labelMapFor(segs[0])[segs[1]] ?? segs[1];
  };

  pageLabel = () => {
    const segs = this.segments();
    if (segs.length < 2) return '';
    const key = segs[segs.length - 1];
    const map = this.labelMapFor(segs[0]);
    // Subtopic leaf slugs (3-segment /hub/topic/subtopic routes) can collide with an
    // unrelated top-level topic's own slug — try the composite 'topic/subtopic' key
    // first to disambiguate.
    if (segs.length >= 3) {
      const compositeKey = segs[segs.length - 2] + '/' + key;
      if (map[compositeKey] !== undefined) return map[compositeKey];
    }
    return map[key] ?? key;
  };

  private labelMapFor(hubSlug: string): Record<string, string> {
    const labels = hubSlug === 'csharp'       ? CSHARP_LABELS
                 : hubSlug === 'aspnet'       ? ASPNET_LABELS
                 : hubSlug === 'sql'          ? SQL_LABELS
                 : hubSlug === 'typescript'   ? TYPESCRIPT_LABELS
                 : hubSlug === 'react'        ? REACT_LABELS
                 : hubSlug === 'javascript'   ? JAVASCRIPT_LABELS
                 : hubSlug === 'html'         ? HTML_LABELS
                 : hubSlug === 'css'          ? CSS_LABELS
                 : hubSlug === 'performance'  ? PERFORMANCE_LABELS
                 : hubSlug === 'blazor'       ? BLAZOR_LABELS
                 : hubSlug === 'node'         ? NODE_LABELS
                 : hubSlug === 'python'       ? PYTHON_LABELS
                 : hubSlug === 'go'           ? GO_LABELS
                 : hubSlug === 'devops'       ? DEVOPS_LABELS
                 : hubSlug === 'containers'   ? CONTAINERS_LABELS
                 : hubSlug === 'aws'          ? AWS_LABELS
                 : hubSlug === 'azure'        ? AZURE_LABELS
                 : hubSlug === 'linux'        ? LINUX_LABELS
                 : hubSlug === 'terraform'    ? TERRAFORM_LABELS
                 : hubSlug === 'service-mesh'  ? MESH_LABELS
                 : hubSlug === 'system-design' ? SYSDESIGN_LABELS
                 : hubSlug === 'arch-patterns'    ? ARCH_LABELS
                 : hubSlug === 'design-patterns' ? DP_LABELS
                 : hubSlug === 'security'        ? SECURITY_LABELS
                 : hubSlug === 'api-design'      ? API_DESIGN_LABELS
                 : hubSlug === 'observability'   ? OBS_LABELS
                 : hubSlug === 'mongodb'         ? MONGO_LABELS
                 : hubSlug === 'redis'           ? REDIS_LABELS
                 : hubSlug === 'graphql'         ? GQL_LABELS
                 : hubSlug === 'messaging'       ? MESSAGING_LABELS
                 : hubSlug === 'testing-hub'    ? TESTING_LABELS
                 : hubSlug === 'dsa'            ? DSA_LABELS
                 : hubSlug === 'ai'             ? AI_LABELS
                 : ROUTE_LABELS;
    return labels;
  }
}
