import { Component, inject } from '@angular/core';
import { Router, RouterLink, NavigationEnd } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { filter, map, startWith } from 'rxjs';

const ROUTE_LABELS: Record<string, string> = {
  '':                   'Home',
  'counter':            'Signals & State',
  'templates':          'Template Syntax',
  'directives':         'Directives',
  'lifecycle':          'Lifecycle Hooks',
  'pipes':              'Pipes',
  'di':                 'Dependency Injection',
  'parent-child':       'Input / Output',
  'content-projection': 'Content Projection',
  'change-detection':   'Change Detection',
  'animations':         'Animations',
  'forms':              'Forms',
  'form-array':         'FormArray',
  'todo':               'Todo (guarded)',
  'zod-forms':          'Zod Validation',
  'custom-validators':  'Custom Validators',
  'cva':                'Control Value Accessor',
  'dynamic-forms':      'Dynamic Forms',
  'wizard-form':        'Wizard Form',
  'http':               'HTTP Client',
  'routing':            'Routing',
  'defer':              '@defer Blocks',
  'store':              'Signal Store',
  'rxjs':               'RxJS Operators',
  'testing':            'Testing',
  'route-resolvers':    'Route Resolvers',
  'preloading':         'Preloading',
  'route-guards':       'Route Guards',
  'http-interceptors':  'HTTP Interceptors',
  'signal-effects':     'Signal Effects',
  'typed-forms':        'Typed Reactive Forms',
  'host-directives':    'Host Directives',
  'let-template-vars':       '@let Template Variables',
  'standalone-migration':    'Standalone Migration',
  'error-handling-patterns': 'Error Handling Patterns',
  'msw':                     'Mock Service Worker',
  'accessibility':           'Accessibility (a11y)',
  'micro-frontends':         'Micro-Frontends',
  'angular-devtools':        'Angular DevTools',
  'bundle-optimization':     'Bundle Optimization',
  'material':           'Angular Material',
  'charts':             'Charts',
  'cdk':                'Angular CDK',
  'ag-grid':            'AG Grid',
  'tanstack-query':     'TanStack Query',
  'date-fns':           'date-fns',
  'tailwind':           'Tailwind CSS',
  'resource-api':       'resource() API',
  'ngrx-signals':       'NgRx Signals',
  'destroy-ref':        'DestroyRef',
  'linked-signal':      'linkedSignal()',
  'zoneless':           'Zoneless Angular',
  'e2e':                'E2E (Playwright)',
  'harnesses':          'Harnesses',
  'ng-image':           'NgOptimizedImage',
  'web-workers':        'Web Workers',
  'pwa':                'PWA / Service Worker',
  'i18n':               'i18n',
  'ssr':                'SSR + Hydration',
  'cheatsheet':         'Cheat Sheet',
  'errors':             'Common Errors',
  'whats-new':          "What's New",
  'mini-projects':      'Mini Projects',
  'learning-paths':     'Learning Paths',
  'interview-prep':     'Interview Prep',
  'quiz-practice':      'Quiz Practice',
  'design-patterns':    'Design Patterns',
  'decision-guides':    'Decision Guides',
  'glossary':           'Glossary',
};

const CSHARP_LABELS: Record<string, string> = {
  'basics':               'Variables & Types',
  'fields':               'Fields & Constants',
  'methods':              'Methods',
  'type-conversion':      'Type Conversion',
  'constructors':         'Constructors',
  'properties-indexers':  'Properties & Indexers',
  'namespaces':           'Namespaces & Usings',
  'oop':                  'Classes & OOP',
  'inheritance':          'Inheritance & Overriding',
  'abstract-interfaces':  'Abstract & Interfaces',
  'static-enums':         'Static, Partial & Enums',
  'structures':           'Structures',
  'system-object':        'System.Object',
  'records':              'Records & Structs',
  'generics':             'Generics',
  'null-safety':          'Null Safety',
  'pattern-matching':     'Pattern Matching',
  'extension-methods':    'Extension Methods',
  'tuples':               'Tuples & Anonymous Types',
  'arrays':               'Arrays',
  'collections':          'Collections',
  'linq':                 'LINQ',
  'strings-datetime':     'Strings, DateTime & Math',
  'io-serialization':     'I/O & Serialization',
  'gc-disposable':        'GC & IDisposable',
  'threading':            'Threading',
  'tasks':                'Tasks & Parallel',
  'async':                'async / await',
  'delegates':            'Delegates & Events',
  'exceptions':           'Exceptions',
  'reflection':           'Reflection & Attributes',
  'iterators':            'Iterators & yield',
  'functional-csharp':   'Functional C# & Result Pattern',
  'regex':                'Regular Expressions',
  'channels':             'Channels & Producer/Consumer',
  'unit-testing':         'Unit Testing (xUnit & Moq)',
  'expression-trees':     'Expression Trees',
  'dynamic':              'dynamic & the DLR',
  'source-generators':    'Source Generators',
  'span-memory':          'Span<T> & Memory<T>',
  'di-dotnet':            'Dependency Injection in .NET',
  'json-advanced':        'System.Text.Json Advanced',
  'unsafe-pointers':      'Unsafe Code & Pointers',
  'native-aot':           'Native AOT',
  'benchmarkdotnet':      'BenchmarkDotNet',
  'pinvoke':              'P/Invoke & Native Interop',
  'dotnet-cli':           '.NET CLI & Tooling',
  'whats-new-9-10':       "What's New in C# 9 & 10",
  'whats-new-11-12':      "What's New in C# 11 & 12",
  'whats-new-latest':     "What's New in C# 13+",
  'cheatsheet':           'C# Cheat Sheet',
  'errors':               'Common C# Errors',
  'mini-projects':        'Mini Projects',
  'learning-paths':       'Learning Paths',
  'interview-prep':       'Interview Prep',
  'quiz-practice':        'Quiz Practice',
  'design-patterns':      'Design Patterns',
  'decision-guides':      'Decision Guides',
  'glossary':             'Glossary',
};

const ASPNET_LABELS: Record<string, string> = {
  'hosting-startup':       'Hosting & Startup',
  'middleware':            'Middleware Pipeline',
  'routing':               'Routing',
  'configuration':         'Configuration & Options',
  'dependency-injection':  'Dependency Injection',
  'logging':               'Logging & Diagnostics',
  'controllers':           'Controllers & Actions',
  'minimal-apis':          'Minimal APIs',
  'model-binding':         'Model Binding & Validation',
  'filters':               'Filters',
  'error-handling':        'Error Handling',
  'ef-core-basics':        'EF Core Basics',
  'ef-relationships':      'EF Relationships & Migrations',
  'caching':               'Caching',
  'authentication':        'Authentication',
  'authorization':         'Authorization',
  'cors':                  'CORS & Security Headers',
  'testing':               'Testing',
  'background-services':   'Background Services',
  'signalr':               'SignalR',
  'health-checks':         'Health Checks & Observability',
  'deployment':            'Deployment',
  'static-files':          'Static Files & Uploads',
  'openapi-swagger':       'OpenAPI & Swagger',
  'api-versioning':        'API Versioning',
  'http-clients':          'HttpClient & Resilience',
  'grpc':                  'gRPC Services',
  'rate-limiting':         'Rate Limiting',
  'aspire':                '.NET Aspire',
  'fluent-validation':     'FluentValidation',
  'minimal-api-advanced':  'Minimal API Advanced',
  'output-caching-advanced': 'Output Caching Advanced',
  'dapper':                'Dapper & Raw SQL',
  'csrf':                  'Anti-forgery & CSRF',
  'feature-flags':         'Feature Flags',
  'localization':          'Localization & Globalization',
  'masstransit':           'MassTransit',
  'response-compression':  'Response Compression',
  'websockets':            'WebSockets',
  'yarp':                  'YARP Reverse Proxy',
  'opentelemetry':         'OpenTelemetry',
  'ef-performance':        'EF Core Performance & Concurrency',
  'web-security':          'Web Security Essentials',
  'secrets':               'Secrets & Data Protection',
  'performance':           'Performance & Diagnostics',
  'cheatsheet':            'Cheat Sheet',
  'errors':               'Common Errors',
  'quiz-practice':         'Quiz Practice',
  'interview-prep':        'Interview Prep',
  'design-patterns':       'Design Patterns',
  'decision-guides':       'Decision Guides',
  'glossary':              'Glossary',
  'mini-projects':         'Mini Projects',
  'learning-paths':        'Learning Paths',
};

const SQL_LABELS: Record<string, string> = {
  'rdbms-concepts':    'RDBMS Concepts',
  'data-modeling':     'Data Modeling',
  'normalization':     'Normalization',
  'db-architecture':   'DB Architecture',
  'data-types':        'Data Types',
  'basics':            'SQL Basics',
  'joins':             'Joins',
  'aggregations':      'Aggregations',
  'subqueries':        'Subqueries',
  'ctes':              'CTEs',
  'window-functions':  'Window Functions',
  'indexes':           'Indexes',
  'transactions':      'Transactions',
  'schema-design':     'Schema Design',
  'stored-procedures': 'Stored Procedures',
  'performance':       'Performance',
  'json-features':             'JSON Features',
  'set-operations':            'Set Operations',
  'null-handling':             'NULL Handling',
  'merge':                     'MERGE / Upsert',
  'string-functions':          'String Functions',
  'date-functions':            'Date & Time Functions',
  'conditional-expressions':   'Conditional Expressions',
  'math-functions':            'Math & Numeric Functions',
  'pivoting':                  'Pivoting & Cross-Tab',
  'constraints':               'Constraints',
  'views':                     'Views',
  'sequences':                 'Sequences & Identity',
  'temp-tables':               'Temp Tables & Table Variables',
  'computed-columns':          'Computed & Generated Columns',
  'stored-functions':          'Stored Functions',
  'cursors':                   'Cursors & Row-by-Row Processing',
  'triggers':                  'Triggers',
  'dynamic-sql':               'Dynamic SQL',
  'isolation-levels':          'Isolation Levels',
  'locking':                   'Locking & Deadlocks',
  'execution-plans':           'Execution Plans',
  'partitioning':              'Partitioning',
  'bulk-operations':           'Bulk Operations',
  'query-store':               'Query Store',
  'statistics':                'Statistics & Optimizer',
  'full-text-search':          'Full-Text Search',
  'security':                  'SQL Security',
  'connection-pooling':        'Connection Pooling',
  'cheatsheet':                'Cheat Sheet',
  'errors':            'Common Errors',
  'quiz-practice':     'Quiz Practice',
  'interview-prep':    'Interview Prep',
  'design-patterns':   'Design Patterns',
  'decision-guides':   'Decision Guides',
  'glossary':          'Glossary',
  'mini-projects':     'Mini Projects',
  'learning-paths':    'Learning Paths',
};

const TYPESCRIPT_LABELS: Record<string, string> = {
  'basics':                   'TS Fundamentals',
  'primitive-types':          'Primitive & Literal Types',
  'interfaces-types':         'Interfaces & Type Aliases',
  'unions':                   'Union & Intersection Types',
  'narrowing':                'Type Guards & Narrowing',
  'enums-tuples':             'Enums & Tuples',
  'generics':                 'Generics Fundamentals',
  'generic-patterns':         'Generic Patterns',
  'utility-types':            'Utility Types',
  'mapped-types':             'Mapped Types',
  'conditional-types':        'Conditional Types',
  'template-literal-types':   'Template Literal Types',
  'classes':                  'Classes & Visibility',
  'decorators':               'Decorators',
  'tsconfig':                 'tsconfig Deep Dive',
  'modules':                  'Module System & Namespaces',
  'declarations':             'Declaration Files (d.ts)',
  'frameworks':               'TypeScript with Frameworks',
  'strict-migration':         'Strict Mode & Migration',
  'ts-performance':           'TypeScript Performance',
  'cheatsheet':               'Cheat Sheet',
  'interview-prep':           'Interview Prep',
};

const REACT_LABELS: Record<string, string> = {
  'basics':            'React Fundamentals',
  'hooks-core':        'Core Hooks',
  'hooks-advanced':    'Advanced Hooks',
  'forms':             'Forms & Validation',
  'router':            'React Router',
  'context':           'Context API',
  'state-management':  'State Management',
  'tanstack-query':    'TanStack Query',
  'performance':       'Performance',
  'patterns':          'React Patterns',
  'typescript':        'TypeScript & React',
  'testing':           'Testing React',
  'nextjs':            'Next.js App Router',
  'native':            'React Native',
  'hook-form':         'React Hook Form',
  'animations':        'Animations',
  'security':          'Security',
  'cheatsheet':        'Cheat Sheet',
  'interview-prep':    'Interview Prep',
};

const JAVASCRIPT_LABELS: Record<string, string> = {
  'fundamentals':   'JavaScript Fundamentals',
  'closures':       'Scope & Closures',
  'hoisting':       'Hoisting & TDZ',
  'symbols':        'Symbols & Iterators',
  'functions':      'Functions Deep Dive',
  'prototypes':     'Prototypes & Classes',
  'objects':        'Object Fundamentals',
  'destructuring':  'Destructuring & Spread',
  'arrays':         'Arrays & Iteration',
  'promises':       'Promises & Async/Await',
  'event-loop':     'Event Loop & Concurrency',
  'error-handling': 'Error Handling',
  'generators':     'Generators',
  'dom':            'DOM Manipulation',
  'events':         'Events & Custom Events',
  'browser-apis':   'Browser APIs',
  'modules':        'ES Modules',
  'bundlers':       'Bundlers & Build Tools',
  'patterns':       'Design Patterns in JS',
  'functional':     'Functional JS',
  'proxy':          'Proxy & Reflect API',
  'weakrefs':       'WeakMap, WeakSet & WeakRef',
  'cheatsheet':     'Cheat Sheet',
  'interview-prep': 'Interview Prep',
};

const HTML_LABELS: Record<string, string> = {
  'document-structure': 'Document Structure',
  'semantic-elements':  'Semantic Elements',
  'forms':              'Forms & Input',
  'media':              'Media Elements',
  'tables':             'Tables',
  'links-navigation':   'Links & Navigation',
  'accessibility':      'Accessibility & ARIA',
  'head-metadata':      'Head & Metadata',
  'custom-elements':    'Web Components',
  'iframes-embeds':     'iFrames & Embeds',
  'canvas-svg':         'Canvas & SVG',
  'performance':        'HTML Performance',
  'pwa-service-workers': 'PWA & Service Workers',
  'seo':                 'HTML SEO',
  'apis':                'HTML5 Browser APIs',
  'fundamentals':         'HTML Fundamentals',
  'headings-paragraphs':  'Headings & Paragraphs',
  'input-types':          'Input Types & Attributes',
  'landmark-elements':    'Landmark Elements',
  'aria-roles':           'ARIA Roles & Attributes',
  'focus-management':     'Focus Management',
  'storage-apis':         'HTML5 Storage APIs',
  'drag-drop':            'Drag & Drop API',
  'cheatsheet':          'HTML Cheat Sheet',
  'interview-prep':      'HTML Interview Prep',
};

const CSS_LABELS: Record<string, string> = {
  'box-model':         'Box Model',
  'flexbox':           'Flexbox',
  'grid':              'CSS Grid',
  'positioning':       'Positioning & Stacking',
  'custom-properties': 'CSS Custom Properties',
  'selectors':         'Selectors Deep Dive',
  'typography':        'Typography',
  'responsive':        'Responsive Design',
  'animations':        'CSS Animations',
  'transitions':       'CSS Transitions',
  'colors-theming':        'Colors & Theming',
  'backgrounds-borders':   'Backgrounds & Borders',
  'container-queries':     'Container Queries',
  'css-layers':            'CSS Cascade Layers',
  'css-nesting':           'CSS Nesting',
  'logical-properties':    'Logical Properties',
  'css-architecture':      'CSS Architecture',
  'tailwind':                    'Tailwind CSS',
  'scroll-driven-animations':   'Scroll-Driven Animations',
  'css-transforms':             'CSS Transforms',
  'css-filters':               'CSS Filters & Effects',
  'fundamentals':              'CSS Fundamentals',
  'cheatsheet':               'CSS Cheat Sheet',
  'interview-prep':           'CSS Interview Prep',
};

const PERFORMANCE_LABELS: Record<string, string> = {
  'core-web-vitals':        'Core Web Vitals',
  'lcp':                    'Largest Contentful Paint',
  'inp':                    'Interaction to Next Paint',
  'cls':                    'Cumulative Layout Shift',
  'critical-rendering-path': 'Critical Rendering Path',
  'browser-rendering':      'Browser Rendering Pipeline',
  'resource-hints':         'Resource Hints',
  'http2-http3':            'HTTP/2 & HTTP/3',
  'caching':                'Caching & Service Workers',
  'image-optimisation':     'Image Optimisation',
  'font-performance':       'Font Performance',
  'js-performance':         'JavaScript Performance',
  'third-party-scripts':    'Third-Party Scripts',
  'measurement':            'Performance Measurement',
  'rum':                    'Real User Monitoring (RUM)',
  'ssr-streaming':          'SSR & Streaming HTML',
  'css-performance':        'CSS Performance',
  'web-workers':            'Web Workers & Off-Main-Thread',
  'performance-budgets':    'Performance Budgets & CI',
  'speculation-rules':      'Speculation Rules API',
  'cheatsheet':             'Web Performance Cheat Sheet',
  'interview-prep':         'Performance Interview Prep',
};

const BLAZOR_LABELS: Record<string, string> = {
  'fundamentals':            'Blazor Fundamentals',
  'render-modes':            'Render Modes',
  'razor-components':        'Razor Components',
  'component-communication': 'Component Communication',
  'forms':                   'Blazor Forms',
  'data-binding':            'Data Binding',
  'routing':                 'Blazor Routing',
  'dependency-injection':    'Dependency Injection',
  'state-management':        'State Management',
  'js-interop':              'JavaScript Interop',
  'server-signalr':          'Blazor Server & SignalR',
  'maui-hybrid':             'MAUI Blazor Hybrid',
  'authentication':          'Authentication in Blazor',
  'error-handling':          'Error Handling & ErrorBoundary',
  'streaming-rendering':     'Streaming Rendering',
  'sections-layouts':        'Sections & Layouts',
  'seo-metadata':            'SEO & Head Metadata',
  'virtualization':          'Component Virtualization',
  'progressive-enhancement': 'Progressive Enhancement',
  'performance':             'Blazor Performance',
  'bunit':                   'Testing with bUnit',
  'cheatsheet':              'Blazor Cheat Sheet',
  'interview-prep':          'Blazor Interview Prep',
};

const PYTHON_LABELS: Record<string, string> = {
  'fundamentals':              'Python Fundamentals',
  'functions-closures':        'Functions & Closures',
  'comprehensions-generators': 'Comprehensions & Generators',
  'file-io':                   'File I/O & Pathlib',
  'oop':                       'OOP in Python',
  'dataclasses-pydantic':      'Dataclasses & Pydantic',
  'decorators-context-managers': 'Decorators & Context Managers',
  'type-hints':                'Type Hints & mypy',
  'collections-itertools':     'Collections & Itertools',
  'asyncio':                   'Async Python (asyncio)',
  'threading-multiprocessing': 'Threading & Multiprocessing',
  'concurrency-patterns':      'Python Concurrency Patterns',
  'fastapi':                   'FastAPI',
  'django':                    'Django',
  'sqlalchemy':                'SQLAlchemy',
  'celery':                    'Celery & Task Queues',
  'numpy-pandas':              'NumPy & Pandas',
  'scikit-learn':              'Machine Learning (scikit-learn)',
  'pytest':                    'Testing with pytest',
  'packaging':                 'Python Packaging & venv',
  'debugging-profiling':       'Debugging & Profiling',
  'cheatsheet':                'Python Cheat Sheet',
  'interview-prep':            'Python Interview Prep',
};

const GO_LABELS: Record<string, string> = {
  'fundamentals':       'Go Fundamentals',
  'structs-interfaces': 'Structs & Interfaces',
  'error-handling':     'Error Handling',
  'slices-maps':        'Slices & Maps',
  'goroutines':         'Goroutines',
  'channels':           'Channels',
  'sync':               'sync & sync/atomic',
  'context':            'context Package',
  'net-http':           'net/http & REST APIs',
  'gin':                'Gin Web Framework',
  'json-encoding':      'JSON & Encoding',
  'grpc':               'gRPC in Go',
  'pgx':                'Database with pgx',
  'gorm':               'GORM',
  'generics':           'Go Generics',
  'patterns':           'Go Patterns',
  'modules':            'Go Modules',
  'testing':            'Testing in Go',
  'cli':                'Go CLI Tools',
  'profiling':          'Go Performance & Profiling',
  'build':              'Go Build & Deployment',
  'cheatsheet':         'Go Cheat Sheet',
  'interview-prep':     'Go Interview Prep',
};

const AWS_LABELS: Record<string, string> = {
  'fundamentals':       'AWS Fundamentals',
  'ec2':                'EC2 & Auto Scaling',
  'ecs-eks':            'ECS & EKS',
  'vpc':                'VPC & Networking',
  'route53-cloudfront': 'Route 53 & CloudFront',
  's3':                 'S3',
  'ebs-efs':            'EBS, EFS & FSx',
  'iam':                'IAM',
  'iam-roles':          'IAM Roles & Federation',
  'rds-aurora':         'RDS & Aurora',
  'dynamodb':           'DynamoDB',
  'lambda':             'Lambda',
  'api-gateway':        'API Gateway',
  'cloudwatch':         'CloudWatch & X-Ray',
  'cloudformation-cdk': 'CloudFormation & CDK',
  'security':           'AWS Security Services',
  'sqs-sns':            'SQS & SNS',
  'eventbridge':        'EventBridge',
  'step-functions':     'AWS Step Functions',
  'load-balancing':     'Elastic Load Balancing',
  'cost-optimization':  'AWS Cost Optimization',
  'cheatsheet':         'AWS Cheat Sheet',
};

const AZURE_LABELS: Record<string, string> = {
  'fundamentals':       'Azure Fundamentals',
  'arm':                'Azure Resource Manager',
  'virtual-machines':   'Virtual Machines',
  'app-service':        'App Service',
  'functions':          'Azure Functions',
  'aks':                'Azure Kubernetes Service',
  'virtual-network':    'Virtual Network',
  'load-balancer':      'Load Balancer & Front Door',
  'storage':            'Blob & Storage',
  'entra-id':           'Entra ID (AAD)',
  'rbac':               'Azure RBAC',
  'sql-cosmos':         'SQL & Cosmos DB',
  'monitor':            'Monitor & App Insights',
  'devops-pipelines':   'DevOps & Pipelines',
  'cost-management':    'Cost Management',
  'security-defender':  'Security Center & Defender',
  'key-vault':          'Key Vault',
  'service-bus':        'Service Bus',
  'container-apps':     'Container Apps',
  'redis':              'Cache for Redis',
  'api-management':     'API Management',
  'bicep':              'Azure Bicep Deep-dive',
  'cheatsheet':         'Azure Cheat Sheet',
};

const CONTAINERS_LABELS: Record<string, string> = {
  'fundamentals':       'Container Fundamentals',
  'docker-cli':         'Docker CLI',
  'docker-images':      'Docker Images & Registry',
  'dockerfile':         'Writing Dockerfiles',
  'multi-stage':        'Multi-Stage Builds',
  'compose':            'Docker Compose',
  'compose-profiles':   'Compose Profiles & Overrides',
  'k8s-architecture':   'Kubernetes Architecture',
  'kubectl':            'kubectl Fundamentals',
  'pods-deployments':   'Pods, Deployments & ReplicaSets',
  'services-ingress':   'Services & Ingress',
  'configmaps-secrets': 'ConfigMaps & Secrets',
  'storage':            'Persistent Volumes & Storage',
  'operators-crds':     'Kubernetes Operators & CRDs',
  'helm':               'Helm',
  'container-security': 'Container Security',
  'rbac':               'Kubernetes RBAC',
  'statefulsets':       'StatefulSets & DaemonSets',
  'resource-limits':    'Resource Requests & Limits',
  'hpa':                'Horizontal Pod Autoscaler',
  'network-policies':   'Network Policies',
  'troubleshooting':    'Kubernetes Troubleshooting',
  'cheatsheet':         'Containers Cheat Sheet',
};

const DEVOPS_LABELS: Record<string, string> = {
  'culture':               'DevOps Culture & Principles',
  'sdlc-agile':            'SDLC & Agile',
  'environment-strategy':  'Environment Strategy',
  'platform-engineering':  'Platform Engineering',
  'git-workflows':         'Git Workflows',
  'github-actions':        'GitHub Actions',
  'azure-pipelines':       'Azure DevOps Pipelines',
  'jenkins':               'Jenkins',
  'continuous-integration':'Continuous Integration',
  'continuous-delivery':   'Continuous Delivery & Deployment',
  'gitops':                'GitOps with ArgoCD & Flux',
  'artifact-management':   'Artifact Management',
  'docker-cicd':           'Docker in CI/CD',
  'kubernetes-deployments':'Kubernetes Deployments',
  'iac':                   'Infrastructure as Code',
  'monitoring':            'Monitoring & Alerting',
  'logging':               'Logging Pipelines',
  'incident-response':     'On-call & Incident Response',
  'devsecops':             'DevSecOps',
  'release-management':    'Release Management',
  'sre':                   'SRE Practices',
  'cheatsheet':            'DevOps Cheat Sheet',
};

const NODE_LABELS: Record<string, string> = {
  'architecture':    'Node.js Architecture',
  'modules':         'Modules & CommonJS',
  'core-modules':    'Core Modules',
  'env-config':      'Env Config & dotenv',
  'express':         'Express.js',
  'fastify':         'Fastify',
  'rest-api':        'REST API Design',
  'websockets':      'WebSockets & Socket.io',
  'graphql':         'GraphQL API',
  'nestjs':          'NestJS',
  'promises-async':  'Promises & Async/Await',
  'streams':         'Streams & Buffers',
  'error-handling':  'Error Handling',
  'prisma':          'Database with Prisma',
  'mongoose':        'MongoDB with Mongoose',
  'caching':         'Caching with Redis',
  'jwt-auth':        'Auth with JWT & Passport',
  'security':        'Security Best Practices',
  'performance':     'Node.js Performance',
  'logging':         'Logging with Pino/Winston',
  'worker-threads':  'Worker Threads',
  'testing':         'Testing Node.js Apps',
  'deployment':      'Deploying Node.js Apps',
  'cheatsheet':      'Node.js Cheat Sheet',
  'interview-prep':  'Node.js Interview Prep',
};

const TERRAFORM_LABELS: Record<string, string> = {
  'fundamentals':      'Terraform Fundamentals',
  'providers':         'Providers',
  'variables':         'Variables',
  'outputs':           'Outputs',
  'resources':         'Resources & Meta-Arguments',
  'data-sources':      'Data Sources',
  'expressions':       'Expressions & Dynamic Blocks',
  'functions':         'Built-in Functions',
  'state':             'Terraform State',
  'remote-backends':   'Remote Backends',
  'workspaces':        'Workspaces',
  'modules':           'Modules',
  'module-patterns':   'Module Patterns',
  'provisioners':      'Provisioners',
  'import':            'Import & Generated Config',
  'cicd':              'CI/CD with Terraform',
  'testing':           'Testing Terraform Code',
  'security':          'Security & Compliance',
  'drift':             'Drift Detection',
  'refactoring':       'Refactoring & State Ops',
  'opentofu':          'OpenTofu',
  'cheatsheet':        'Terraform Cheatsheet',
  'interview-prep':    'Terraform Interview Prep',
};

const LINUX_LABELS: Record<string, string> = {
  'fundamentals':          'Linux Fundamentals',
  'file-system':           'File System & Hierarchy',
  'essential-commands':    'Essential Commands',
  'file-permissions':      'File Permissions & Ownership',
  'users-groups':          'Users & Groups',
  'process-management':    'Process Management',
  'system-monitoring':     'System Monitoring',
  'networking':            'Networking Commands',
  'firewall':              'Firewall & iptables',
  'ssh':                   'SSH & Remote Access',
  'bash-scripting':        'Bash Scripting Basics',
  'bash-advanced':         'Advanced Bash Scripting',
  'package-management':    'Package Management',
  'systemd':               'systemd & Services',
  'disk-storage':          'Disk & Storage',
  'environment-variables': 'Environment Variables & Shell Config',
  'log-analysis':          'Log Analysis',
  'performance-tuning':    'Performance Tuning',
  'vim':                   'Vim & Text Editors',
  'security-hardening':    'Linux Security Hardening',
  'cron':                  'Cron & Scheduling',
};

const MESH_LABELS: Record<string, string> = {
  'fundamentals':       'Service Mesh Fundamentals',
  'istio-architecture': 'Istio Architecture',
  'istio-install':      'Istio Installation & Configuration',
  'linkerd':            'Linkerd',
  'traffic-management': 'Traffic Management',
  'resilience':         'Retries, Timeouts & Circuit Breaking',
  'load-balancing':     'Load Balancing Algorithms',
  'mtls':               'mTLS & Service Identity',
  'authorization':      'Authorization Policies',
  'metrics':            'Metrics & Telemetry',
  'tracing':            'Distributed Tracing',
  'kiali':              'Kiali & Dashboards',
  'gateway-api':        'Kubernetes Gateway API',
  'ingress-gateway':    'Ingress Gateway',
  'performance':        'Service Mesh Performance',
  'envoy':              'Envoy Proxy Deep Dive',
  'ambient-mesh':       'Ambient Mesh',
  'multi-cluster':      'Multi-cluster Mesh',
  'consul':             'Consul Connect',
  'cheatsheet':         'Service Mesh Cheat Sheet',
  'interview-prep':     'Service Mesh Interview Prep',
};

const ARCH_LABELS: Record<string, string> = {
  'monolith-vs-modular':       'Monolith vs Modular Monolith',
  'layered-architecture':      'Layered Architecture',
  'clean-architecture':        'Clean / Onion Architecture',
  'hexagonal-architecture':    'Hexagonal Architecture',
  'vertical-slice':            'Vertical Slice Architecture',
  'service-oriented':          'Service-Oriented Architecture',
  'microservices-principles':  'Microservices Principles',
  'service-communication':     'Service Communication',
  'api-gateway-pattern':       'API Gateway Pattern',
  'service-discovery':         'Service Discovery',
  'circuit-breaker':           'Circuit Breaker',
  'sidecar-service-mesh':      'Sidecar & Service Mesh',
  'event-driven':              'Event-Driven Architecture',
  'cqrs-event-sourcing':       'CQRS & Event Sourcing',
  'saga-choreography':         'Saga & Choreography',
  'inbox-outbox':              'Inbox & Outbox Pattern',
  'ddd-core':                  'Domain-Driven Design Core',
  'bounded-contexts':          'Bounded Contexts',
  'aggregates-domain-events':  'Aggregates & Domain Events',
  'anti-corruption-layer':     'Anti-Corruption Layer',
  'strangler-fig':             'Strangler Fig Pattern',
  'backend-for-frontend':      'Backend for Frontend (BFF)',
  'adr':                       'Architecture Decision Records',
  'pattern-comparison':        'Pattern Comparison Guide',
  'interview-prep':            'Architecture Interview Prep',
};

const SYSDESIGN_LABELS: Record<string, string> = {
  'framework':                'System Design Framework',
  'capacity-estimation':      'Capacity Estimation',
  'cap-theorem':              'CAP & PACELC Theorems',
  'networking':               'Networking Fundamentals',
  'scaling':                  'Horizontal vs Vertical Scaling',
  'load-balancing':           'Load Balancing',
  'caching':                  'Caching Strategies',
  'cdn':                      'Content Delivery Networks',
  'sharding':                 'Database Sharding',
  'sql-vs-nosql':             'SQL vs NoSQL',
  'replication':              'Replication Strategies',
  'indexes':                  'Indexes & Query Optimisation',
  'distributed-transactions': 'Distributed Transactions',
  'high-availability':        'High Availability Design',
  'fault-tolerance':          'Fault Tolerance Patterns',
  'distributed-tracing':      'Distributed Tracing',
  'disaster-recovery':        'Disaster Recovery',
  'url-shortener':            'Design a URL Shortener',
  'social-feed':              'Design a Social Feed',
  'chat-application':         'Design a Chat Application',
  'search-engine':            'Design a Search Engine',
  'payment-system':           'Design a Payment System',
  'video-streaming':          'Design Netflix / YouTube',
  'ai-ml-system-design':      'AI/ML System Design',
  'cheatsheet':               'System Design Cheat Sheet',
  'interview-prep':           'System Design Interview Guide',
};

const TECH_SECTIONS: Record<string, { label: string; path: string }> = {
  'angular':         { label: 'Angular',               path: '/angular'         },
  'csharp':          { label: 'C#',                    path: '/csharp'          },
  'aspnet':          { label: 'ASP.NET Core',           path: '/aspnet'          },
  'sql':             { label: 'SQL',                   path: '/sql'             },
  'html':            { label: 'HTML',                  path: '/html'            },
  'css':             { label: 'CSS',                   path: '/css'             },
  'javascript':      { label: 'JavaScript',            path: '/javascript'      },
  'typescript':      { label: 'TypeScript',            path: '/typescript'      },
  'react':           { label: 'React',                 path: '/react'           },
  'blazor':          { label: 'Blazor',                path: '/blazor'          },
  'performance':     { label: 'Web Performance',       path: '/performance'     },
  'node':            { label: 'Node.js',               path: '/node'            },
  'python':          { label: 'Python',                path: '/python'          },
  'go':              { label: 'Go',                    path: '/go'              },
  'mongodb':         { label: 'MongoDB / NoSQL',       path: '/mongodb'         },
  'redis':           { label: 'Redis',                 path: '/redis'           },
  'graphql':         { label: 'GraphQL',               path: '/graphql'         },
  'messaging':       { label: 'Messaging & Events',    path: '/messaging'       },
  'design-patterns': { label: 'Design Patterns',       path: '/design-patterns' },
  'arch-patterns':   { label: 'Architecture Patterns', path: '/arch-patterns'   },
  'api-design':      { label: 'API Design',            path: '/api-design'      },
  'system-design':   { label: 'System Design',         path: '/system-design'   },
  'security':        { label: 'Security & Auth',       path: '/security'        },
  'observability':   { label: 'Observability & SRE',   path: '/observability'   },
  'devops':          { label: 'Git & DevOps',          path: '/devops'          },
  'linux':           { label: 'Linux & Bash',          path: '/linux'           },
  'containers':      { label: 'Docker & Kubernetes',   path: '/containers'      },
  'terraform':       { label: 'Terraform / IaC',       path: '/terraform'       },
  'azure':           { label: 'Azure',                 path: '/azure'           },
  'aws':             { label: 'AWS',                   path: '/aws'             },
  'service-mesh':    { label: 'Service Mesh & Istio',  path: '/service-mesh'    },
  'dsa':             { label: 'DSA',                   path: '/dsa'             },
  'testing-hub':     { label: 'Testing',               path: '/testing-hub'     },
  'ai':              { label: 'AI & LLMs',             path: '/ai'              },
};

@Component({
  selector: 'app-breadcrumb',
  standalone: true,
  imports: [RouterLink],
  template: `
    @if (segments().length > 0) {
      <nav class="breadcrumb" aria-label="breadcrumb">
        <a routerLink="/" class="bc-home" title="Home">
          <svg width="14" height="14" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h4a1 1 0 001-1v-3h2v3a1 1 0 001 1h4a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"/>
          </svg>
        </a>
        @if (techSection()) {
          <span class="bc-sep">›</span>
          @if (segments().length > 1) {
            <a [routerLink]="techSection()!.path" class="bc-section-link">{{ techSection()!.label }}</a>
          } @else {
            <span class="bc-current">{{ techSection()!.label }}</span>
          }
        }
        @if (segments().length > 1) {
          <span class="bc-sep">›</span>
          <span class="bc-current">{{ pageLabel() }}</span>
        }
      </nav>
    }`,
  styles: [`
    .breadcrumb {
      display: flex;
      align-items: center;
      gap: .3rem;
      padding: .7rem 1.25rem .3rem;
      font-size: .82rem;
      color: #9ca3af;
    }
    .bc-home {
      display: flex;
      align-items: center;
      color: #6366f1;
      text-decoration: none;
      padding: 2px 4px;
      border-radius: 4px;
      transition: background .12s;
      &:hover { background: #f0f0ff; color: #4338ca; }
    }
    .bc-sep { color: #d1d5db; font-size: .9rem; }
    .bc-section-link {
      color: #6366f1;
      font-size: .82rem;
      font-weight: 600;
      text-decoration: none;
      padding: 2px 4px;
      border-radius: 4px;
      transition: background .12s;
      &:hover { background: #f0f0ff; color: #4338ca; }
    }
    .bc-current {
      color: #374151;
      font-weight: 600;
      font-size: .82rem;
    }
  `],
})
export class BreadcrumbComponent {
  private router = inject(Router);

  segments = toSignal(
    this.router.events.pipe(
      filter(e => e instanceof NavigationEnd),
      startWith(null),
      map(() => this.router.url.replace(/\?.*/, '').split('/').filter(Boolean)),
    ),
    { initialValue: [] as string[] },
  );

  techSection = () => {
    const segs = this.segments();
    return segs.length > 0 ? (TECH_SECTIONS[segs[0]] ?? null) : null;
  };

  pageLabel = () => {
    const segs = this.segments();
    if (segs.length < 2) return '';
    const key = segs[segs.length - 1];
    const labels = segs[0] === 'csharp'       ? CSHARP_LABELS
                 : segs[0] === 'aspnet'       ? ASPNET_LABELS
                 : segs[0] === 'sql'          ? SQL_LABELS
                 : segs[0] === 'typescript'   ? TYPESCRIPT_LABELS
                 : segs[0] === 'react'        ? REACT_LABELS
                 : segs[0] === 'javascript'   ? JAVASCRIPT_LABELS
                 : segs[0] === 'html'         ? HTML_LABELS
                 : segs[0] === 'css'          ? CSS_LABELS
                 : segs[0] === 'performance'  ? PERFORMANCE_LABELS
                 : segs[0] === 'blazor'       ? BLAZOR_LABELS
                 : segs[0] === 'node'         ? NODE_LABELS
                 : segs[0] === 'python'       ? PYTHON_LABELS
                 : segs[0] === 'go'           ? GO_LABELS
                 : segs[0] === 'devops'       ? DEVOPS_LABELS
                 : segs[0] === 'containers'   ? CONTAINERS_LABELS
                 : segs[0] === 'aws'          ? AWS_LABELS
                 : segs[0] === 'azure'        ? AZURE_LABELS
                 : segs[0] === 'linux'        ? LINUX_LABELS
                 : segs[0] === 'terraform'    ? TERRAFORM_LABELS
                 : segs[0] === 'service-mesh'  ? MESH_LABELS
                 : segs[0] === 'system-design' ? SYSDESIGN_LABELS
                 : segs[0] === 'arch-patterns' ? ARCH_LABELS
                 : ROUTE_LABELS;
    return labels[key] ?? key;
  };
}
