import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

interface InterviewQuestion {
  id: number;
  q: string;
  a: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  topic: string;
  expanded?: boolean;
}

@Component({
  selector: 'app-js-interview-prep',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './interview-prep.html',
  styleUrl: './interview-prep.scss',
})
export class JsInterviewPrep {
  activeDifficulty = signal<string>('all');
  activeTopic = signal<string>('all');

  difficulties = ['all', 'beginner', 'intermediate', 'advanced'];
  topics = ['all', 'Closures', 'Async', 'Prototypes', 'Types', 'Event Loop', 'Modules', 'Performance', 'Patterns'];

  questions: InterviewQuestion[] = [
    // Beginner
    { id: 1, q: 'What is the difference between var, let, and const?', a: '<code>var</code> is function-scoped, hoisted with value <code>undefined</code>, and can be re-declared. <code>let</code> and <code>const</code> are block-scoped and are in the Temporal Dead Zone (TDZ) from the start of the block until the declaration — accessing them before the declaration throws a ReferenceError. <code>const</code> prevents reassignment of the binding (the variable cannot point to a new value) but does not make objects immutable — you can still mutate object properties. Use <code>const</code> by default, <code>let</code> when you need to reassign, avoid <code>var</code>.', difficulty: 'beginner', topic: 'Types', expanded: false },
    { id: 2, q: 'What is the difference between == and ===?', a: '<code>===</code> (strict equality) compares value AND type — no coercion. <code>==</code> (loose equality) applies type coercion rules before comparing, leading to surprising results like <code>"0" == false // true</code>. Always use <code>===</code> unless you explicitly need coercion (rare). Special cases: <code>NaN !== NaN</code> (use <code>Number.isNaN()</code>); <code>+0 === -0</code> (use <code>Object.is()</code> if distinction matters).', difficulty: 'beginner', topic: 'Types', expanded: false },
    { id: 3, q: 'What are the falsy values in JavaScript?', a: 'There are exactly six falsy values: <code>false</code>, <code>0</code> (and <code>-0</code>, <code>0n</code>), <code>""</code> (empty string), <code>null</code>, <code>undefined</code>, and <code>NaN</code>. Everything else is truthy — including <code>[]</code>, <code>{}</code>, <code>"false"</code>, and <code>0</code> as a string. Prefer <code>??</code> (nullish coalescing) over <code>||</code> when you only want to guard against <code>null</code>/<code>undefined</code> — <code>||</code> treats <code>0</code> and <code>""</code> as falsy too.', difficulty: 'beginner', topic: 'Types', expanded: false },
    { id: 4, q: 'Explain typeof and when it surprises people.', a: '<code>typeof</code> returns a string: <code>"number"</code>, <code>"string"</code>, <code>"boolean"</code>, <code>"undefined"</code>, <code>"object"</code>, <code>"function"</code>, <code>"symbol"</code>, <code>"bigint"</code>. Surprises: (1) <code>typeof null === "object"</code> — a historical bug in JS, null is not an object; (2) <code>typeof function(){} === "function"</code> — functions have their own type string even though they are objects; (3) <code>typeof undeclaredVar === "undefined"</code> — doesn\'t throw, unlike accessing the variable directly. Use <code>Array.isArray()</code> for arrays since <code>typeof [] === "object"</code>.', difficulty: 'beginner', topic: 'Types', expanded: false },

    // Closures
    { id: 5, q: 'What is a closure and give a practical example.', a: 'A closure is a function that remembers variables from its outer lexical scope even after that scope has finished executing. Whenever you define a function inside another function, the inner function closes over the outer function\'s variables. Practical uses: (1) <strong>Private state</strong>: <code>function createCounter() { let n=0; return { inc: ()=>++n, get: ()=>n }; }</code> — <code>n</code> is private. (2) <strong>Partial application</strong>: <code>const add5 = x => x + 5</code> closes over 5. (3) <strong>Event handlers</strong>: a click handler closes over the data it was created with. The closure variable is not a copy — it\'s a live reference.', difficulty: 'intermediate', topic: 'Closures', expanded: false },
    { id: 6, q: 'Classic closure bug: for loop with var. Explain and fix.', a: '<code>for (var i=0; i<3; i++) { setTimeout(()=>console.log(i), 0); }</code> logs "3 3 3" — all callbacks share the SAME <code>i</code> variable (var is function-scoped), and by the time they run, the loop has finished (i=3). Fixes: (1) Use <code>let</code> — block-scoped, creates a new binding per iteration: <code>for (let i=0; ...)</code>. (2) IIFE to capture current value: <code>setTimeout((i => () => console.log(i))(i), 0)</code>. (3) <code>forEach</code> or array methods — callback creates a new scope.', difficulty: 'intermediate', topic: 'Closures', expanded: false },

    // Async
    { id: 7, q: 'Explain the JavaScript Event Loop.', a: 'JavaScript is single-threaded. The event loop coordinates between: (1) <strong>Call stack</strong> — executes synchronous code. (2) <strong>Microtask queue</strong> — Promise callbacks (<code>.then</code>), <code>queueMicrotask()</code>, MutationObserver. (3) <strong>Macrotask queue</strong> — setTimeout, setInterval, I/O callbacks. After each task, the engine drains ALL microtasks before picking the next macrotask. So: <code>setTimeout(..., 0)</code> runs after all Promises even though both are "async". Render steps happen between macrotasks (in browsers). This is why blocking the call stack with a long computation freezes the UI.', difficulty: 'intermediate', topic: 'Event Loop', expanded: false },
    { id: 8, q: 'What is the difference between Promise.all and Promise.allSettled?', a: '<code>Promise.all([p1,p2,p3])</code> resolves when ALL resolve — rejects immediately if ANY rejects (fail-fast). Use when all results are required and failure of any means failure of all (e.g. parallel API calls that must all succeed). <code>Promise.allSettled([p1,p2,p3])</code> waits for ALL to settle regardless of outcome — returns <code>[{status:"fulfilled",value:...},{status:"rejected",reason:...}]</code>. Use when you need to process all results including failures (e.g. batch operations where some can fail). Also: <code>Promise.race</code> (first to settle wins), <code>Promise.any</code> (first fulfillment wins).', difficulty: 'intermediate', topic: 'Async', expanded: false },
    { id: 9, q: 'How do you handle errors in async/await?', a: 'Three patterns: (1) <strong>try/catch</strong>: <code>try { const d = await fetch(url); } catch(e) { handle(e); }</code> — catches both network errors and thrown errors from awaited code. (2) <strong>.catch()</strong> on the returned Promise: <code>doWork().catch(handleError)</code>. (3) <strong>Result tuple</strong>: wrap in a utility: <code>const [err, data] = await to(promise)</code> — avoids try/catch nesting for complex flows. Always handle errors — unhandled Promise rejections are logged as warnings and in Node.js 15+ crash the process.', difficulty: 'intermediate', topic: 'Async', expanded: false },
    { id: 10, q: 'What is the difference between microtasks and macrotasks?', a: '<strong>Microtasks</strong>: Promise callbacks (.then/.catch/.finally), queueMicrotask(), MutationObserver. Run immediately after the current task finishes — the entire microtask queue is drained before the next macrotask. <strong>Macrotasks</strong>: setTimeout, setInterval, setImmediate (Node), I/O, UI events. One macrotask runs per event loop tick. Order: current task → drain all microtasks → render (browser) → next macrotask. Consequence: <code>Promise.resolve().then(() => console.log("micro"))</code> always logs before <code>setTimeout(() => console.log("macro"), 0)</code>.', difficulty: 'advanced', topic: 'Event Loop', expanded: false },

    // Prototypes
    { id: 11, q: 'Explain the prototype chain.', a: 'Every JavaScript object has an internal <code>[[Prototype]]</code> link (accessed via <code>Object.getPrototypeOf(obj)</code> or <code>obj.__proto__</code>). When you access a property that doesn\'t exist on the object, JS walks up the chain: object → its prototype → its prototype\'s prototype → ... → <code>Object.prototype</code> → <code>null</code>. This is how methods like <code>.toString()</code> work — they live on <code>Object.prototype</code>. ES6 classes are syntactic sugar over prototype chains: <code>class Dog extends Animal</code> sets <code>Dog.prototype.__proto__ = Animal.prototype</code>.', difficulty: 'intermediate', topic: 'Prototypes', expanded: false },
    { id: 12, q: 'What does "new" do when calling a constructor function?', a: 'When you call <code>new Foo()</code>, JavaScript: (1) Creates a new empty object. (2) Sets its <code>[[Prototype]]</code> to <code>Foo.prototype</code>. (3) Calls <code>Foo</code> with <code>this</code> bound to the new object. (4) If <code>Foo</code> explicitly returns an object, that object is used; otherwise the new object from step 1 is returned. This is why forgetting <code>new</code> with a regular constructor function pollutes the global scope — <code>this</code> becomes <code>window</code> (non-strict) or throws (strict mode). ES6 <code>class</code> always requires <code>new</code> — calling without it throws a TypeError.', difficulty: 'intermediate', topic: 'Prototypes', expanded: false },

    // Modules
    { id: 13, q: 'What is the difference between CommonJS require() and ES Modules import?', a: '<strong>CommonJS</strong>: <code>require()</code> is synchronous, dynamic (can be called anywhere, conditionally), values are copied at require() time. Used in Node.js by default. <strong>ESM</strong>: <code>import</code> is static (must be at top level), asynchronous-capable, exports are live bindings (importers see updates). ESM is statically analyzable so bundlers can tree-shake. Key practical differences: ESM supports top-level await; ESM has <code>import.meta.url</code> (no <code>__dirname</code>); mixing requires care (<code>.mjs</code> / <code>"type":"module"</code> in package.json). Modern code should prefer ESM.', difficulty: 'intermediate', topic: 'Modules', expanded: false },

    // Performance
    { id: 14, q: 'What is debouncing and throttling? When to use each?', a: '<strong>Debouncing</strong>: delay execution until N ms have passed with no new calls. The timer resets on each call. Use for: search-as-you-type (fire after user stops typing), window resize handler, form validation. <strong>Throttling</strong>: allow at most one execution per N ms. Subsequent calls within the window are ignored or queued. Use for: scroll event handlers, mouse move tracking, infinite scroll triggers, rate-limiting API calls. Both prevent over-calling expensive operations on rapid events. Lodash provides <code>_.debounce</code> and <code>_.throttle</code>; or implement with <code>setTimeout</code>/<code>clearTimeout</code>.', difficulty: 'intermediate', topic: 'Performance', expanded: false },
    { id: 15, q: 'What is memoization and when should you use it?', a: 'Memoization caches the return value of a function for a given set of arguments — on subsequent calls with the same args, return the cached result instead of recomputing. Implement: store args→result in a Map/object; check before calling. Use when: (1) the function is pure (same inputs = same outputs), (2) it\'s computationally expensive (Fibonacci, heavy calculations), (3) it\'s called repeatedly with the same args. Don\'t over-memoize: cache has memory cost; for cheap functions the overhead of cache lookup may exceed computation. React\'s <code>useMemo</code> and <code>useCallback</code> are memoization hooks.', difficulty: 'intermediate', topic: 'Performance', expanded: false },

    // Advanced
    { id: 16, q: 'What is the Temporal Dead Zone (TDZ)?', a: 'The TDZ is the period between the start of a block scope and the <code>let</code>/<code>const</code> declaration. The binding EXISTS (it\'s been hoisted) but is UNINITIALIZED — accessing it throws a <code>ReferenceError</code>. Example: <code>{ console.log(x); let x = 1; }</code> → ReferenceError. This is intentional: it prevents the accidental-undefined bugs that <code>var</code> caused. The TDZ ends at the point of the declaration. Function parameters are also in a TDZ in the parameter list — <code>function f(a=b, b=1)</code> where accessing <code>b</code> before it\'s defined throws.', difficulty: 'advanced', topic: 'Closures', expanded: false },
    { id: 17, q: 'Explain how the "this" keyword works in JavaScript.', a: '<code>this</code> is determined by HOW a function is called, not where it\'s defined (except arrow functions). Rules: (1) <strong>Method call</strong>: <code>obj.fn()</code> → <code>this = obj</code>. (2) <strong>Function call</strong>: <code>fn()</code> → <code>this = undefined</code> (strict) or <code>window</code> (non-strict). (3) <strong>Constructor</strong>: <code>new Fn()</code> → <code>this = new object</code>. (4) <strong>Explicit binding</strong>: <code>fn.call(ctx)</code>, <code>fn.apply(ctx)</code>, <code>fn.bind(ctx)</code>. (5) <strong>Arrow functions</strong>: no own <code>this</code> — capture <code>this</code> from enclosing lexical scope at definition time (never changes). Common bug: passing a method as a callback loses <code>this</code> — fix with arrow wrapper or <code>.bind()</code>.', difficulty: 'advanced', topic: 'Closures', expanded: false },
    { id: 18, q: 'What is a Proxy and what problems does it solve?', a: '<code>new Proxy(target, handler)</code> wraps an object and intercepts operations (get, set, has, apply, construct...) via trap methods. Solves: (1) <strong>Validation</strong>: reject invalid property writes in the set trap. (2) <strong>Reactivity</strong>: Vue 3\'s reactivity system intercepts get (track dependency) and set (trigger re-render). (3) <strong>Logging/debugging</strong>: log every property access. (4) <strong>Default values</strong>: return defaults for missing properties. vs <code>Object.defineProperty</code>: Proxy covers ALL operations and ALL properties (even future ones); defineProperty only covers specific named properties. Always use <code>Reflect.method()</code> inside traps to forward correctly.', difficulty: 'advanced', topic: 'Patterns', expanded: false },
    { id: 19, q: 'What is event delegation and why is it efficient?', a: 'Event delegation attaches ONE listener to a parent element instead of N listeners on N children. When a child is clicked, the event bubbles up to the parent. The handler uses <code>e.target.closest(selector)</code> to identify which child was acted on. Why efficient: (1) O(1) listeners regardless of list size — N child elements need only 1 listener. (2) Works for dynamically added children — no need to re-attach listeners when items are added/removed. (3) Single cleanup point. Implementation: <code>list.addEventListener("click", e => { const item = e.target.closest(".item"); if(item) handle(item); })</code>.', difficulty: 'intermediate', topic: 'Patterns', expanded: false },
    { id: 20, q: 'How does garbage collection work in JavaScript and what causes memory leaks?', a: 'JS uses a <strong>mark-and-sweep</strong> GC: starting from roots (global, stack), mark all reachable objects; sweep (collect) the unmarked ones. An object is collected when no references to it remain. <strong>Common memory leaks</strong>: (1) <strong>Global variables</strong> — always reachable; (2) <strong>Detached DOM nodes</strong> — removed from DOM but still referenced in JS; (3) <strong>Forgotten event listeners</strong> — global listeners on window/document keep objects alive; (4) <strong>Closures over large objects</strong> — long-lived closures hold references; (5) <strong>Timers not cleared</strong> — setInterval callbacks reference objects indefinitely. Use Chrome DevTools Memory panel to take heap snapshots and find leaks.', difficulty: 'advanced', topic: 'Performance', expanded: false },
  ];

  filtered = computed(() => {
    const diff = this.activeDifficulty();
    const topic = this.activeTopic();
    return this.questions.filter(q =>
      (diff === 'all' || q.difficulty === diff) &&
      (topic === 'all' || q.topic === topic)
    );
  });

  toggle(q: InterviewQuestion) { q.expanded = !q.expanded; }
  setDifficulty(d: string) { this.activeDifficulty.set(d); }
  setTopic(t: string) { this.activeTopic.set(t); }
}
