import { Component } from '@angular/core';
import { PageMetaComponent } from '../../../../components/shared/page-meta/page-meta';
import { TheoryBlockComponent, TheoryPoint } from '../../../../components/shared/theory-block/theory-block';
import { QuizBlockComponent, QuizQuestion } from '../../../../components/shared/quiz-block/quiz-block';
import { QnaBlockComponent, QnaItem } from '../../../../components/shared/qna-block/qna-block';

@Component({
  selector: 'app-node-interview-prep',
  standalone: true,
  imports: [PageMetaComponent, TheoryBlockComponent, QuizBlockComponent, QnaBlockComponent],
  templateUrl: './interview-prep.html',
  styleUrl: './interview-prep.scss'
})
export class NodeInterviewPrep {
  theory: TheoryPoint[] = [
    {
      heading: 'Core Node.js Concepts (Foundations)',
      points: [
        'Event loop: single-threaded, non-blocking I/O. Phases: timers → pending I/O → idle → poll → check (setImmediate) → close. process.nextTick runs between phases. Blocking the event loop with synchronous CPU work stalls all requests.',
        'V8 engine executes JavaScript. libuv provides the event loop, thread pool (default 4 threads) for blocking I/O (fs, crypto, DNS). I/O operations never block the main thread — they are offloaded to the OS and libuv thread pool.',
        'require() (CJS) vs import (ESM): CJS is synchronous, loads at runtime, exports via module.exports. ESM is static, async, tree-shakeable, uses import/export. Modern Node.js (v12+) supports ESM natively with "type":"module" or .mjs extension.',
        'Buffer: raw binary data, fixed-size allocation outside V8 heap. Used for file I/O, network, crypto. Buffer.from(str, "utf8") converts string. Buffer.toString("base64") encodes.',
      ]
    },
    {
      heading: 'Async, Streams, and Error Handling',
      points: [
        'Callbacks → Promises → async/await: evolution of async Node.js. Callback hell: nested callbacks for sequential async ops. Promises: chainable .then()/.catch(). async/await: synchronous-looking code, same Promise semantics. util.promisify converts callback APIs.',
        'Promise combinators: all (fail fast), allSettled (collect all), race (first settles), any (first succeeds). Common interview question: parallel vs sequential — await in for loop is sequential, Promise.all() is concurrent.',
        'Streams solve the memory problem: process a 10GB file with constant memory by handling it in chunks. Readable, Writable, Transform, Duplex. pipeline() is preferred over pipe() — auto error propagation and cleanup. Backpressure: writable.write() returns false when full.',
        'Error handling: operational (expected — handle gracefully) vs programmer (bug — crash). asyncHandler wraps Express async routes to forward errors. process.on("unhandledRejection") + "uncaughtException" — log and exit(1). Graceful shutdown: server.close() → drain DB → exit.',
      ]
    },
    {
      heading: 'Performance, Security, and Architecture',
      points: [
        'Clustering: one Node.js process = one CPU core. Cluster module + PM2 spawn N processes sharing one port. Worker threads for CPU work within a process — message passing, SharedArrayBuffer + Atomics for shared state. Piscina for thread pools.',
        'Security checklist: helmet (15+ HTTP headers), bcrypt (cost 12) for passwords, parameterized queries (no injection), rate limiting (express-rate-limit + Redis store for multi-instance), CORS explicit allowlist, JWT secrets in env vars, never log sensitive data.',
        'Caching patterns: cache-aside (check → miss → DB → store → return), write-through (update cache + DB on write), TTL for freshness vs load balance. Redis for shared cache across instances. Cache stampede prevention: mutex lock or stale-while-revalidate.',
        'Deployment: multi-stage Docker (builder → production stage, npm ci --only=production), non-root USER node, SIGTERM graceful shutdown, /health + /ready probes, NODE_ENV=production. Secrets in environment variables — never in images.',
      ]
    },
  ];

  quiz: QuizQuestion[] = [
    { q: 'What happens to other requests when synchronous CPU work runs in Node.js?', options: ['They run in parallel threads', 'They queue up and wait — the event loop is blocked during synchronous work', 'They are dropped with a 503 error', 'They run in the libuv thread pool'], answer: 1, explanation: 'Node.js JavaScript runs on a single thread. Synchronous operations block this thread exclusively — no I/O callbacks, no timers, no HTTP requests can be processed until the synchronous work finishes. Offload CPU work to worker_threads or a job queue.' },
    { q: 'What is the order of process.nextTick vs setImmediate vs setTimeout(fn, 0)?', options: ['setTimeout → setImmediate → nextTick', 'nextTick → setTimeout(0) → setImmediate (but setTimeout vs setImmediate order depends on context)', 'setImmediate → nextTick → setTimeout(0)', 'They all fire in registration order'], answer: 1, explanation: 'process.nextTick always fires first — before the next event loop phase. Between setTimeout(0) and setImmediate: if called from the main module, the order is non-deterministic. Inside an I/O callback, setImmediate always fires before setTimeout(0) because we\'re already past the timers phase.' },
    { q: 'How does Node.js handle file system operations without blocking?', options: ['V8 handles file I/O in a background thread', 'libuv provides a thread pool (4 threads by default) for blocking OS calls like file I/O', 'Node.js uses non-blocking system calls for all file operations', 'File I/O blocks but on a separate CPU core'], answer: 1, explanation: 'libuv maintains a thread pool (UV_THREADPOOL_SIZE, default 4). Blocking OS calls (file read, DNS lookup, crypto) are offloaded to pool threads. When complete, the callback is queued to the event loop. The main thread is never blocked.' },
    { q: 'What is backpressure in Node.js streams?', options: ['CPU pressure when processing large files', 'Signal from a slow Writable to a fast Readable to slow down — writable.write() returns false when buffer is full', 'Network congestion between client and server', 'Memory pressure from large Buffer allocations'], answer: 1, explanation: 'When a Writable\'s buffer fills up, writable.write() returns false. The Readable should pause. When the buffer drains, the "drain" event fires — resume the Readable. pipeline() and pipe() handle backpressure automatically. Ignoring it causes all data to buffer in memory.' },
    { q: 'What is the N+1 problem in the context of GraphQL or REST APIs?', options: ['Running N queries for N records', 'Fetching a list (1 query) then making N individual queries for each item\'s related data', 'Returning N+1 items when only N are requested', 'Caching N queries plus 1 miss'], answer: 1, explanation: 'N+1: 1 query for the parent list (10 posts), then 10 individual queries for each post\'s author — 11 total. Solve with include (Prisma/Mongoose), DataLoader (GraphQL), or SQL JOIN. The fix reduces N+1 to 1-2 total queries.' },
    { q: 'Why should bcrypt be used instead of SHA-256 for password hashing?', options: ['bcrypt outputs longer hashes', 'bcrypt is slow by design (adjustable cost) — brute force a bcrypt hash takes thousands of years; SHA-256 can be computed billions of times per second on a GPU', 'SHA-256 is reversible', 'bcrypt is natively supported by Node.js'], answer: 1, explanation: 'SHA-256 is a general-purpose hash — fast, billions per second on GPUs. A stolen SHA-256 database can be brute-forced in hours. bcrypt\'s cost factor (2^N iterations) is adjustable — at cost 12, one hash takes ~250ms. The same attack takes thousands of years.' },
    { q: 'What does httpOnly on a cookie prevent?', options: ['The cookie being sent over HTTP (non-HTTPS)', 'JavaScript from accessing the cookie — XSS attacks cannot steal it', 'Cross-origin requests from using the cookie', 'The cookie from being set by the server'], answer: 1, explanation: 'httpOnly cookies are inaccessible to JavaScript — document.cookie does not include them, and XSS attacks cannot read them. The browser still sends them on requests automatically. This is critical for refresh tokens: even if an attacker injects JS, they cannot steal the token.' },
    { q: 'What does graceful shutdown mean for a Node.js server?', options: ['Shutting down without logging errors', 'On SIGTERM: stopping new connections (server.close()), waiting for in-flight requests to complete, closing DB connections, then exiting', 'Restarting the process after a crash', 'Shutting down only idle workers'], answer: 1, explanation: 'Without graceful shutdown, SIGKILL abruptly terminates: in-flight HTTP requests are dropped, DB transactions roll back. server.close() stops accepting new connections but waits for active ones. After draining, close DB pool and exit. PM2, K8s, and Docker all send SIGTERM before SIGKILL — handle it.' },
  ];

  qna: QnaItem[] = [
    { q: 'Explain the Node.js event loop in detail.', a: 'Node.js has a single JavaScript thread powered by V8. The event loop processes asynchronous callbacks in phases: (1) Timers — expired setTimeout/setInterval. (2) Pending I/O — I/O callbacks from previous iteration. (3) Idle/Prepare — internal. (4) Poll — wait for new I/O events and execute I/O callbacks. (5) Check — setImmediate callbacks. (6) Close — close event callbacks. process.nextTick() runs between every phase. Non-blocking I/O is handled by libuv\'s thread pool and OS async APIs — callbacks are queued to the event loop when complete.' },
    { q: 'How do you scale a Node.js application to handle more traffic?', a: 'Vertical (single server): cluster mode (N workers = N CPU cores, PM2), connection pooling, caching (Redis), async all the way (no blocking code). Horizontal (multiple servers): stateless design (JWT, not sessions), shared cache (Redis), shared DB, load balancer (Nginx, ALB). For CPU-bound bottlenecks: worker_threads or queue-based job processing (BullMQ). For DB bottlenecks: read replicas, query optimization, caching. Measure first — profiling reveals actual bottlenecks.' },
    { q: 'What are streams and when would you use them?', a: 'Streams process data in chunks instead of loading it all into memory. Use when: processing files larger than available RAM (log processing, CSV import), real-time data (HTTP responses, WebSockets), building pipelines (compress while encrypting while uploading). Four types: Readable (source), Writable (sink), Transform (modify — gzip, cipher), Duplex (both — TCP socket). Use stream.pipeline() not .pipe() — pipeline propagates errors and destroys all streams on failure.' },
    { q: 'What is the difference between cluster mode and worker_threads?', a: 'Cluster: spawns N separate OS processes, each with their own V8 instance and memory. Processes communicate via IPC. All share one server port (OS distributes connections). Use for: HTTP server throughput — multiply req/s across CPU cores. Worker threads: N threads in one process, share V8 heap and can use SharedArrayBuffer. Communication via message passing. Lower startup overhead. Use for: CPU-intensive work (image processing, crypto) within one request handler — keeps main thread free.' },
    { q: 'How do you prevent SQL and NoSQL injection in Node.js?', a: 'SQL injection: never concatenate user input into SQL strings. Always use parameterized queries / prepared statements. ORMs like Prisma and TypeORM parameterize automatically. For raw queries: use tagged template literals (prisma.$queryRaw, pg\'s $1 placeholders). NoSQL injection (MongoDB): validate that user-supplied objects don\'t contain operators ($where, $regex, $gt). Use Mongoose or Joi/Zod to validate input shape before passing to queries. The root rule: never trust client-supplied data — always parameterize or validate.' },
    { q: 'How would you debug high memory usage in a Node.js production app?', a: 'Step 1: Monitor process.memoryUsage().heapUsed over time — growing heap means leak. Step 2: Enable --heap-prof and take heap snapshots. Step 3: In Chrome DevTools Memory tab, compare snapshots — look for increasing object counts. Step 4: Common leak sources: global Maps/arrays growing without bounds, EventEmitter listeners not removed on socket disconnect, closures keeping references to large objects, caches without TTL/eviction. Step 5: Fix: WeakMap/WeakRef for caches, removeListener() in disconnect handlers, bounded collections (LRU caches).' },
    { q: 'What are the key differences between JWT authentication and server-side sessions?', a: 'JWT: stateless — no DB lookup per request. Token carries user info (sub, role, exp). Horizontal scaling without sticky sessions. Cannot revoke before expiry without blacklist (Redis). Good for: microservices, mobile apps, third-party clients. Sessions: stateful — session ID stored in DB or Redis. Server controls the session — instant revocation. Simpler logout (delete from DB). Requires sticky sessions or shared session store for horizontal scaling. Good for: traditional web apps with immediate revocation requirements. Both can be secure — choice depends on architecture.' },
    { q: 'What is middleware in Express and how does the middleware chain work?', a: 'Middleware are functions with (req, res, next) signature registered with app.use() or route-specific use(). They execute in registration order. Each middleware must either: call next() to pass to the next middleware, call next(err) to skip to error middleware, or send a response (res.json(), res.send(), res.end()). Error middleware has 4 args: (err, req, res, next) and must be registered last. Common middleware: helmet (headers), cors (CORS), express.json (parse body), rate limiters, auth (verify JWT), logging. If a middleware does not call next() or respond, the request hangs.' },
  ];
}
